### ISSUE TITLE
bin/doom install fails with  Native compiler error while (Re)generating autoloads file on emacs 28.0.50

### ISSUE THREAD

**Issue by malcook** [hlissner/doom-emacs#5217] opened 2021-06-30 03:08 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

`bin/doom install ` to complete without error

### What actually happened?

```
 > Natively compiling 1 files...
    \342\234\223 Installed 139 packages
  Regenerating autoloads files
  > (Re)generating autoloads file...
    > Generating autoloads file...
    x There was an unexpected error
      Message: Native compiler error
      Data: (native-compiler-error lambda (arg22 arg23 arg24 &optional arg25 arg26 arg27 arg28) (let ((f #'write-region)) (funcall f arg22 arg23 arg24 arg25 arg26 arg27 arg28)))
      Backtrace:
        (signal native-compiler-error ((lambda (arg22 arg23 arg24 &optional arg25
        (comp--native-compile (lambda (arg22 arg23 arg24 &optional arg25 arg26 arg
        (comp-trampoline-compile write-region)
        (comp-subr-trampoline-install write-region)
        (fset write-region (closure ((write-region . #<subr write-region>) (old .
        (progn (fset #'write-region vnew) (ignore write-region) (autoload-generate
        (unwind-protect (progn (fset #'write-region vnew) (ignore write-region) (a
        (let* ((vnew #'(lambda (start end filename &optional append visit lockname
        (let ((write-region (symbol-function #'write-region))) (let* ((vnew #'(lam
        (progn (fset #'load vnew) (ignore load) (let ((write-region (symbol-functi
    ! Extended backtrace logged to doom-emacs/.local/doom.error.log
    x There was an unexpected error
      Message: Native compiler error
      Data: (native-compiler-error lambda (arg29 arg30 arg31 &optional arg32 arg33 arg34 arg35) (let ((f #'write-region)) (funcall f arg29 arg30 arg31 arg32 arg33 arg34 arg35)))
      Backtrace:
        (signal native-compiler-error ((lambda (arg29 arg30 arg31 &optional arg32
        (comp--native-compile (lambda (arg29 arg30 arg31 &optional arg32 arg33 arg
        (comp-trampoline-compile write-region)
        (comp-subr-trampoline-install write-region)
        (fset write-region #<subr write-region>)
        (unwind-protect (progn (fset #'write-region vnew) (ignore write-region) (a
        (let* ((vnew #'(lambda (start end filename &optional append visit lockname
        (let ((write-region (symbol-function #'write-region))) (let* ((vnew #'(lam
        (progn (fset #'load vnew) (ignore load) (let ((write-region (symbol-functi
        (unwind-protect (progn (fset #'load vnew) (ignore load) (let ((write-regio
    ! Extended backtrace logged to doom-emacs/.local/doom.error.log
```

### Describe your attempts to resolve the issue

I reviewed other issues dealing with native compilation but none seemed to pertain.

### Steps to reproduce

```

# First install Doom somewhere
git clone https://github.com/hlissner/doom-emacs ~/doom-emacs
# Then create a place to store our private doom configs. The bin/doom script
# recognizes the DOOMDIR environment variable.
export DOOMDIR=~/doom-emacs-config
mkdir -p "$DOOMDIR"


# Set up Doom for the first time; this may take a while
cd ~/doom-emacs

export EMACS=~/.emacs.d/emacs/src/emacs
## where I have built emacs 28.0.50

## doom emacs requires more recent git than 2.19, so, following
## https://serverfault.com/questions/709433/install-a-newer-version-of-git-on-centos-7#comment1379291_813293
sudo yum install \
https://repo.ius.io/ius-release-el7.rpm \
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum install git224

## putting /usr/bin on PATH to get more recent git I just installed
PATH=/usr/bin bin/doom install

witness reported error
```

### System Information

https://pastebin.com/W4Q0r1tM

**Comment by darrenkenny** [comment] 2021-07-02 17:27
I'm seeing something similar with any of the recent 28.0 builds and native-comp. 

I had an installation that was working, but when I did a `doom sync` things wouldn't load anymore. Tried going back to basics, and doing a re-install like this, and again it failed to generate the autoloads file, and any future doom command would fail with `There was an unexpected error`.

Now it looks like nothing will work since the autoloads file doesn't exist, and I see output like:

```text
$ env DEBUG=1 doom sync                                                                                           ─╯
DOOM Initializing straight
Eager macro-expansion failure: (error "Recursive load" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/jka-compr.el.gz" "/Applications/Emacs.app/Contents/Resources/lisp/info.el.gz" "/Users/username/.doom-develop/.local/straight/repos/straight.el/straight.el" "/Users/username/.doom-develop/core/core-cli.el" "/Users/username/.doom-develop/bin/doom")
DOOM Initializing recipes
DOOM Installing core packages
DOOM Initializing Doom CLI
DOOM Initializing Doom
x There was an unexpected error
  Message: File is missing
  Data: (file-missing . "Cannot open load file")
  Backtrace:
    (load "/Users/username/.doom-develop/.local/autoloads.28.0.50
    (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) n
    (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message
    (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (if doom-de
    (doom-initialize)
    (load-with-code-conversion "/Users/username/.doom-develop/init.el" "/Users/
    (load "/Users/username/.doom-develop/init" t nomessage)
    (let (file-name-handler-alist) (load (expand-file-name doom-module-init-fi
    (condition-case e (let (file-name-handler-alist) (load (expand-file-name d
    (load-with-code-conversion "/Users/username/.doom-develop/cor
! Extended backtrace logged to .local/doom.error.log
x There was an unexpected error
  Message: Error in private config
  Data: (doom-private-error . "init.el")
  Backtrace:
    (signal doom-private-error ("init.el" (no-catch exit 255)))
    (let* ((source (file-name-sans-extension target)) (err (cond ((not (featur
    (doom--handle-load-error (no-catch exit 255) "/Users/username/.doom-develop
    (condition-case e (let (file-name-handler-alist) (load (expand-file-name d
    (load-with-code-conversion "/Users/username/.doom-develop/cor
    (require core-cli)
    (load-with-code-conversion "/Users/username/.doom-develop/bin
    (command-line-1 ("-scriptload" "/Users/username/.doom-develop/bin/doom" "--
    (command-line)
    (normal-top-level)
! Extended backtrace logged to .local/doom.error.log
No catch for tag: exit, 255
```

No matter what `doom` command I run now, it fails. 

My only workaround was to fallback to use Emacs 27.2, which runs just fine...

**Comment by hlissner** [comment] 2021-07-09 17:31
I've been on top of native-comp for the past several months and haven't seen these issues, nor can I reproduce them on any of my test systems (nixOS, Arch, macOS, and Ubuntu), so I am inclined to suspect your local installation of Emacs. As I have no reason yet to suspect this is a Doom issue I will close this, but feel free to follow up here if you find out more.

**Closed by hlissner** 2021-07-09 17:31 UTC
Labels: 1. external, 2. status:unknown, re:native-comp

**Comment by hlissner** [comment] 2021-07-09 17:35
@darrenkenny Your issue appears to be unrelated to this thread. Your first error originates from your private `~/.doom.d/init.el` file (i.e. `(signal doom-private-error ("init.el" (no-catch exit 255)))` suggests you're throwing something somewhere without catching it). Please investigate your config. [The Discord](https://doomemacs.org/discord) would be a better place to discuss this.
