### ISSUE TITLE
How to match `projectile-find-file` and `counsel-projectile-find-file` on filename only?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [hlissner/doom-emacs#5020] opened 2021-05-09 12:15 UTC
I have a fairly standard project which I don't believe is above `ivy-sort-max-size`

I've tried setting ` (setq counsel-projectile-find-file-matcher 'counsel-projectile-find-file-matcher-basename)` as per the readme for counsel-projectile. Checking with `spc h v` shows it is set, however `spc p f` and `M-x counsel-projectile-find-file` still has the standard behaviour of matching the entire path.

I notice that there's a custom `+ivy/projectile-find-file` function which is supposed to select the correct search method based on where (counsel-)projectile-find-file is being invoked from, manually invoking `counsel-projectile-find-file` and `projectile-find-file` manually it is hard to see any difference between the two. I notice that looking in `+evil-bindings.el` shows `spc p f` bound to `'projectile-find-file`, should it not be this custom function?

Anyway, changing it via
```
(after! projectile
  (map! :leader
        (:prefix-map ("p" . "project")
         :desc "definitely counsel"     "f" #'counsel-projectile-find-file)))
```
Still doesn't give the desired behaviour, is maybe something overriding it at invocation?

What is the intended way to have these functions match by filename only?

**Comment by JordanAnthonyKing** [comment] 2021-05-09 12:31
Apologies, examining this further it does seem that the setting works, however it is the highlighting of the buffer that is misleading:
![image](https://user-images.githubusercontent.com/58787893/117572431-646de600-b0c2-11eb-9f06-72fd039eb0f9.png)
This project has many more files in the `/attributes/` path, and counsel-projectile is correctly filtering to only the ones that actually contain `attributes` in the filename, however the highlighting makes it appear that it is matching on the path, not the filename.

**Comment by hlissner** [comment] 2021-05-09 16:33
To match by filename, use regex. `/attributes`. Or add additional keywords. `/attributes\. \.ts$`.

-----

As this is not a bug or an actionable ticket, I will close this, but feel free to follow up here.

**Closed by hlissner** 2021-05-09 16:33 UTC
Labels: delete me, invalid
