### ISSUE TITLE
doom sync does not run when literate is enabled on FreeBSD

### ISSUE THREAD

**Issue by timotheosh** [hlissner/doom-emacs#3820] opened 2020-08-24 12:15 UTC
**What did you expect to happen?**
doom sync to sync the changes made in config.org

**What actually happened?**
doom sync successfully tangles config.org, reports that it is restarting and then silently returns to the shell prompt.
Output:
```
$ doom sync --debug
> Compiling your literate config...
  - Tangled 1 code block from config.org.oTysjf
  - Restarting...
$
```

**Additional details:**
- Latest Doom Emacs e3750dbf66896eb4a88aa39789e48f9cb5d690ab
- Emacs version 27.1
- FreeBSD 12.1 Operating System

**Steps to reproduce:**
1 Login to a FreeBSD system, install emacs-devel-27.1 package
2. Clone latest version of doom emacs
3. Enable literate in the init.el file
4. Create config.org
5. Run doom sync

**System information:**
<details><pre>
((emacs
  (version . "27.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "Aug 24, 2020")
  (buildopts "--disable-build-details --localstatedir=/var --with-x --enable-acl --with-cairo --with-dbus --without-gconf --with-gif --with-gnutls --with-gsettings --with-x-toolkit=gtk3 --with-harfbuzz --with-jpeg --with-json --with-file-notification=kqueue --with-lcms2 --with-m17n-flt --without-imagemagick --with-mailutils --with-modules --with-sound=oss --with-libotf --with-png --with-toolkit-scroll-bars --with-rsvg --with-threads --with-tiff --with-xft --with-xim --with-xml2 --with-xpm --without-xwidgets --x-libraries=/usr/local/lib --x-includes=/usr/local/include --prefix=/usr/local --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/share/emacs/info/ --build=amd64-portbld-freebsd12.1 'CFLAGS=-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing ' 'CPPFLAGS=-isystem /usr/local/include' 'LDFLAGS= -fstack-protector-strong -L/usr/local/lib '")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD e3750dbf6 2020-08-23 18:48:50 -0400")
  (dir . "/usr/home/thawes/.config/testdoom/"))
 (system
  (type . berkeley-unix)
  (config . "amd64-portbld-freebsd12.1")
  (shell . "/usr/local/bin/bash")
  (uname . "FreeBSD 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64")
  (path "~/.local/bin" "~/.cargo/bin" "~/programs/share/golang/bin" "~/programs/golang/current/bin" "~/programs/sbin" "~/programs/bin" "~/.roswell/bin" "~/.local/bin" "~/perl5/bin" "~/.local/bin" "/usr/local/gerbil/bin" "/sbin" "/bin" "/usr/sbin" "/usr/bin" "/usr/local/sbin" "/usr/local/bin" "~/bin" "/usr/local/libexec/emacs/27.1/amd64-portbld-freebsd12.1"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2020-08-24 18:10
This is a duplicate of #3746

**Closed by hlissner** 2020-08-24 18:10 UTC
Labels: is:duplicate
