### ISSUE TITLE
After doom upgrade, error in doom-num-cpus on init

### ISSUE THREAD

**Issue by rubin55** [hlissner/doom-emacs#4719] opened 2021-03-02 09:36 UTC
**What did you expect to happen?**
I expected doom to start as always after doing a doom upgrade.

**What actually happened?**
I got an exception on function doom-num-cpus.

**Additional details:**
N/A, no changed config, config has been working + unchanged for months.
See attached [backtrace.txt](https://github.com/hlissner/doom-emacs/files/6067597/backtrace.txt)

**Steps to reproduce:**
1. Run `doom upgrade`
2. Start `emacs`
3. Observe attached backtrace

**System information:**
<details><pre>
$ doom info
x There was an unexpected error
  Message: Symbol's function definition is void
  Data: (void-function . doom-system-distro-version)
  Backtrace:
    (doom-system-distro-version)
    (cons (doom-system-distro-version) (sh "uname" "-msr"))
    (cons (quote info) (cons (doom-system-distro-version) (sh "uname" "-msr"))
    (list (quote system) (cons (quote info) (cons (doom-system-distro-version)
    (list (list (quote system) (cons (quote info) (cons (doom-system-distro-ve
    (progn (fset (function symlink-path) vnew) (ignore symlink-path) (list (li
    (unwind-protect (progn (fset (function symlink-path) vnew) (ignore symlink
    (let* ((vnew (function (lambda (file) (format "%s%s" (abbrev-path file) (i
    (let ((symlink-path (symbol-function (function symlink-path)))) (let* ((vn
    (progn (fset (function abbrev-path) vnew) (ignore abbrev-path) (let ((syml
! Extended backtrace logged to .local/doom.error.log
</pre></details>

**More system information**
1 socket, 8 core, 32 thread Power 9, 64GiB RAM, Red Hat Enterprise Linux 8.3.
Has been running with Doom on this OS/setup for more than 6 months.

**Comment by mjanonis** [comment] 2021-03-02 10:05
Duplicate of #4715

**Comment by gpetrini** [comment] 2021-03-02 10:53
I got the exact same error message. No change in private config files.

**Closed** 2021-03-02 15:41 UTC
Labels: duplicate
