### ISSUE TITLE
org-superstar: "could not find package org-superstar in recipe repositories"

### ISSUE THREAD

**Issue by polaris64** [hlissner/doom-emacs#2909] opened 2020-04-16 08:25 UTC
After a recent upgrade (84d2e676335c9dbdd4ac165ea4fada29e3106d80...d3aa59586f469e455448fde06e24dd04363265a9) there are problems with Org mode, specifically the package `org-superstar` doesn't seem to be installed.

Some features such as `elfeed` (which reads news feeds via an Org file using `elfeed-org`) and `org-capture` fail while this package is not installed. To fix it, currently I have to install the package manually via `package-install`.

**Additional details:**
`doom doctor` output:
<details><pre>
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50devhelp.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50figlet.el (source)...
Loading /etc/emacs/site-start.d/50mu4e.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...

Package error: (error Could not find package org-superstar in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))

  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 52 modules
  ✓ Detected 218 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
  x org-superstar is not installed
  x org is not installed
    > :lang python
      ! Couldn't find nosetests. Running tests through nose will not work.

There are 1 warnings!
✓ Finished! (4.9845s)
</pre></details>

**System information:**
NOTE: the output below was generated after installing `org-superstar` manually via `package-install`.

<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      Sep 23, 2019
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-wvqver/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop 10031153b 2020-04-16 03:37:19 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64
        path       (~/.local/bin ~/.cargo/bin ~/.yarn/bin ~/.config/yarn/global/node_modules/.bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/jvm/java-8-oracle/bin /usr/lib/jvm/java-8-oracle/db/bin /usr/lib/jvm/java-8-oracle/jre/bin /storage/SDKs/Android/Sdk/build-tools /storage/SDKs/Android/Sdk/emulator /storage/SDKs/Android/Sdk/platform-tools /storage/SDKs/Android/Sdk/tools/bin /storage/Software/android-studio/bin /usr/lib/emacs/26.3/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax spell grammar :tools debugger docker editorconfig (eval +overlay) (lookup +docsets) lsp magit rgb :lang data emacs-lisp (javascript +lsp) latex lua markdown (org +dragndrop +present) (php +lsp) (python +lsp) (rust +lsp) sh web :app (rss +org) :config (default +bindings +smartparens))
        packages   ((mu4e-alert))
        unpin      (n/a)
        elpa       (notmuch org-superstar)
</pre></details>

**Comment by hlissner** [comment] 2020-04-16 08:28
This is a duplicate of #2802. See https://github.com/hlissner/doom-emacs/issues/2802#issuecomment-606654151 for workaround.

**Closed by hlissner** 2020-04-16 08:28 UTC
Labels: is:duplicate

**Comment by polaris64** [comment] 2020-04-16 08:48
Thanks for the quick response; that workaround fixed the issue.  I now also know a little more about how `straight` and MELPA repositories work as a result, so in a way I'm happy this happened ;)
