### ISSUE TITLE
With editor causing problems (I guess)

### ISSUE THREAD

**Issue by DoubleClick7** [hlissner/doom-emacs#4394] opened 2020-12-09 10:10 UTC
**What did you expect to happen?**
I expected `doom sync && doom build` to work

**What actually happened?**
I get shown this https://pastebin.com/kpHYQKYF

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.9.11-zen2-1-zen #1 ZEN SMP PREEMPT Sat, 28 Nov 2020 02:08:52 +0000 x86_64
        path       (~/chromedriver/chromedriver ~/.emacs.d/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Nov 25, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        font       #<font-spec nil nil Source Code Pro nil nil nil nil nil 16 nil nil nil ((:name . Source Code Pro))>
        theme      ewal-doom-one
        build      HEAD -> develop fbb8d1b99 2020-12-08 23:01:07 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo indent-guides ligatures minimap (modeline +light) neotree ophints (popup +defaults) vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric ibuffer undo :term eshell shell term vterm :checkers syntax :tools (eval +overlay) lookup magit make rgb lsp :os tty :lang (cc +lsp) (emacs-lisp +lsp) (javascript +lsp) markdown org php (python +lsp) sh (web +lsp) :email (mu4e +gmail) :config (default +bindings +smartparens))
        packages   ((ewal-doom-themes) (with-editor) (ewal) (fira-code-mode) (prettier) (sublimity) (spacemacs-theme) (webpaste) (zone-nyan) (nyan-mode) (evil-commentary) (evil-tutor) (sublime-themes) (cyberpunk-theme) (ample-theme) (ample-zen-theme) (afternoon-theme))
        unpin      (n/a)
        elpa       (spacemacs-theme ewal-spacemacs-themes ewal-doom-themes ewal doom-themes)
```
</pre></details>

**Comment by icmor** [comment] 2020-12-11 04:12
Duplicate of #4171 and #4169
The compilation of vterm's dynamic module messes with the doom build command. You can either remove the with-editor folder and then run doom sync to rebuild the package
```
rm -rf ~/.emacs.d/.local/straight/build*/with-editor && doom sync
```
or build doom without vterm, then select it in your init.el and run doom sync. In this case, vterm will ask you to compile the external module after opening emacs which doesn't cause any bugs.

**Closed** 2020-12-11 07:32 UTC
Labels: is:bug
