### ISSUE TITLE
evilem-motion-*-line is extremely slow on emacs-plus

### ISSUE THREAD

**Issue by qhuyduong** [hlissner/doom-emacs#1141] opened 2019-01-26 08:21 UTC
### Observed behavior

`evilem-motion-previous/next-line` is extremely slow on emacs-plus. It's okay on emacs-mac.

Interestingly, I have tried it on Spacemacs + emacs-plus but don't see the issue.

### Expected behavior
It's faster!

### Steps to reproduce

1. Trigger `evilem-motion-next-line`
2. Type in 2 characters corresponding to the desired line

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 27.0.50 (Jan 26, 2019)
- Doom: 2.0.9 (develop 7ca2b42d2bfa911051820448b3b4e59682672488)
- Graphic display: t (daemon: nil)
- System features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS CANNOT_DUMP LCMS2 GMP
- Details:
  elc count: 0
  uname -a:  Darwin Huys-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company (ivy +fuzzy) :ui evil-goggles hl-todo modeline neotree vc-gutter vi-tilde-fringe window-select :emacs dired electric imenu vc :tools macos magit :lang data emacs-lisp javascript markdown (org +babel +capture) (ruby +rbenv) :config default)
  packages:  n/a
  exec-path: (~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.nvm/versions/node/v8.12.0/bin/ ~/.pyenv/shims/ ~/.rbenv/shims/ ~/.pyenv/bin/ ~/.nvm/ /usr/local/opt/imagemagick@6/bin/ ~/.cask/bin/ /usr/local/opt/fzf/bin/ /usr/local/Cellar/emacs-plus/HEAD-ce085f1/libexec/emacs/27.0.50/x86_64-apple-darwin18.2.0/)
```
</details>

**Comment by hlissner** [comment] 2019-01-26 08:55
I cannot reproduce this on Mojave+emacs-plus. Can you offer any other context? Such as:

- The major mode(s) you tested it in? 
- Whether or not `visual-line-mode` is enabled? 
- How tall your Emacs frame is in characters?

**Comment by qhuyduong** [comment] 2019-01-26 09:17
@hlissner 
1. It happens with every major modes
2. It happens with either `visual-line-mode` enabled or disabled
3. It happens no matter how tall Emacs frame is.

Attach captured screen.

![jan-26-2019 16-16-40](https://user-images.githubusercontent.com/16358771/51785130-d803b780-2185-11e9-90b5-8a3329dc1a99.gif)

**Comment by qhuyduong** [comment] 2019-01-27 01:42
I have found out the reason: I have built emacs-plus from HEAD! So there's something wrong with the latest Emacs.

But the strange point is that the issue doesn't happen with Spacemacs on HEAD.

**Comment by hlissner** [comment] 2019-02-27 23:49
Since I've been unable to reproduce this on any of my builds or OSes, I'll consider this an issue on Emacs HEAD and close this issue for now. I'm not sure what Spacemacs could've done differently. If you have any ideas, let me know. I'll keep an eye out for it.

**Closed by hlissner** 2019-02-27 23:49 UTC
Labels: external
