### ISSUE TITLE
Find-file tab completion requires two "tab" presses sometimes

### ISSUE THREAD

**Issue by biox** [hlissner/doom-emacs#760] opened 2018-07-16 15:21 UTC
### Observed behavior

Bad:
- I am browsing files via `find-file` and highlight a dir that I'd like to enter - I press tab. Nothing happens. I press tab again, I'm in the directory. 

This behavior is inconsistent and make for bad UX for tab preferrers. The ctrl+L shortcut works as anticipated.

Related issue: https://github.com/syl20bnr/spacemacs/issues/7516

### Expected behavior

I press tab, I'm in the directory, regardless of uniqueness. Same behavior every time.

### Steps to reproduce

```bash
mkdir ~/{test,test2}
<open emacs>
`M-x find-file`
highlight test folder
<TAB>
oh noes!
<TAB>
ok fine
```

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin16.7.0)
- Emacs: 26.1 (May 28, 2018)
- Doom: 2.0.9 (develop 53df5178a3e79e84fec3dc7f942ce2e1ff4ca18a)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin MACC02VK5ECHTD7 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash (popup +all +defaults) vc-gutter vi-tilde-fringe window-select treemacs :editor :emacs ediff electric eshell imenu vc :tools macos magit password-store :lang emacs-lisp go (java +meghanada) javascript latex markdown nix (org +attach +babel +capture +export +present) python ruby sh :config)
  packages:  n/a
  exec-path: (/usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin16.7.0/)
  ``````
</details>

**Comment by hlissner** [comment] 2018-07-16 16:18
I agree, but this cannot be trivially fixed on the Doom side, because there is no one ivy command that embodies those preferences. `ivy-partial-or-done` is the closest we've got. That it requires two TABs to enter non-unique candidates is [intentional by design](https://github.com/abo-abo/swiper/issues/1364).

If an alternative is devised, I'd be happy to add it to Doom!

**Comment by biox** [comment] 2018-07-16 16:29
Correct me if I'm wrong, but couldn't we bind tab to ivy-alt-done while we're in the file-browsey mode, similar to our C-l bind?

**Comment by hlissner** [comment] 2018-07-16 16:34
You could, but then you break completion. It'll open the selected file instead of completing. But perhaps that's an acceptable compromise?

**Comment by biox** [comment] 2018-07-16 16:38
I personally see it as acceptable, because it means that tabbing behavior will be consistent - I'm not at liberty to speak for other users, but I do believe that hitting tab should have an expected result - not two distinct results that depend on filenames.

If a user highlights a file and presses tab, I expect they'd like to enter that particular directory, but I also understand that some people may prefer it to be more "bashy".

It would be easy enough for me to remap the key personally, not sure what the better default is though.

**Comment by hliebert** [comment] 2018-07-17 13:43
I actually very much prefer the default bash-type behavior and would rather press `TAB` twice than lose it. I think Helm (at least in Spacemacs) has immediate candidate selection on `TAB` and I personally found this irritating. Just my 2 cents.

**Comment by hlissner** [comment] 2018-08-30 23:31
I've given this some thought, and it's evident there is no superior answer, so I've decided to leave it to its default. After all, changing its behavior is a trivial, 1 or 2 line change:

```elisp
(map! :after counsel :map counsel-find-file-map [tab] #'ivy-alt-done)

;; or

(after! counsel
  (define-key counsel-find-file-map [tab] #'ivy-alt-done))
```

That said, I understand if this is a difficult thing to discover, especially with how obtuse `ivy-alt-done` and `ivy-partial-or-done` (and their docstrings) are. I will document it in `:completion ivy`'s documentation (once I'm finished with it, along with the 2.1 release).

**Closed by hlissner** 2018-08-30 23:31 UTC
Labels: enhancement, external
