### ISSUE TITLE
typescript-tsx mode loads web-mode snippets.

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#6022] opened 2022-01-21 19:00 UTC
### What did you expect to happen?

Works like rjsx-mode

### What actually happened?

Loads web-mode snippets 

### Steps to reproduce

Open TSX file

### System Information

https://pastebin.com/8eUqxMZA

**Comment by jeetelongname** [comment] 2022-01-22 15:56
typescript-tsx-mode derives from web-mode not js2 or typescript mode, I am not sure of a major mode that does sadly

**Comment by hlissner** [comment] 2022-01-27 15:07
I can only half reproduce this. See https://github.com/doomemacs/snippets/blob/master/typescript-tsx-mode/.yas-parents, where typescript-tsx-mode declares +web-react-mode, typescript-mode, and rjsx-mode as parent modes. In my tests, I can see the snippets of all the above modes *and* web-mode (since typescript-tsx-mode is derived from web-mode). I think this is working as intended.

There isn't much else to go off of here, so I'll close this.

**Closed by hlissner** 2022-01-27 15:07 UTC
Labels: invalid, delete me
