### ISSUE TITLE
.projectile missing from projectile root markers

### ISSUE THREAD

**Issue by nate** [hlissner/doom-emacs#2261] opened 2019-12-28 06:40 UTC
This commit reduces the number of projectile root markers which is cool and great: https://github.com/hlissner/doom-emacs/commit/9b25582be1c9f0ace2e3ed161705e66943ba4587

But it also removes the `.projectile` root marker: https://github.com/bbatsov/projectile/blob/0f5018fd7e7b3a1d224d3aa96edff0b40306e79f/projectile.el#L327

I can't tell if dropping that was intentional or not but it seems like something that's worth keeping since it's the default recommended in projectile's docs.

Thoughts?

**Comment by nate** [comment] 2019-12-28 06:43
It mentions `.projectile` at the bottom of this section and elsewhere https://projectile.readthedocs.io/en/latest/projects/#file-markers

**Comment by hlissner** [comment] 2019-12-28 06:53
This is a duplicate of #1974. 

The removal of `.projectile` was indeed intentional. See https://github.com/hlissner/doom-emacs/issues/1974#issuecomment-546977542 for an explanation. Sorry for the inconvenience!

**Closed by hlissner** 2019-12-28 06:53 UTC
Labels: is:duplicate

**Comment by nate** [comment] 2019-12-28 06:56
ok, thanks!
