### ISSUE TITLE
Transparency stops whenever overlay appears

### ISSUE THREAD

**Issue by destroyer449** [hlissner/doom-emacs#4641] opened 2021-02-11 17:10 UTC
**What did you expect to happen?**
Emacs stays transparent.

**What actually happened?**
Emacs transparency turns off when Ivy(I have +childframe enabled, not sure if this matters), evil command mode, or any temporary frame like capture templates appear. If I go to a different workspace and back, or resize the window, the transparency will reappear

**Additional details:**
- Include a link to your private config: https://github.com/destroyer449/dotfiles/tree/master/.config/doom

**Steps to reproduce:**
1. Add ```(defvar doom/frame-transparency '(85 . 85))
;; Set frame transparency
(set-frame-parameter (selected-frame) 'alpha doom/frame-transparency)
(add-to-list 'default-frame-alist `(alpha . ,doom/frame-transparency))``` to your private config.
2. Restart emacs daemon.
3. Open graphical emacsclient frame.
4. Open Ivy, evil command mode, etc.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.10.13-zen1-2-zen #1 ZEN SMP PREEMPT Sat, 06 Feb 2021 11:08:59 +0000 x86_64
        path       (~/.config/emacs/bin/ /usr/local/bin /sbin /usr/sbin ~/.config/emacs/bin/ ~/.cabal/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.local/share/cargo/bin ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/lib ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/git ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/python ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/autojump ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/colorize ~/.cache/antigen/bundles/robbyrussell/oh-my-zsh/plugins/github ~/.cache/antigen/bundles/hlissner/zsh-autopair ~/.cache/antigen/bundles/arzzen/calc.plugin.zsh ~/.cache/antigen/bundles/IngoMeyer441/zsh-easy-motion ~/.cache/antigen/bundles/hcgraf/zsh-sudo ~/.cache/antigen/bundles/softmoth/zsh-vim-mode ~/.cache/antigen/bundles/zsh-vi-more/vi-increment ~/.cache/antigen/bundles/zsh-vi-more/vi-increment/functions ~/.cache/antigen/bundles/zsh-vi-more/vi-motions ~/.cache/antigen/bundles/zsh-vi-more/vi-motions/functions ~/.cache/antigen/bundles/zsh-vi-more/vi-quote ~/.cache/antigen/bundles/zsh-vi-more/vi-quote/functions ~/.cache/antigen/bundles/MichaelAquilina/zsh-you-should-use ~/.cache/antigen/bundles/zsh-users/zsh-autosuggestions ~/.cache/antigen/bundles/zsh-users/zsh-syntax-highlighting /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.config/emacs/
        version    28.0.50
        build      Jan 20, 2021
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB
        traits     (gui daemon server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        font       #<font-spec nil nil JetBrainsMono Nerd Font nil nil nil nil nil 12 nil nil nil nil>
        theme      doom-gruvbox
        build      HEAD -> develop, origin/develop, origin/HEAD e08c5f537 2021-02-07 23:57:44 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +fuzzy +icons +prescient +childframe) :ui doom doom-dashboard doom-quit (emoji +unicode +ascii) hl-todo hydra indent-guides minimap modeline nav-flash neotree ophints (popup +defaults) (ligatures +extra) unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) (undo +tree) vc :term eshell vterm :checkers syntax (spell +aspell) grammar :tools (debugger +lsp) editorconfig (eval +overlay) gist (lookup +dictionary) (lsp +peek) (magit +forge) make pdf rgb taskrunner :lang (cc +lsp) emacs-lisp (haskell +lsp) (java +lsp) (latex +lsp +latexmk +cdlatex) (lua +lsp) markdown (org +pretty +dragndrop +brain +noter +gnuplot +present +pandoc) (python +lsp) (rust +lsp) (sh +lsp) (yaml +lsp) :email (mu4e +gmail) :app calendar (rss +org) :config literate (default +bindings +smartparens))
        packages   ((dmenu) (emms) (evil-tutor) (peep-dired) (wc-mode) (evil-quickscope) (virtualenvwrapper) (tree-sitter) (tree-sitter-langs) (vimrc-mode) (solaire-mode :disable t) (command-log-mode))
        unpin      (n/a)
        elpa       (vimrc-mode command-log-mode)

</pre></details>

**Comment by hlissner** [comment] 2021-02-11 19:10
I'm afraid I don't know the cause of or a solution for this issue, but I'm certain it isn't a Doom issue, so I will close it. You've set the transparency correctly and Doom does not interfere with those frame parameters. This is possibly an issue with your particular build of Emacs for your particular distro, but more likely an issue with your OS/WM compositor. As I cannot reproduce it with picom and Emacs 28 + native-comp + pgtk, I suggest switching to that build, if you can (e.g. https://aur.archlinux.org/packages/emacs-pgtk-native-comp-git/ if you're on Arch).

**Closed by hlissner** 2021-02-11 19:10 UTC
Labels: invalid
