### ISSUE TITLE
t movement broken (inconsistent with vim and/or vanilla evil)

### ISSUE THREAD

**Issue by leoalekseyev** [hlissner/doom-emacs#3261] opened 2020-05-31 09:44 UTC
**Example**
Here is a sample line from doom emacs config:
```
       company           ; the ultimate code completion backend
```
Consider the point being anywhere inside the word "company" and issue the command `vt<SPC>`.

**What did you expect to happen?**
Visual mark extends from where the point was to the end of the word (up until the first space)

**What actually happened?**
```
       company           ; the ultimate code completion backend
                      ^-------- visual mark extends to here
```

**Discussion**
This behavior is caused by evil-snipe and is fixed by disabling it globally. I am not sure it is an evil-snipe issue, however, since I have evil-snipe installed in Spacemacs and it doesn't exhibit this bug. However, it is possible Spacemacs is doing some extra configuration to turn off this behavior. Regardless, having a basic movement exhibit behavior not consistent with vim/evil out of the box is a bug; if this behavior is expected it should be prominently documented.

**Comment by hlissner** [comment] 2020-05-31 09:56
This should be reported to [evil-snipe](https://github.com/hlissner/evil-snipe#usage). It can be worked around with `(setq evil-snipe-skip-leading-whitespace nil)` for the time being. The issue is evil-snipe isn't recognizing that continuous stream of whitespace as non-indentation. I'll look into it when I can.

**Comment by leoalekseyev** [comment] 2020-05-31 10:00
I opened an issue in evil-snipe: https://github.com/hlissner/evil-snipe/issues/70, however this should be documented either in the FAQ or evil module doc or both

**Comment by hlissner** [comment] 2020-05-31 10:16
As of 37b1a78dc and https://github.com/hlissner/evil-snipe/commit/6dcac7f2516c6137a2de532fc2c052f242559ee3 this should be fixed. I'll document it in editor/evil's readme soon.

**Closed by hlissner** 2020-05-31 10:16 UTC
Labels: :editor evil, is:external, status:resolved-elsewhere
