### ISSUE TITLE
can't save workspace; invalid-read-syntax "#" in modeline when attempted

### ISSUE THREAD

**Issue by Subcomediante** [hlissner/doom-emacs#6044] opened 2022-01-26 22:39 UTC
### What did you expect to happen?

When I try to save a workspace (SPC TAB s), the workspace is saved and I can then load it from file or switch. 

### What actually happened?

The workspace is not saved, and this is displayed in the modeline:
Invalid read syntax "#"
.
This problem has occurred for a few weeks intermittently. I can't figure out what I might have done to cause it. It now occurs every time I try to save a workspace.

Here's the backtrace:

Debugger entered--Lisp error: (invalid-read-syntax "#")
  read(#<buffer  *temp*>)
  #f(compiled-function (&rest rest) (interactive #f(compiled-function () #<bytecode 0x1ff2aef11039>)) #<bytecode 0x1ff2abac144d>)("/Users/jeff/.emacs.d/.local/etc/workspaces/..." #<hash-table equal 0/10 0x1ff2b3218e59> (:not . "\\(?:workspaces\\)"))
  apply(#f(compiled-function (&rest rest) (interactive #f(compiled-function () #<bytecode 0x1ff2af28b9dd>)) #<bytecode 0x1ff2abac144d>) ("/Users/jeff/.emacs.d/.local/etc/workspaces/..." #<hash-table equal 0/10 0x1ff2b3218e59> (:not . "\\(?:workspaces\\)")))
  #f(advice-wrapper :after #f(compiled-function (&rest rest) (interactive #f(compiled-function () #<bytecode 0x1ff2a744141d>)) #<bytecode 0x1ff2abac144d>) +popup--persp-mode-restore-popups-a)("/Users/jeff/.emacs.d/.local/etc/workspaces/..." #<hash-table equal 0/10 0x1ff2b3218e59> (:not . "\\(?:workspaces\\)"))
  apply(#f(advice-wrapper :after #f(compiled-function (&rest rest) (interactive #f(compiled-function () #<bytecode 0x1ff2b7879e91>)) #<bytecode 0x1ff2abac144d>) +popup--persp-mode-restore-popups-a) ("/Users/jeffballowe/.emacs.d/.local/etc/workspaces/..." #<hash-table equal 0/10 0x1ff2b3218e59> (:not . "\\(?:workspaces\\)")))
  persp-load-state-from-file("/Users/jeff/.emacs.d/.local/etc/workspaces/..." #<hash-table equal 0/10 0x1ff2b3218e59> (:not . "\\(?:workspaces\\)"))
  persp-save-to-file-by-names("/Users/jeff/.emacs.d/.local/etc/workspaces/..." #<hash-table equal 2/10 0x1ff2abac6f7d> ("workspaces"))
  (let ((fname (expand-file-name +workspaces-data-file persp-save-dir))) (persp-save-to-file-by-names fname *persp-hash* (list name)) (and (member name (persp-list-persp-names-in-file fname)) t))
  +workspace-save("workspaces")
  (if (+workspace-save name) (+workspace-message (format "'%s' workspace saved" name) 'success) (+workspace-error (format "Couldn't save workspace %s" name)))
  +workspace/save("workspaces")
  funcall-interactively(+workspace/save "workspaces")
  call-interactively(+workspace/save nil nil)
  command-execute(+workspace/save)

### Describe your attempts to resolve the issue

I've consulted all the resources mentioned above and in the Doom Emacs debugging and issue reporting documentation.

I have only done 1 thing, because it was the only thing I understood to do: update Doom. When I did that, I found "Doom is already up-to-date," but when the script tried to update packages an error message displayed and asked me if which of 5 possible things I'd like to do. Not understanding much about any of them, I chose "1) Abort." Maybe I should try one of the other 4 choices? I tried this again and ended up in the same place. The full text of the terminal output:
=======
jeff/.emacs.d/bin % doom upgrade
> Executing 'doom upgrade' with Emacs 27.2 at 2022-01-26 10:02:47
  > Preparing to upgrade Doom Emacs and its packages...
  ✓ Doom is already up-to-date!
  Doom is up-to-date!
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
    > Updating packages (this may take a while)...
      > In repository "transient", HEAD on default branch "master" has diverged from "origin/master"

           1) Abort
           2) Merge "origin/master" into "master"
           3) Rebase "master" onto "origin/master"
           4) Reset "master" to "origin/master"
           5) Magit log "master...origin/master" and open recursive edit

        How to proceed? (1, 2, 3, 4, 5) 1

! Aborted

        ! Script was abruptly aborted! Run 'doom sync' to repair inconsistencies

### Steps to reproduce

1. Open and org file.
2. Create a second window. 
3. Open another org file.
4. Press SPC TAB r to rename workspace
5. rename workspace to x
6. Press SPC TAB s to save workspace
7. Choose workspace x and press return
8. Invalid read syntax "#" displays in modeline
9. Press SPC TAB x
8. Press SPC TAB l to load workspace x hoping that it was saved despite error message
9. Invalid read syntax "#" displays in modeline and no workspace choice to load presents

Please note that I get and error referencing "NSKeyedUnarchiver" every time I start (doom) emacs from the terminal. Most of the time I don't have any problem using emacs, but sometimes I do. This is one of those times. This error message in the terminal on startup may have nothing to do with this specific problem, of course. I just want to mention it. I've tried the only suggested remedy for getting rid of this error message (I found one in the Doom Emacs Discourse) to no avail. I'm attaching the full error message as part of a file called invalid-read-syntax.pdf that also contains 

1. output from debug-on-error
2. message buffer contents
3. doom.error.log contents
4. my config.el

Thank you!
[invalid-read-syntax.pdf](https://github.com/hlissner/doom-emacs/files/7945880/invalid-read-syntax.pdf)

### System Information

https://pastebin.com/t8CDNJBn

**Comment by hlissner** [comment] 2022-01-27 00:02
Duplicate of https://github.com/hlissner/doom-emacs/issues/6043

**Closed by hlissner** 2022-01-27 00:02 UTC
Labels: duplicate, delete me
