### ISSUE TITLE
If the build works, icons fail to load.

### ISSUE THREAD

**Issue by jorschach-g** [hlissner/doom-emacs#3924] opened 2020-09-10 20:26 UTC
Followed: function definition is void: ad-Advice-newline-and-indent #3172

With the 27.1 system upgrade, the enter key and the included icons (the flavor that changes with different layers of *) does not work under the current situation.

There might be some of the inner interference that not functioning under this specific build.
But as stated as other above, after using said method, which is:

> I'm currently having the same issue as well. I don't have org manually installed, and I can provide my config files if need be. I attempted to load org with `doom upgrade; doom sync && doom build` and no extra modules added and that still doesn't work.

As said above, with the force update, it still does not work.

And after remove and rebuild the org-* (org related) libs, icons are failing.

And the enter key half worked.

The said problem shall repeat itself after macOS reboot.

I do not yet know why.

But please fix it soon.

_Originally posted by @jorschach-g in https://github.com/hlissner/doom-emacs/issues/3172#issuecomment-690701924_

**Comment by jorschach-g** [comment] 2020-09-10 20:33
And with further testing, it seems that the build deprived of bold, strikethrough, and other word process capability that org-mode have.

**Comment by hlissner** [comment] 2020-09-10 22:05
Duplicate of #3172

**Closed by hlissner** 2020-09-10 22:05 UTC
Labels: is:duplicate
