### ISSUE TITLE
Ripgrep always terminates with `error code 2` on macOS

### ISSUE THREAD

**Issue by sfc-gh-mpilman** [hlissner/doom-emacs#3605] opened 2020-07-21 20:59 UTC
**What did you expect to happen?**
I am running `counsel-projectile-rg` on a project and I would expect to see files+lines where the entered string appears. Did used to work very well but broke recently (I didn't upgrade doom for a while, so I don't know where exactly this broke).

**What actually happened?**
I see the following error (`error code 2`):
<img width="278" alt="image" src="https://user-images.githubusercontent.com/65370928/88106212-5a461f80-cb62-11ea-9b08-a9bf503b3f14.png">
Sadly I couldn't figure out how to debug this. I can't break on error (seems no elisp error is happening) and I can't figure out which command emacs is executing (I am not a elisp programmer - so my debugging capabilities are limited).

**Additional details:**

`company-rg` is working fine:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/65370928/88106392-a6915f80-cb62-11ea-807b-8af9834e1e25.png">
So I am not quite sure what the difference between these two commands are, but maybe this additional information helps?

**Steps to reproduce:**
This just happened after upgrading to the newest doom emacs.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Nov 17, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop f3bb23aa7 2020-07-21 16:19:08 -0400")
  (dir . "~/.home/doom/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.0.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64")
  (path "~/bin" "/opt/local/bin" "/usr/local/bin" "/usr/local/sbin" "/opt/local/sbin" "~/.local/bin" "~/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/Apple/usr/bin" "~/Applications/SnowSQL.app/Contents/MacOS" "/usr/local/Cellar/llvm/9.0.0/bin" "~/.rvm/bin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +childframe) :ui doom doom-dashboard modeline doom-quit ophints hl-todo nav-flash (popup +all +defaults) vi-tilde-fringe window-select vc-gutter workspaces :editor format (evil +everywhere) snippets :emacs dired electric vc :tools eval editorconfig macos magit upload lookup lsp :checkers syntax :term eshell :lang (cc +lsp) csharp data emacs-lisp go markdown (org +capture +present) sh :config (default +bindings +snippets +evil-commands))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2020-07-21 21:07
This is a duplicate of #3038. See https://github.com/hlissner/doom-emacs/issues/3038#issuecomment-624165004 for workaround. 

Run `rg --with-filename --no-heading --line-number --color never TEXT` by hand on your project to determine what error is causing it. Please move discussion there.

**Closed by hlissner** 2020-07-21 21:07 UTC
Labels: is:duplicate

**Comment by sfc-gh-mpilman** [comment] 2020-07-21 21:58
thanks -  #3038 didn't look like the same problem... I will comment there.
