### ISSUE TITLE
[BUG] Invalid function `org-preserve-local-variables`

### ISSUE THREAD

**Issue by CGenie** [hlissner/doom-emacs#2362] opened 2020-01-13 05:30 UTC
It seems that bug https://github.com/hlissner/doom-emacs/issues/1205 is back again. Here's the traceback I'm getting when `toggle-debug-on-error` is turned on:

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (invalid-function org-preserve-local-variables)
  org-preserve-local-variables("Copied: Subtree(s) with 133 characters")
  org-copy-subtree(1 nil t)
  org-archive-subtree(nil)
  funcall-interactively(org-archive-subtree nil)
  call-interactively(org-archive-subtree nil nil)
  command-execute(org-archive-subtree)
</pre></details>

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 18301b0b9 2020-01-10 05:59:54 -0500
        dir        ~/org/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.1-arch1-1 #1 SMP PREEMPT Fri, 29 Nov 2019 13:37:24 +0000 x86_64
        path       (~/.opam/azuracast-stats/bin ~/.nix-profile/bin ~/.local/bin ~/go/bin /tmp/fnm-shell-1251044/bin ~/.gem/ruby/2.2.0/bin ~/perl5/bin ~/.gem/ruby/2.1.0/bin ~/bin ~/.cabal/bin ~/.cargo/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/android-ndk /opt/android-sdk/platform-tools /opt/brlcad/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl)
config  envfile    nil
        elc-files  200
        modules    (:completion company (ivy +fuzzy +icons +prescient) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors parinfer rotate-text snippets :emacs (dired +ranger +icons) electric vc :term eshell :tools direnv docker eval gist (lookup +docsets) lsp magit make pass pdf :lang data erlang emacs-lisp fsharp go (haskell +intero) hy javascript latex lua markdown nix ocaml (org +dragndrop +ipython +pandoc +present) perl purescript python racket rust sh web :email notmuch :app calendar irc :config (default +bindings +smartparens))
        packages   (general add-node-modules-path dante dash dash-functional doom-themes elixir-mode emms f (dired-git-info :recipe (:host github :repo "clemera/dired-git-info" :files (:defaults "*"))) diredful haskell-mode helm-org-rifle hledger-mode ivy-posframe json-navigator json-snatcher keyfreq ledger-mode lsp-haskell lsp-mode lsp-ui golden-ratio ocp-indent org-mime org-ql (org-sidebar :recipe (:host github :repo "alphapapa/org-sidebar")) org-static-blog org-sticky-header posframe reason-mode repl-toggle salt-mode tuareg undohist (vc-fossil :recipe (:host github :repo "venks1/emacs-fossil" :branch "trunk")))
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment] 2020-01-13 05:33
I'll close this as a duplicate of #1205 and continue this discussion there.

**Closed by hlissner** 2020-01-13 05:33 UTC
Labels: is:duplicate
