### ISSUE TITLE
magit-previous-line, magit-next-line not loaded even when magit-mode is

### ISSUE THREAD

**Issue by telotortium** [hlissner/doom-emacs#6101] opened 2022-02-09 21:00 UTC
### What did you expect to happen?

Pressing up and down arrow (the `magit-previous-line` and `magit-next-line` commands) should work in a Magit buffer at startup.

### What actually happened?

When I press these keys, I see the following errors:

```
command-execute: Wrong type argument: commandp, magit-next-line
command-execute: Wrong type argument: commandp, magit-previous-line
```

### Describe your attempts to resolve the issue

These are resolved if I `(require 'magit-extras)`, where these commands live. So right now I have in my config

```
(after! magit
  (require 'magit-extras))
```

### Steps to reproduce

See above.

### System Information

https://pastebin.com/7MjKsPxg

**Comment by hlissner** [comment] 2022-02-09 21:09
I cannot reproduce this with Doom's vanilla magit module. Since it seems you've "forked" the magit module, this looks like a local issue with your `package!` statement for magit, as both `magit-next-line` and `magit-previous-line` are [autoloaded](https://github.com/magit/magit/blob/master/lisp/magit-extras.el#L234-L277). I'll close this since this isn't a Doom issue, but feel free to follow up here.

**Closed by hlissner** 2022-02-09 21:09 UTC
Labels: invalid, delete me

**Comment by hlissner** [comment] 2022-02-09 21:12
Actually, it seems your `M-x doom/info` is indicating *all* your modules are in non-standard locations, so it's hard to tell if you actually copied it or not. Perhaps you're doing something nonstandard with the location of your .emacs.d and .doom.d?

**Comment by hlissner** [comment] 2022-02-09 21:13
Ah, I see, you've moved your .emacs.d _into_ .doom.d. That's new. This may be causing issues, since Doom treats your .doom.d as a special space. Try moving it out, preferably to `~/.doom.d` or `~/.config/doom`, then run `doom sync && doom build` and see if the issue goes away.

**Comment by telotortium** [comment] 2022-02-11 00:22
I would prefer not to move it out, because I add the Doom emacs.d as a submodule of my .doom.d Git repo so that I can version my config and Doom together. Do you support this use case? If not, I might add some custom code to my config.el to check the Doom Emacs commit on startup.
