### ISSUE TITLE
Feature Request - delayed eager loading

### ISSUE THREAD

**Issue by peterhoeg** [hlissner/doom-emacs#2787] opened 2020-03-29 00:56 UTC
**Describe the feature**

First of all, doom is awesome. 

So the problem  to address here is that while doom starts exceptionally fast, the first time you open a file in of the bigger modes, there is a noticeable delay as things are loaded.

If we could tag a mode (such as org) for delayed eager loading, then after a few seconds of inactivity after the various minor modes are loaded, the mode is loaded in the background and when the first file is opened, it's all ready to go.

**System information**
<details><pre>
- EMACSDIR=nil
- DOOMDIR=nil
- Auto-yes on
((emacs
  (version . "27.0.90")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Mar 29, 2020")
  (buildopts "--prefix=/nix/store/wjvcdc0v8a9xz8kn6svpxvxjhlk554qp-emacs-27.0.90-custom --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-xwidgets --with-cairo --with-harfbuzz --without-makeinfo CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 064603f6e 2020-03-28 20:08:53 -0400")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/nix/store/6n3in6lnnphm539aza7z6rn7yj0kh6q5-zsh-5.8/bin/zsh")
  (uname . "Linux 5.5.9 #1-NixOS SMP Thu Mar 12 06:18:49 UTC 2020 x86_64")
  (path "/nix/store/q2jgyn66i7h2vcsc5irkkpv6p2b4jdif-emacs-packages-deps/bin" "/nix/store/s3hyvgxag7nplm3hf5myxm64zvc2sa3i-emacs-bin-env/bin" "~/.local/bin" "~/.local/bin" "/run/wrappers/bin" "~/.local/share/flatpak/exports/bin" "/var/lib/flatpak/exports/bin" "~/.nix-profile/bin" "/etc/profiles/per-user/peter/bin" "/nix/var/nix/profiles/default/bin" "/run/current-system/sw/bin" "/nix/store/7ai901gmznr8fgimybzsbgfpidx1i79q-sub-p-2019-12-18T17-49-51+08-00/share/p/bin" "/nix/store/izjmiryj8kx1ykd62bxz20j1sghb1ckr-sub-q-2020-02-24T21-54-51+08-00/share/q/bin" "~/.config/zsh/plugins/fzf-marks" "/nix/store/7ai901gmznr8fgimybzsbgfpidx1i79q-sub-p-2019-12-18T17-49-51+08-00/share/p/bin" "/nix/store/izjmiryj8kx1ykd62bxz20j1sghb1ckr-sub-q-2020-02-24T21-54-51+08-00/share/q/bin" "/nix/store/wjvcdc0v8a9xz8kn6svpxvxjhlk554qp-emacs-27.0.90-custom/libexec/emacs/27.0.90/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 175)
  (modules :completion (company +childframe) (ivy +childframe +icons) :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) rotate-text snippets word-wrap :emacs dired electric vc :term vterm :checkers grammar spell (syntax +childframe) :tools debugger direnv editorconfig (eval +overlay) (lookup +dictionary +docsets) (lsp +peek) magit make pass rgb :lang (cc +lsp) crystal data emacs-lisp (haskell +lsp) markdown nix (org +hugo +pandoc +pomodoro +present) plantuml (python +lsp) rest (ruby +lsp +rails) (sh +lsp) :email mu4e :config (default +bindings +smartparens))
  (packages (heaven-and-hell))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment] 2020-03-29 01:18
Delayed (and incremental) eager loading [already exists in Doom](https://github.com/hlissner/doom-emacs/blob/develop/core/core.el#L341-L414). Big packages like org and magit are incrementally loaded this way.

Unfortunately, lazy loading is not the cause of that slowness you're seeing. If you eager load `org` at startup, you'll still notice a slow first-time load of any org file.

So what's the real problem? I'm not sure. Flyspell adds a few seconds to it; not much we can do about that without disabling it or rewriting that package. And I can reproduce this delay in vanilla emacs, so evidently it is in org's nature to start up slowly the first time -- if that's so, not sure there's any we can do about it.

**Comment by peterhoeg** [comment] 2020-03-29 06:33
>   Delayed (and incremental) eager loading already exists in Doom. Big
>   packages like org and magit are incrementally loaded this way.

I ignorantly assumed that was the case due to org being slow - apologies.

>   So what's the real problem? I'm not sure. Flyspell adds a few seconds to
>   it; not much we can do about that without disabling it or rewriting that
>   package.

According to the emacs profiler, when opening a new .org file immediately after launch, yasnippet uses 55% CPU.

I'll dig around next weekend to see if I can find something.

**Comment by hlissner** [comment] 2020-04-18 02:24
I'll close this for now, but feel free to follow up here if you find anything.

**Closed by hlissner** 2020-04-18 02:24 UTC
Labels: :lang org, is:emacs, re:performance, status:nofix
