### ISSUE TITLE
Doom install (fresh checkout) or doom upgrade does not work

### ISSUE THREAD

**Issue by duck2code** [hlissner/doom-emacs#5096] opened 2021-05-25 18:01 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

I expect Doom Emacs to do upgrade correctly. I'm running this on Apple MacOS Catalina using brew emacs 27.2.

### What actually happened?

10:52 $ doom install
> Installing straight...

error: unknown switch `b'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree
fatal: remote origin already exists.
fatal: expected shallow/unshallow, got ERR upload-pack: not our ref e46292db6910e8e7701d53acaf188de0101ae30f
fatal: The remote end hung up unexpectedly
fatal: Could not parse object 'e46292db6910e8e7701d53acaf188de0101ae30f'.
  ✓ Done!
x There was an unexpected error
  Message: File is missing
  Data: (file-missing . "Cannot open load file")
  Backtrace:
    (require straight "/Users/ajchen/.emacs.d/.local/straight/repos/straight.e
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli
    (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist
    (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-w
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight
    (doom-initialize-core-packages)
    (eval-buffer #<buffer  *load*-621506> nil "/Users/ajchen/.emacs.d/core/cor
    (load-with-code-conversion "/Users/ajchen/.emacs.d/core/core-cli.el" "/Use
! Extended backtrace logged to .emacs.d/.local/doom.error.log
No catch for tag: exit, 255

### Describe your attempts to resolve the issue

Tried fresh install via git clone and didn't work after `doom upgrade` failed.

### Steps to reproduce

1. Do git clone of Doom Emacs.
2. Run .emacs.d/bin/doom install

### System Information

https://pastebin.com/HhzEqzKb

**Comment by hlissner** [comment] 2021-05-25 18:07
Duplicate of #5088.

Git 2.28 is required

**Closed by hlissner** 2021-05-25 18:07 UTC
Labels: delete me, duplicate
