### ISSUE TITLE
Buffer Manipulation Regression

### ISSUE THREAD

**Issue by ohhskar** [hlissner/doom-emacs#4535] opened 2021-01-18 02:25 UTC
**What did you expect to happen?**
Managing buffers to work properly:
- Killing buffers when in a tab to kill a buffer only when using SPC-b-d
- Show other workspace buffers when using SPC-b-b
- Kill other buffers when using SPC-b-O
- Show doom-dashboard when starting a new window or killing buffers

**What actually happened?**
Buffers not working properly:
- Entire tab window is killed when running SPC-b-d
- 0 workspace buffers are present, but shown in ibuffer
- 0 buffers are killed even when other buffers are present
- doom-dashboard does not show, only the scratch buffer is shown

**Additional details:**
[Personal Config](https://github.com/ohhskar/.doom.d)

View Echo Area Messages
```
Starting Emacs daemon.
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
define-obsolete-function-alias: Wrong number of arguments: (3 . 4), 2
When done with this frame, type SPC q f
Buffer is read-only: #<buffer  *Treemacs-Scoped-Buffer-Perspective #1*>
o p is undefined
SPC ESC is undefined
Error in minibuffer-exit-hook (+ivy--set-jump-point-maybe-h): (void-variable +ivy--origin)
Switched to ’MPA2’
Loading /home/ohhskar/.emacs.d/.local/cache/recentf...done
Note: c-basic-offset, tab-width, evil-shift-width adjusted to 2
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
File mode specification error: (doom-hook-error +cc-init-rtags-maybe-h (wrong-number-of-arguments (3 . 4) 2))
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
Error in post-command-hook (rtags-post-command-hook): (wrong-number-of-arguments (3 . 4) 2)
Quit
SPC ESC is undefined
Note: c-basic-offset, tab-width, evil-shift-width adjusted to 2
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
File mode specification error: (doom-hook-error +cc-init-rtags-maybe-h (wrong-number-of-arguments (3 . 4) 2))
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
Error in post-command-hook (rtags-post-command-hook): (wrong-number-of-arguments (3 . 4) 2)
Quit
Updating buffer list...
Formats have changed, recompiling...done
Updating buffer list...done
ibuffer-projectile: groups set
Commands: m, u, t, RET, g, k, S, D, Q; q to quit; h for help
Quit [5 times]
Killed 0 other buffers [2 times]
Quit [2 times]
evil-line-move: Beginning of buffer [2 times]
```

**Steps to reproduce:**
1. Start a new emacs instance ( Doom-dashboard not showing here)
2. Open a project and initial buffer `SPC p p`
3.  Open a new buffer
3.1  using Dired `SPC o -`
or
3.2  using treemacs `SPC o p`
4. Kill other buffers `SPC b O` (0 buffers killed)
5. Try to change to another buffer in works `SPC b b` (0 workspaces shown)
6. Kill a buffer in tab `SPC b d` (Entire tab window killed)

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.10.7-arch1-1 #1 SMP PREEMPT Wed, 13 Jan 2021 12:02:01 +0000 x86_64
        path       (~/.local/share/nvm/v15.6.0/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Jan 17, 2021
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-pgtk --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 PGTK XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (gui daemon server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil Iosevka Term nil nil regular nil nil 18 nil nil nil nil>
        theme      doom-tomorrow-night
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD b03fdabe 2021-01-13 14:07:47 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo indent-guides modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric ibuffer undo vc :checkers syntax spell :tools (eval +overlay) lookup magit :lang cc emacs-lisp javascript markdown org sh web :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by ohhskar** [comment] 2021-01-18 02:27
I'm inclined to believe this is a Emacs 28+ issue based on #4534 as the same errors occur: `Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)`.

**Comment by hlissner** [comment] 2021-01-18 02:30
It is indeed a duplicate of #4534. Your other issues are likely a result of the error. See #4534 for a workaround.

**Closed by hlissner** 2021-01-18 02:30 UTC
Labels: duplicate
