### ISSUE TITLE
Missing icons in company popup

### ISSUE THREAD

**Issue by memeplex** [hlissner/doom-emacs#5563] opened 2021-10-02 22:11 UTC
### What did you expect to happen?

When a company autocompletion popup opens, there are icons at the LHS of each item of the list.

### What actually happened?

Empty black boxes appear instead.

![image](https://user-images.githubusercontent.com/2845433/135732927-7c2ad643-3126-49f4-8a84-30d8cfc38dd6.png)

### Describe your attempts to resolve the issue

Rerun `all-the-icons-install-fonts` and checked that all went ok.

Checked that the fonts were properly installed under `~/Library/Fonts`.

Followed the troubleshooting instructions here https://github.com/domtronn/all-the-icons.el#troubleshooting.

### Steps to reproduce

1. Create a simple python file somewhere.
2. Open it using doom-emacs.
3. Try to autocomplete some stuff, for example:

```
class C:
     def f(): pass
c = C()
c.<ctrl-space>
```

### System Information

https://pastebin.com/GdZqbAjx

**Comment by memeplex** [comment] 2021-10-02 23:27
I've enabled lsp/pyright and things now look like:

![image](https://user-images.githubusercontent.com/2845433/135734227-e95771fd-3ee6-4eac-925e-6521b71c37b9.png)

That weird box seems to be for the likes of snippets, is it actually an icon? In that case, it doesn't seem like a good choice to me, it really looks like something is missing.

**Comment by hlissner** [comment] 2021-10-03 09:41
This is not a bug, though I agree it's an odd default. [Company simply uses this icon for snippets](https://github.com/company-mode/company-mode/blob/master/icons/vscode-dark/symbol-snippet.svg). Please request [upstream](https://github.com/company-mode/company-mode) that they choose a better one.

As this is not a Doom issue I will close it.

**Closed by hlissner** 2021-10-03 09:41 UTC
Labels: invalid, delete me

**Comment by memeplex** [comment] 2021-10-03 19:22
I see, I started a discussion upstream (since that's their channel for feature requests): https://github.com/company-mode/company-mode/discussions/1233. Thank you.
