### ISSUE TITLE
lsp-mode: how to use other flycheck checkers

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#1530] opened 2019-07-02 08:19 UTC
lsp-mode use lsp-ui as it's default flycheck checker, and it runned by language server. If I want to add new flycheck checker after lsp-ui, how should I do?

I have tried:

```
(defun my-flycheck-setup ()
  (flycheck-add-next-checker 'lsp-ui 'python-pylint)
)

(add-hook 'python-mode-hook 'my-flycheck-setup)
```

**Comment by hlissner** [comment] 2019-07-02 12:24
Give this a try:


```elisp
(defun my-flycheck-setup ()
  (flycheck-add-next-checker 'lsp-ui 'python-pylint))

;; These MODE-local-vars-hook hooks are a Doom thing. They're executed after MODE-hook, on
;; hack-local-variables-hook. Although `lsp!` is attached to python-mode-local-vars-hook, it should 
;; occur earlier than my-flycheck-setup this way:
(add-hook 'python-mode-local-vars-hook #'my-flycheck-setup)
```

**Comment by gagbo** [comment] 2019-08-23 06:33
Seems to work fine 👍 

![Capture d’écran 2019-08-23 à 08 28 51](https://user-images.githubusercontent.com/10496163/63571479-9bb00280-c580-11e9-8e3a-6bc985ae37f6.png)

**Comment by vikigenius** [comment] 2019-11-15 00:21
@hlissner 

This doesn't seem to work any more I have an error in my messages buffer saying:

```
File local-variables error: (doom-hook-error my-flycheck-setup (error lsp-ui is not a valid syntax checker))
```

**Comment by vikigenius** [comment] 2019-11-15 00:30
Ok I changed the hook to ``lsp-ui-mode-local-vars-hook`` now it works fine

**Comment by hlissner** [comment] 2019-11-15 01:14
@vikigenius `MODE-local-vars-hook` hooks are only run for major modes. `lsp-ui-mode` is a minor mode. You're getting no error before it's not being run.

I can't reproduce your other issues.

**Comment by gagbo** [comment] 2019-11-15 09:28
I'm using the method we discussed about in the discord (using the `local-vars-hook` method to create a `lsp-ui-hook` family)

```lisp
;; config.el
(after! lsp-ui
  (add-hook! 'lsp-ui-mode-hook
    (run-hooks (intern (format "%s-lsp-ui-hook" major-mode)))))

(defun gagbo-go-flycheck-setup ()
  "Setup Flycheck checkers for Golang"
  (flycheck-add-next-checker 'lsp-ui 'golangci-lint))

(add-hook 'go-mode-lsp-ui-hook
          #'gagbo-go-flycheck-setup)

(defun gagbo-python-flycheck-setup ()
  "Setup Flycheck checkers for Python"
  (flycheck-add-next-checker 'lsp-ui 'python-pylint))

(add-hook 'python-mode-lsp-ui-hook
          #'gagbo-python-flycheck-setup)
```

With this I don't have any issues running multiple checkers (these days I mostly use Go, I didn't check again for Python)

Side note 1 :
The `next-checkers` attribute list is a global one. Meaning after a long session, changing mode/projects multiple times, the `next-checker` attribute of `'lsp-ui` checker will be very long with a lot of duplicate. I don't know how it affects performance yet

Side note 2 :
That will also probably allow me to disable some lsp-ui features for specific languages/major-modes.

Side note 3 :
Actually I would have liked a way to disable lsp-ui altogether for specific languages, and with this method it's possible but lsp-ui will have to load before being deactivated (since the hook is after lsp-ui is loaded). For now I don't need to do this so I don't care, but maybe that's worth exploring

**Comment by egidijusz** [comment] 2019-12-13 17:29
I've added 
```lisp
(add-hook 'lsp-after-initialize-hook (lambda
                                       ()
                                       (flycheck-add-next-checker 'lsp-ui 'elixir-credo)))
```
to my `~/.doom.d/config.el` which seems to be working fine too (and is not duplicating entries in `next-chekers` list, to my knowledge).

**Comment by polothy** [comment] 2020-05-31 16:30
Hrm, none of these seemed to do anything when I added them to my `config.el`.  Trying to get `golangci-lint` to run while using `lsp-mode`.  Just curious if anyone had any updated workarounds I could try?  If not, sorry for the noise!

**Comment by gagbo** [comment] 2020-05-31 20:58
The checker has been renamed from `lsp-ui` to `lsp`, so changing the name like this should work.

Also, a recent patch of Doom (yesterday I believe ?) automated the change; if you already have golangci-lint as your flycheck linter when lsp starts, lsp will just add itself to golangci

**Comment by polothy** [comment] 2020-06-01 02:22
That fixed it! Thanks very much!

**Comment by blez** [comment] 2020-11-11 18:32
Somewhy this fix https://github.com/hlissner/doom-emacs/commit/134554dd69d9b1cea3d2190422de580fddf40ecd does not work for me.
I have the following in my config.el
```
(add-hook 'go-mode-local-vars-hook
          (lambda ()
            (when (flycheck-may-enable-checker 'golangci-lint)
              (flycheck-select-checker 'golangci-lint))))
```
And I can see errors only from `golangci-lint`

**Comment by alexppg** [comment] 2021-07-18 12:11
It seems that this doesn't work anymore. When checking the `flycheck-checker` on a golang buffer, its value is `lsp`.

> ```
> (add-hook! 'lsp-after-initialize-hook
>   (run-hooks (intern (format "%s-lsp-hook" major-mode))))
> (defun go-flycheck-setup ()
>   (flycheck-add-next-checker 'lsp 'golangci-lint))
> (add-hook 'go-mode-lsp-hook
>           #'go-flycheck-setup)
> ```

**Comment by blez** [comment] 2021-07-19 09:45
@alexppg It still works for me
Try to run `flycheck-verify-setup` maybe you will see why `golangci-lint` is not presented

**Comment by alexppg** [comment] 2021-07-21 15:15
That's actually true, I wasn't aware of that function, thanks! I actually tried in other modes, but having this, I'll update again if I really can't make it work.

**Comment by jtpavlock** [comment] 2021-08-06 00:48
Should this be re-labeled as a bug in doom/upstream? Yes, there's a workaround, but doom currently ships "broken".

**Comment by hlissner** [comment] 2021-08-06 07:59
Instead of adding it to `go-mode-lsp-hook`, it may work to just _append_ the hook to `go-mode-local-vars-hook`, e.g. 

`(add-hook 'go-mode-local-vars-hook #'go-flycheck-setup 'append)`

I've updated my earlier snippet with that.

------

> Should this be re-labeled as a bug in doom/upstream?

This is an upstream issue. LSP and flycheck give us clunky interfaces for chaining checkers, especially when LSP activation is deferred, as it currently is in Doom.

In any case, this thread was started as a how-to request for support, which is no longer welcome on our issue tracker (use our Discord for that), so I will close this, but feel free to follow up here.

**Closed by hlissner** 2021-08-06 07:59 UTC
Labels: re:elisp, :checkers syntax, :tools lsp, 1. question
