### ISSUE TITLE
doom cli initializes straight too early.

### ISSUE THREAD

**Issue by guraltsev** [hlissner/doom-emacs#3371] opened 2020-06-12 20:06 UTC
**What did you expect to happen?**
Get documentation from `doom` cli by issuing from my home dir: 
Windows:
```
.emacs.d\bin\doom.cmd --help
```
Linux:
```
~/.emacs.d/bin/doom --help
```
and get a help message

**What actually happened?**
doom starts installing `straight` even if `sync` is not specified on the command line.

**Comment by hlissner** [comment] 2020-06-12 20:16
That's the expected behavior. Doom needs straight bootstrapped early, because it is used to install other core dependencies that the CLI itself (and Doom core in general) need.

**Comment by hlissner** [comment] 2020-06-12 20:19
I'm working on a CLI rewrite which should address this, but for the time being I'll close this as it's not really a bug.

**Closed by hlissner** 2020-06-12 20:19 UTC
Labels: is:invalid
