### ISSUE TITLE
(wrong-type-argument stringp mouse-wheel-down-event) on Emacs 27.1, on openSUSE

### ISSUE THREAD

**Issue by PerunaVelho** [hlissner/doom-emacs#3784] opened 2020-08-20 00:15 UTC
i did a fresh OpenSuse TW install and magit and org are not working. The error message for everything is:

```
Failed to load magit package incrementally, because: (wrong-type-argument stringp mouse-wheel-down-event)"
```

Sidenote: starting with emacs-x11 command does not produce the errors so it might be something to do with the Emacs launcher script on Open Suse and dbus but i'm not certain as it goes wayyy over my head. There is a solution which is to alias emacs to emacs-x11 systemwide but i feel like the dbus gymnastics are there for a reason.

**Comment by hlissner** [comment] 2020-08-20 04:56
This is a known issue with a build of Emacs 27.1 on openSUSE Tumbleweed. I'm not certain of the cause. I don't know enough about openSUSE and its ecosystem to suggest where to get a working build of 27.1 from. @agraul can you advise?

**Comment by agraul** [comment] 2020-08-20 09:57
I've been using [this one](https://build.opensuse.org/package/show/home:AndreasSchwab:emacs:27/emacs) without any problems for the last months (RCs at first), you can switch to it with
```
zypper addrepo obs:// home:AndreasSchwab:emacs:27 emacs27
zypper refresh emacs27
zypper dup --allow-vendor-change --from emacs27
```
Disclaimer: That is a personal repository and I don't know if its maintainer accepts bug reports. Please only use it temporarily until the package in the distribution is fixed.

There is a mailing list [thread](https://lists.opensuse.org/opensuse-factory/2020-08/msg00167.html) about this issue with a [mail](https://lists.opensuse.org/opensuse-factory/2020-08/msg00172.html) that mentions the `/usr/bin/emacs` script. There is also a link to a bug report in that mail, but that bug does not contain much information. The bug is marked as fixed, but the update is still in QA before it reaches Tumbleweed. I don't know if that bug is the very same as what you describe, once the update is out you can try again.

Sadly I also don't really grasp the helper script and can't help with that.

**Comment by tecosaur** [comment] 2020-08-25 13:19
As another stopgap measure, running
```elisp
(assq-delete-all 'mouse-wheel-down-event load-history)
```
Seems to do the trick.

**Comment by tecosaur** [comment] 2020-09-04 02:54
I believe this has been fixed with the latest update :smiley:

**Comment by brejoc** [comment] 2020-09-04 07:07
Can confirm that the latest update to emacs in Tumbleweed fixed it. That's version `27.1-3.1`.

**Closed** 2020-09-04 09:32 UTC
Labels: is:external, re:openSUSE, status:has-workaround
