### ISSUE TITLE
File mode specification error (ledger-mode)

### ISSUE THREAD

**Issue by jackbaty** [hlissner/doom-emacs#2509] opened 2020-02-09 19:42 UTC
**What did you expect to happen?**
Open a .ledger file into ledger-mode without error

**What actually happened?**
When opening my 2020.ledger file, the following shows in messages and the mini buffer...

> File mode specification error: (wrong-type-argument stringp (hledger ledger))

The buffer claims to be in ledger-mode but there's no syntax highlighting at all.

If I cheat and replace the recently-updated lines [here](https://github.com/hlissner/doom-emacs/blob/af9d8257f18f3eb2c0ee7b751c4f6d69be4a93dd/modules/lang/ledger/config.el#L11) with a simple path like "/usr/local/bin/ledger", the error does not occur.

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument stringp ("hledger" "ledger"))
  locate-file-internal(("hledger" "ledger") ("/Users/jbaty/bin/" "/Users/jbaty/Library/Python/3.7/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/Apple/usr/bin" "/Library/Apple/bin" "/usr/local/go/bin" "/Library/TeX/texbin" "." "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/") ("") 1)
  locate-file(("hledger" "ledger") ("/Users/jbaty/bin/" "/Users/jbaty/Library/Python/3.7/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/Apple/usr/bin" "/Library/Apple/bin" "/usr/local/go/bin" "/Library/TeX/texbin" "." "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/") ("") 1)
  executable-find(("hledger" "ledger"))
  (if (executable-find ledger-binary-path) (funcall orig-fn) (message "Couldn't find '%s' executable" ledger-binary-path))
  +ledger--check-version-a(#f(compiled-function () (interactive nil) #<bytecode 0x45b33139>))
  apply(+ledger--check-version-a #f(compiled-function () (interactive nil) #<bytecode 0x45b33139>) nil)
  ledger-check-version()
  (let ((delay-mode-hooks t)) (text-mode) (setq major-mode (quote ledger-mode)) (setq mode-name "Ledger") (progn (if (get (quote text-mode) (quote mode-class)) (put (quote ledger-mode) (quote mode-class) (get (quote text-mode) (quote mode-class)))) (if (keymap-parent ledger-mode-map) nil (set-keymap-parent ledger-mode-map (current-local-map))) (let ((parent (char-table-parent ledger-mode-syntax-table))) (if (and parent (not (eq parent (standard-syntax-table)))) nil (set-char-table-parent ledger-mode-syntax-table (syntax-table)))) (if (or (abbrev-table-get ledger-mode-abbrev-table :parents) (eq ledger-mode-abbrev-table local-abbrev-table)) nil (abbrev-table-put ledger-mode-abbrev-table :parents (list local-abbrev-table)))) (use-local-map ledger-mode-map) (set-syntax-table ledger-mode-syntax-table) (setq local-abbrev-table ledger-mode-abbrev-table) (ledger-check-version) (setq font-lock-defaults (quote (ledger-font-lock-keywords t nil nil nil))) (add-hook (quote font-lock-extend-region-functions) (quote ledger-fontify-extend-region)) (add-hook (quote completion-at-point-functions) (function ledger-complete-at-point) nil t) (add-hook (quote after-save-hook) (quote ledger-report-redo) nil t) (add-hook (quote post-command-hook) (quote ledger-highlight-xact-under-point) nil t) (ledger-init-load-init-file) (set (make-local-variable (quote comment-start)) ";") (set (make-local-variable (quote indent-line-function)) (function ledger-indent-line)) (set (make-local-variable (quote indent-region-function)) (quote ledger-post-align-postings)))
  (progn (make-local-variable (quote delay-mode-hooks)) (let ((delay-mode-hooks t)) (text-mode) (setq major-mode (quote ledger-mode)) (setq mode-name "Ledger") (progn (if (get (quote text-mode) (quote mode-class)) (put (quote ledger-mode) (quote mode-class) (get (quote text-mode) (quote mode-class)))) (if (keymap-parent ledger-mode-map) nil (set-keymap-parent ledger-mode-map (current-local-map))) (let ((parent (char-table-parent ledger-mode-syntax-table))) (if (and parent (not (eq parent ...))) nil (set-char-table-parent ledger-mode-syntax-table (syntax-table)))) (if (or (abbrev-table-get ledger-mode-abbrev-table :parents) (eq ledger-mode-abbrev-table local-abbrev-table)) nil (abbrev-table-put ledger-mode-abbrev-table :parents (list local-abbrev-table)))) (use-local-map ledger-mode-map) (set-syntax-table ledger-mode-syntax-table) (setq local-abbrev-table ledger-mode-abbrev-table) (ledger-check-version) (setq font-lock-defaults (quote (ledger-font-lock-keywords t nil nil nil))) (add-hook (quote font-lock-extend-region-functions) (quote ledger-fontify-extend-region)) (add-hook (quote completion-at-point-functions) (function ledger-complete-at-point) nil t) (add-hook (quote after-save-hook) (quote ledger-report-redo) nil t) (add-hook (quote post-command-hook) (quote ledger-highlight-xact-under-point) nil t) (ledger-init-load-init-file) (set (make-local-variable (quote comment-start)) ";") (set (make-local-variable (quote indent-line-function)) (function ledger-indent-line)) (set (make-local-variable (quote indent-region-function)) (quote ledger-post-align-postings))))
  ledger-mode()
  set-auto-mode-0(ledger-mode nil)
  #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x400923ab>)()
  apply(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x400923ab>) nil)
  so-long--set-auto-mode(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x400923ab>))
  apply(so-long--set-auto-mode #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x400923ab>) nil)
  #f(advice-wrapper :around #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x400923ab>) so-long--set-auto-mode)()
  apply(#f(advice-wrapper :around #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x400923ab>) so-long--set-auto-mode) nil)
  set-auto-mode()
  normal-mode(t)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40091bc7>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40091bc7>) (nil t))
  (if (setq doom-large-file-p (and buffer-file-name (not doom-large-file-p) (file-exists-p buffer-file-name) (condition-case nil (progn (> (nth 7 (file-attributes buffer-file-name)) (* 1024 1024 (assoc-default buffer-file-name doom-large-file-size-alist ...)))) (error nil)))) (prog1 (apply orig-fn args) (if (memq major-mode doom-large-file-excluded-modes) (setq doom-large-file-p nil) (if (fboundp (quote so-long-minor-mode)) (progn (so-long-minor-mode 1))) (message "Large file detected! Cutting a few corners to improve performance..."))) (apply orig-fn args))
  doom--optimize-for-large-files-a(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40091bc7>) nil t)
  apply(doom--optimize-for-large-files-a #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40091bc7>) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer 2019.ledger> "~/sync/Ledger/2019.ledger" nil nil "~/sync/Ledger/2019.ledger" (89262362 16777220))
  find-file-noselect("~/sync/Ledger/2019.ledger" nil nil nil)
  find-file("~/sync/Ledger/2019.ledger")
  #f(compiled-function (f) #<bytecode 0x4572f76d>)("~/sync/Ledger/2019.ledger")
  ivy-call()
 [snip]
</pre></details>

**Steps to reproduce:**
1. Open any .ledger file

**System information:**
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Nov 17, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop af9d8257f 2020-02-09 04:33:17 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /usr/local/bin/fish
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (~/bin/ ~/Library/Python/3.7/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /Library/Apple/bin /usr/local/go/bin /Library/TeX/texbin . /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer vc :tools (eval +overlay) :checkers spell :tools (lookup +docsets) macos magit make pdf :lang clojure common-lisp data emacs-lisp latex ledger markdown (org +dragndrop +hugo +pandoc +present) ruby (sh +fish) web :app (rss +org) :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (org-ql) (org-journal) (posframe) (ivy-posframe) (org-roam :recipe (:host github :repo jethrokuan/org-roam)))
        elpa       (n/a)
        unpin      (n/a)
```
</details>

**Comment by hlissner** [comment] 2020-02-09 19:56
Sorry about that. Looks like a regression. https://github.com/hlissner/doom-emacs/pull/2508 was just merged with a fix for this issue. Thanks for bringing it to my attention!

**Closed by hlissner** 2020-02-09 19:56 UTC
Labels: :lang ledger, is:regression, status:resolved
