### ISSUE TITLE
Literate config: Tangling not working with latest changes to modules/config/literate/autoload.el 

### ISSUE THREAD

**Issue by colormotor** [hlissner/doom-emacs#3729] opened 2020-08-11 14:10 UTC
**What did you expect to happen?**
Generating an updated `config.el` from `config.org` with `doom sync` 

**What actually happened?**
The file is not updated and the log states:
`Tangled 0 code blocks from config.org`

**Additional details:**
I am really not  experienced with Elisp, but it seems that the contents of `config.org` are not copied to the temporary buffer in `autoload.el`. I suspect maybe it is a compatibility issue with my version of org? I checked and I am using 9.4.

I tested earlier versions of `autoload.el` and everything works with #8580b53. The version previous to the latest, logs that the source code block has been tangled, but the `config.el` file is not generated.

I pulled the most recent version of doom with `doom upgrade`, and tried using a basic config:
```
#+TITLE: Emacs Doom Config
#+PROPERTY: header-args :emacs-lisp :tangle yes :cache yes :results silent :comments link :exports code
#+BEGIN_SRC emacs-lisp
(message "test")
#+END_SRC
```
I am running doom on OSX.

**Comment by hlissner** [comment] 2020-08-11 18:01
My bad. This was caused by a regression in eb9cb0c6e. As of https://github.com/hlissner/doom-emacs/commit/64dfc709bf783848b6f27e70fe08ba5ce44ce6a0 this should be fixed. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Closed** 2020-08-11 18:01 UTC
Labels: is:bug

**Comment by colormotor** [comment] 2020-08-11 20:05
Thanks you for the quick fix and for the great work!
