### ISSUE TITLE
variable-pitch (face) /= doom-variable-pitch-font

### ISSUE THREAD

**Issue by egorbelibov** [hlissner/doom-emacs#4999] opened 2021-05-07 12:14 UTC
After upgrading to `Doom v2.0.9 (HEAD -> develop b2c4e0f16 2021-05-07 02:37:47 -0400)` I have noticed that `eww` has its face set to `Sans-serif`, even though I have `doom-variable-pitch-font` set to `(font-spec :family "JetBrains Mono" :size 12)`

**What did you expect to happen?**
The `variable-pitch` font in `eww` should be the same as `doom-variable-pitch-font`.

**What actually happened?**
The `variable-pitch` font in `eww` is `Sans-serif`, which doesn't correspond to the `doom-variable-pitch-font`.

**Additional details:**
My font config:
```emacs-lisp
(setq
 doom-font (font-spec :family "JetBrains Mono" :size 12)
 doom-big-font (font-spec :family "JetBrains Mono" :size 12)
 doom-variable-pitch-font (font-spec :family "JetBrains Mono" :size 12)
 doom-serif-font (font-spec :family "JetBrains Mono" :size 12))
```

Current workaround is:
```emacs-lisp
(custom-set-faces
 '(variable-pitch ((t (:family "JetBrains Mono")))))
```

**Steps to reproduce:**
1. upgrade Doom emacs to latest version (Doom v2.0.9 (HEAD -> develop b2c4e0f16)
2. open any page in the eww browser
3. check font with: SPC h F (It is not the same as `doom-variable-pitch-font`)

**System information:**
https://pastebin.com/EmkzqMGr

**Comment by hlissner** [comment] 2021-05-07 17:33
Duplicate of #5000.

In the future please _please_ do not ignore the issue template.

**Comment by egorbelibov** [comment] 2021-05-07 19:31
@hlissner Seems like hlissner/doom-emacs@578dddd did not fix this specific issue. As per you request, I've updated the issue description. Let me know if you need anything else to replicate this. Thanks you.

**Comment by hlissner** [comment] 2021-05-07 20:34
Please follow up in #5000.

**Closed by hlissner** 2021-05-07 20:34 UTC
Labels: duplicate

**Comment by egorbelibov** [comment] 2021-05-07 20:36
Just FYI: I think it might have something to do with the merging of this piece of code: https://github.com/hlissner/doom-emacs/blob/9ef11d0e3129d7bce754b208726e2be25377ac72/core/core-ui.el#L596-L615

**Comment by egorbelibov** [comment] 2021-05-07 21:05
Reverting `((variable-pitch ((t (:font ,doom-variable-pitch-font))))))))` to `(set-face-attribute 'variable-pitch nil :font doom-variable-pitch-font))))` fixes it.
