### ISSUE TITLE
Recursive load workspaces.el

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#470] opened 2018-03-21 12:28 UTC
### Observed behavior
Latest develop branch gives the following error and fails to start emacs.
<img width="593" alt="screen shot 2018-03-21 at 21 21 35" src="https://user-images.githubusercontent.com/1908865/37709761-91720104-2d4e-11e8-8553-93751359deae.png">

### Steps to reproduce

1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.

### System information

- Mac OSX 10.12
- GNU Emacs 25.3.1

**Comment by hlissner** [comment] 2018-03-22 09:18
I'm able to reproduce this. It appears to be a bug on Emacs 25.3 on MacOS, and doesn't appear on Emacs 26 or on Linux. I'll look into this.

**Comment by hlissner** [comment] 2018-03-22 10:58
And done! This has been fixed in `develop`. Let me know if that isn't the case!

I'll leave this issue open until it gets merged into `master`.

**Comment by zeronone** [comment] 2018-03-22 12:16
@hlissner Yep, it is fixed. 👍

**Comment by russmatney** [comment] 2018-03-25 15:58
Thanks for the quick fix!

Sadly, I'm hitting another `Recursive load: ".emacs.d/core/autoload/buffers.el"`:

![screen shot 2018-03-25 at 11 44 55 am](https://user-images.githubusercontent.com/1596350/37876970-333bb7de-3022-11e8-8cc8-28a41cf3a994.png)

Upgrading to emacs 26 fixed it for me - to anyone looking to do that, on OSX that means downloading the 26.0.91-1 pretest [at emacs for osx](https://emacsformacosx.com/builds) and/or `brew upgrade --devel emacs`/`brew upgrade --devel emacs-plus`

**Comment by hlissner** [comment] 2018-03-26 20:59
@russmatney Hmm, I'm unable to reproduce your issue on Emacs 25.3 on MacOS. Do you have your config up on github somewhere where I can see it?

**Comment by russmatney** [comment] 2018-03-27 02:14
@hlissner I had some trouble reproducing but was finally able to - seeing this issue plus a handful of errors in emacs 25.3. Error output at startup:

```
Error (use-package): smartparens/:catch: Invalid byte opcode: op=183, ptr=11
Error (use-package): evil/:config: Invalid byte opcode: op=183, ptr=34
Error (use-package): evil-visualstar/:init: Invalid byte opcode: op=183, ptr=2
Error (use-package): ivy/:catch: Symbol’s function definition is void: record
Warning (initialization): An error occurred while loading ‘/Users/dot/.emacs.d/init.el’:

error: Invalid byte opcode: op=183, ptr=2

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
Error (doom-init-hook): void-function in ’ivy-mode’ -> Symbol’s function definition is void: record
Error (doom-init-hook): void-function in ’savehist-mode’ -> Symbol’s function definition is void: record
Error (doom-init-hook): error in ’doom|init-ui’ -> Recursive load: "/Users/dot/.emacs.d/core/autoload/buffers.el", "/Users/dot/.emacs.d/core/autoload/buff...
```

The recursive load is not an issue for me on 26.0.91, instead i'm seeing a handful of use-package errors:

```
Error (use-package): helm/:catch: Assertion failed: (not (symbolp body))
Error (use-package): haskell-mode/:catch: Wrong type argument: cl-slot-descriptor, [cl-struct-cl-slot-descriptor file unbound string nil]
Error (use-package): flow-minor-mode/:catch: Wrong type argument: cl-slot-descriptor, [cl-struct-cl-slot-descriptor file unbound string nil]
Error (use-package): rjsx-mode/:catch: Wrong type argument: cl-slot-descriptor, [cl-struct-cl-slot-descriptor file unbound string nil]
Error (use-package): graphql-mode/:catch: Wrong type argument: cl-slot-descriptor, [cl-struct-cl-slot-descriptor type (quote netrc) symbol ((:documentation . "The backend type.") (:custom . symbol) (:group default))]
Error (use-package): ivy/:catch: Wrong type argument: cl-slot-descriptor, [cl-struct-cl-slot-descriptor type (quote netrc) symbol ((:documentation . "The backend type.") (:custom . symbol) (:group default))]
Error (use-package): ivy-hydra/:init: Symbol’s value as variable is void: ivy-minibuffer-map
Error (doom-init-hook): void-function in ’ivy-mode’ -> Symbol’s function definition is void: ivy-mode
```

Notably these are showing up on my home machine, but not my work computer, wherever everything on emacs 26 is all hunky dory. not sure yet what the difference there is. I'm on the latest doom develop branch, and just nuked and reinstalled my `.local/` to be sure it wasn't anything hanging around.

My config is here: https://github.com/russmatney/doom.d/tree/develop. Forgive the mess, i'm, uh, between clean configs at the moment - hoping to clean it up into a more presentable ~/.doom.d soon! (everyone on our team is built on doom at this point :D Thanks for the awesome work, we're huge fans!)

**Comment by hlissner** [comment] 2018-08-02 16:19
Since the original issue is resolved (and I'm preparing to merge into master), I'll close this.

@russmatney Are you still experiencing these issues? A lot has changed in Doom land. Perhaps it's been fixed along the way.

**Closed by hlissner** 2018-08-02 16:19 UTC
Labels: bug, fixed in develop
