### ISSUE TITLE
How do I disable auto save after tide-fix

### ISSUE THREAD

**Issue by drocha87** [hlissner/doom-emacs#4674] opened 2021-02-20 13:49 UTC
How to avoid this annoying behavior of auto save after `tide-fix` ? I was looking for a variable in `C-h v`  to disable this behavior and I could not find.

Actually when I choose an option in the menu to complete the symbol, I have the same auto-save behavior, which I would like to disable too.

**Comment by notarock** [comment] 2021-02-21 02:39
There doesn't seems to be any variables for that... Maybe try asking the people over at tide? Judging from [this line](https://github.com/ananthakumaran/tide/blob/7f7334b42a40dd3093b830e887c36cdb4ef40858/tide.el#L1320) it might be an expected behavior of tide and so there's no easy way to disable it :thinking:

**Comment by hlissner** [comment] 2021-02-23 19:50
This appears to be an external issue, with `tide`. Please request this of them. I will close this since this isn't a Doom issue.

**Closed by hlissner** 2021-02-23 19:50 UTC
Labels: :lang javascript, is:external
