### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by ecvgit** [hlissner/doom-emacs#2974] opened 2020-04-25 20:17 UTC
**What did you expect to happen?**
I tried to upgrade using 
doom upgrade

**What actually happened?**

! (120/199) Encountered error with org-superstar
    x (error Failed to run "git"; see buffer *straight-process*)
      - fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      HEAD

**Comment by hlissner** [comment] 2020-04-25 20:38
This appears to be a duplicate of https://github.com/hlissner/doom-emacs/issues/2802. Try the solution in https://github.com/hlissner/doom-emacs/issues/2802#issuecomment-606654151.

**Comment by hlissner** [comment] 2020-05-03 23:39
I'll assume no news is good news. Feel free to follow up if that isn't the case.

**Closed by hlissner** 2020-05-03 23:39 UTC
Labels: is:duplicate
