### ISSUE TITLE
"Noel's crash course" link in documentation is dead

### ISSUE THREAD

**Issue by anshukla** [hlissner/doom-emacs#4799] opened 2021-03-14 07:06 UTC
**What did you expect to happen?**
...
Clicking on "Noel’s crash course on Doom Emacs" in https://github.com/hlissner/doom-emacs/blob/0769b47cc84f15f9f546df0b6cd82c90c23d6b21/docs/index.org takes me to website

**What actually happened?**
...
404

Can be reproduced from the GitHub link as well

**Comment by jonathanabennett** [comment] 2021-03-14 09:49
A bit of Googling brings me to https://noelwelsh.com/posts/doom-emacs/ as the correct link

**Comment by hlissner** [comment] 2021-03-14 15:27
Duplicate of #4709

**Closed by hlissner** 2021-03-14 15:27 UTC
Labels: duplicate
