### ISSUE TITLE
Project-ignored directories should be excluded from +ivy-project-search results

### ISSUE THREAD

**Issue by fermata101** [hlissner/doom-emacs#5074] opened 2021-05-20 20:16 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

I have a project with an excluded directory in the .projectile file.  I would expect +default/search-project and +ivy-project-search to ignore this directory when doing project level searches.

Note that +ivy/projectile-find-file excludes the directory correctly because it calls counsel-projectile-find-file which takes excluded dirs into account.

### What actually happened?

Project searches do not exclude this directory.

### Describe your attempts to resolve the issue

I was able to hack +ivy-file-search to tell counsel-rg to exclude these paths by passing "-g!" arguments for the excluded dirs (which are in projectile-ignored-directories-rel.)  +ivy-file-search is already doing this for the .git directory.

It is probably a better fix to modify +ivy-project-search to call counsel-projectile-rg instead of counsel-rg.  counsel-projectile-rg seems to automatically take excluded paths into account.

### Steps to reproduce

1. Set up a new project by creating a .projectile file.  Add a line "-/dir1" to this file.
2. Create a directory "dir1" under the project dir.
3. Create some files in the project root and in directory dir1 containing text which includes "FINDME".
4. Open a file in the project and then run +default/search-project (SPC /) searching for "FINDME".
5. Note that the search results include content from dir1.
6. (I only tested with ivy, but from looking at the code in +helm/project-search, it looks like it has the same issue.)

### System Information

https://pastebin.com/Wniteyc9

**Comment by hlissner** [comment] 2021-05-20 20:34
`+ivy-project-search` uses ripgrep. Ripgrep does not obey `.projectile` files, and I have no intention of implementing that, nor connecting it to `projectile-rg` because a) it's tremendously slow, b) projectile will be replaced with project.el in the future, and c) it is redundant with what ripgrep already supports through `.ignore` and `.gitignore` files, which all of Doom's file/search commands respect. Alternatively, you can adjust `counsel-rg-base-command` with exemption flags to apply to all searches.

As this is not a bug or an issue I will address (at least, not this way), I will close this. Sorry for the trouble!

**Closed by hlissner** 2021-05-20 20:34 UTC
Labels: 1. request, 2. status:nofix, :core, re:projects
