### ISSUE TITLE
doom-emacs cann't recognize remapped alt key

### ISSUE THREAD

**Issue by hy-zhao** [hlissner/doom-emacs#5145] opened 2021-06-06 02:06 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

I am using external USB-HID keyboard with Macbook Pro 16. I hope the remapped alt and command key function well, so that i can use M-x(remapped alt+x) and Cmd-s, etc.

### What actually happened?

After remapped alt key as command, command as alt on my external keyboard, the remapped left alt key can not be recognized as meta, and remapped left command key is recognized as `s`, when running Emacs.app

### Describe your attempts to resolve the issue

I tried run Emacs.app without doom-emacs, the remapped alt and command key functions as I expect.

I also tried run emacs in terminal with and without doom-emacs, which both functions as i expect.

So, only when running Emacs.app with doom-emacs configuration, the left remapped two keys could not function well.

### Steps to reproduce

1. MacOS, settings -> keyboard -> Modifier keys -> select keyboard USB-HID keyboard -> Option key to Command, Command key to Option
2. run Emacs.app, press left M-x(remmaped alt+x), and Cmd + s

### System Information

https://pastebin.com/W3FhaJV6

**Comment by hlissner** [comment] 2021-06-06 02:08
Duplicate of #5143.

See https://github.com/hlissner/doom-emacs/issues/5143

**Closed by hlissner** 2021-06-06 02:08 UTC
Labels: duplicate
