### ISSUE TITLE
Update emacs-format-all-the-code

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#4253] opened 2020-11-11 12:57 UTC
https://github.com/lassik/emacs-format-all-the-code/pull/104 has finally been merged and we can correctly have bash-style format by default. Perhaps it's time to update :)

**Comment by hlissner** [comment] 2020-11-11 19:24
Duplicate of #4041. See https://github.com/hlissner/doom-emacs/issues/4041#issuecomment-704447601

**Closed by hlissner** 2020-11-11 19:24 UTC
Labels: duplicate
