### ISSUE TITLE
Don't enable configuration for disabled features/modes

### ISSUE THREAD

**Issue by evanrelf** [hlissner/doom-emacs#3661] opened 2020-08-01 03:27 UTC
**Describe the feature**

I have the `ui/ophints` feature disabled, but I still have an "Evil goggles" mapping at `SPC t g`. I think this mapping should only be configured if `evil-goggles` is enabled.

I've seen other errors about "Wrong type argument" or `nil` functions or whatever, relating to features I've disabled, or packages I've disabled with `disable-packages!`. This `evil-goggles` one is just the most obvious offender.

It would be great if things didn't silently break with fleeting errors when I disable packages, and especially when I disable features.

So far I'm loving Doom Emacs and I appreciate all the love that's been put into it. I just would like to thin it down a bit for my own personal config.

EDIT: I'll add more as I find them. These options are available to me, but do not work:

- "Evil goggles" (`SPC t g`) despite not enabling `ui/ophints`
- "Open deft" (`SPC n d`) despite not enabling `ui/deft`
- "Org export to clipboard" (`SPC n y`) despite disabling `htmlize` and `ox-clip`
- "Look up online (w/ prompt)" (`SPC s O`) despite disabling `request`
- "Dictionary" (`SPC s t`) despite not configuring any dictionary backends

If there's a more correct way of disabling packages, please let me know.

**System information**

<details>

```
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER
        build      Jul 31, 2020
        buildopts  (--prefix=/nix/store/c27zvaqcdjviss061zcb1mny5bncpsyv-emacs-gcc-20200726.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD e07cc77 2020-07-31 18:18:07 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/fish
        uname      Linux 5.4.53 #1-NixOS SMP Wed Jul 22 07:33:18 UTC 2020 x86_64
        path       (/nix/store/hrlwsr7k7fqbdxjvjvii0imsk86fch3d-binutils-wrapper-2.31.1/bin /nix/store/k6rnzlmcvm37d0nw4fkz6ivmykmrdn39-binutils-2.31.1/bin ~/.local/bin ~/.config/git/scripts ~/.cabal/bin ~/.local/share/cargo/bin ~/.config/cargo/bin ~/.config/emacs/bin /nix/store/0ny29hsmx2akig0wf1qci7mlpg9xhshd-kitty-0.18.1/bin /nix/store/7kaq9dgywnwpv632mji9qwfva1b9bgsq-imagemagick-6.9.11-14/bin /nix/store/nm025c8kk42wqq01jpcyi58aq3ipl9zz-xsel-unstable-2019-08-21/bin /nix/store/w5dbhl95nkysmhp1h2hqikjvkn8g1hzs-ncurses-6.2-dev/bin ~/.local/bin ~/.config/git/scripts ~/.cabal/bin ~/.local/share/cargo/bin ~/.config/cargo/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/evanrelf/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/c27zvaqcdjviss061zcb1mny5bncpsyv-emacs-gcc-20200726.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +tng) (ivy +prescient) :ui doom doom-dashboard doom-quit nav-flash (popup +defaults) vc-gutter :editor (evil +everywhere) fold multiple-cursors :emacs (dired +ranger) electric ibuffer undo vc :checkers syntax (spell +aspell) :tools lookup magit terraform :lang data haskell json markdown nix org racket rust (sh +fish) web yaml :config (default +bindings +smartparens))
        packages   ((modus-operandi-theme) (mood-line) (evil-terminal-cursor-changer) (magit-delta) (simpleclip))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2020-08-01 10:14
This is a duplicate of #1312 (and #1396).

See https://github.com/hlissner/doom-emacs/issues/1312#issuecomment-480650364 for an explanation.

**Closed by hlissner** 2020-08-01 10:14 UTC
Labels: is:duplicate

**Comment by hlissner** [comment] 2020-08-01 10:24
> I've seen other errors about "Wrong type argument" or nil functions or whatever, relating to features I've disabled, or packages I've disabled with disable-packages!

Can you be more specific about this? What commands are emitting "wrong type argument" errors? This seems unrelated to `commandp` errors you should be getting trying to invoke commands that don't exist, and would most certainly be considered a bug if they are true.

**Comment by evanrelf** [comment] 2020-08-01 17:48
Ah my bad, sorry for creating a duplicate issue.

> What commands are emitting "wrong type argument" errors?

I will be on the lookout for this error and report it when I see it again.

**Comment by evanrelf** [comment] 2020-08-01 17:57
Here are the errors when using these keys:

- "Evil goggles" (`SPC t g`) despite not enabling `ui/ophints`

  > Wrong type argument: commandp, evil-goggles-mode

- "Open deft" (`SPC n d`) despite not enabling `ui/deft`

  > Wrong type argument: commandp, deft

- "Org export to clipboard" (`SPC n y`) despite disabling `htmlize` and `ox-clip`
  
  I'm prompted with a choice of export format. Choosing any option simply opens the current buffer in a new window, unmodified.

- "Look up online (w/ prompt)" (`SPC s O`) despite disabling `request`

  I'm prompted with a choice of search engine. Choosing "DuckDuckGo" or "Google" gives the following error:
  > Cannot open load file: No such file or directory, request

  I didn't test all the options, so there may be others that are failing due to the `request` package being disabled. However "Youtube", "GitHub", and "Doom Emacs issues" were options I tried which worked.

- "Dictionary" (`SPC s t`) despite not configuring any dictionary backends

  I'm prompted to look up a word in the dictionary. Typing any word, valid or not, gives this error:
  > No dictionary backend is available

**Comment by evanrelf** [comment] 2020-08-01 18:03
I imagine there could be a way of disabling mappings "at compile time" when running the `doom` CLI utility, via some codegen of variables or something. Since package management is done via the CLI, and you have to run `doom sync` to apply changes anyways, the enabled packages and enabled keys (or any other conditional config) would always stay in sync.

Similar to how the envfile is generated ahead of time to avoid the hit to startup time, because the environment variables aren't going to change much.
