### ISSUE TITLE
Error during doom upgrade

### ISSUE THREAD

**Issue by michaelknowles** [hlissner/doom-emacs#4974] opened 2021-05-03 17:58 UTC
Trying to upgrade Doom Emacs and getting an error.

- I've run doom up multiple times
- I've run purge, clean, sync, and compile.
```
❯ doom up
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to doom.error.log
```

Backtrace: https://pastebin.com/D6hFateg

**Additional details:**
Config: https://github.com/michaelknowles/dotfiles/tree/master/doom.d

**Steps to reproduce:**
doom up

**System information:**
generated    May 03, 2021 10:56:16
distro       "Arch Linux" Linux 5.11.16-arch1-1 x86_64
emacs        28.0.50 makepkg 0c75d7d08 ~/.emacs.d/ -> ~/.emacs.d/
doom         2.0.9 HEAD -> develop e68c83fd4 2021-05-03 13:27:20 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        /usr/bin/zsh
features     ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS GTK3 ZLIB
traits       batch server-running envvar-file
modules      :completion company (ivy +fuzzy +icons) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline ophints (popup +defaults) ligatures treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs (dired +icons) electric undo vc :term eshell :checkers syntax spell :tools (eval +overlay) lookup lsp magit pdf :lang clojure data emacs-lisp (go +lsp) json javascript latex markdown org (rust +lsp) sh (web +lsp) yaml :config (default +bindings +smartparens)

**Comment by hlissner** [comment] 2021-05-03 18:38
Duplicate of #4950

**Closed by hlissner** 2021-05-03 18:38 UTC
Labels: delete me, duplicate
