### ISSUE TITLE
vi keybindings in mu4e message window

### ISSUE THREAD

**Issue by Mic92** [hlissner/doom-emacs#3635] opened 2020-07-27 10:43 UTC
**Describe the feature**

When using spacemacs also hjkl motions work inside the message windows and not just the header window.
It looks like they use some helper function that is not present in doom-emacs: https://github.com/syl20bnr/spacemacs/blob/d46eacd83842815b24afcb2e1fee5c80c38187c5/layers/%2Bemail/mu4e/packages.el#L44

**System information**

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD
        build      Jul 27, 2020
        buildopts  (--prefix=/nix/store/2cj2l8hkwid4462zz3rx6cwqfd2vyz5f-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  nil
        daemonp    daemon
doom    version    2.0.9
        build      fatal: not a git repository (or any of the parent directories): .git
        dir        /nix/store/xqajmdyhgs3szkpw4f76pmp8vlnaaa71-doom-private/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.4.53 #1-NixOS SMP Wed Jul 22 07:33:18 UTC 2020 x86_64
        path       (~/bin/ ~/.cargo/bin/ ~/go/bin/ ~/.nix-profile/bin/ /run/wrappers/bin/ /run/current-system/sw/bin/ /nix/store/pj43dfd5k4zb0ivafkyqpr1blzd616ry-git-2.27.0/bin/ /nix/store/fx068zbx45pad9191xg6cx4ghpr3pcnd-sqlite-3.32.3-bin/bin/ /nix/store/87bfn29g80wazh2f2idq062iccmiwmyy-unzip-6.0/bin/ /nix/store/2cj2l8hkwid4462zz3rx6cwqfd2vyz5f-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold format snippets :emacs dired electric undo vc :checkers syntax :tools direnv editorconfig (eval +overlay) lookup lsp magit make :lang (cc +lsp) data emacs-lisp (go +lsp) javascript latex lua markdown nix org python rst (ruby +rails) rust sh web yaml :email mu4e :config (default +bindings +smartparens))
        packages   ((mu4e-alert) (csharp-mode) (editorconfig) (vimrc-mode) (coffee-mode) (meson-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by Mic92** [comment] 2020-07-27 10:46
The function is provided by this package: https://github.com/syl20bnr/spacemacs/blob/master/layers/+distributions/spacemacs-base/local/evil-evilified-state/evil-evilified-state.el

**Comment by Mic92** [comment] 2020-07-27 11:39
Not quite sure if https://github.com/hlissner/doom-emacs/commit/3ccada7150e4d2cfd7680f8efd107346d208d3e1 solves it. Let me test.

**Comment by hlissner** [comment] 2020-07-27 18:04
https://github.com/hlissner/doom-emacs/commit/3ccada7150e4d2cfd7680f8efd107346d208d3e1 should indeed fix this, so I'll consider this a duplicate of https://github.com/hlissner/doom-emacs/pull/3464.

**Closed by hlissner** 2020-07-27 18:04 UTC
Labels: delete me, is:duplicate

**Comment by Mic92** [comment] 2020-07-27 20:01
Fixed indeed!
