### ISSUE TITLE
Debug info display in term messed up after running doom/reload

### ISSUE THREAD

**Issue by shelper** [hlissner/doom-emacs#5006] opened 2021-05-08 02:20 UTC
I made a void function called (fo) and just use that to invoke the debug info.
everything is fine untill i run command `doom/reload` in emacs, then the debug info is not displayed correctly, as show below:

**What did you expect to happen?**
![image](https://user-images.githubusercontent.com/546163/117522565-2ec1e380-af82-11eb-9db9-336d49c7ac3a.png)

**What actually happened?**
![image](https://user-images.githubusercontent.com/546163/117522528-fc17eb00-af81-11eb-8241-108f0c9b6f3c.png)

**Additional details:**

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. Replace them with precise steps to reproduce your issue.
4. Include code samples, keybinds, and commands.
5. Please don't skimp on details.
6. Then fill in "system information" below or this issue will be deleted.

**System information:**

![image](https://user-images.githubusercontent.com/546163/117522618-78aac980-af82-11eb-91ef-ade6ba9c4f2f.png)

**Comment by hlissner** [comment] 2021-05-08 03:15
I can't reproduce that. This a terminal issue, not a Doom issue. Not enough info to go on otherwise. I'll close this until I have more leads or have reason to believe otherwise, but feel free to follow up here anyway.

-----

In the future, please do not take a screenshot of your `M-x doom/info`. It's not very useful, because all the useful information is cut off.

**Closed by hlissner** 2021-05-08 03:15 UTC
Labels: invalid
