### ISSUE TITLE
New EMACS26+ constants break make

### ISSUE THREAD

**Issue by jcf** [hlissner/doom-emacs#479] opened 2018-03-24 15:34 UTC
Pull the latest changes in develop where the new [`EMACS26+` constant](https://github.com/hlissner/doom-emacs/commit/5eadfdc880bf2e98f8574871c4bdae2da6d65352) was added. Run `make` in `~/.emacs.d` and you get this:

```
Source file ‘/home/jcf/.emacs.d/core/core.el’ newer than byte-compiled file
Eager macro-expansion failure: (void-variable EMACS26+)
Eager macro-expansion failure: (void-variable EMACS26+)
Symbol’s value as variable is void: EMACS26+
make: *** [Makefile:55: clean] Error 255
```

Trashing `*.elc` and restarting Emacs seems to have fixed things.

``` sh
cd ~/.emacs.d
find . -iname '*.elc' -delete
```

**Comment by hlissner** [comment] 2018-03-24 21:12
That is expected behavior. Interactive Doom prioritizes *.elc files over their *.el counterpart, regardless of file age (for performance reasons). You will need to clear *.elc files (with `make clean`) or recompile (with `make recompile`).

That said, I've just pushed a fix that should force make to run Emacs in a session where newer files are prioritized over byte-compiled ones (since performance isn't high priority in non-interactive Emacs).

However, your interactive Emacs session will still be broken until you `make clean` or `make recompile`.

**Closed by hlissner** 2018-03-24 21:12 UTC
