### ISSUE TITLE
+lookup/references fails to jump

### ISSUE THREAD

**Issue by AllenDang** [hlissner/doom-emacs#5025] opened 2021-05-10 06:06 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.

### What did you expect to happen?

Repo steps:
1. Move cursor on an method of golang.
2. Press SPC-c-D.
3. Select one result, press Enter.

Expect:
The source file related to select method will be opened.

### What actually happened?

Popup closed and source file of related method doesn't be opened.

### Describe your attempts to resolve the issue

I checked Message, xref and lsp related buffer, no error message appeared.

### Steps to reproduce

1. Open Emacs.
2. SPC-p-p select and open a golang project.
3. Open one golang source file.
4. Put cursor on a function name.
5. SPC-c-D.
6. Select one item in popup and press ENTER.

### System Information

https://pastebin.com/sKEzuQ07

**Comment by hlissner** [comment] 2021-05-10 06:08
Duplicate of #4894

**Closed by hlissner** 2021-05-10 06:08 UTC
Labels: duplicate
