### ISSUE TITLE
Can't access double-ctrl command - example : C-c C-l

### ISSUE THREAD

**Issue by alx** [hlissner/doom-emacs#3762] opened 2020-08-16 11:19 UTC
**What did you expect to happen?**

I'm trying to create a new link in org mode, I've found the `C-c C-l` shortcut, which should be straightforward.

**What actually happened?**

When I type `C-c`, a buffer shows the possible following commands, but I'm unable to type the following `C-l` command.

**Additional details:**

- default config on fresh doom-emacs install, so might it be something related to i3 or some terminal configuration ?

![image](https://user-images.githubusercontent.com/373/90333034-9bdfb400-dfc2-11ea-9bee-24b82400e412.png)

**Steps to reproduce:**
1. Fresh install doom-emacs
2. Capture new journal: `SPC n n j`
3. `C-c C-l`, `C-c` opens a hint buffer with possible commands, impossible to type `C-l`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "sept. 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 9a8fc46 2020-08-15 15:13:50 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64")
  (path "~/.cargo/bin" "~/esp/xtensa-esp32-elf/bin" "~/.local/bin" "~/bin" "~/go/bin" "/usr/local/go/bin" "~/miniconda2/bin" "~/go/bin" "/usr/local/go/bin" "~/miniconda2/bin" "~/.cargo/bin" "~/esp/xtensa-esp32-elf/bin" "~/.local/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/gopath" "~/.fzf/bin" "~/gopath" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by alx** [comment] 2020-08-17 12:09
As found another shortcut to `org-insert-link` with `SPC m l l`, but it doesn't explain why the nest `C-l` command is not working.

**Comment by hlissner** [comment] 2020-08-17 20:17
This is likely due to the fact that you use Emacs a) in the terminal and b) in tmux. I have tmux keybinds for `C-{h,j,k,l}` for switching panes, so, naturally, `C-l` will never make it to Emacs.

Without tmux, terminal Emacs receives `C-l` fine for me.

I'll close this since it isn't a Doom issue in particular, but feel free to follow up here if it turns out tmux (or something else in your terminal) isn't the cause.

**Closed by hlissner** 2020-08-17 20:17 UTC
Labels: is:bug

**Comment by alx** [comment] 2020-08-18 07:18
Thanks for the help, that was the correct issue, it's indeed working well outside tmux.
