### ISSUE TITLE
[BUG] Failed to load editorconfig (No such file or directory)

### ISSUE THREAD

**Issue by bersace** [hlissner/doom-emacs#2216] opened 2019-12-20 10:25 UTC
**What did you expect to happen?**

EditorConfig mode to be enabled.

**What actually happened?**

EditorConfig is not available, editorconfig-mode is undefined.

**Additional details:**
- Include a link to your private config : https://gitlab.com/bersace/dotfiles/tree/master/files/.config/doom
- Include any warnings or errors logged to \*Messages\* 

A message at startup says :
```
Failed to load deferred package editorconfig: (file-missing Cannot open load file Not such file or directory editorconfig)
```

**Steps to reproduce:**
1. Run Doom Emacs
1. Open a random file.
1. `M-x` and search for `editorconfig-mode`.

**System information:**
<details><pre>
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
((emacs
  (version . "26.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2")
  (build . "sept. 23, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 6d40f30a0 2019-12-20 05:01:44 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64")
  (path "~/src/dalibo/cornac/service/cornac/files" "~/.cache/pyenv/plugins/pyenv-virtualenvwrapper/shims" "~/.cache/pyenv/libexec" "~/.cache/pyenv/plugins/python-build/bin" "~/.cache/pyenv/plugins/pyenv-virtualenvwrapper/bin" "~/.cache/pyenv/plugins/pyenv-virtualenv/bin" "~/.cache/pyenv/plugins/pyenv-update/bin" "~/.cache/pyenv/plugins/pyenv-installer/bin" "~/.cache/pyenv/plugins/pyenv-doctor/bin" "~/.cache/pyenv/shims" "~/.gem/ruby/2.3.0/bin" "~/.poetry/bin" "~/.cache/pyenv/shims" "~/.cache/pyenv/bin" "~/.cache/gopath/bin" "~/.local/bin" "~/.poetry/bin" "~/.gem/ruby/2.3.0/bin" "~/.poetry/bin" "~/.cache/pyenv/shims" "~/.cache/pyenv/bin" "~/.cache/gopath/bin" "~/.local/bin" "~/.poetry/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "/usr/lib/emacs/26.1/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) tabs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +bindings +everywhere) fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools ansible direnv docker editorconfig eval flycheck (lookup +docsets) lsp magit :lang (cc +lsp) data emacs-lisp go (java +meghanada) (javascript +lsp) markdown org php (python +pyenv) rst sh web :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by bersace** [comment] 2019-12-20 10:25
I execute `bin/doom refresh` and `bin/doom upgrade` without success.

**Comment by bersace** [comment] 2019-12-20 10:39
Wiping .local solved this. @hlissner do you want me to close the issue or do you want to investigate how could editorconfig have vanished ?

**Comment by hlissner** [comment] 2019-12-21 04:09
We may as well close it. It's difficult to determine the cause after-the-fact, and I cannot reproduce it locally. I'll have to wait until it happens again.

If this does happen again, try cycling the `:tools editorconfig` module (disable, refresh, enable, refresh).

**Closed by hlissner** 2019-12-21 04:09 UTC
Labels: :tools editorconfig, re:packages, status:unknown

**Comment by bersace** [comment] 2019-12-23 08:04
@hlissner that's fair. Thanks for the hint ! Wiping .local is quite heavy and resets recent files, etc. I'll try this next time.
