### ISSUE TITLE
Company popup is not working as expect in clojure-mode

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#2762] opened 2020-03-23 19:57 UTC
**What did you expect to happen?**
When a company popup opens, I should control it using arrow keys or `C j` and `C k`.

**What actually happened?**
Pressing arrow keys, `C j`, `C k` just do the default Emacs shortcut for each (move line, break line, help). It doesn't even use my evil shortcuts (`C j` and `C k` would switch buffers, for example).

This only happens in `clojure-mode`.

**Additional details:**
- https://github.com/ericdallo/dotfiles/blob/master/emacs/.doom.d/config.el

**Steps to reproduce:**
1. Open a file in `clojure-mode` and starts a REPL (`SPC m '`)
2. Evaluate a buffer (`SPC e b`) and try to write some code
3. When auto-completing, try to move between choices in company popup using `C j`, `C k` or arrow keys

**System information:**

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD
        build      mar 23, 2020
        buildopts  (--prefix=/nix/store/p8r1w5w30gn2nciahj0yzbxlsr5frgbs-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 4b20c7206 2020-03-13 17:34:44 -0400
        dir        ~/.dotfiles/doom-emacs/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.4.24 #1-NixOS SMP Thu Mar 5 15:43:52 UTC 2020 x86_64
        path       (/nix/store/qvz2dc1b3p94n6vr0ha82vnv772vy50i-emacs-packages-deps/bin ~/dev/nu/nucli.py/bin ~/dev/nu/nudev/docker/forticlientvpn ~/dev/nu/ios-cli ~/dev/nu/nucli ~/dev/nu/nudev ~/.npm-packages/bin ~/.emacs.d/bin ~/.local/bin /nix/store/fdhwkcm0xg9j0brd5q3gqf00lpa2dklm-kitty-0.14.6/bin /nix/store/ygvwvzqf9zfgicqbilnpgk6dzs2s9szw-imagemagick-6.9.10-71/bin /nix/store/x3swj9lpp73dl17vffrnbhap2bb2ysgv-xsel-unstable-2018-01-10/bin /nix/store/jwhd7yi26sfbi5djclxrr3ims6r5796i-ncurses-6.1-20190112-dev/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/thiagoko/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/p8r1w5w30gn2nciahj0yzbxlsr5frgbs-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company (ivy +fuzzy +icons) :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons) electric ibuffer vc :term eshell vterm :checkers syntax :tools docker (eval +overlay) (lookup +docsets) lsp magit :lang cc clojure data elixir emacs-lisp go hy javascript markdown nix (org +dragndrop +ipython +pandoc +present) python ruby rust scala sh :config (default +bindings +smartparens))
        packages   ((adoc-mode) (color-identifiers-mode) (evil-escape :disable t) (flycheck-clj-kondo) (lispyville) (lsp-ui :disable t) (sort-words) (uuidgen) (vlf))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by thiagokokada** [comment] 2020-03-26 18:43
One more info, the problem only happens after opening CIDER. Before opening CIDER REPL it works fine.

**Comment by hlissner** [comment] 2020-03-29 20:15
This is a duplicate of #1335

**Closed by hlissner** 2020-03-29 20:15 UTC
Labels: is:duplicate
