### ISSUE TITLE
doom doctor reports: org is not installed?

### ISSUE THREAD

**Issue by tamasgal** [hlissner/doom-emacs#2530] opened 2020-02-12 16:27 UTC
**What did you expect to happen?**
I had some weird issues when I opened org files (I could not catch the error since it disappeared after half a second) and when I ran `doom doctor` it said that `org is not installed`. I did several `doom update` and `doom upgrade`s but it did not help so I deleted the `~/.emacs.d` folder and made a fresh clone and `doom install`.

Still, if I run `doom doctor` I get this:

```shell
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 43 modules
  ✓ Detected 179 packages
  > Checking Doom core for irregularities...
    ! Couldn't find the `fd' binary; project file searches will be slightly slower
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
  x org is not installed
    > :lang sh
      ! Couldn't find shellcheck. Shell script linting will not work


There are 2 warnings!
✓ Finished! (1.7580s)
```

Org-mode now works without errors but I am not sure what to do do get rid of that warning (error?)?

**Additional details:**
My configuration: https://github.com/tamasgal/rc/tree/master/doom.d

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD f9eb6a3b6 2020-02-11 19:24:08 -0500")
  (dir . "~/.rc/doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.14.168-1-MANJARO #1 SMP PREEMPT Mon Jan 27 16:56:25 UTC 2020 x86_64")
  (path "~/.nimble/bin" "~/go/bin" "~/modules/software/julia/1.3.0-rc4/bin" "~/opt/bin" "/var/lib/snapd/snap/bin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/opt/cuda/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/var/lib/snapd/snap/bin" "~/.gem/ruby/2.6.0/bin" "~/.emacs.d/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs workspaces :editor (evil +everywhere) file-templates multiple-cursors snippets :emacs dired electric ibuffer vc :term eshell shell term vterm :checkers syntax spell grammar :tools direnv (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp julia latex markdown (org +jupyter +pandoc +present) (python +lsp) rst sh :email mu4e :app calendar :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2020-02-12 16:37
This is a duplicate of #2284. See it for details.

**Closed by hlissner** 2020-02-12 16:37 UTC
Labels: is:bug

**Comment by tamasgal** [comment] 2020-02-12 16:48
I am sorry, no idea how i missed that :see_no_evil:

**Comment by hlissner** [comment] 2020-02-12 18:47
No worries! It's easy to miss.

**Comment by tamasgal** [comment] 2020-02-12 18:51
I just realised it's really hidden. This wasn't like this before (or did I get so used to the GitLab way, where similar issues are immediately listed below the title field)?? Maybe my brain tricks me but I thought GitHub displayed those also directly under the title field before...

I usually do not use the direct search anymore because I got used to the completion 😅 

Never mind...

![Screenshot 2020-02-12 at 19 48 43](https://user-images.githubusercontent.com/1730350/74366766-e6dcfc80-4dd0-11ea-8648-cff938a692cd.png)
