### ISSUE TITLE
Evil-mode `df ` (`d`, `f`, `SPC`) does not work

### ISSUE THREAD

**Issue by andmis** [hlissner/doom-emacs#6282] opened 2022-04-11 15:52 UTC
### What did you expect to happen?

Enter `;; Hello, world` into a `.el` buffer. Move point to the `H`. Type `df ` (`d`, `f`, `SPC`).

I expected the result to be `;; |world`, but the result is `;; | world` (the space is not deleted).

Interestingly, I can reproduce this in Elisp and Python buffers, but not Fundamental mode buffers.

### What actually happened?

See above.

### Describe your attempts to resolve the issue

I'm new to Emacs and Doom so I am not sure where to begin debugging this.

### Steps to reproduce

See above.

### System Information

https://pastebin.com/n7Ny1kWs

**Comment by hlissner** [comment] 2022-04-14 02:57
Duplicate of https://github.com/hlissner/evil-snipe/issues/86.

**Closed by hlissner** 2022-04-14 02:57 UTC
Labels: duplicate, delete me
