### ISSUE TITLE
prettify-symbols-mode won't render some glyphs

### ISSUE THREAD

**Issue by oakrc** [hlissner/doom-emacs#3615] opened 2020-07-23 05:34 UTC
**What did you expect to happen?**
That the glyphs be correctly shown in a source file.

**What actually happened?**
A hollow rectangle shows up instead.

**Additional details:**
- [My config](https://github.com/oakrc/dotfiles/tree/master/.doom.d)
- Screenshots
![rectangle](https://user-images.githubusercontent.com/25710522/88254175-3f120780-cc69-11ea-8732-1b6002724a69.png)
![non-rectangle](https://user-images.githubusercontent.com/25710522/88254177-433e2500-cc69-11ea-8106-8dccc4bbe4ce.png)
- No errors

**Steps to reproduce:**
1. `rm -rf ~/.emacs.d`
2. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d && cd ~/.emacs.d && bin/doom install`
3. enable `pretty-code` in `init.el`
4. restart Emacs
5. view some code and observe the rectangles

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Jun 10, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 1dfe690 2020-07-23 00:51:20 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64
        path       (~/bin ~/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.emacs.d/bin/ ~/.local/bin ~/.emacs.d/bin/ /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:input chinese japanese :completion company (ivy +fuzzy +icons) :ui deft doom doom-dashboard doom-quit hl-todo minimap modeline ophints (popup +all +defaults) pretty-code tabs treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors snippets :emacs dired electric ibuffer undo vc :term eshell vterm :checkers syntax :tools (debugger +lsp) docker ein (eval +overlay) gist (lookup +dictionary +offline) lsp (magit +forge) (pass +auth) pdf rgb tmux :lang (cc +lsp) data emacs-lisp (json +lsp) (java +lsp) (javascript +lsp) (latex +cdlatex +fold +lsp) ledger (markdown +grip) (org +present +dragndrop +hugo +noter +dragndrop +journal +jupyter +roam +pomodoro) php (python +lsp +pyenv) qt rust (sh +lsp +fish) web yaml :app calendar irc :config literate (default +bindings +smartparens))
        packages   ((org-fancy-priorities) (origami) (indium) (org-roam-server) (ascii-art-to-unicode) (org-ref) (org-roam-bibtex) (ivy-bibtex) (parsebib :recipe (:files (*.el))) (nov) (mathpix.el :recipe (:host github :repo jethrokuan/mathpix.el)) (fish-mode) (systemd) (ssh-config-mode) (protobuf-mode) (calctex :recipe (:host github :repo johnbcoughlin/calctex :files (calctex-pkg.el org-calctex/*el calctex*/*el))) (org-tanglesync) (org-projectile) (powershell))
        unpin      (org-roam)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment] 2020-07-23 05:36
Duplicate of #3611. See https://github.com/hlissner/doom-emacs/issues/3611#issuecomment-662676796 for solution.

**Closed by hlissner** 2020-07-23 05:36 UTC
Labels: is:duplicate

**Comment by oakrc** [comment] 2020-07-23 06:21
Sorry for not noticing it.
I tried using some patched nerd fonts (F{i,u}raCode, Iosevka) and the symbols still won't render for me.
```lisp
(setq doom-font (font-spec :family "Iosevka Nerd Font Mono" :size 40))
```
![patched-font-rect](https://user-images.githubusercontent.com/25710522/88257033-afbd2200-cc71-11ea-8cb3-1464ba47f0a4.png)
