### ISSUE TITLE
An unexpected error occurred during installation

### ISSUE THREAD

**Issue by 368573607** [hlissner/doom-emacs#6142] opened 2022-02-22 16:01 UTC
### What did you expect to happen?

When I install doom emacs, it should be executed normally.

### What actually happened?

It throws an error. Here is the back trace:
```
x There was an unexpected error
      Message: Wrong type argument
      Error: (wrong-type-argument arrayp nil)
      Backtrace:
        (substring nil 0 0)
        (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
        (shell-quote-argument nil)
        (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
        (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name direct...
        (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file...
        (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (exp...
        (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n...
        (let* ((result result) (exit (car result)) (invoked (numberp exit)) (succe...
        (let ((directory x6) (result x4) (args x2) (program x0)) (let* ((result re...
```
When I try to install doom-emacs by `~/.emacs.d/bin/doom install`

### Describe your attempts to resolve the issue

I tried repeating the command but got the same result. It is bad.

### Steps to reproduce

1. Open the terminal
2. Run a command: `~/.emacs.d/bin/doom install`
3. Got the error

### System Information

https://pastebin.com/6tG75xks

**Comment by hlissner** [comment] 2022-02-22 18:09
Duplicate of https://github.com/hlissner/doom-emacs/issues/5918.

Please use the search bar on our issue tracker before submitting issues.

**Closed by hlissner** 2022-02-22 18:09 UTC
Labels: duplicate, delete me
