### ISSUE TITLE
Closing magit after making commit leaves behind a new window

### ISSUE THREAD

**Issue by benj02** [hlissner/doom-emacs#506] opened 2018-04-03 06:38 UTC
### Observed behavior

Best way to show it is with a screencast:

[![magit](https://thumbs.gfycat.com/DependentImprobableHedgehog-size_restricted.gif)](https://gfycat.com/DependentImprobableHedgehog)

You open the magit status buffer, and make a commit. After that close the status buffer with `q` and you're left with an extra window. This only happens when you open the commit buffer, it doesn't happen if you strictly open magit buffers. I suspect because it isn't being detected by `+popup` as it doesn't have `*magit` in its name

### Expected behavior

After closing magit status buffer the window layout should be as it started.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 25.3.1 (Feb 08, 2018)
- Doom: 2.0.9 (master https://github.com/hlissner/doom-emacs/commit/5242fe3ff600443f419209eb2385de12b2e4dfe9)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
- Details:
  ```elisp
  uname -a:  Linux thinkpad 4.15.12-1-zen #1 ZEN SMP PREEMPT Wed Mar 21 15:14:46 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (eval nil) (evil (+everywhere)) (file-templates nil) (lookup (+devdocs +docsets)) (services nil) (snippets nil) (spellcheck nil) (syntax-checker nil) (version-control nil) (workspaces nil) :completion (ivy nil) :ui (doom-dashboard nil) (doom-modeline nil) (doom-quit nil) (evil-goggles nil) (hl-todo nil) (nav-flash nil) (vi-tilde-fringe nil) (window-select nil) :tools (electric-indent nil) (eshell nil) (gist nil) (imenu nil) (impatient-mode nil) (make nil) (magit nil) (neotree nil) (password-store nil) (pdf nil) (rotate-text nil) (term nil) (tmux nil) (upload nil) :lang (cc nil) (crystal nil) (clojure nil) (csharp nil) (data nil) (elixir nil) (elm nil) (emacs-lisp nil) (ess nil) (go nil) (haskell (+intero)) (hy nil) (java (+meghanada)) (javascript nil) (julia nil) (latex nil) (ledger nil) (lua nil) (markdown nil) (nix nil) (ocaml nil) (org (+attach +babel +capture +export +present +publish)) (perl nil) (php nil) (plantuml nil) (purescript nil) (python nil) (rest nil) (ruby nil) (rust nil) (scala nil) (sh nil) (swift nil) (typescript nil) (web nil) :config)
  packages:  (ace-link ace-window adaptive-wrap alchemist all-the-icons anaconda-mode android-mode async auctex auto-compile auto-yasnippet avy (centered-window :recipe (centered-window :fetcher github :repo anler/centered-window-mode)) cider clj-refactor cmake-mode coffee-mode command-log-mode company company-anaconda company-auctex company-dict (company-glsl :recipe (company-glsl :fetcher github :repo Kaali/company-glsl)) company-go company-inf-ruby company-irony company-irony-c-headers company-lua company-php company-quickhelp company-racer company-restclient company-shell company-sourcekit company-statistics company-tern company-web counsel counsel-css counsel-dash counsel-projectile crystal-mode csharp-mode cuda-mode demangle-mode devdocs dired-k disaster dockerfile-mode doom-themes dumb-jump editorconfig elixir-mode elm-mode (emacs-snippets :recipe (emacs-snippets :fetcher github :repo hlissner/emacs-snippets :files (*))) emmet-mode ensime eslintd-fix ess ess-R-data-view ess-smart-equals evil evil-anzu evil-args evil-collection evil-commentary evil-easymotion evil-embrace evil-escape evil-exchange evil-goggles evil-indent-plus evil-ledger evil-magit evil-matchit evil-mc evil-multiedit evil-numbers evil-org evil-snipe evil-surround evil-textobj-anyblock evil-vimish-fold evil-visualstar (exec-path-from-shell :ignore t) expand-region flycheck flycheck-cask flycheck-crystal flycheck-elm flycheck-irony flycheck-ledger flycheck-perl6 flycheck-plantuml flycheck-popup-tip flycheck-pos-tip flycheck-rust flyspell flyspell-correct flyspell-correct-ivy fringe-helper gist git-gutter-fringe git-link git-timemachine gitconfig-mode gitignore-mode glsl-mode go-eldoc go-guru go-mode gorepl-mode groovy-mode haml-mode haskell-mode haxor-mode helpful hide-mode-line highlight-indentation highlight-numbers highlight-quoted hindent hl-todo htmlize hy-mode hydra imenu-anywhere imenu-list impatient-mode inf-crystal inf-ruby intero irony irony-eldoc ivy ivy-bibtex ivy-hydra ivy-rich ivy-rtags ivy-xref js2-mode js2-refactor json-mode julia-mode ledger-mode less-css-mode lua-mode macrostep magit magithub makefile-executor markdown-mode markdown-toc meghanada merlin mips-mode modern-cpp-font-lock moonscript multi-term nasm-mode nav-flash neotree nix-mode nlinum nlinum-hl nlinum-relative nodejs-repl nose ob-crystal ob-go ob-mongo ob-rust ob-sql-mode ob-translate omnisharp opencl-mode (org-bullets :recipe (org-bullets :fetcher github :repo Kaligule/org-bullets)) org-download org-plus-contrib org-tree-slide (osx-clipboard :ignore t) overseer ox-pandoc ox-reveal pass password-store pcre2el pdf-tools perl6-mode persistent-soft persp-mode php-boris (php-extras :recipe (php-extras :fetcher github :repo arnested/php-extras)) php-mode php-refactor-mode phpunit pip-requirements plantuml-mode prodigy projectile psc-ide pug-mode purescript-mode quelpa quickrun racer rainbow-delimiters rainbow-mode rake restclient rjsx-mode (rotate-text :recipe (rotate-text :fetcher github :repo debug-ito/rotate-text.el)) rspec-mode rtags ruby-refactor rust-mode sass-mode sbt-mode scala-mode shackle shader-mode shrink-path skewer-mode slime smart-forward smartparens smex solaire-mode ssh-deploy stylus-mode swift-mode swiper tern tide toc-org toml-mode tuareg typescript-mode undo-tree use-package vi-tilde-fringe vimrc-mode visual-fill-column vue-mode web-beautify web-mode wgrep which-key xref-js2 yaml-mode yard-mode yasnippet)
  elc dirs:  n/a
  exec-path: (/usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/25.3/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment] 2018-04-03 06:44
Do you know if this is standard magit behavior? Because doom's popup system, by default, ignores magit as much as it can.

Please try something for me: open magit, make a commit and in the commit window do `M-; +popup-buffer-mode` and see if it returns `t` or `nil`. I want to know if `+popup-buffer-mode` is active in it.

**Comment by UndeadKernel** [comment] 2018-04-03 09:12
Hi @hlissner, it is not standard Magit behavior.
There should be no extra window left open.

**Comment by benj02** [comment] 2018-04-03 19:35
Thanks for getting back!

It's definitely not normal magit behavior, this doesn't happen in stock emacs with just magit installed for example.

I tried `+popup-buffer-mode` on every magit buffer and got `nil` every time

**Comment by ppasieka** [comment] 2018-04-04 07:47
And issue with window left opened after commit started around week ago (max 2 weeks). Before it was closing after pressing 'q'.

**Comment by jcf** [comment] 2018-04-04 09:11
@hlissner I'm using this configuration based on what's in the default config, and what you posted to Hastebin:

``` emacs-lisp
(after! magit
  (defun +magit/quit (&optional _kill-buffer)
    (interactive)
    (magit-restore-window-configuration)
    (mapc #'kill-buffer (doom-buffers-in-mode 'magit-mode nil t)))

  (setq magit-bury-buffer-function #'+magit/quit
        magit-popup-display-buffer-action nil)
  (map! :map magit-mode-map [remap quit-window] #'+magit/quit)

  (set! :popup "^\\(?: ?\\*\\)?magit: "
    '((slot . -1) (side . right) (size . 90))
    '((select . t)))
  (set! :popup "^\\*magit.*popup\\*"
    '((slot . 0) (side . right))
    '((select . t)))
  (set! :popup "^\\(?: ?\\*\\)?magit-revision:.*"
    '((slot . 2) (side . right) (window-height . 0.6))
    '((select . t)))
  (set! :popup "^\\(?: ?\\*\\)?magit-diff:.*"
    '((slot . 2) (side . right) (window-height . 0.6))
    '((select . nil))))

(def-package! evil-magit
  :after magit
  :config
  (define-key magit-mode-map (kbd doom-leader-key) nil)
  (add-hook! 'magit-mode-hook (evil-snipe-mode -1)))
```

Is it worth adding this behind a feature  (maybe `magit +testing`?) in develop so we can all pull the latest and give feedback based on Git refs etc?

**Comment by robbert-vdh** [comment] 2018-04-04 09:18
This is caused by evil-collection's '[simple](https://github.com/emacs-evil/evil-collection/blob/5d25e08f94b5fc9814f97a3225292b483cb59b91/evil-collection-simple.el)' keybindings. Those keybindings override common keys like `q` and `SPC` in some special buffers, including Magit. I had the same issue a few weeks ago and I ended up fixing it by disabling the keybindings entirely since they don't add anything useful and tend to only break things. As a temporary fix, you could add this to your init.el:

```elisp
(def-package-hook! evil-collection :pre-config
  (delq 'simple evil-collection-mode-list))
```

**Comment by hlissner** [comment] 2018-04-08 20:14
With 17a3008, 9315558 and 120f770, this issue _should_ be resolved. Please update and let me know if that isn't the case.

**Comment by hlissner** [comment] 2018-04-09 00:47
460461e should resolve your issue (and the OP's issue). Let me know how it fares.

**Closed** 2018-08-02 16:28 UTC
Labels: bug, fixed in develop
