### ISSUE TITLE
SPC w s/SPC w v bindings fails with error

### ISSUE THREAD

**Issue by jcrono** [hlissner/doom-emacs#588] opened 2018-05-16 06:38 UTC
---

### Observed behavior

After updating to latest HEAD on develop
Trying to split window via `SPC w s` or `SPC w v` fails with the following error:
```
Cannot open load file: No such file or directory: feature/evil/autoload/evil
```
`:sp` `:vs` works fine

### Expected behavior

`SPC w s` splits window with no error.

### Steps to reproduce

1. Open emacs,
2. press `SPC w s`,

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 25.3.1 (May 09, 2018)
- Doom: 2.0.9 (develop https://github.com/hlissner/doom-emacs/commit/b4a7e5348a6ff2bffacd1e2a9677532a1c515b5e)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
- Details:
  ```elisp
  uname -a:  Linux multivac 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion ivy :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree unicode vi-tilde-fringe window-select :tools editorconfig electric-indent eshell make magit pdf term :lang data emacs-lisp (latex +latexmk +okular) markdown (org +attach +babel +capture +export +present +publish) python rust sh web :config :private python-extra (keybindings +repeat) personal)
  packages:  (ace-link ace-window adaptive-wrap all-the-icons anaconda-mode anzu async auctex auctex-latexmk auto-compile auto-yasnippet avy (centered-window :recipe (centered-window :fetcher github :repo anler/centered-window-mode)) command-log-mode company company-anaconda company-auctex company-dict company-racer company-shell company-statistics company-web counsel counsel-css counsel-dash counsel-projectile (devdocs-lookup :recipe (devdocs-lookup :fetcher github :repo skeeto/devdocs-lookup)) dired-k dockerfile-mode doom-themes dumb-jump editorconfig (emacs-snippets :recipe (emacs-snippets :fetcher github :repo hlissner/emacs-snippets :files (*))) emmet-mode evil evil-anzu evil-args evil-collection evil-commentary evil-easymotion evil-embrace evil-escape evil-exchange evil-goggles evil-indent-plus evil-magit evil-matchit evil-mc evil-multiedit evil-numbers evil-org evil-snipe evil-surround evil-textobj-anyblock evil-vimish-fold evil-visualstar (exec-path-from-shell :ignore t) expand-region flycheck flycheck-cask flycheck-popup-tip flycheck-rust flyspell flyspell-correct flyspell-correct-ivy git-gutter-fringe git-link git-timemachine gitconfig-mode gitignore-mode graphql-mode haml-mode haxor-mode helpful hide-mode-line highlight-indentation highlight-numbers highlight-quoted hl-todo htmlize hydra ivy ivy-bibtex ivy-hydra ivy-rich ivy-xref json-mode less-css-mode macrostep magit magithub makefile-executor markdown-mode markdown-toc mips-mode multi-term nasm-mode nav-flash neotree nlinum nlinum-hl nlinum-relative nose ob-mongo ob-rust ob-sql-mode ob-translate (org-bullets :recipe (org-bullets :fetcher github :repo Kaligule/org-bullets)) org-download org-plus-contrib org-tree-slide (osx-clipboard :ignore t) overseer ox-pandoc ox-reveal pcre2el pdf-tools persistent-soft persp-mode pip-requirements projectile pug-mode pyvenv quelpa quickrun racer rainbow-delimiters rainbow-mode restart-emacs rust-mode sass-mode shrink-path slim-mode slime smartparens smex solaire-mode stylus-mode super-save swiper toc-org toggle-quotes toml-mode undo-tree unicode-fonts use-package vi-tilde-fringe vimrc-mode visual-fill-column web-beautify web-mode wgrep which-key yaml-mode yapfify yasnippet)
  elc dirs:  (core/ core/autoload/)
  exec-path: (/home/crono/.nimble/bin /home/crono/.cargo/bin /home/crono/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/25.3/x86_64-pc-linux-gnu)
  ```

```
</details>

**Comment by hlissner** [comment] 2018-05-16 18:00
I am aware of the cause of this issue and have a fix ready for it in the next batch of commits. They'll be up later today. 

Thanks for letting me know!

**Comment by hlissner** [comment] 2018-05-16 18:02
Note: here is a workaround for the time being (add to `~/.doom.d/init.el`):

```elisp
(add-to-list 'load-path doom-modules-dir)
```

**Comment by hlissner** [comment] 2018-05-18 00:19
This should be fixed as of the latest `develop`. Please update, run `make` and you should be golden. Let me know if that isn't the case!

If it is fixed, I'd like to leave this issue open until the 2.1 release.

**Comment by igor-kupczynski** [comment] 2018-05-18 07:52
It did the trick for me, thank you!

**Closed** 2018-08-02 16:37 UTC
Labels: bug, fixed in develop
