### ISSUE TITLE
[HOWTO] use (doom! (ivy +childframe)) only in graphic, not terminal?

### ISSUE THREAD

**Issue by HesperusArcher** [hlissner/doom-emacs#1661] opened 2019-08-11 01:21 UTC
**What I want to achieve**
I use graphic Emacs in most time, also use it in terminal when testing about cjk fonts or modifying some face colors, etc. So I want to use `(ivy +childframe) on in graphic, not terminal.

Follow up with an expanded explanation, if necessary. A few suggestions of what
you could include are:
- I think I haven't found the right package to def to config the feature. I tried to type:
```elisp
(doom!
  :completion
  (if (display-graphic-p)
    (ivy
     +childframe))
```
but it seems not to work.

**System information**
<details><pre>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /bin/bash
- Emacs: 26.2 (4月 13, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD, _upgrade/develop f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2                                                                                                                   
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 4.19.62-1-MANJARO #1 SMP PREEMPT Sun Jul 28 09:14:58 UTC 2019 x86_64
  modules:   (:completion company (ivy +childframe) :ui indent-guides vc-gutter :editor multiple-cursors snippets :emacs dired vc :term term :tools eval lsp magit rgb 
:lang data emacs-lisp ess latex markdown python :config default)                                                                                                      
  packages:  (ace-pinyin aggressive-fill-paragraph aggressive-indent company-box company-tabnine electric-operator ess-smart-equals eval-in-repl ivy-posframe magic-lat
ex-buffer symbol-overlay youdao-dictionary poly-R poly-markdown (awesome-tab :recipe (awesome-tab :fetcher github :repo manateelazycat/awesome-tab)) (awesome-tray :rec
ipe (awesome-tray :fetcher github :repo manateelazycat/awesome-tray)) (auto-save :recipe (auto-save :fetcher github :repo manateelazycat/auto-save)) (awesome-pair :rec
ipe (awesome-pair :fetcher github :repo manateelazycat/awesome-pair)) (company-english-helper :recipe (company-english-helper :fetcher github :repo manateelazycat/comp
any-english-helper) :disable t) (color-rg :recipe (color-rg :fetcher github :repo manateelazycat/color-rg)) (insert-translated-name :recipe (insert-translated-name :fe
tcher github :repo manateelazycat/insert-translated-name)) (open-newline :recipe (open-newline :fetcher github :repo manateelazycat/open-newline)) (thing-edit :recipe 
(thing-edit :fetcher github :repo manateelazycat/thing-edit)) (smart-align :recipe (smart-align :fetcher github :repo manateelazycat/smart-align)) (snails :recipe (sna
ils :fetcher github :repo manateelazycat/snails)) (delete-block :recipe (delete-block :fetcher github :repo manateelazycat/delete-block)))                            
  exec-path: (~/miniconda2/bin ~/miniconda2/condabin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/
core_perl /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)                                                                                                                    
  ```
</pre></details>

**Comment by hlissner** [comment] 2019-08-15 06:20
This appears to be an upstream issue, in ivy-posframe. [A PR was introduced to fall back to the minibuffer in TTY emacs](https://github.com/tumashu/ivy-posframe/pull/53), but it seems to be broken in later commits. It would be best to bring this up with them.

Anyway, there is currently no good way to have dynamic conditional modules. Your module list should be static, and should not be changing from session to session. You could have multiple `doom!` calls wrapped in conditions. e.g.

```elisp
(doom! ...)

(when ... (doom! ...))
```

However, do not use this for conditions that may change between Emacs sessions (like `display-graphic-p`). `doom refresh` only installs the modules it can see. Since `bin/doom` runs in a non-interactive session, only your non-gui modules will be installed (i.e. `+childframe`'s dependencies will never be installed).

**Comment by gagbo** [comment] 2019-08-15 10:54
I suppose I did not really check out the latest ivy-posframe in a while (6 weeks), it looks like they changed the PR I made from "advising the advices" to using a macro to define all advices : https://github.com/tumashu/ivy-posframe/commit/8abcf525652d8a112df0e7256998f428a29e3fab#diff-de06f0ff7ffe6cec621757e70cfd9188

I don't know exactly how macro expansion works, but is it possible that the macro is expanded/evaluated only once on the first call and then stored forever ?

**Comment by hlissner** [comment] 2019-08-15 19:14
@gagbo The expanded macro isn't baking in the `display-graphic-p` check, fortunately. However, the new approach appears to no-op if not in a graphical session, whereas your original solution would invoke a fallback. This gimps ivy in tty Emacs.

**Comment by gagbo** [comment] 2019-09-09 22:32
Do you still have the issue ? I closed upstream since I don't have regression anymore (I forgot to check before)

**Comment by hlissner** [comment] 2019-10-12 23:35
I'll presume this has been resolved upstream, so I'll close this. Feel free to follow up here if that isn't the case.

**Closed by hlissner** 2019-10-12 23:35 UTC
Labels: is:question, re:bin/doom, re:elisp, re:modules, status:resolved-elsewhere
