### ISSUE TITLE
How can I truncate filenames in `projectile-find-file` and `counsel-projectile-find-file`

### ISSUE THREAD

**Issue by JordanAnthonyKing** [hlissner/doom-emacs#5021] opened 2021-05-09 13:45 UTC
My projects often have a lot of depth, and some paths longer than the width of the emacs window. Is it possible to truncate long filepaths so that I can still see the filename?

**Comment by hlissner** [comment] 2021-05-09 16:36
See `SPC h f ivy-set-display-transformer` for defining transformers for ivy/counsel commands. You can define one to shorten the file names however you wish.

----

As this is not a bug or an actionable ticket (our issue tracker will no longer be for how-to questions once our Discourse is up), I will close this, but feel free to follow up here.

**Closed by hlissner** 2021-05-09 16:36 UTC
Labels: delete me, invalid

**Comment by JordanAnthonyKing** [comment] 2021-05-09 17:28
> See `SPC h f ivy-set-display-transformer` for defining transformers for ivy/counsel commands. You can define one to shorten the file names however you wish.

I had tried this before commenting but with little luck, taking a more thorough look at the readme for ivy-rich shows that for `counsel-projectile-*` and other extended ivy/counsel commands ivy-rich needs to be loaded after counsel-projectile, which doom isn't.

After enabling and disabling ivy-rich mode somethig simple like this works fine:
```
(after! ivy-rich
  (plist-put! ivy-rich-display-transformers-list
              'counsel-projectile-find-file (lambda (x) (shrink-path-dirs x))))
```

Is this worth raising a bug over?

**Comment by hlissner** [comment] 2021-05-09 18:08
Try

```lisp
(after! counsel-projectile
  (ivy-set-display-transformer #'counsel-projectile-find-file #'name-of-your-private-transformer-function))
```

>  ivy-rich needs to be loaded after counsel-projectile, which doom isn't.

ivy-rich does not target counsel-projectile-find-file, so ivy-rich isn't relevant to this issue. It's more likely you are seeing the effect of [this line](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/ivy/config.el#L333), hence my suggestion above.

> Is this worth raising a bug over?

No. Haven't ruled out that this is a configuration issue, rather than a bug.

**Comment by JordanAnthonyKing** [comment] 2021-05-09 18:53
```
(after! counsel-projectile
  (ivy-set-display-transformer
              #'counsel-projectile-find-file (lambda (x) (shrink-path-dirs x))))
```
Does not work on startup, or after disabling and reenabling ivy-rich.

**Comment by hlissner** [comment] 2021-05-10 00:05
Then I suppose the only option is to manually update ivy-rich:

```elisp
(after! counsel-projectile
  (ivy-set-display-transformer #'counsel-projectile-find-file #'shrink-path-dirs)
  (ivy-rich-set-display-transformer))
```

**Comment by JordanAnthonyKing** [comment] 2021-05-10 14:15
```
(after! ivy-rich
  (ivy-set-display-transformer #'counsel-projectile-find-file #'shrink-path-dirs)
  (ivy-rich-set-display-transformer))
```

This also does not work
