### ISSUE TITLE
Doom Upgrade Issue - Symbol's function definition is void: straight--process-buffer

### ISSUE THREAD

**Issue by glanham-jr** [hlissner/doom-emacs#4988] opened 2021-05-05 21:17 UTC
I attempted to upgrade Doom Emacs, but ran into an error message I hadn't seen before.

**Steps to reproduce:**
`doom upgrade`

**Expected**
The process would complete without fail

**Actual**
I would receive the error message below.

```
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

**System information:**
https://pastebin.com/42HCKJE9

**Comment by hlissner** [comment] 2021-05-05 21:23
Duplicate of #4950.

**Closed by hlissner** 2021-05-05 21:23 UTC
Labels: delete me, duplicate

**Comment by glanham-jr** [comment] 2021-05-08 16:34
This seems to be a recurring issue from what I've seen in the bug tracker (apologies for not searching better originally). While it can't be automated for now, what if this specific exception is caught, and the new message includes a suggestion to remove the "straight.el" file manually?

https://github.com/hlissner/doom-emacs/issues/4950#issuecomment-829944410

Specifically this snippet of code which worked for me.
```bash
# In your .config/emacs or .emacs.d directory
rm -r .local/straight/repos/straight.el
./bin/doom sync -up
```

My elisp is rusty, but here is a psuedo-code solution I was thinking of. The message needs improved, but this is the general idea.

```lisp
(defvar doom--cli-updated-recipes nil)
(defun doom--cli-recipes-update ()
  "Updates straight and recipe repos."
  (unless doom--cli-updated-recipes
    (straight--make-build-cache-available)
    (print! (start "Updating recipe repos..."))
    (if (boundp 'straight--process-buffer) ; only attempt to upgrade if this is defined
        (progn
          (print-group!
           (doom--with-package-recipes
            (delq
             nil (mapcar (doom-rpartial #'gethash straight--repo-cache)
                         (mapcar #'symbol-name straight-recipe-repositories)))
            (recipe package type local-repo)
            (let ((esc (unless doom-debug-p "\033[1A"))
                  (ref (straight-vc-get-commit type local-repo))
                  newref output)
              (print! (start "\033[KUpdating recipes for %s...%s") package esc)
              (doom--straight-with (straight-vc-fetch-from-remote recipe)
                                   (when .it
                                     (setq output .output)
                                     (straight-merge-package package)
                                     (unless (equal ref (setq newref (straight-vc-get-commit type local-repo)))
                                       (print! (success "\033[K%s updated (%s -> %s)")
                                               package
                                               (doom--abbrev-commit ref)
                                               (doom--abbrev-commit newref))
                                       (unless (string-empty-p output)
                                         (print-group! (print! (info "%s" output))))))))))
          (setq straight--recipe-lookup-cache (make-hash-table :test #'eq)
                doom--cli-updated-recipes t))
      (print! "straight--proces-buffer is not defined. Consider running the following commands.\n 'rm -r ../../.local/straight/repos/straight.el' then '../.././bin/doom sync -up'"))))
```

**Comment by hlissner** [comment] 2021-05-08 18:25
U'm aware of the issue and already deployed a solution (see https://github.com/hlissner/doom-emacs/commit/f3c496d295c04ac1bed3266cc72c3b9b222fe4cd), but it will only prevent this in the future. It won't help folks upgrading from before the change.
