### ISSUE TITLE
can't restart doom sometimes

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#2904] opened 2020-04-15 10:39 UTC
**What did you expect to happen?**
`SPC q r` - restart and restore session.

**What actually happened?**
I get this message and it fails to restart.

```
Saving session
cl--position: Selecting deleted buffer
```

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (s-f) #<bytecode 0x1578f0fbffb1>)((lambda (buffer) (when (funcall (with-no-warnings '(lambda (buffer &rest rest-args) (when ... ...))) buffer) (let ((vars-list (with-current-buffer buffer (delete-if-not ... ... :key ...)))) (funcall (with-no-warnings '(closure ... ... ...)) buffer 'def-indirect-buffer vars-list)))))
  cl--position(nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) (lambda (b) (when (persp-buffer-filtered-out-p b persp-filter-save-buffers-functions) 'skip)) persp-tramp-save-buffer (lambda (b) (when (eq 'dired-mode (buffer-local-value 'major-mode b)) `(def-buffer ,(buffer-name b) ,(buffer-local-value ... b) ,(buffer-local-value ... b)))) (lambda (b) `(def-buffer ,(buffer-name b) ,(buffer-file-name b) ,(buffer-local-value 'major-mode b)))) 0 nil nil)
  cl-position(nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) (lambda (b) (when (persp-buffer-filtered-out-p b persp-filter-save-buffers-functions) 'skip)) persp-tramp-save-buffer (lambda (b) (when (eq 'dired-mode (buffer-local-value 'major-mode b)) `(def-buffer ,(buffer-name b) ,(buffer-local-value ... b) ,(buffer-local-value ... b)))) (lambda (b) `(def-buffer ,(buffer-name b) ,(buffer-file-name b) ,(buffer-local-value 'major-mode b)))) :if #f(compiled-function (sl) #<bytecode 0x1578f0fbfde9>) :key #f(compiled-function (s-f) #<bytecode 0x1578f0fbffb1>))
  apply(cl-position nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) (lambda (b) (when (persp-buffer-filtered-out-p b persp-filter-save-buffers-functions) 'skip)) persp-tramp-save-buffer (lambda (b) (when (eq 'dired-mode (buffer-local-value 'major-mode b)) `(def-buffer ,(buffer-name b) ,(buffer-local-value ... b) ,(buffer-local-value ... b)))) (lambda (b) `(def-buffer ,(buffer-name b) ,(buffer-file-name b) ,(buffer-local-value 'major-mode b)))) (:if #f(compiled-function (sl) #<bytecode 0x1578f0fbfde9>) :key #f(compiled-function (s-f) #<bytecode 0x1578f0fbffb1>)))
  cl-find(nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) (lambda (b) (when (persp-buffer-filtered-out-p b persp-filter-save-buffers-functions) 'skip)) persp-tramp-save-buffer (lambda (b) (when (eq 'dired-mode (buffer-local-value 'major-mode b)) `(def-buffer ,(buffer-name b) ,(buffer-local-value ... b) ,(buffer-local-value ... b)))) (lambda (b) `(def-buffer ,(buffer-name b) ,(buffer-file-name b) ,(buffer-local-value 'major-mode b)))) :if #f(compiled-function (sl) #<bytecode 0x1578f0fbfde9>) :key #f(compiled-function (s-f) #<bytecode 0x1578f0fbffb1>))
  apply(cl-find nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) (lambda (b) (when (persp-buffer-filtered-out-p b persp-filter-save-buffers-functions) 'skip)) persp-tramp-save-buffer (lambda (b) (when (eq 'dired-mode (buffer-local-value 'major-mode b)) `(def-buffer ,(buffer-name b) ,(buffer-local-value ... b) ,(buffer-local-value ... b)))) (lambda (b) `(def-buffer ,(buffer-name b) ,(buffer-file-name b) ,(buffer-local-value 'major-mode b)))) :if #f(compiled-function (sl) #<bytecode 0x1578f0fbfde9>) (:key #f(compiled-function (s-f) #<bytecode 0x1578f0fbffb1>)))
  find-if(#f(compiled-function (sl) #<bytecode 0x1578f0fbfde9>) ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) (lambda (b) (when (persp-buffer-filtered-out-p b persp-filter-save-buffers-functions) 'skip)) persp-tramp-save-buffer (lambda (b) (when (eq 'dired-mode (buffer-local-value 'major-mode b)) `(def-buffer ,(buffer-name b) ,(buffer-local-value ... b) ,(buffer-local-value ... b)))) (lambda (b) `(def-buffer ,(buffer-name b) ,(buffer-file-name b) ,(buffer-local-value 'major-mode b)))) :key #f(compiled-function (s-f) #<bytecode 0x1578f0fbffb1>))
  #f(compiled-function (b) #<bytecode 0x1578f0fbffcd>)(#<killed buffer>)
  mapcar(#f(compiled-function (b) #<bytecode 0x1578f0fbffcd>) (#<buffer todo.org> #<buffer 20200415095844-core_infra.org> #<buffer 20200415095823-core_infra_cilium.org> #<buffer 20200415095643-core_platform.org> #<killed buffer> #<buffer 20200409112408-etcd_authentication.org> #<buffer 20200415095138-etcd_security_tls.org> #<buffer 20200409113336-etcd_clustering.org> #<buffer *Deft*> #<buffer 20200414170054-core_team_support.org>))
  persp-buffers-to-savelist(#s(perspective :name "main" :buffers (#<buffer todo.org> #<buffer 20200415095844-core_infra.org> #<buffer 20200415095823-core_infra_cilium.org> #<buffer 20200415095643-core_platform.org> #<killed buffer> #<buffer 20200409112408-etcd_authentication.org> #<buffer 20200415095138-etcd_security_tls.org> #<buffer 20200409113336-etcd_clustering.org> #<buffer *Deft*> #<buffer 20200414170054-core_team_support.org>) :window-conf (((min-height . 8) (min-width . 20) (min-height-ignore . 6) (min-width-ignore . 7) (min-height-safe . 2) (min-width-safe . 4) (min-pixel-height . 144) (min-pixel-width . 160) (min-pixel-height-ignore . 100) (min-pixel-width-ignore . 49) (min-pixel-height-safe . 36) (min-pixel-width-safe . 32)) hc (pixel-width . 1272) (pixel-height . 1359) (total-width . 159) (total-height . 75) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (vc (pixel-width . 843) (pixel-height . 1359) (total-width . 105) (total-height . 75) (normal-height . 1.0) (normal-width . 0.662754303599374) (combination-limit . t) (leaf (pixel-width . 843) (pixel-height . 681) (total-width . 105) (total-height . 38) (normal-height . 0.5010989010989011) (normal-width . 1.0) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring ... :idx -1))) (buffer "20200409113336-etcd_clustering.org" (selected . t) (hscroll . 0) (fringes 4 4 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 694) (start . 1)) (prev-buffers ("*doom*" 1 1578) ("20200409113336-etcd_clustering.org" 1 618) ("20200415095138-etcd_security_tls.org" 1 85) ("todo.org" 1 323) ("20200409112408-etcd_authentication.org" 1 15) ("*Deft*" 1 13) ("20200414170054-core_team_support.org" 1 398) ("*scratch*" 1 1))) (leaf (last . t) (pixel-width . 843) (pixel-height . 678) (total-width . 105) (total-height . 37) (normal-height . 0.4989010989010989) (normal-width . 1.0) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring ... :idx -1))) (buffer "todo.org" (selected) (hscroll . 0) (fringes 4 4 t nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 788) (start . 124)) (prev-buffers ("todo.org" 124 506) ("20200415095823-core_infra_cilium.org" 1 38) ("20200415095844-core_infra.org" 1 78) ("20200415095643-core_platform.org" 1 81) ("20200409113336-etcd_clustering.org" 1 500) ("20200415095138-etcd_security_tls.org" 1 88)))) (leaf (last . t) (pixel-width . 429) (pixel-height . 1359) (total-width . 54) (total-height . 75) (normal-height . 1.0) (normal-width . 0.33724569640062596) (parameters (window-side . right) (window-slot . 0) (better-jumper-struct . #s(better-jumper-jump-list-struct :ring (0 1 . ...) :idx -1))) (buffer "*org-roam*" (selected) (hscroll . 0) (fringes 4 4 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated . side) (point . 1) (start . 1)) (prev-buffers ("*org-roam*" 1 1)))) :parameters ((last-project-root . "/home/james/Dropbox/Notes/")) :weak nil :auto nil :hidden nil))
  persp-to-savelist(#s(perspective :name "main" :buffers (#<buffer todo.org> #<buffer 20200415095844-core_infra.org> #<buffer 20200415095823-core_infra_cilium.org> #<buffer 20200415095643-core_platform.org> #<killed buffer> #<buffer 20200409112408-etcd_authentication.org> #<buffer 20200415095138-etcd_security_tls.org> #<buffer 20200409113336-etcd_clustering.org> #<buffer *Deft*> #<buffer 20200414170054-core_team_support.org>) :window-conf (((min-height . 8) (min-width . 20) (min-height-ignore . 6) (min-width-ignore . 7) (min-height-safe . 2) (min-width-safe . 4) (min-pixel-height . 144) (min-pixel-width . 160) (min-pixel-height-ignore . 100) (min-pixel-width-ignore . 49) (min-pixel-height-safe . 36) (min-pixel-width-safe . 32)) hc (pixel-width . 1272) (pixel-height . 1359) (total-width . 159) (total-height . 75) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (vc (pixel-width . 843) (pixel-height . 1359) (total-width . 105) (total-height . 75) (normal-height . 1.0) (normal-width . 0.662754303599374) (combination-limit . t) (leaf (pixel-width . 843) (pixel-height . 681) (total-width . 105) (total-height . 38) (normal-height . 0.5010989010989011) (normal-width . 1.0) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring ... :idx -1))) (buffer "20200409113336-etcd_clustering.org" (selected . t) (hscroll . 0) (fringes 4 4 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 694) (start . 1)) (prev-buffers ("*doom*" 1 1578) ("20200409113336-etcd_clustering.org" 1 618) ("20200415095138-etcd_security_tls.org" 1 85) ("todo.org" 1 323) ("20200409112408-etcd_authentication.org" 1 15) ("*Deft*" 1 13) ("20200414170054-core_team_support.org" 1 398) ("*scratch*" 1 1))) (leaf (last . t) (pixel-width . 843) (pixel-height . 678) (total-width . 105) (total-height . 37) (normal-height . 0.4989010989010989) (normal-width . 1.0) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring ... :idx -1))) (buffer "todo.org" (selected) (hscroll . 0) (fringes 4 4 t nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 788) (start . 124)) (prev-buffers ("todo.org" 124 506) ("20200415095823-core_infra_cilium.org" 1 38) ("20200415095844-core_infra.org" 1 78) ("20200415095643-core_platform.org" 1 81) ("20200409113336-etcd_clustering.org" 1 500) ("20200415095138-etcd_security_tls.org" 1 88)))) (leaf (last . t) (pixel-width . 429) (pixel-height . 1359) (total-width . 54) (total-height . 75) (normal-height . 1.0) (normal-width . 0.33724569640062596) (parameters (window-side . right) (window-slot . 0) (better-jumper-struct . #s(better-jumper-jump-list-struct :ring (0 1 . ...) :idx -1))) (buffer "*org-roam*" (selected) (hscroll . 0) (fringes 4 4 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated . side) (point . 1) (start . 1)) (prev-buffers ("*org-roam*" 1 1)))) :parameters ((last-project-root . "/home/james/Dropbox/Notes/")) :weak nil :auto nil :hidden nil))
  mapcar(persp-to-savelist (#s(perspective :name "main" :buffers (#<buffer todo.org> #<buffer 20200415095844-core_infra.org> #<buffer 20200415095823-core_infra_cilium.org> #<buffer 20200415095643-core_platform.org> #<killed buffer> #<buffer 20200409112408-etcd_authentication.org> #<buffer 20200415095138-etcd_security_tls.org> #<buffer 20200409113336-etcd_clustering.org> #<buffer *Deft*> #<buffer 20200414170054-core_team_support.org>) :window-conf (((min-height . 8) (min-width . 20) (min-height-ignore . 6) (min-width-ignore . 7) (min-height-safe . 2) (min-width-safe . 4) (min-pixel-height . 144) (min-pixel-width . 160) (min-pixel-height-ignore . 100) (min-pixel-width-ignore . 49) (min-pixel-height-safe . 36) (min-pixel-width-safe . 32)) hc (pixel-width . 1272) (pixel-height . 1359) (total-width . 159) (total-height . 75) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (vc (pixel-width . 843) (pixel-height . 1359) (total-width . 105) (total-height . 75) (normal-height . 1.0) (normal-width . 0.662754303599374) (combination-limit . t) (leaf (pixel-width . 843) (pixel-height . 681) (total-width . 105) (total-height . 38) (normal-height . 0.5010989010989011) (normal-width . 1.0) (parameters (better-jumper-struct . ...)) (buffer "20200409113336-etcd_clustering.org" (selected . t) (hscroll . 0) (fringes 4 4 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 694) (start . 1)) (prev-buffers ("*doom*" 1 1578) ("20200409113336-etcd_clustering.org" 1 618) ("20200415095138-etcd_security_tls.org" 1 85) ("todo.org" 1 323) ("20200409112408-etcd_authentication.org" 1 15) ("*Deft*" 1 13) ("20200414170054-core_team_support.org" 1 398) ("*scratch*" 1 1))) (leaf (last . t) (pixel-width . 843) (pixel-height . 678) (total-width . 105) (total-height . 37) (normal-height . 0.4989010989010989) (normal-width . 1.0) (parameters (better-jumper-struct . ...)) (buffer "todo.org" (selected) (hscroll . 0) (fringes 4 4 t nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 788) (start . 124)) (prev-buffers ("todo.org" 124 506) ("20200415095823-core_infra_cilium.org" 1 38) ("20200415095844-core_infra.org" 1 78) ("20200415095643-core_platform.org" 1 81) ("20200409113336-etcd_clustering.org" 1 500) ("20200415095138-etcd_security_tls.org" 1 88)))) (leaf (last . t) (pixel-width . 429) (pixel-height . 1359) (total-width . 54) (total-height . 75) (normal-height . 1.0) (normal-width . 0.33724569640062596) (parameters (window-side . right) (window-slot . 0) (better-jumper-struct . #s(better-jumper-jump-list-struct :ring ... :idx -1))) (buffer "*org-roam*" (selected) (hscroll . 0) (fringes 4 4 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated . side) (point . 1) (start . 1)) (prev-buffers ("*org-roam*" 1 1)))) :parameters ((last-project-root . "/home/james/Dropbox/Notes/")) :weak nil :auto nil :hidden nil) #s(perspective :name "etcd-bootstrap" :buffers (#<buffer aws.go> #<buffer README.md>) :window-conf (((min-height . 4) (min-width . 51) (min-height-ignore . 3) (min-width-ignore . 6) (min-height-safe . 1) (min-width-safe . 4) (min-pixel-height . 72) (min-pixel-width . 412) (min-pixel-height-ignore . 50) (min-pixel-width-ignore . 41) (min-pixel-height-safe . 18) (min-pixel-width-safe . 32)) hc (pixel-width . 1272) (pixel-height . 1359) (total-width . 159) (total-height . 75) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (leaf (pixel-width . 332) (pixel-height . 1359) (total-width . 41) (total-height . 75) (normal-height . 1.0) (normal-width . 0.2610062893081761) (parameters (window-side . left) (window-slot . 0) (better-jumper-struct . #s(better-jumper-jump-list-struct :ring ... :idx -1))) (buffer " *Treemacs-Scoped-Buffer-Perspective etcd-bootstra..." (selected) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated . t) (point . 43) (start . 1)) (prev-buffers (" *Treemacs-Scoped-Buffer-Perspective etcd-bootstra..." 1 43))) (leaf (last . t) (pixel-width . 940) (pixel-height . 1359) (total-width . 118) (total-height . 75) (normal-height . 1.0) (normal-width . 0.7389937106918238) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring ... :idx -1))) (buffer "aws.go" (selected . t) (hscroll . 0) (fringes 4 4 t nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 753) (start . 1)) (prev-buffers ("aws.go" 1 751) ("*doom*" 1 1578) ("README.md" 551 2364) ("20200409113336-etcd_clustering.org" 1 618) ("20200415095138-etcd_security_tls.org" 1 85) ("todo.org" 1 323) ("20200409112408-etcd_authentication.org" 1 15) ("*Deft*" 1 13) ("20200414170054-core_team_support.org" 1 398) ("*scratch*" 1 1)))) :parameters ((last-project-root . "/home/james/sky/etcd-bootstrap/")) :weak nil :auto nil :hidden nil)))
  persps-to-savelist(#<hash-table equal 3/10 0x1578f0fc6205>)
  persp-save-state-to-file("/home/james/.emacs.d/.local/etc/workspaces/autosav...")
  (cond ((require 'persp-mode nil t) (if persp-mode nil (persp-mode 1)) (setq persp-auto-save-opt 0) (persp-save-state-to-file file)) ((and (require 'frameset nil t) (require 'restart-emacs nil t)) (let ((frameset-filter-alist (append '(...) frameset-filter-alist)) (desktop-base-file-name (file-name-nondirectory file)) (desktop-dirname (file-name-directory file)) (desktop-restore-eager t) desktop-file-modtime) (make-directory desktop-dirname t) (let ((desktop-file-modtime (nth 5 (file-attributes ...)))) (desktop-save desktop-dirname t)))) ((error "No session backend to save session with")))
  doom-save-session()
  doom/quicksave-session()
  doom/restart-and-restore(nil)
  funcall-interactively(doom/restart-and-restore nil)
  call-interactively(doom/restart-and-restore nil nil)
  command-execute(doom/restart-and-restore)

</pre></details>

**System information:**
<details><pre>
emacs   version    27.0.90
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Apr 07, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -flto -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 83a95925d 2020-04-14 01:29:27 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64
        path       (~/.pyenv/bin ~/.cargo/bin ~/.cabal/bin ~/.local/bin ~/go/bin ~/godev/bin ~/.emacs.d/bin /opt/google-cloud-sdk/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.0.90/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui deft doom doom-dashboard hl-todo indent-guides (modeline +light) nav-flash ophints (popup +all +defaults) (pretty-code +pragmata-pro) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term term :checkers syntax spell :tools ansible docker editorconfig (eval +overlay) (lookup +docsets +dictionary) lsp magit make terraform :lang data emacs-lisp (go +lsp) (java +lsp) javascript markdown (org +dragndrop +journal +roam) (python +lsp +pyenv) (scala +lsp) sh :app calendar :config (default +bindings +smartparens))
        packages   ((magit-todos :disable t) (atomic-chrome) (org-roam :pin 4af4d2e4d5f18422fe0f90d5d83fe4c10ef1a20f))
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by jsravn** [comment] 2020-04-15 10:39
Related to https://github.com/hlissner/doom-emacs/issues/1525 most likely.

**Comment by hlissner** [comment] 2020-04-22 05:24
This is indeed a duplicate of #1525. I'll look into the issue and follow up there.

**Closed by hlissner** 2020-04-22 05:24 UTC
Labels: is:duplicate
