### ISSUE TITLE
Failed install @ org-contrib?

### ISSUE THREAD

**Issue by shanff** [hlissner/doom-emacs#5397] opened 2021-08-19 03:17 UTC
### What did you expect to happen?

Expect $HOME/.emacs.d/doom install to complete successfully.

### What actually happened?

After the doom (develop branch) repo is cloned in part 1 of the 2 step install, it gets through what looks to be a long set of installs and then fails on org-contrib.  The second run through results in the same error, albeit a much shorter list.

```
> Executing 'doom install' with Emacs 27.2 at 2021-08-18 22:02:32
  Installing Doom Emacs!

  > Creating .doom.d/
    ✓ Created .doom.d/
  ! init.el already exists, skipping
  ! config.el already exists, skipping
  ! packages.el already exists, skipping
  - Envvar file already exists, skipping
  Installing plugins
  > Installing packages...
    - Checked out project: 4072f35d85bf0a1c669329d66633e4819f497c1c
    > Building project...
    > Building project > Building xref...
    > Building project...
    - Checked out dired-git-info: 9461476a28a5fec0784260f6e318237c662c3430
    > Building dired-git-info...
    > Updating recipe repos...
    > Cloning org-contrib... emacsmirror-mirror...
    x There was an unexpected error
      Message: Wrong type argument
      Data: (wrong-type-argument . arrayp)
      Backtrace:
        (substring nil 0 0)
        (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
        (shell-quote-argument nil)
        (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
        (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name direct
        (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file
        (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (exp
        (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n
        (let* ((result result) (exit (car result)) (invoked (numberp exit)) (succe
        (let ((directory x6) (result x4) (args x2) (program x0)) (let* ((result re
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

### Describe your attempts to resolve the issue

I've tried Emacs as installed by Ubuntu 20.04 (on WSL1) PPA (27.1) and as installed by homebrew(27.2) - both fail at the same spot.
This is a new install of Ubuntu 20.04 on WSL1 with fresh apt update and apt upgrade.  

### Steps to reproduce

1.  $HOME/.emacs.d/doom install
2.  fails at or right below Cloning org-contrib... emacsmirror-mirror...

### System Information

https://gist.github.com/shanff/9d0cfb6ec155de60e6179cfcc159e73e

**Comment by shanff** [comment] 2021-08-19 03:17
init.el, config.el, packages.el under $HOME/.doom.d are untouched.

**Comment by hlissner** [comment] 2021-08-19 03:19
Duplicate of https://github.com/hlissner/doom-emacs/issues/5207. See https://github.com/hlissner/doom-emacs/issues/5207#issuecomment-877750996.

**Closed by hlissner** 2021-08-19 03:19 UTC
Labels: duplicate
