### ISSUE TITLE
pdf-tools autoload doesn't work

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#306] opened 2017-12-26 18:00 UTC
I did
```
(def-package! pdf-tools
  :if (string= (getenv "GUI") "t")
  :mode (("\\.pdf\\'" . pdf-view-mode))
  :config
  (pdf-tools-install))
```
and there are a bunch of warnings related to symbol void.

I tried manually doing (package-initialization) but it still doesn't work. Does doom handle elpa autoloads differently?

**Comment by hlissner** [comment] 2017-12-26 18:09
Could you copy-paste those warnings here? 

There isn't anything wrong with your `def-package!` declaration. pdf-tools is _not_ included in Doom (yet), so I assumed you have installed it in your private module?

Doom doesn't handle ELPA autoloads _at all_ (and doesn't need to, since `use-package` sets up its own autoloads, e.g. `:mode (("\\.pdf\\'" . pdf-view-mode))` creates an implicit autoload for `pdf-view-mode`.

**Comment by amosbird** [comment] 2017-12-26 18:47
Something like `Symbol's function definition is void: pdf-occur-global-minor-mode`

All elisp files listed in pdf-tool-autoloads.el are not loaded at all.

**Comment by hlissner** [comment] 2017-12-27 01:05
Yes, you'll need to manually load `pdf-tool-autoloads.el` with `(load "pdf-tool-autoloads.el" nil t)`

Perhaps something like:

```emacs-lisp
(def-package! pdf-tools
  :if (display-graphic-p)
  :mode ("\\.pdf$" . pdf-view-mode)
  :init (load "pdf-tools-autoloads" nil t)
  :config (pdf-tools-install))
```

**Comment by amosbird** [comment] 2017-12-27 01:41
Thanks!  btw, `  :if (display-graphic-p)` won't work if I always start emacs in daemon first :3

**Comment by hlissner** [comment] 2017-12-27 05:58
No problem! I'll assume your issue is resolved and close this.

> Do I need to add these autoload command manually for all packages?

Only for monolithic packages with autoloaded functions spread across many files, like Auctex, helm, org and haskell-mode (I've already done it for these packages). I do this because I like to only specify exactly what i nee, and in practice, I don't need most of those autoloads files; they end up only adding to the startup time.

> btw, `:if (display-graphic-p)` won't work if I always start emacs in daemon first :3

Oh! That hadn't occurred to me! Good to know :D

**Closed by hlissner** 2017-12-27 05:58 UTC

**Comment by xarthurx** [comment] 2018-02-01 13:12
@hlissner 

`  :init (load "pdf-tools-autoloads" nil t)`

This line, if I'm not wrong, seems not work.
I stuck here for a while and by `eval-region` of the config part, I'm sure the problem is not there.
So the reason might be in this line.

Sorry, I'm not very familar about the loading process.
