### ISSUE TITLE
No color in compilation buffers

### ISSUE THREAD

**Issue by mplanchard** [hlissner/doom-emacs#5150] opened 2021-06-07 15:15 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Compilation buffers maintain color output by underlying processes

### What actually happened?

Compilation buffers do not maintain color output by underlying processes

### Describe your attempts to resolve the issue

My environment is:

|||
|-|-|
| OS | Ubuntu 20.04|
| emacs | 27.1 |
| doom | Doom v2.0.9 (HEAD -> develop b2376a847 2021-06-06 20:36:55 -0400) |
| config | [here](https://github.com/mplanchard/githome/tree/master/all/.doom.d) |
|||

Sometime over the last few weeks, a `doom upgrade` led to colors being stripped from compilation buffers (for example `make`, `rustic-test`, and `pytest`). Now any output that has colors when I run it in the terminal is colorless when run in a compilation buffer. 

I'm pretty sure I haven't changed anything that might be related in my config.

So far I've totally deleted the `~/.emacs.d/.local` directory and run a fresh `doom sync`, and done several doom upgrade/sync cycles over the last couple of weeks to see if anything changed. I've also switched between several themes (`doom-dark+`, `kaolin-dark`, and `doom-gruvbox`) to see if it was a theming issue. There are no errors on the `*Messages*` buffer.

Here's what I get running the profiler for a `cargo test` run: https://pastebin.com/WVHmwViQ

I saw a call to `xterm-color-filter`, which `xterm-color-preserve-properties`. This was set to `nil`, but setting it to `t` doesn't change anything.

I'm unsure where to go from here, and any help is greatly appreciated! 

P.S. also thank you so much for this project. It's amazing!

### Steps to reproduce

1. Open emacs
2. Go to any project that can run a compilation buffer (I first noticed on a private rust project, and that's what the profiler output is for, but this also happens when running `make test` or any pytest command for my open source [safetywrap](https://github.com/mplanchard/safetywrap/))
3. Run the compilation command (e.g. `make test`, `rustic-test`, etc.)
4. The compilation buffer has no color

### System Information

https://pastebin.com/0pa13rGR

**Comment by hlissner** [comment] 2021-06-07 15:30
I cannot reproduce this in vanilla Doom with `doom sync`.

![image](https://user-images.githubusercontent.com/510883/121045149-b0747f00-c783-11eb-93a7-6d92feeddb8e.png)

Please try reproducing it [in vanilla Doom.](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)

**Comment by mplanchard** [comment] 2021-06-07 15:43
I'm getting the same thing in vanilla doom + modules - config (C-c C-p). Struggling to resolve some path issues with vanilla doom minus modules. I will work on figuring that out, and I can also start bisecting modules to figure out if one of them is causing this issue. 

Output of `make test` in vanilla doom + modules

![image](https://user-images.githubusercontent.com/6752481/121049086-03970380-c77d-11eb-8386-e069ab4a117a.png)

Output in a vterm buffer

![image](https://user-images.githubusercontent.com/6752481/121049166-18739700-c77d-11eb-9c1d-6db80894e284.png)

**Comment by mplanchard** [comment] 2021-06-07 16:01
Commenting out every module in the init.el file didn't help in the doom + modules sandbox. Also managed to get vanilla doom running the same make command, and am not getting the colored output there either:

![image](https://user-images.githubusercontent.com/6752481/121052141-b36d7080-c77f-11eb-8df7-bb2dd87bb00c.png)

**Comment by hlissner** [comment] 2021-06-07 16:09
This is because pytest detects you're running in a "dumb" terminal and so it suppresses colors. Check its manpages for a switch to explicitly tell it to emit ansi color codes. e.g. `rg` has `--color=always`.

**Comment by mplanchard** [comment] 2021-06-07 16:15
Same thing with `pytest --color=yes` and `cargo test --color=always`

![image](https://user-images.githubusercontent.com/6752481/121054052-98036500-c781-11eb-9487-bce3c648bfa8.png)

(omitting some of the cargo output, but normally the `ok`s are green)

![image](https://user-images.githubusercontent.com/6752481/121054161-b2d5d980-c781-11eb-86ee-03a34e27b7b5.png)

**Comment by mplanchard** [comment] 2021-06-07 16:21
Oh, but running with `--color=yes` does work in vanilla doom + modules!

**Comment by hlissner** [comment] 2021-06-07 16:23
Actually, it looks like it's working in `cargo`'s case. It's just your theme sets the face it uses for `Finished` and `Running` bold but colorless.

Works for for me in doom-dracula and doom-one:

![image](https://user-images.githubusercontent.com/510883/121055162-0698f080-c78b-11eb-88e3-d0624ffdb012.png)

![image](https://user-images.githubusercontent.com/510883/121055239-17496680-c78b-11eb-9d6a-07748840c885.png)

Try using a different theme.

**Comment by hlissner** [comment] 2021-06-07 16:25
Without `--color=always`

![image](https://user-images.githubusercontent.com/510883/121055601-68595a80-c78b-11eb-9c12-ce20f481cd6f.png)

**Comment by mplanchard** [comment] 2021-06-07 16:26
Yeah, I tried using three themes: `doom-dark+`, `doom-grubox`, and `kaolin-dark`. I get the same results for all of them. Given that `--color=always` works in the vanilla doom plus modules, it must be some package I have installed though that's causing the issue. I also don't understand why it would have previously output color even when running without `--color=always` or similar arguments for both pytest and cargo.

**Comment by hlissner** [comment] 2021-06-07 16:29
Must be. It works fine for me in doom-dark+ and doom-gruvbox:

![image](https://user-images.githubusercontent.com/510883/121056108-dd2c9480-c78b-11eb-920e-eaa671a3cf42.png)

![image](https://user-images.githubusercontent.com/510883/121056138-e74e9300-c78b-11eb-9d77-0ff36f1e55aa.png)

In any case, I'll close this as it's not a Doom issue, but feel free to follow up here.

**Closed by hlissner** 2021-06-07 16:29 UTC
Labels: invalid

**Comment by mplanchard** [comment] 2021-06-07 16:30
Yeah, thanks very much for the debugging help! I'll report back when I figure out the cause.

**Comment by mplanchard** [comment] 2021-06-07 16:33
Hey so actually in your output the `ok`s should be green, shouldn't they?

![image](https://user-images.githubusercontent.com/6752481/121056778-2e388a80-c784-11eb-9077-a388fc2cc6a1.png)

**Comment by mplanchard** [comment] 2021-06-07 17:33
I figured it out!

Something had set the following line in `custom.el`:

```elisp
 '(rustic-ansi-faces
   ["#222222" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1"])
```

which breaks cargo output. Deleting that and what had been set for `ansi-color-names-vector` has fixed both cargo and pytest output in comint mode. I'm still not sure what set these to begin with, but if it happens again I'll at least know where to look.

Thanks again for the help debugging!
