### ISSUE TITLE
given parent class xref-parent-location is not a class in erlang-mode

### ISSUE THREAD

**Issue by heiheshang** [hlissner/doom-emacs#6086] opened 2022-02-04 14:11 UTC
### What did you expect to happen?

run erlang-mode success

### What actually happened?

`Loading erlang-skels...done` 
`eieio-defclass-internal : Given parent class xref-parent-location`

### Steps to reproduce

`ebugger entered--Lisp error: (error "Given parent class xref-file-location is not a cla...") signal(error ("Given parent class xref-file-location is not a cla...")) error("Given parent class %S is not a class" xref-file-location) #f(compiled-function (cname superclasses slots options) "Define CNAME as a new subclass of SUPERCLASSES.\nSLOTS are the slots residing in that class definition, and OPTIONS\nholds the class options.\nSee defclass' for more information." #<bytecode -0x9e5eaf01564a1dc>)(erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) (:documentation "An erlang location is a file location plus arity."))
apply(#f(compiled-function (cname superclasses slots options) "Define CNAME as a new subclass of SUPERCLASSES.\nSLOTS are the slots residing in that class definition, and OPTIONS\nholds the class options.\nSee defclass' for more information." #<bytecode -0x9e5eaf01564a1dc>) (erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) (:documentation "An erlang location is a file location plus arity."))) eieio-defclass-internal(erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) (:documentation "An erlang location is a file location plus arity.")) (progn (defalias 'erlang-xref-location-p (eieio-make-class-predicate 'erlang-xref-location)) (defalias 'erlang-xref-location--eieio-childp (eieio-make-child-predicate 'erlang-xref-location)) (defalias 'erlang-xref-location-child-p #'erlang-xref-location--eieio-childp) (make-obsolete 'erlang-xref-location-child-p "use (cl-typep ... \\='erlang-xref-location) instead" "25.1") (define-symbol-prop 'erlang-xref-location 'cl-deftype-satisfies #'erlang-xref-location--eieio-childp) (eieio-defclass-internal 'erlang-xref-location '(xref-file-location) '((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) '(:documentation "An erlang location is a file location plus arity.")) (cl-defmethod erlang-xref-location-arity ((this erlang-xref-location)) "Access the slot arity' from object of class erla..." (slot-value this 'arity)) (defun erlang-xref-location (&rest slots) "Create a new object of class type erlang-xref-loc..." (declare (compiler-macro (lambda (whole) (if (not (stringp ...)) whole (macroexp-warn-and-return (format "Obsolete name arg %S to constructor %S" ... ...) ...))))) (apply #'make-instance 'erlang-xref-location slots))) (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.") (progn (cl-defmethod xref-backend-identifier-at-point ((_backend (eql erlang-etags))) (if (eq this-command 'xref-find-references) (if (use-region-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol)) (erlang-id-to-string (erlang-get-identifier-at-point)))) (cl-defmethod xref-backend-definitions ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier)) (cl-defmethod xref-backend-apropos ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier t)) (cl-defmethod xref-backend-identifier-completion-table ((_backend (eql erlang-etags))) (let ((erlang-replace-etags-tags-completion-table t)) (tags-completion-table))) (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.") (cl-defmethod xref-location-marker ((locus erlang-xref-location)) (cl-call-next-method locus))) eval((progn (cl-defmethod xref-backend-identifier-at-point ((_backend (eql erlang-etags))) (if (eq this-command 'xref-find-references) (if (use-region-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol)) (erlang-id-to-string (erlang-get-identifier-at-point)))) (cl-defmethod xref-backend-definitions ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier)) (cl-defmethod xref-backend-apropos ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier t)) (cl-defmethod xref-backend-identifier-completion-table ((_backend (eql erlang-etags))) (let ((erlang-replace-etags-tags-completion-table t)) (tags-completion-table))) (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.") (cl-defmethod xref-location-marker ((locus erlang-xref-location)) (cl-call-next-method locus)))) byte-code("\300\301!\203\34\0\300\302!\203\34\0\300\303!\203\34\0\300\304!\203\34\0\305\306!\210\300\207" [erlang-soft-require xref cl-generic eieio etags eval (progn (cl-defmethod xref-backend-identifier-at-point ((_backend (eql erlang-etags))) (if (eq this-command 'xref-find-references) (if (use-region-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol)) (erlang-id-to-string (erlang-get-identifier-at-point)))) (cl-defmethod xref-backend-definitions ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier)) (cl-defmethod xref-backend-apropos ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier t)) (cl-defmethod xref-backend-identifier-completion-table ((_backend (eql erlang-etags))) (let ((erlang-replace-etags-tags-completion-table t)) (tags-completion-table))) (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.") (cl-defmethod xref-location-marker ((locus erlang-xref-location)) (cl-call-next-method locus)))] 2) autoload-do-load((autoload "erlang" ("/home/oper/.emacs.d/.local/autoloads.28.0.91.elc" . 666560) t nil) erlang-mode) command-execute(erlang-mode record) execute-extended-command(nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg))) #<subr funcall-interactively>(execute-extended-command nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg))) apply(#<subr funcall-interactively> (execute-extended-command nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg)))) funcall-interactively(execute-extended-command nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg))) #<subr call-interactively>(execute-extended-command nil nil) apply(#<subr call-interactively> (execute-extended-command nil nil)) explain-pause--wrap-call-interactively(#<subr call-interactively> execute-extended-command nil nil) apply(explain-pause--wrap-call-interactively #<subr call-interactively> (execute-extended-command nil nil)) call-interactively(execute-extended-command nil nil) command-execute(execute-extended-command)`

### System Information

https://pastebin.com/uvgsctA8

**Comment by hlissner** [comment] 2022-02-04 14:25
Duplicate of https://github.com/hlissner/doom-emacs/issues/6083.

Please use the other issue.

**Closed by hlissner** 2022-02-04 14:25 UTC
Labels: duplicate, delete me
