### ISSUE TITLE
Suspicious state fromsyntax checker go-vet

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#1225] opened 2019-03-07 14:05 UTC
So I have been having this issue when I was working with go. 

![screenshot 2019-03-07 at 9 56 58 pm](https://user-images.githubusercontent.com/3354145/53961906-bbfc1a00-4124-11e9-8cba-d4ee0dbe8c79.png)

I have recently formatted my laptop. Perhaps this is not related to Doom but could any one with similar experience point me to the direction where I could have a clue of what's going on? 

I have installed goimports, guru and all relative packages for emacs. Seems that I still cannot get the auto pop imports working, together with format before saving.

**Comment by ccressent** [comment] 2019-03-08 01:54
Hi @andyafter,

You are using go v1.12, aren't you?
The issue is that go v1.12 has completely deprecated `go tool vet` in favor of `go vet` and the `flycheck` package has not been updated accordingly yet. See here:
- https://github.com/flycheck/flycheck/issues/1523
- https://github.com/flycheck/flycheck/pull/1548

Until `flycheck` is updated, stay on go v1.11, or if that's not possible use one of the workarounds suggested in the first link above.

**Comment by andyafter** [comment] 2019-03-08 03:20
Thanks @ccressent, just want to make sure, the goimports package is working fine, but it is not automatically correcting all the imports when I'm saving. Is this also related to go-vet update?

**Comment by ccressent** [comment] 2019-03-08 04:28
Not as far as I'm aware; it's probably something different.

Are you sure the `goimports` binary is in your path (the path seen by Emacs that is; use `M-x getenv` to find out)?

**Comment by bennyhahmeen** [comment] 2019-03-31 21:39
This is now fixed in [flycheck/flycheck#1548](https://github.com/flycheck/flycheck/pull/1548). It does require a doom user to run **_doom update_** to update packages however.

**Comment by Altlock** [comment] 2019-04-15 13:46
I had the same issue in regular Emacs. The same procedure(updating packages) resolved it. Thank you. :)

**Closed** 2019-09-22 04:05 UTC
Labels: is:external, module:lang:go, module:tools:flycheck, status:resolved-elsewhere
