### ISSUE TITLE
doom upgrade breaks on dart-mode

### ISSUE THREAD

**Issue by shivahnshankar** [hlissner/doom-emacs#5527] opened 2021-09-28 06:38 UTC
### What did you expect to happen?

doom upgrade to upgrade and finish without errors

### What actually happened?

"doom upgrade" aborted with the following error:
`In repository "dart-mode", failed to get status:
      
        Failed to get unambiguous name for "main"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) 1 
        Aborted
        Script was abruptly aborted! Run 'doom sync' to repair inconsistencies`

### Describe your attempts to resolve the issue

tried doing this multiple times with same results. Didn't see anything on the lsp-dart repository

### Steps to reproduce

run `doom upgrade`

### System Information

https://pastebin.com/ZLJ99BQn

**Comment by hlissner** [comment] 2021-09-28 09:25
Duplicate of https://github.com/hlissner/doom-emacs/issues/4984

Please search for issues before posting new ones.

**Closed by hlissner** 2021-09-28 09:25 UTC
Labels: duplicate, delete me
