### ISSUE TITLE
Error in doom/sync: Symbol's value as variable is void

### ISSUE THREAD

**Issue by gjm** [hlissner/doom-emacs#4946] opened 2021-04-29 10:31 UTC
After running `doom/upgrade`, when syncing, I get this error:

```
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    x There was an unexpected error
      Message: Symbol's value as variable is void
      Data: (void-variable . comp-native-version-dir)
      Backtrace:
        (concat comp-native-version-dir "/" (file-name-nondirectory (comp-el-to-el
        (doom--eln-file-name "/home/gjm/files/emacs/doom-emacs/.local/straight/bui
        (let* ((eln-name (doom--eln-file-name file)) (eln-file (doom--find-eln-fil
        (doom--eln-file-outdated-p "/home/gjm/files/emacs/doom-emacs/.local/straig
        (if want-native-compile (doom--eln-file-outdated-p file))
        (or (if want-byte-compile (doom--elc-file-outdated-p file)) (if want-nativ
        (if (or (if want-byte-compile (doom--elc-file-outdated-p file)) (if want-n
        (while (consp --cl-var--) (setq file (car --cl-var--)) (if (or (if want-by
        (let* ((outdated nil) (--cl-var-- (doom-files-in build-dir :match "\\.el$"
        (or (file-newer-than-file-p repo-dir build-dir) (file-exists-p (straight--
```

[doom.error.log](https://github.com/hlissner/doom-emacs/files/6397919/doom.error.log)

**System information:**
https://pastebin.com/7SJ7L1sV

**Comment by hlissner** [comment] 2021-04-29 17:20
According to your doom/info, you're don't have native compilation enabled in your current build of Emacs. Reinstall Emacs with it to fix this. 

As this is not a Doom issue I will close this.

**Closed by hlissner** 2021-04-29 17:20 UTC
Labels: invalid

**Comment by gjm** [comment] 2021-04-29 17:25
@hlissner Doom requires native compilation?!?

**Comment by hlissner** [comment] 2021-04-29 17:27
@gjm It does not, no, but I've just realized that I misunderstood your issue and that this is a duplicate of #4947, which I've fixed.
