### ISSUE TITLE
sync with a literate not working as expected on Windows

### ISSUE THREAD

**Issue by elken** [hlissner/doom-emacs#4639] opened 2021-02-11 09:32 UTC
**What did you expect to happen?**
Running `doom sync` on any other platform (including windows, until recently) should tangle my config and run sync

**What actually happened?**
![image](https://user-images.githubusercontent.com/2872862/107619579-49b6dd00-6c4b-11eb-9bbd-107abe913e5a.png)

It just tangles my config and returns. If I remove the CLI file in the literate module, `doom sync` runs as normal.

**Additional details:**
- Include a link to your private config
https://github.com/elken/.doom.d
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

**Steps to reproduce:**
1. Clone doom
2. `doom install`but cancel after creating default directories (the install continues fine but the problem exists regardless)
3. Enable `literate` module
4. Move `config.el` to `config.org` in 1 export block
5. Run `doom sync`
6. 
![image](https://user-images.githubusercontent.com/2872862/107620022-f85b1d80-6c4b-11eb-979b-7383fead10d1.png)

**System information:**
```
SYSTEM  type       windows-nt
        config     x86_64-w64-mingw32
        shell      C:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/27.1/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
        path       (c:/Program Files (x86)/Common Files/Oracle/Java/javapath C:/Python38/Scripts/ C:/Python38/ C:/Windows/system32 C:/Windows C:/Windows/System32/Wbem C:/Windows/System32/WindowsPowerShell/v1.0/ C:/Windows/System32/OpenSSH/ C:/Program Files/dotnet/ C:/Program Files/Microsoft SQL Server/130/Tools/Binn/ C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ C:/Program Files/nodejs/ C:/ProgramData/chocolatey/bin C:/Program Files/PuTTY/ C:/Program Files/Microsoft VS Code/bin C:/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn/ C:/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn/ C:/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn/ C:/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn/ C:/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn/ C:/Program Files (x86)/LINQPad5 C:/Program Files/Git/cmd C:/Program Files/LLVM/bin C:/Program Files/MiKTeX/miktex/bin/x64/ . C:/Program Files/Docker/Docker/resources/bin C:/ProgramData/DockerDesktop/version-bin C:/Program Files/CMake/bin C:/Program Files/Emacs/emacs-28.0.50-snapshot/bin ~/AppData/Local/Microsoft/WindowsApps ~/AppData/Roaming/npm ~/.dotnet/tools C:/Program Files (x86)/GnuWin32/bin C:/Program Files (x86)/Nmap C:/Program Files/Emacs/x86_64/bin ~/.emacs.d/bin C:/Program Files/MiKTeX/miktex/bin/x64 C:/msys64/mingw64/bin ~/php ~/AppData/Local/ComposerSetup/bin ~/AppData/Roaming/Composer/vendor/bin ~/AppData/Local/gitkraken/bin . c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/27.1/x86_64-w64-mingw32)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 21, 2020
        buildopts  --without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static'
        features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (batch envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop e08c5f537 2021-02-07 23:57:44 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +childframe +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo (ligatures +extra +hasklig) modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs (dired +icons) electric undo vc :term eshell vterm :checkers syntax :tools (debugger +lsp) editorconfig (eval +overlay) lookup (lsp +peek) (magit +forge) pdf rgb :os tty :lang (clojure +lsp) data emacs-lisp fsharp (java +meghanada) (javascript +lsp) (kotlin +lsp) nix (org +dragndrop +hugo +present +pretty) (php +lsp) rest (rust +lsp) scheme sh (web +html +lsp +css) :email mu4e :config literate (default +bindings +smartparens))
        packages   ((org-variable-pitch :recipe (:host github :repo cadadr/elisp)) (weblorg) (visual-fill-column) (org-make-toc) (mu4e-alert) (exwm) (rainbow-mode) (graphql-mode) (desktop-environment) (which-key-posframe) (doom-modeline-now-playing) (oauth2))
        unpin      (n/a)
        elpa       (n/a)
```

**Comment by hlissner** [comment] 2021-02-11 22:49
Duplicate of #3746 (later moved to #4273)

**Closed by hlissner** 2021-02-11 22:49 UTC
Labels: duplicate
