### ISSUE TITLE
Allow setting :weight, :slant, :width on variable-pitch font faces 

### ISSUE THREAD

**Issue by t-e-r-m** [hlissner/doom-emacs#6316] opened 2022-04-19 20:28 UTC
### What did you expect to happen?

Hi, since this commit:
https://github.com/hlissner/doom-emacs/commit/19203a91a3252f50aa01be987714174c59652f20

I have been unable to set the weight for mixed-pitch fonts.  It always defaults to "Medium", instead of the weight specified by me.

### What actually happened?

For example, setting this:
`doom-variable-pitch-font (font-spec :family "Franklin ITC Pro" :weight 'light :size 16)`
Gives me this (via `SPC h '`):
`-ITC-Franklin ITC Pro-medium-normal-normal-*-16-*-*-*-*-0-iso10646-1`
Changing `weight` does nothing.

### Describe your attempts to resolve the issue

Reverting the commit mentioned above solves this.

I don't think this feature should just be turned off because EWW or some other program has issues with it.  My main use-cases for mixed-pitch fonts are `org-mode` and `outline-minor-mode`, and not having the correct weight is a dealbreaker.  A flag would be better.

### Steps to reproduce

1. set `doom-variable-pitch-font` with `:weight` other than `'medium` (one that's supported by your font)
2. `SPC h r f`
3. `SPC h '` over mixed-pitch text to see that the `weight` property isn't respected.

### System Information

https://pastebin.com/7PdNdjV2

**Comment by hlissner** [comment] 2022-04-19 20:36
Duplicate of https://github.com/hlissner/doom-emacs/issues/6131.

**Closed by hlissner** 2022-04-19 20:36 UTC
Labels: duplicate

**Comment by hlissner** [comment] 2022-04-19 20:39
Correction: the effect is different, but the cause is the same: font information is lost when converting `font-spec`'s to xlfd strings, or when passing font objects to a face's `:font` attribute. The fix I'm working on for #6131 will fix this.
