### ISSUE TITLE
[BUG] python mode, auto completion not work in straight branch

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1702] opened 2019-08-23 17:15 UTC
**Describe the issue**
The same `~/.doom.d/init.el`, `develop` branch auto-completion can be used, and the `straight` branch does not work, do not understand what is the situation?

**System information**
<details><pre>
Mac Mojave
emacs-plus 26.2
</pre></details>

**Comment by hlissner** [comment] 2019-08-23 17:33
This is a duplicate of #1696. I will follow up there.

**Closed by hlissner** 2019-08-23 17:33 UTC
Labels: is:duplicate
