### ISSUE TITLE
Org-Ref package blocks Doom from upgrading

### ISSUE THREAD

**Issue by quarkquartet** [hlissner/doom-emacs#6011] opened 2022-01-17 02:55 UTC
### What did you expect to happen?

Run `doom upgrade` and upgrade doom and plugins normally.

### What actually happened?

I simply put `(package! org-ref)` in `package.el`, run `doom sync` to install the org-ref package.

Then I run doom upgrade someday. It gives me this:

```
> Updating packages (this may take a while)...
      ✓ (150/230) org-roam: 5b15159 -> 69742c3 [1 commit(s)]
          69742c3 (feat)db: add customizability of extra element link parsing (#2042)
      > In repository "org-ref", failed to get status:

        Failed to get unambiguous name for "master"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1)
```

I wonder is this issue comes solely from upstream org-ref, or from the consistency between doom upgrade function and that plugin?

### Describe your attempts to resolve the issue

Remove org-ref, upgrade doom, and install org-ref back can achieve everything. But that's not the way we are expecting doom to behave...

### Steps to reproduce

Download doom and install.

Add `(package! org-ref)` in `~/.doom.d/package.el`

Run `doom sync` to install package.

Run `doom upgrade` and you'll see it.

### System Information

https://pastebin.com/pJ8xN5h5

**Comment by hlissner** [comment] 2022-01-17 04:29
Duplicate of https://github.com/hlissner/doom-emacs/issues/4984

**Closed by hlissner** 2022-01-17 04:29 UTC
Labels: duplicate, delete me
