### ISSUE TITLE
`bin/doom` command to update `init.el` based on `init.example.el`

### ISSUE THREAD

**Issue by qleguennec** [hlissner/doom-emacs#984] opened 2018-10-28 17:08 UTC
There is currently no way to update `init.el` based on `init.example.el`.

I was thinking of something like `bin/doom update-init-file`, that, through el macros, would update `init.el` with missing entries from `init.example.el`.

That way, each time a new feature is pulled from develop into `.emacs.d/init.el`, if the user runs `bin/doom update-init-file`, their `.doom.d/init.el` would contain new features.

That would require to modify the current text schema (feature, comment) to be more lispy. Something like:
```
(doom! :feature
    eval               ; run code, run (also, repls))
```
```
(doom! :feature
    eval :enabled t :desc "run code, run (also, repls)")
```

If @hlissner thinks that's a valuable idea, I'd like to do a POC as an exercise on macros.

**Comment by ocharles** [comment] 2018-10-28 17:56
Spacemacs has a nice feature where it just opens ediff to merge the new
example file into your example. That'd do the job for me.

**Comment by hlissner** [comment] 2018-10-29 06:44
I've had this sitting my local branch for a while. I'm not sure if it'll make it into Doom in its current incarnation, but it will eventually:

```elisp
(defun doom--get-modules (file)
  (unless (file-exists-p file)
    (user-error "%s does not exist" file))
  (with-temp-buffer
    (insert-file-contents file)
    (when (re-search-forward "(doom! " nil t)
      (goto-char (match-beginning 0))
      (cdr (sexp-at-point)))))

(defun doom--put-modules (tmpfile modules)
  (with-temp-file tmpfile
    (delay-mode-hooks (emacs-lisp-mode))
    (insert (replace-regexp-in-string " " "\n" (prin1-to-string modules)))
    (indent-region (point-min) (point-max))))

;;;###autoload
(defun doom/what-has-changed ()
  "Open an ediff session to compare the module list in
~/.emacs.d/init.example.el and ~/.doom.d/init.el."
  (interactive)
  (let ((old-modules (doom--get-modules (expand-file-name "init.example.el" doom-emacs-dir)))
        (new-modules (doom--get-modules (expand-file-name "init.el" doom-private-dir)))
        (example-init-el "/tmp/doom-init.example.el")
        (private-init-el "/tmp/doom-private-init.el"))
    (doom--put-modules example-init-el old-modules)
    (doom--put-modules private-init-el new-modules)
    (ediff private-init-el example-init-el)))
```

**Comment by hlissner** [comment] 2018-10-30 20:02
Just realized this is a duplicate of #581, as well, so I'll close this.

**Closed by hlissner** 2018-10-30 20:02 UTC
Labels: duplicate
