### ISSUE TITLE
Briefly summarize your issue here

### ISSUE THREAD

**Issue by micdiamond** [hlissner/doom-emacs#5370] opened 2021-08-12 10:27 UTC
### What did you expect to happen?

M-x doom/reload to reload doom without errors

### What actually happened?

I'm getting an error when running M-x doom/reload within emacs. 

-*- mode: compilation; default-directory: "~/.doom.d/" -*-
Comint started at Sun Aug  8 09:32:10

/bin/bash: getent: command not found -ic '"/Users/MicDiamond/.emacs.d/bin/doom" env'
/bin/bash: /bin/bash:: No such file or directory

Comint exited abnormally with code 127 at Sun Aug  8 09:32:12

### Describe your attempts to resolve the issue

ran doom env from the terminal (as suggested by someone on doom emacs discord)

Synced, and reopened doom but I'm still getting the same error. 

When I ran doom env in the terminal, this was the output:
-*- mode: compilation; default-directory: "~/" -*-
Comint started at Thu Aug 12 20:21:38

/bin/bash: getent: command not found -ic '"/Users/MrDiamond/.emacs.d/bin/doom" env'
/bin/bash: /bin/bash:: No such file or directory

Comint exited abnormally with code 127 at Thu Aug 12 20:21:40

### Steps to reproduce

Open emacs
type M-x 
type doom/reload
press enter

### System Information

https://pastebin.com/n9mn9wsx

**Comment by micdiamond** [comment] 2021-08-12 10:31
Notes
-On mac OSX 11.5.1
- The install process wasn't so straightforward so I might have messed something up with the directories
- When I Doom sync from terminal it still works fine

**Comment by micdiamond** [comment] 2021-08-12 10:32
Also, someone else on discord said "I'm on a mac as well. exact same issue"

**Comment by hlissner** [comment] 2021-08-12 17:38
Duplicate of https://github.com/hlissner/doom-emacs/issues/5344.

**Closed by hlissner** 2021-08-12 17:38 UTC
Labels: duplicate
