### ISSUE TITLE
[HOWTO] activate neotree keybinding

### ISSUE THREAD

**Issue by verajosemanuel** [hlissner/doom-emacs#2138] opened 2019-12-02 12:47 UTC
Followed instructions here for activating Neotree

[https://github.com/hlissner/doom-emacs/issues/2007](https://github.com/hlissner/doom-emacs/issues/2007)

After refresh and restart, any keybinding is not working. A message is shown:

`<any key> is not defined`

System is ubuntu Eoan

**Comment by hlissner** [comment] 2019-12-02 23:23
Duplicate of #2135.

**Closed by hlissner** 2019-12-02 23:23 UTC
Labels: is:duplicate
