### ISSUE TITLE
doom roll back (batch git checkout)?

### ISSUE THREAD

**Issue by bladrome** [hlissner/doom-emacs#4352] opened 2020-12-02 07:26 UTC
**Describe the feature**

doom is an aggressive distro, but sometime carelessness may annoy people. Is that possible to add some roll back mechanism so that we can back to a worked version(commit)?
- clear install is time comsuming
- bug fix is uncertainty

**Comment by hlissner** [comment] 2020-12-02 07:31
Duplicate of #4273

**Closed by hlissner** 2020-12-02 07:31 UTC
Labels: duplicate
