### ISSUE TITLE
Packages are not pinned

### ISSUE THREAD

**Issue by bkchr** [hlissner/doom-emacs#2414] opened 2020-01-23 21:51 UTC
**What did you expect to happen?**

Packages should be pinned.

**What actually happened?**

doom upgrade downloads the latest git version.

Could I have fucked up the pinning somehow?

**Comment by nwolfe** [comment] 2020-01-23 21:57
See also: https://github.com/hlissner/doom-emacs/issues/2373

Pinning was temporarily reverted: https://github.com/hlissner/doom-emacs/commit/453e20534ff80ea29af77ab7226529399e7c939a

**Comment by hlissner** [comment] 2020-01-23 22:19
Pinning was temporarily disabled. I'm also considering dropping pinning entirely and going for rolling-release with a rollback mechanism because the necessary work needed to achieve an immutable, reproducible config is turning out less and less feasible.

For the time being, I'll close this as a duplicate of #2373 and keep you posted there.

**Closed by hlissner** 2020-01-23 22:19 UTC
Labels: is:duplicate

**Comment by bkchr** [comment] 2020-01-23 22:34
Ahh okay ty for the fast response.
