### ISSUE TITLE
Copying text in terminal does not work

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#3674] opened 2020-08-03 10:55 UTC
**What did you expect to happen?**
To be able to copy text in terminal.

**What actually happened?**
Using the latest commit 15e1562, if I open emacs in terminal then try to copy any text by pressing `M-w`, I get one of two behaviours:

- If I am not using tmux, the text does not get copied and instead some gibberish is outputted in terminal.
- If I have emacs inside of a tmux session, I get the error `apply: Opening output file: Permission denied, /dev/pts/0`

**_This happens in vanilla Doom and not in vanilla Emacs._**

**Additional details:**
I don't get any errors when not using tmux. When using tmux, I am unable to copy the stack trace. Instead, here's a screenshot
![Screenshot from 2020-08-03 11-49-39](https://user-images.githubusercontent.com/17233936/89175485-c885db80-d57f-11ea-981d-9bbe0236b7e7.png)

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 15e156294 2020-08-03 02:52:55 -0400")
  (dir . "~/Work/Projects/dotfiles/emacs/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64")
  (path "~/.local/bin" "~/.local/share/texlive/2020/root/bin/x86_64-linux" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/.fzf/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company (ivy +icons) :ui doom hl-todo modeline nav-flash ophints vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer vc (undo +tree) :term eshell :checkers syntax spell :tools (eval +overlay) (lookup +docsets) magit make :lang (cc +irony +rtags) data emacs-lisp (latex +latexmk) markdown (org +attach +capture +dragndrop +present) python sh :email mu4e :app calendar :config literate (default +bindings +smartparens))
  (packages (mu4e-alert) (hungry-delete) (yasnippet-snippets) (edit-server) (org-clock-today) (dired-subtree) (dired-single) (org-super-agenda) (xterm-color) (openwith) (rotate) (smartrep) (origami) (try) (el-patch) (auto-dim-other-buffers))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2020-08-08 07:49
This is technically a duplicate of #3498, #3195, #2671, and #1994, and has been resolved in 0a4841b with the introduction of [an :os tty module](https://github.com/hlissner/doom-emacs/blob/develop/modules/os/tty/README.org). This makes clipetty (the cause of your error) opt-in, and gated behind an `+osc` flag (without which it will use `xclip.el` instead).

Have a look at its documentation; I'd recommend you enable it if you want clipboard integration (with or without clipetty).

**Closed by hlissner** 2020-08-08 07:49 UTC
Labels: is:duplicate
