### ISSUE TITLE
purcell/inheritenv changes master to main, broke doom sync

### ISSUE THREAD

**Issue by bersace** [hlissner/doom-emacs#4679] opened 2021-02-22 08:19 UTC
**What did you expect to happen?**

bin/doom sync -pu to success.

**What actually happened?**

bin/doom sync -pu fails with `fatal: Couldn't find remote ref refs/heads/master`

**Additional details:**
- Include a link to your private config : https://gitlab.com/bersace/dotfiles/-/tree/master/files/.config/doom

<details><summary>doom.error.log</summary><pre>
(straight-vc-git-fetch-from-remote (:type git :flavor melpa :host github :repo "purcell/inheritenv" :package "inheritenv" :local-repo "inheritenv"))

(apply straight-vc-git-fetch-from-remote (:type git :flavor melpa :host github :repo "purcell/inheritenv" :package "inheritenv" :local-repo "inheritenv"))
</pre></details>

``` console
$ dirs -p
~/.emacs.d/.local/straight/repos/inheritenv
$ cat .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/purcell/inheritenv.git
        tagOpt = --no-tags
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
        remote = origin
        merge = refs/heads/main
        rebase = true
$ git remote -v
origin  https://github.com/purcell/inheritenv.git (fetch)
origin  https://github.com/purcell/inheritenv.git (push)
$ git fetch 
fatal: Couldn't find remote ref refs/heads/master
```

**Steps to reproduce:**
1. Install Doom from late 2020
2. Update using git
3. run bin/doom sync -pu

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment] 2021-02-23 19:39
Duplicate of #3435

**Closed by hlissner** 2021-02-23 19:39 UTC
Labels: duplicate
