### ISSUE TITLE
[BUG]  Issue with straight and upgrade

### ISSUE THREAD

**Issue by brettgilio** [hlissner/doom-emacs#1886] opened 2019-10-12 22:19 UTC
**Describe the issue**
When running `bin/doom update` or `bin/doom upgrade` it returns an error. It has been doing this for about a week now, I was hoping it would self resolve but it has not.

<details><pre>
There was an unexpected error:
  error (error)
Wrong type argument: listp, "There were errors:

   - undo-tree: ((error Failed to run \"git\"; see buffer *straight-process*) fatal: no upstream configured for branch 'master')"
</pre></details>

**System information**
<details><pre>
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
((emacs
  (version . "26.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2")
  (build . "Sep 22, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 90b59d00d 2019-10-12 00:48:48 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64")
  (path "~/Downloads/mlton-20180207-1.amd64-linux/bin" "~/Repos/sml-redprl/bin" "~/.opam/default/bin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "/usr/lib/emacs/26.1/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit pdf :lang data emacs-lisp markdown ocaml (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
  (packages sml-mode redprl redtt)
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment] 2019-10-12 22:26
This is a duplicate of #1721. See https://github.com/hlissner/doom-emacs/issues/1721#issuecomment-539221633

**Closed by hlissner** 2019-10-12 22:26 UTC
Labels: is:duplicate

**Comment by brettgilio** [comment] 2019-10-12 22:36
> This is a duplicate of #1721. See [#1721 (comment)](https://github.com/hlissner/doom-emacs/issues/1721#issuecomment-539221633)

Thank you!
