### ISSUE TITLE
Plugin request: add magit-delta support

### ISSUE THREAD

**Issue by innerout** [hlissner/doom-emacs#4109] opened 2020-10-18 11:50 UTC
**Describe the feature**
- If the feature involves new plugins, include links to them
Link to plugin [magit-delta](https://github.com/dandavison/magit-delta).
- If the feature involves replacement of current functionality, how the new
  functionality is better?
Magit-delta makes it easier to distinguish changes in magit diffs. 

**System information**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.8.14-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 08 Oct 2020 00:01:25 +0000 x86_64")
  (path "~/.cargo/bin" "/opt/draw.io" "~/.local/bin" "/other/things/in/path" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/var/lib/snapd/snap/bin" "~/.emacs.d/bin/" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "28.0.50")
  (build . "Oct 17, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2")
  (traits batch envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop bba035a1a 2020-10-16 23:42:59 -0400")
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold multiple-cursors snippets word-wrap :emacs (dired +icons) electric undo vc :term vterm :checkers syntax (spell +flyspell) grammar :tools (debugger +lsp) docker (eval +overlay) lookup (lsp +peek) magit pdf :os tty :lang (cc +lsp) data emacs-lisp (latex +lsp) (markdown +grip) (org +attach +babel +capture +export) (python +lsp +pyright) (scala +lsp) (sh +lsp) (yaml +lsp) :email (mu4e +gmail) :config (default +bindings +smartparens))
  (packages (drag-stuff :disable t) (mu4e-maildirs-extension) (mu4e-alert) (color-identifiers-mode) (cmake-font-lock) (eldoc-cmake) (gitconfig-mode) (gitignore-mode) (goto-addr) (goto-line-preview) (flycheck-clang-tidy) (whole-line-or-region) (gitlab-ci-mode) (gitlab-ci-mode-flycheck) (beacon))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by robbert-vdh** [comment] 2020-10-18 12:18
For reference, #3021 was a previous PR for magit-delta.

**Comment by drchsl** [comment] 2020-10-18 12:24
How does this differ from `(setq magit-diff-refine-hunk 'all)`?

**Comment by drchsl** [comment] 2020-10-18 12:27
There's also `(setq magit-diff-refine-hunk 'all)` if you want more fine grained diff-highlighting.

**Comment by innerout** [comment] 2020-10-18 12:46
Thanks for your suggestions! I did not know about PR #3021. Also, I did not know magit had built-in support for that. While some features cannot be in doom's code, it should be easier to discover them. Maybe some configuration options could be suggested in the module's documentation for users to experiment with and check if they are useful?

**Comment by robbert-vdh** [comment] 2020-10-18 15:19
The main differences between magit-delta and `magit-diff-refine-hunk 'all` for me are that magit-delta adds syntax highlighting, is a bit less slow (huge diffs can still take a while to fontify), and that the word diffs are a bit better and easier to read.

**Comment by innerout** [comment] 2020-10-18 16:15
From the little time I have used delta, I can agree with you about the word diffs and that the text is easier to read.

**Comment by hlissner** [comment] 2020-10-18 20:04
This is a duplicate of #3021.

**Closed by hlissner** 2020-10-18 20:04 UTC
Labels: duplicate
