### ISSUE TITLE
org-mouse not fully functional in org-mode

### ISSUE THREAD

**Issue by mtwomey** [hlissner/doom-emacs#5256] opened 2021-07-12 06:06 UTC
### What did you expect to happen?

( after `(require 'org-mouse)` )

When I left click (click-1) on a heading or drawer, it should be collapsed / expanded.

### What actually happened?

When I left-click, `mouse-set-point` is run instead. Using a clean stock install of the latest Doom Emacs.

### Describe your attempts to resolve the issue

Moved my .doom.d directory out of the way, did a clean install of Doom Emacs and retested. 

### Steps to reproduce

1. Open emacs
2. eval `(require 'org-mouse)`
3. Create a new org document
4. Create a heading with some text under it
5. Tab / Shift tab to demonstrate the folding
6. Left-click on the heading which should now fold / unfold (but it does not)

### System Information

https://pastebin.com/dh4pPzMx

**Comment by hlissner** [comment] 2021-07-12 14:34
Judging from `org-mouse-features`'s possible values:

```elisp
(defcustom org-mouse-features
  '(context-menu yank-link activate-stars activate-bullets activate-checkboxes)
  "The features of org-mouse that should be activated.
Changing this variable requires a restart of Emacs to get activated."
  :type '(set :greedy t
	      (const :tag "Mouse-3 shows context menu" context-menu)
	      (const :tag "C-mouse-1 and mouse-3 move trees" move-tree)
	      (const :tag "S-mouse-2 and drag-mouse-3 yank link" yank-link)
	      (const :tag "Activate headline stars" activate-stars)
	      (const :tag "Activate item bullets" activate-bullets)
	      (const :tag "Activate checkboxes" activate-checkboxes)))
```

And skimming through `org-mouse`'s source, the package only enables you to click _on the headings asterisks_ (among other things), but there is no setting to make drawers or entire headings clickable. You'll have to request it upstream if you want this feature.

Since this appears to be a case of mistaken expectations (and everything is working as intended otherwise), I will close this.

**Closed by hlissner** 2021-07-12 14:34 UTC
Labels: delete me, invalid

**Comment by mtwomey** [comment] 2021-07-12 15:13
Agreed. Sorry about that. I will request upstream or implement myself.
