### ISSUE TITLE
fill-column indicator module is no longer working after chaning min emacs version to 27.1

### ISSUE THREAD

**Issue by CSRaghunandan** [hlissner/doom-emacs#5243] opened 2021-07-07 08:23 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Enabling `fill-column` module in `init.el`, should automatically enable `display-fill-column-indicator-mode` 

### What actually happened?

Even after enabling `fill-column` module, `display-fill-column-indicator` is not enabled on any of the major-modes in emacs. I tried running `doom sync` multiple times, but the issue is not resolved.

### Describe your attempts to resolve the issue

I manually enabled fill column indicators for org-mode, conf-mode and prog-mode by using hooks.

### Steps to reproduce

Enable fill-colmn module in init.el
run doom sync
restart emacs and open any programming language file

### System Information

https://pastebin.com/avRSkTrE

**Comment by hlissner** [comment] 2021-07-07 15:37
The fill-column module was removed because it became too trivial once we dropped 26.x support in 044a1a5f2. `display-fill-column-indicator` is built into Emacs 27.1+. To activate it add `(add-hook 'doom-first-buffer-hook #'global-display-fill-column-indicator-mode)`.

As this is not a bug I will close this.

**Closed by hlissner** 2021-07-07 15:37 UTC
Labels: invalid

**Comment by CSRaghunandan** [comment] 2021-07-07 20:01
Thanks for the quick response and tips on activation.
