### ISSUE TITLE
Doom CLI erroring out

### ISSUE THREAD

**Issue by destroyer449** [hlissner/doom-emacs#4321] opened 2020-11-25 22:24 UTC
**What did you expect to happen?**
doom upgrade to upgrade doom and return no errors

**What actually happened?**
all `doom` commands simply return: No catch for tag: exit, 255.

**Additional details:**
- Include a link to your private config: https://github.com/destroyer449/dotfiles/tree/master/.config/doom

```
  doom-initialize-core-modules()
  (if no-config-p nil (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing core modules" 0 5 (face font-lock-comment-face)))))) (doom-initialize-core-modules))
  (progn (setq doom-init-modules-p t) (if no-config-p nil (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing core modules" 0 5 (face font-lock-comment-face)))))) (doom-initialize-core-modules)) (let* ((init-p (and t (condition-case e (let (file-name-handler-alist) (load ... t ...)) ((debug doom-error) (signal ... ...)) ((debug error) (doom--handle-load-error e ... doom-private-dir)))))) (if init-p (progn (if doom-debug-p (progn (let (...) (message ...)))) (maphash (doom-module-loader doom-module-init-file) doom-modules) (run-hook-wrapped 'doom-before-init-modules-hook #'doom-try-run-hook) (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let (file-name-handler-alist) (load ... t ...)) ((debug doom-error) (signal ... ...)) ((debug error) (doom--handle-load-error e ... doom-private-dir))) (load custom-file 'noerror (not doom-debug-mode)))) nil)))
  (if (or force-p (not doom-init-modules-p)) (progn (setq doom-init-modules-p t) (if no-config-p nil (if doom-debug-p (progn (let ((inhibit-message ...)) (message #("DOOM Initializing core modules" 0 5 ...))))) (doom-initialize-core-modules)) (let* ((init-p (and t (condition-case e (let ... ...) (... ...) (... ...))))) (if init-p (progn (if doom-debug-p (progn (let ... ...))) (maphash (doom-module-loader doom-module-init-file) doom-modules) (run-hook-wrapped 'doom-before-init-modules-hook #'doom-try-run-hook) (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let ... ...) (... ...) (... ...)) (load custom-file 'noerror (not doom-debug-mode)))) nil))))
  doom-initialize-modules(nil)
  (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (progn (set-default 'exec-path doom--initial-exec-path) (set-default 'load-path doom--initial-load-path) (set-default 'process-environment doom--initial-process-environment)) (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) (file-missing (if (locate-file doom-autoloads-file load-path) (signal 'doom-autoload-error e) (signal 'doom-error (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it"))))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file 'noerror)) (require 'core-modules) (autoload 'doom-initialize-packages "core-packages") (autoload 'doom-initialize-core-packages "core-packages") (eval-after-load 'package #'(lambda nil (require 'core-packages))) (eval-after-load 'straight #'(lambda nil (doom-initialize-packages))) (add-hook 'doom-first-input-hook #'gcmh-mode) (add-hook 'after-change-major-mode-hook #'doom-run-local-var-hooks-maybe-h) (add-hook 'emacs-startup-hook #'doom-load-packages-incrementally-h) (add-hook 'hack-local-variables-hook #'doom-run-local-var-hooks-h) (add-hook 'window-setup-hook #'doom-display-benchmark-h) (let ((fn (intern (format "%s-h" 'doom-first-buffer-hook)))) (fset fn #'(lambda (&rest _) (if after-init-time (progn (run-hook-wrapped ... ...) (set ... nil))))) (put 'doom-first-buffer-hook 'permanent-local t) (let ((--dolist-tail-- (list 'after-find-file 'doom-switch-buffer-hook))) (while --dolist-tail-- (let ((on (car --dolist-tail--))) (if (functionp on) (advice-add on :before fn) (add-hook on fn)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (let ((fn (intern (format "%s-h" 'doom-first-file-hook)))) (fset fn #'(lambda (&rest _) (if after-init-time (progn (run-hook-wrapped ... ...) (set ... nil))))) (put 'doom-first-file-hook 'permanent-local t) (let ((--dolist-tail-- (list 'after-find-file 'dired-initial-position-hook))) (while --dolist-tail-- (let ((on (car --dolist-tail--))) (if (functionp on) (advice-add on :before fn) (add-hook on fn)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (let ((fn (intern (format "%s-h" 'doom-first-input-hook)))) (fset fn #'(lambda (&rest _) (if after-init-time (progn (run-hook-wrapped ... ...) (set ... nil))))) (put 'doom-first-input-hook 'permanent-local t) (let ((--dolist-tail-- (list 'pre-command-hook))) (while --dolist-tail-- (let ((on (car --dolist-tail--))) (if (functionp on) (advice-add on :before fn) (add-hook on fn)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p))
  (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (progn (set-default 'exec-path doom--initial-exec-path) (set-default 'load-path doom--initial-load-path) (set-default 'process-environment doom--initial-process-environment)) (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) (file-missing (if (locate-file doom-autoloads-file load-path) (signal 'doom-autoload-error e) (signal 'doom-error (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it"))))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file 'noerror)) (require 'core-modules) (autoload 'doom-initialize-packages "core-packages") (autoload 'doom-initialize-core-packages "core-packages") (eval-after-load 'package #'(lambda nil (require 'core-packages))) (eval-after-load 'straight #'(lambda nil (doom-initialize-packages))) (add-hook 'doom-first-input-hook #'gcmh-mode) (add-hook 'after-change-major-mode-hook #'doom-run-local-var-hooks-maybe-h) (add-hook 'emacs-startup-hook #'doom-load-packages-incrementally-h) (add-hook 'hack-local-variables-hook #'doom-run-local-var-hooks-h) (add-hook 'window-setup-hook #'doom-display-benchmark-h) (let ((fn (intern (format "%s-h" 'doom-first-buffer-hook)))) (fset fn #'(lambda (&rest _) (if after-init-time (progn ... ...)))) (put 'doom-first-buffer-hook 'permanent-local t) (let ((--dolist-tail-- (list 'after-find-file 'doom-switch-buffer-hook))) (while --dolist-tail-- (let ((on ...)) (if (functionp on) (advice-add on :before fn) (add-hook on fn)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (let ((fn (intern (format "%s-h" 'doom-first-file-hook)))) (fset fn #'(lambda (&rest _) (if after-init-time (progn ... ...)))) (put 'doom-first-file-hook 'permanent-local t) (let ((--dolist-tail-- (list 'after-find-file 'dired-initial-position-hook))) (while --dolist-tail-- (let ((on ...)) (if (functionp on) (advice-add on :before fn) (add-hook on fn)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (let ((fn (intern (format "%s-h" 'doom-first-input-hook)))) (fset fn #'(lambda (&rest _) (if after-init-time (progn ... ...)))) (put 'doom-first-input-hook 'permanent-local t) (let ((--dolist-tail-- (list 'pre-command-hook))) (while --dolist-tail-- (let ((on ...)) (if (functionp on) (advice-add on :before fn) (add-hook on fn)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p)))
  doom-initialize()
  eval-buffer(#<buffer  *load*> nil "/home/dominic/.config/emacs/init.el" nil t)  ; Reading at buffer position 2620
  load-with-code-conversion("/home/dominic/.config/emacs/init.el" "/home/dominic/.config/emacs/init.el" t t)
  load("/home/dominic/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1e9ec0f3780a4b27>) #f(compiled-function () #<bytecode -0x7609236cc6afed5>) t)
  command-line()
  normal-top-level()
```

**Steps to reproduce:**
run `bin/doom upgrade`
run any other doom command afterward

**System information:**
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.9.10-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 22 Nov 2020 14:22:26 +0000 x86_64
	path       (~/.config/emacs/bin/ ~/.config/emacs/bin/ /usr/local/bin /sbin /usr/sbin ~/.config/emacs/bin/ ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.config/emacs/
	version    28.0.50
	build      Nov 13, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
	traits     (gui envvar-file)
DOOM    dir        ~/.config/doom/
	version    2.0.9
	font       nil
	theme      nil
	build      HEAD -> develop, origin/develop, origin/HEAD e4563e9b0 2020-11-25 15:29:45 -0500
	elc-files  0
	modules    (:completion (company +childframe) (ivy +fuzzy +icons (, +fonts)) :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo hydra indent-guides minimap modeline neotree ophints (popup +defaults) unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs (dired +icons) electric (ibuffer +icons) (undo +tree) vc :term eshell vterm :checkers syntax spell :tools (debugger +lsp) editorconfig (eval +overlay) gist (lookup dictionary) (lsp +peek) (magit +forge) make pdf rgb taskrunner :lang (cc +lsp) emacs-lisp (haskell +lsp) (java +lsp) lua markdown (org +brain +pretty +gnuplot +present) (python +lsp) (sh +lsp) (yaml +lsp) :email (mu4e +gmail) :app calendar :config literate (default +bindings +smartparens))
	packages   ((dmenu) (emms) (emojify) (evil-tutor) (org-bullets) (peep-dired) (rainbow-mode) (sublimity) (tldr) (wc-mode) (evil-quickscope) (ivy-posframe) (virtualenvwrapper) (tree-sitter) (tree-sitter-langs) (cdlatex))
	unpin      (n/a)
	elpa       (n/a)
```

**Comment by hlissner** [comment] 2020-11-26 02:12
Duplicate of #4317

**Closed by hlissner** 2020-11-26 02:12 UTC
Labels: duplicate
