### ISSUE TITLE
These packages cannot be found

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#346] opened 2018-01-11 09:40 UTC
![screen shot 2018-01-11 at 5 39 42 pm](https://user-images.githubusercontent.com/3354145/34818682-8271ab2a-f6f6-11e7-94f8-6aea06f389cd.png)
As shown above, tried it twice but those packages seems not available.

**Comment by hlissner** [comment] 2018-01-12 19:37
This issue is a duplicate of #327, but should have been fixed. Have you a) updated Doom to the latest `develop` and b) re-byte-compiled (if you have at all)?

**Closed** 2018-01-19 02:49 UTC
Labels: uncertain
