### ISSUE TITLE
[BUG] doom upgrade fails with "Error with packages" (wrong-number-of-arguments)

### ISSUE THREAD

**Issue by tchajed** [hlissner/doom-emacs#2215] opened 2019-12-19 23:00 UTC
**What did you expect to happen?**
...
Doom upgrade should succeed

**What actually happened?**
...
Doom upgrade failed with an error.

**Additional details:**
My config is at https://github.com/tchajed/dotfiles/tree/master/emacs/doom.

<details><pre>

Loading /Users/tchajed/doom-emacs.d/core/autoload/buffers.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/cache.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/cli.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/config.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/debug.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/files.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/fonts.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/format.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/help.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/packages.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/plist.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/projects.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/scratch.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/sessions.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/text.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/themes.el (source)...
Loading /Users/tchajed/doom-emacs.d/core/autoload/ui.el (source)...
DOOM Initializing package.el
DOOM Initializing straight
DOOM Initializing doom-packages

In toplevel form:
autoloads.el:2268:50:Warning: reference to free variable ‘rotate-text-words’
autoloads.el:2268:50:Warning: assignment to free variable ‘rotate-text-words’

In end of data:
autoloads.el:4601:1:Warning: the following functions are not known to be
    defined: restart-emacs, +evil/next-end-of-method, +org/toggle-fold,
    +org/close-fold, outline-hide-subtree, magit-version,
    vi-tilde-fringe-mode, +workspace-p, perspective-p,
    +workspace-contains-buffer-p, persp-contain-buffer-p, +workspace-current,
    get-current-persp, lsp-deferred, doom-modeline-set-modeline,
    doom-modeline-def-segment, doom-modeline-def-modeline

Eager macro-expansion failure: (wrong-number-of-arguments (3 . 3) 2)
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 3) 2)
...
  (let ((n 0)) (let ((--dolist-tail-- (hash-table-keys straight--recipe-cache)) package) (while --dolist-tail-- (setq package (car --dolist-tail--)) (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p (file-directory-p ...))) (condition-case e (and (straight-use-package ... nil nil ...) (not existed-p) (file-directory-p ...) (setq n ...)) ((debug error) (signal ... ...))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (= n 0) (ignore (doom--format-print (doom--format (format (doom--format-class (quote success) "No packages need to be installed"))))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Installed & built %d packages") n))) t))
  (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (let ((n 0)) (let ((--dolist-tail-- (hash-table-keys straight--recipe-cache)) package) (while --dolist-tail-- (setq package (car --dolist-tail--)) (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p ...)) (condition-case e (and ... ... ... ...) (... ...)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (= n 0) (ignore (doom--format-print (doom--format (format (doom--format-class ... "No packages need to be installed"))))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Installed & built %d packages") n))) t)))
  doom-cli-packages-install()
  (and (doom-cli-packages-install) (setq success t))
  (progn (and (doom-cli-packages-install) (setq success t)) (and (doom-cli-packages-build) (setq success t)) (and (doom-cli-packages-purge prune-p (quote builds-p) prune-p prune-p) (setq success t)))
  (unwind-protect (progn (and (doom-cli-packages-install) (setq success t)) (and (doom-cli-packages-build) (setq success t)) (and (doom-cli-packages-purge prune-p (quote builds-p) prune-p prune-p) (setq success t))) (doom-cli-reload-package-autoloads (or success (not if-necessary-p))) (doom-cli-byte-compile nil (quote recompile)))
  (let (success) (if (and (not inhibit-envvar-p) (file-exists-p doom-env-file)) (progn (doom-cli-reload-env-file (quote force)))) (mapc (function doom--cli-delete-autoloads-file) (list doom-autoload-file doom-package-autoload-file)) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (doom-cli-reload-core-autoloads (not if-necessary-p)) (unwind-protect (progn (and (doom-cli-packages-install) (setq success t)) (and (doom-cli-packages-build) (setq success t)) (and (doom-cli-packages-purge prune-p (quote builds-p) prune-p prune-p) (setq success t))) (doom-cli-reload-package-autoloads (or success (not if-necessary-p))) (doom-cli-byte-compile nil (quote recompile))) t)
  (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (let (success) (if (and (not inhibit-envvar-p) (file-exists-p doom-env-file)) (progn (doom-cli-reload-env-file (quote force)))) (mapc (function doom--cli-delete-autoloads-file) (list doom-autoload-file doom-package-autoload-file)) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (doom-cli-reload-core-autoloads (not if-necessary-p)) (unwind-protect (progn (and (doom-cli-packages-install) (setq success t)) (and (doom-cli-packages-build) (setq success t)) (and (doom-cli-packages-purge prune-p (quote builds-p) prune-p prune-p) (setq success t))) (doom-cli-reload-package-autoloads (or success (not if-necessary-p))) (doom-cli-byte-compile nil (quote recompile))) t))
  (let ((if-necessary-p (cdr (assq (quote if-necessary-p) --alist--))) (inhibit-envvar-p (cdr (assq (quote inhibit-envvar-p) --alist--))) (prune-p (cdr (assq (quote prune-p) --alist--)))) :bare t (doom--format-print (doom--format (format (doom--format-class (quote start) "Initiating a refresh of Doom Emacs...")))) (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (let (success) (if (and (not inhibit-envvar-p) (file-exists-p doom-env-file)) (progn (doom-cli-reload-env-file (quote force)))) (mapc (function doom--cli-delete-autoloads-file) (list doom-autoload-file doom-package-autoload-file)) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (doom-cli-reload-core-autoloads (not if-necessary-p)) (unwind-protect (progn (and (doom-cli-packages-install) (setq success t)) (and (doom-cli-packages-build) (setq success t)) (and (doom-cli-packages-purge prune-p (quote builds-p) prune-p prune-p) (setq success t))) (doom-cli-reload-package-autoloads (or success (not if-necessary-p))) (doom-cli-byte-compile nil (quote recompile))) t)))
  (closure ((plist :bare t :group "Maintenance") (aliases re sync) (name . refresh) cl-struct-doom-cli-option-tags cl-struct-doom-cli-tags t) (--alist--) (ignore --alist--) (let ((if-necessary-p (cdr (assq (quote if-necessary-p) --alist--))) (inhibit-envvar-p (cdr (assq (quote inhibit-envvar-p) --alist--))) (prune-p (cdr (assq (quote prune-p) --alist--)))) :bare t (doom--format-print (doom--format (format (doom--format-class (quote start) "Initiating a refresh of Doom Emacs...")))) (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (let (success) (if (and (not inhibit-envvar-p) (file-exists-p doom-env-file)) (progn (doom-cli-reload-env-file (quote force)))) (mapc (function doom--cli-delete-autoloads-file) (list doom-autoload-file doom-package-autoload-file)) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (doom-cli-reload-core-autoloads (not if-necessary-p)) (unwind-protect (progn (and (doom-cli-packages-install) (setq success t)) (and (doom-cli-packages-build) (setq success t)) (and (doom-cli-packages-purge prune-p ... prune-p prune-p) (setq success t))) (doom-cli-reload-package-autoloads (or success (not if-necessary-p))) (doom-cli-byte-compile nil (quote recompile))) t))))(nil)
  funcall((closure ((plist :bare t :group "Maintenance") (aliases re sync) (name . refresh) cl-struct-doom-cli-option-tags cl-struct-doom-cli-tags t) (--alist--) (ignore --alist--) (let ((if-necessary-p (cdr (assq (quote if-necessary-p) --alist--))) (inhibit-envvar-p (cdr (assq (quote inhibit-envvar-p) --alist--))) (prune-p (cdr (assq (quote prune-p) --alist--)))) :bare t (doom--format-print (doom--format (format (doom--format-class (quote start) "Initiating a refresh of Doom Emacs...")))) (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (let (success) (if (and (not inhibit-envvar-p) (file-exists-p doom-env-file)) (progn (doom-cli-reload-env-file ...))) (mapc (function doom--cli-delete-autoloads-file) (list doom-autoload-file doom-package-autoload-file)) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (doom-cli-reload-core-autoloads (not if-necessary-p)) (unwind-protect (progn (and ... ...) (and ... ...) (and ... ...)) (doom-cli-reload-package-autoloads (or success ...)) (doom-cli-byte-compile nil (quote recompile))) t)))) nil)
  (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command))
  (let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command)))
  doom-cli-execute("refresh")
  (list (doom-cli-upgrade doom-auto-accept force-p) (doom-cli-execute "refresh") (if (doom-cli-packages-update) (progn (doom-cli-reload-package-autoloads (quote force)) t)))
  (delq nil (list (doom-cli-upgrade doom-auto-accept force-p) (doom-cli-execute "refresh") (if (doom-cli-packages-update) (progn (doom-cli-reload-package-autoloads (quote force)) t))))
  (if (delq nil (list (doom-cli-upgrade doom-auto-accept force-p) (doom-cli-execute "refresh") (if (doom-cli-packages-update) (progn (doom-cli-reload-package-autoloads (quote force)) t)))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Done! Restart Emacs for changes to take effect.")))) (doom--format-print (doom--format (format "Nothing to do. Doom is up-to-date!"))))
  (let ((force-p (cdr (assq (quote force-p) --alist--)))) :bare t (if (delq nil (list (doom-cli-upgrade doom-auto-accept force-p) (doom-cli-execute "refresh") (if (doom-cli-packages-update) (progn (doom-cli-reload-package-autoloads (quote force)) t)))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Done! Restart Emacs for changes to take effect.")))) (doom--format-print (doom--format (format "Nothing to do. Doom is up-to-date!")))))
  (closure ((plist :bare t :group "Maintenance") (aliases up) (name . upgrade) t) (--alist--) (ignore --alist--) (let ((force-p (cdr (assq (quote force-p) --alist--)))) :bare t (if (delq nil (list (doom-cli-upgrade doom-auto-accept force-p) (doom-cli-execute "refresh") (if (doom-cli-packages-update) (progn (doom-cli-reload-package-autoloads ...) t)))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Done! Restart Emacs for changes to take effect.")))) (doom--format-print (doom--format (format "Nothing to do. Doom is up-to-date!"))))))(nil)
  funcall((closure ((plist :bare t :group "Maintenance") (aliases up) (name . upgrade) t) (--alist--) (ignore --alist--) (let ((force-p (cdr (assq (quote force-p) --alist--)))) :bare t (if (delq nil (list (doom-cli-upgrade doom-auto-accept force-p) (doom-cli-execute "refresh") (if (doom-cli-packages-update) (progn ... t)))) (doom--format-print (doom--format (format (doom--format-class ... "Done! Restart Emacs for changes to take effect.")))) (doom--format-print (doom--format (format "Nothing to do. Doom is up-to-date!")))))) nil)
  (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command))
  (let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command)))
  doom-cli-execute("upgrade" nil)
  (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract (current-time) start-time))))
  (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract (current-time) start-time)))))
  (condition-case e (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract (current-time) start-time))))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" (get (car e) (quote error-message)))) (print! (bold "Data:")) (print-group! (if (cdr e) (let ((--dolist-tail-- ...) item) (while --dolist-tail-- (setq item ...) (print! "%S" item) (setq --dolist-tail-- ...))) (print! "n/a")))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join (append (list (file-name-nondirectory load-file-name) "-d" command) args) " ")) (error ""))))
  (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract ... start-time))))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" (get ... ...))) (print! (bold "Data:")) (print-group! (if (cdr e) (let ... ...) (print! "n/a")))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join (append ... args) " ")) (error ""))))))
  (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (setq args (cons command args)) (setq command "help"))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time ...)))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" ...)) (print! (bold "Data:")) (print-group! (if ... ... ...))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join ... " ")) (error "")))))))
  (lambda (--alist--) (ignore --alist--) (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (setq args (cons command args)) (setq command "help"))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time ...)) (and (doom-cli-execute command args) (print! ... ...))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" ... ...) (print! ...) (print-group! ...) (print! ...) (print-group! ...)) (if debug-on-error nil (terpri) (print! ... ...) (error ""))))))))(((command . "upgrade")))
  funcall((lambda (--alist--) (ignore --alist--) (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (setq args (cons command args)) (setq command "help"))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let (...) (and ... ...)) (user-error (print! ... ...) (print! ... ...) (error "")) ((debug error) (print! ...) (print-group! ... ... ... ... ...) (if debug-on-error nil ... ... ...))))))) ((command . "upgrade")))
  (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command))
  (let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command)))
  doom-cli-execute(:main ("upgrade"))
  (let* ((loaddir (file-name-directory (file-truename load-file-name))) (emacsdir (getenv "EMACSDIR")) (user-emacs-directory (or emacsdir (expand-file-name "../" loaddir))) (load-prefer-newer t)) (setq load-path (cons (expand-file-name "core" user-emacs-directory) load-path)) (require (quote core)) (require (quote core-cli)) (defcli! :main ((help-p ["-h" "--help"] "Same as help command") (debug-p ["-d" "--debug"] "Turns on doom-debug-mode (and debug-on-error)") (yes-p ["-y" "--yes"] "Auto-accept all confirmation prompts") (emacsdir ["--emacsdir" dir] "Use the emacs config at DIR (e.g. ~/.emacs.d)") (doomdir ["--doomdir" dir] "Use the private module at DIR (e.g. ~/.doom.d)") (localdir ["--localdir" dir] "Use DIR as your local storage directory") &optional command &rest args) "A command line interface for managing Doom Emacs.\n\nIncludes package management, diagnostics, unit tests, and byte-compilation.\n\nThis tool also makes it trivial to launch Emacs out of a different folder or\nwith a different private module." :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (setq args (cons command args)) (setq command "help"))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time ...)) (and (doom-cli-execute command args) (print! ... ...))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" ... ...) (print! ...) (print-group! ...) (print! ...) (print-group! ...)) (if debug-on-error nil (terpri) (print! ... ...) (error ""))))))) (doom-cli-execute :main (cdr (member "--" argv))) (setq argv nil))
  eval-buffer(#<buffer  *load*> nil "/Users/tchajed/doom-emacs.d/bin/doom" nil t)  ; Reading at buffer position 4627
  load-with-code-conversion("/Users/tchajed/doom-emacs.d/bin/doom" "/Users/tchajed/doom-emacs.d/bin/doom" nil t)
  load("/Users/tchajed/doom-emacs.d/bin/doom" nil t t)
  command-line-1(("-scriptload" "/Users/tchajed/doom-emacs.d/bin/doom" "--" "upgrade"))
  command-line()
  normal-top-level()

</pre></details>

**Steps to reproduce:**
Ran a doom upgrade with the linked config and doom c81b8445c4278 (develop as of now).

**System information:**
<details><pre>
((emacs
  (version . "26.2")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Apr 12, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop c81b8445c 2019-12-19 15:04:05 -0500"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/bash")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "~/code/sw/coq/_build/install/default/bin/" "~/.opam/4.07.1/bin" "~/doom-emacs.d/bin" "~/.gem/bin" "~/.dotfiles/bin" "~/code/sw/latexrun" "~/.cargo/bin" "~/go/bin" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "~/.fzf/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Applications/VMware Fusion.app/Contents/Public" "/usr/local/MacGPG2/bin" "/Library/TeX/texbin" "." "/Applications/Wireshark.app/Contents/MacOS" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hydra hl-todo modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :tools editorconfig eval flycheck lookup lsp magit pdf :lang coq data emacs-lisp go (haskell +intero) latex lua markdown ocaml (org +export +present +protocol) python racket rust (sh +fish) web :config (default +bindings +smartparens))
  (packages default-text-scale math-symbol-lists "(frame-fns :recipe (:host github :repo \"emacsmirror/frame-fns\"))" "(frame-cmds :recipe (:host github :repo \"emacsmirror/frame-cmds\"))" "(zoom-frm :recipe (:host github :repo \"emacsmirror/zoom-frm\"))" keyfreq)
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment] 2019-12-19 23:10
This is a duplicate of #2213.

**Closed by hlissner** 2019-12-19 23:10 UTC
Labels: is:duplicate
