### ISSUE TITLE
Search fails on any string

### ISSUE THREAD

**Issue by ohhskar** [hlissner/doom-emacs#6339] opened 2022-04-27 13:57 UTC
### What did you expect to happen?

Searching highlights the string that I'm searching using 'evil-ex-search-forward'.

### What actually happened?

String is not searched. I get `Search failed: "string"`.

### Describe your attempts to resolve the issue

Tried rebuilding emacs and doom-emacs. Other methods to search works as expected. `evil-ex-search-*` commands all fail.

### Steps to reproduce

Search using 'evil-ex-search-forward'

### System Information

https://pastebin.com/BFDJCCXM

**Comment by ohhskar** [comment] 2022-04-27 14:37
For additional information: `evil-search-*` commands seem to work as expected

**Comment by jpgrayson** [comment] 2022-04-27 19:18
I ran into the same problem. The issue seems to have arisen due to changes to the emacs master branch (i.e. emacs 29 branch).

Okay with 29.0.50 master 935f400a3 (April 21)
Fails with 29.0.50 master abc92b0d5 (April 27)

There are about 100 commits between those versions. I have not tried to bisect further to find the commit that precipitated the problem.

**Comment by hlissner** [comment] 2022-04-27 19:37
I cannot reproduce this issue on Emacs 27.x or 28, and it appears to be a 29 issue (further evidenced by @jpgrayson's findings). I highly recommend downgrading to 28.1 instead. Doom will not support 29 for now, because it is in a highly unstable stage of its development cycle---new breakages are introduced almost every other week.

Since this is not a Doom issue, and a solution exists, I will close it, but feel free to follow up here.

**Closed by hlissner** 2022-04-27 19:37 UTC
Labels: invalid, delete me
