### ISSUE TITLE
non-interactive flag for install command

### ISSUE THREAD

**Issue by enchant97** [hlissner/doom-emacs#5772] opened 2021-11-12 16:51 UTC
### Describe your request

I'd like a non-interactive install option under the `doom install` command.

### Briefly explain its use-case

Run `doom install --no-prompt` to install without the need for human interaction. Existing flags such as `--no-fonts` would be taken into account.

**Comment by hlissner** [comment] 2021-11-21 15:32
Duplicate of https://github.com/hlissner/doom-emacs/issues/4603

**Closed by hlissner** 2021-11-21 15:32 UTC
Labels: needs-triage, 1. request
