### ISSUE TITLE
[BUG] auto-closing braces/parens in latex and many modes

### ISSUE THREAD

**Issue by yoavm448** [hlissner/doom-emacs#2308] opened 2020-01-04 22:38 UTC
**edit**: this applies to _many more modes_, not just latex. The info about `latex-mode` is probably redundant, so Ive added that in italics and a strike through on all of the latex info.

In latex, _and many more modes,_ typing a left brace (`([{`) auto-inserts a right one, but when deleting the left one it doesn't auto-remove the right one.
That is, typing `(` then `BACKSPACE` leaves you with a hanging `)`. 
press `(` => `(|)`; then `BACKSPACE` => `|)`

**What did you expect to happen?**
The closing brace should be auto-removed also.

**What actually happened?**
The closing brace is left hanging.

**Additional details:**
Ive tried this with an empty `.doom.d/config.el` and got the same behavior.
Thought this might be an issue with `smart-parens`, ~but upon examination the keys `([{` on insert mode are bonud to `LaTeX-insert-left-brace`~.
~I tried `map!`ing them back to the normal `self-insert-command` and got exactly the same behavior. (I did verify with `SPC h k` that the remapping worked.)~

~In case this matters:
`TeX-electric-(escape|math)` are `nil`,
`TeX-electric-sub-and-superscript` is `t`,
`LaTeX-electric-left-right-brace` is `nil`,
`latex-electric-env-pair-mode` is `nil`.~

**Steps to reproduce:**
(~enable the latex module in `.init.el` and edit a .tex file~ - _appearently this applies to many more modes, Ive been using only latex lately_)
Type `(` and then `BACKSPACE`, and a `)` gets left behind.

**System information:**
<details><pre>
$ ~/.emacs.d/bin/doom info
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
((emacs
  (version . "26.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2")
  (build . "Apr 11, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-cQxEw2/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 13be4fa17 2020-01-04 04:57:58 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64")
  (path "”/tools/bin" "~/.cargo/bin" "~/.scripts" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/jvm/java-13-oracle/bin" "/usr/lib/jvm/java-13-oracle/db/bin" "~/.emacs.d/bin”" "/usr/lib/emacs/26.1/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +auto +childframe) (ivy +icons +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs (dired +icons) electric vc :term term :tools eval flycheck flyspell (lookup +docsets) magit pass :lang data emacs-lisp latex (org +dragndrop +attach +babel +capture +export +present +protocol) python sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by jadestrong** [comment] 2020-01-05 06:03
In other mode, like web-mode、js2-mode、rust-mode etc, delete single quote、double quote and braces also has this bug.

**Comment by yoavm448** [comment] 2020-01-05 08:44
Yes, you are right. Only been using latex lately. is this a known bug?
Ive updated the issue on the 'other modes' part.

**Comment by hlissner** [comment] 2020-01-06 20:51
I've been wondering about this myself. It surfaced recently due to emacs-evil/evil@1d6ba80, which broke backspace wherever it was bound to `evil-delete-backward-and-join` in a variety of modes (and impacted smartparens, in particular).

As of 7150631 this should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by yoavm448** [comment] 2020-01-06 21:37
I've just ran `doom upgrade` and nothing changed - auto-closing parens still remain behind, at least on python and latex modes on which I checked. Am I missing something?

**Comment by jadestrong** [comment] 2020-01-07 02:00
me too.

**Comment by hlissner** [comment] 2020-01-07 03:04
I can no longer reproduce this in latex mode. Back to the drawing board, I guess!

**Comment by jadestrong** [comment] 2020-01-07 03:35
`C-h k` show me that backspace still be binded `evil-delete-backward-char-and-join`.
![81C7AC43-34F7-4FE0-A9D6-21C03D0531E2](https://user-images.githubusercontent.com/18475217/71866605-b525a580-3141-11ea-85c4-ad4d141381cd.png)

**Comment by bixuanzju** [comment] 2020-01-07 09:46
> `C-h k` show me that backspace still be bound to `evil-delete-backward-char-and-join`.
> ![81C7AC43-34F7-4FE0-A9D6-21C03D0531E2](https://user-images.githubusercontent.com/18475217/71866605-b525a580-3141-11ea-85c4-ad4d141381cd.png)

Same here after updating to the latest version.

**Closed** 2020-01-11 22:30 UTC
Labels: :editor evil, is:update

**Comment by hlissner** [comment] 2020-01-11 22:51
Looks like I was advising the wrong command. This should be fixed in 52b69ec. Let me know if that isn't the case.

> C-h k show me that backspace still be bound to evil-delete-backward-char-and-join.

The cause is `evil-delete-backward-char-and-join` uses `delete-region` to delete text (which doesn't trigger the change hooks smartparens listens for). It used to use `backward-delete-char-untabify`, which _did_ trigger those hooks.

The fix was **not** to remap `evil-delete-backward-char-and-join`, but to  advise it to use `backward-delete-char-untabify` again.
