### ISSUE TITLE
(system-name) reports in uppercase when config.el is first read but lowercase when evaluated later

### ISSUE THREAD

**Issue by rgkirch** [hlissner/doom-emacs#5522] opened 2021-09-26 21:28 UTC
### What did you expect to happen?

I expected `(system-name)` to report the same on emacs launch as with `C-x C-e` 

### What actually happened?

`(system-name)` reports in all caps on emacs launch and all lower when evaluated with `C-x C-e` or `M-;`

### Describe your attempts to resolve the issue

My config is fixed now since I can just check for `(equal "MYPC" (upcase (system-name)))` but this seems worth fixing since it added a lot of friction and is surprising behavior.

### Steps to reproduce

my windows specific configuration in `config.el` wasn't running when I thought it should. I have it behind a check e.g.
`(when (equal "mypc" (system-name))
    (setq org-directory "c:/Users/user/Documents/org/"))`

it was confusing to see that `(system-name)` reported "mypc" when I ran it with `C-x C-e`
I added a `(print (system-name))` in my config.el, restarted emacs, and it printed "MYPC"

`runemacs.exe -q` and then `(system-name)` reports in all uppercase "MYPC"

### System Information

https://pastebin.com/Umdw9GC5

**Comment by hlissner** [comment] 2021-09-26 22:15
Your `doom/info` tells me you have generated an envvar file. `doom install` will have prompted you to generate this file. Running `doom env` will forcibly regenerate it. 

It dumps your shell environment into a file that Doom will load at startup, which I presume includes an environment variable which influences what Emacs displays when `(system-name)` is called. On Linux/MacOS I presume it'd be `HOST` or `HOSTNAME`, but I have no idea about Windows.

You will have to either correct this variable in your environment or blacklist it when regenerating it: `doom env --reject "HOST"`

In any case, this is not a bug on Doom's end. It is correctly reading your (albiet misconfigured) environment, so I will close this. Feel free to follow up here if you have reason to suspect otherwise.

**Closed by hlissner** 2021-09-26 22:15 UTC
Labels: invalid

**Comment by rgkirch** [comment] 2021-09-26 23:01
Ok, thanks.

Yea, I'm happy now that I know that I need to upcase system-name. I wanted to bring it up in case it's a bug and definitely leave a solution for anyone facing the same issue.
I checked the `.emacs.d/.local/env` file and I found four variables with my system name. I changed all of them to something else but emacs still reported the original name after restarting emacs. I don't know what that means and I don't care enough to find out.
If anything is a bug it would be that `(system-name)` reports in lowercase instead of all caps. I agree it's not an issue with doom though since `system-name` is a function in `editfns.c`

Thanks for looking into it and thanks for your work on doom. It's been a dream.
