### ISSUE TITLE
[REQUEST] anyway to install package without straight?

### ISSUE THREAD

**Issue by PoiScript** [hlissner/doom-emacs#1736] opened 2019-08-30 14:27 UTC
Currently I'm working on a machine with limited access to the internet. I used to modify the `package-archives` variable and update packages via a mirror. 

However, straight seems to download packages from GitHub directly. And it will takes a long time from my machine even after using a proxy server. For example, downloading three packages spent up to seven minutes to finish: 

![image](https://user-images.githubusercontent.com/17513314/64028074-8f293c80-cb74-11e9-9a07-ab608044b907.png)

So, is there anyway to continue using the legacy way for installing and updating packages?

**Comment by hlissner** [comment] 2019-09-02 05:07
Sorry to say, package.el as a backend for package management has been done away with (almost) entirely. You can still install individual packages with its API (through `M-x package-install` or `use-package`'s `:ensure` keyword), but there is no way to tell Doom to "install all its packages through package.el" anymore.

I'll see if I can find a way around it, but I'm not sure how to best address this issue.

**Comment by PoiScript** [comment] 2019-09-03 15:28
Actually, the best solution is to tell straight to download source directly instead of cloning them.

I don't think it's a good idea to keep a local git repo for each package. Every time I update my package, there're immediately tons of git command running in the background and my computer quickly get 100% cpu and  freeze out for a few seconds.

I'm now still reading about the document and I will probably create a new issue on that.

**Comment by bersace** [comment] 2021-04-16 10:09
Hi,

`bin/doom update` and `--threads` are gone as I write this comment. I also hit timeouts with straights and github:

``` console
$ bin/doom sync -pu
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
  > Updating packages (this may take a while)...
    > (241/271) Fetching cfrs...
**HANG HERE**
    x The package manager threw an error
      fatal: impossible d'accéder à 'https://github.com/Alexander-Miller/cfrs.git/' : Failed to connect to github.com port 443: Connexion terminée par expiration du délai d'attente
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
$
```

How to workaround this ?

**Comment by bersace** [comment] 2021-04-16 10:10
Disabling `-u` make `bin/doom sync` succeed.

**Comment by hlissner** [comment] 2021-04-16 19:16
Since:

1. I cannot reproduce these errors,
2. I have no intention of bringing back package.el,
3. Doom is shallow-cloning packages by default (already minimizes how much must be downloaded)

There is nothing I can do here for the original issue, so I will close it.

> fatal: impossible d'accéder à 'https://github.com/Alexander-Miller/cfrs.git/' : Failed to connect to github.com port 443: Connexion terminée par expiration du délai d'attente

@bersace Your issue is unrelated, but there are two probable causes for your issue:

1. It is simply a timeout issue. No choice but to wait and try again later, or clone it yourself:
   ```sh
   cd ~/.emacs.d/.local/straight/repos
   rm -rf cfrs
   git clone https://github.com/Alexander-Miller/cfrs cfrs
   doom sync
   ```
2. Are you on macos? If so, you may need to [update your credentials on your keychain](https://docs.github.com/en/github/getting-started-with-github/updating-credentials-from-the-macos-keychain).

> Disabling -u makes bin/doom sync succeed.

Of course, `-u` = update packages. Without it, packages aren't updated. i.e. No outgoing connections.

**Closed by hlissner** 2021-04-16 19:16 UTC
Labels: is:question, re:packages, status:nofix
