### ISSUE TITLE
Moving .doom.d to .config/doom breaks doom

### ISSUE THREAD

**Issue by ncihnegn** [hlissner/doom-emacs#5382] opened 2021-08-14 07:58 UTC
### What did you expect to happen?

When I move .doom.d to .config/doom, I expect everything works.

### What actually happened?

Emacs doesn't open Doom buffer on startup. It opens scratch instead and vi mapping is not working.

### Describe your attempts to resolve the issue

I moved .config/doom back to .doom.d. Then it works.

### Steps to reproduce

1. ```mv ~/.doom.d ~/.config/doom; doom sync```
2. Open emacs. There should be no Doom buffer.
3. ```mv ~/.config/doom ~/.doom.d; doom sync```
4. Open emacs. Emacs should open with Doom buffer.

### System Information

https://pastebin.com/a2BXLVhb

**Comment by iyefrat** [comment] 2021-08-14 08:00
have you run `doom sync` after moving it?

**Comment by ncihnegn** [comment] 2021-08-14 08:36
Yes.

**Comment by hlissner** [comment] 2021-08-14 16:48
I can't reproduce this. Check for errors/warnings in \*Messages\* (`C-h e` to open it) at startup.

**Comment by ncihnegn** [comment] 2021-08-14 20:52
The only thing in *Messages* is
```Doom loaded 381 packages across 73 modules in 1.341s [2 times]```

**Comment by shaunsingh** [comment] 2021-08-16 00:30
In my case (macos, emacs-plus) I had to `rm -r ~/.emacs.d` and rerun the doom install script

**Comment by hlissner** [comment] 2021-09-26 09:53
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [ ] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing dependencies, or a corrupt Emacs installation).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Closed by hlissner** 2021-09-26 09:53 UTC
Labels: 1. bug, needs-triage
