### ISSUE TITLE
c++ lookup references result window doesn't show

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#815] opened 2018-08-19 08:51 UTC
as said in title, the result show in `*Rtags*` buffer which stay background. is this related to pop up window manager?  plus I already run `+cc/reload-compile-db`.

**Comment by hlissner** [comment] 2018-08-19 16:49
Could this be related to #768?

Could you try running `(delete-file (locate-library "rtags.elc"))`, then restart Emacs and see if the issue is resolved?

**Comment by chengyi** [comment] 2018-08-20 00:54
@hlissner it seems strange, after I restart emacs(I don't do anything else), it works again. but then i delete rtags library in `/usr/local/share/emacs/site-lisp`.

**Comment by benj02** [comment] 2018-08-28 21:41
I was the reporter of #768. The issue resurfaced for me as well (this seems to be the exact same issue). Last time doing `(delete-file (locate-library "rtags.elc"))` did not resolve the issue, but this time it did.

I'm on Arch Linux with Emacs 26.1, and the `rtags-git` AUR package installed, which installs the file `/usr/share/emacs/site-lisp/rtags/rtags.elc` which seems to be the culprit. There must be some kind of conflict between the elpa version and the AUR version, although I'm not sure what it is.

```diff
--- /usr/share/emacs/site-lisp/rtags/rtags.el   2018-08-07 20:09:41.000000000 -0700
+++ /home/benj/.emacs.d/.local/packages/elpa/rtags-20180814.1713/rtags.el       2018-08-27 20:59:19.708648059 -0700
@@ -5,6 +5,7 @@
 ;; Author: Jan Erik Hanssen <jhanssen@gmail.com>
 ;;         Anders Bakken <agbakken@gmail.com>
 ;; URL: http://rtags.net
+;; Package-Version: 20180814.1713
 ;; Version: 2.10

 ;; This file is not part of GNU Emacs.
@@ -1480,7 +1481,8 @@
            (completing-read prompt collection predicate require-match default-value hist)))

         ((eq rtags-completing-read-behavior 'default-when-empty)
-         (setq prompt (replace-regexp-in-string "^\\(.*\\): " (concat "\\1 (default: " default-value "): ") prompt))
+         (when (> (length default-value) 0)
+           (setq prompt (replace-regexp-in-string "^\\(.*\\): " (concat "\\1 (default: " default-value "): ") prompt)))
          (let ((ret (if (fboundp 'completing-read-default)
                         (completing-read-default prompt collection predicate nil nil hist)
                       (completing-read prompt collection predicate nil nil hist))))
```

Haven't tried it, but I'd guess this would go away if you didn't install the packaged elisp from `rtags-git`. Looks like you could get that by adding the parameter `-DRTAGS_NO_ELISP_FILES=1` to the cmake line in the PKGBUILD. I'll try this and report back.

**Comment by hlissner** [comment] 2019-02-28 22:50
Sorry for the late followup. This should be resolved by now so I'll consider this issue resolved. Let me know if that isn't the case and I will reopen it.

**Closed by hlissner** 2019-02-28 22:50 UTC
Labels: external
