### ISSUE TITLE
Magit broken with recent pull on develop branch

### ISSUE THREAD

**Issue by prabhu-madanagopal** [hlissner/doom-emacs#978] opened 2018-10-23 06:47 UTC
rm -rf ~/.emacs.d    
git clone https://github.com/hlissner/doom-emacs.git ~/.emacs.d    
cd ~/.emacs.d 
git checkout develop 
bin/doom refresh

Eager macro-expansion failure: (error ":condition-case must be a list of error handlers; see the documentation: ((ghub-422 (signal (quote ghubp-error-review-is-active) nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal (quote ghubp-error-review-is-active) nil)) (signal (car it) (cdr it))))))")
Eager macro-expansion failure: (error ":condition-case must be a list of error handlers; see the documentation: ((ghub-422 (signal (quote ghubp-error-review-is-active) nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal (quote ghubp-error-review-is-active) nil)) (signal (car it) (cdr it))))))")

**Comment by prabhu-madanagopal** [comment] 2018-10-23 06:50
[init.el.zip](https://github.com/hlissner/doom-emacs/files/2504830/init.el.zip)

Attached ~/.doom.d/init.el

**Comment by prabhu-madanagopal** [comment] 2018-10-23 06:52
`Debugger entered--Lisp error: (error ":condition-case must be a list of error handlers; see the documentation: ((ghub-422 (signal (quote ghubp-error-review-is-active) nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal (quote ghubp-error-review-is-active) nil)) (signal (car it) (cdr it))))))")
  signal(error (":condition-case must be a list of error handlers; see the documentation: ((ghub-422 (signal (quote ghubp-error-review-is-active) nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal (quote ghubp-error-review-is-active) nil)) (signal (car it) (cdr it))))))"))
  error(":condition-case must be a list of error handlers; see the documentation: %S" ((ghub-422 (signal 'ghubp-error-review-is-active nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal 'ghubp-error-review-is-active nil)) (signal (car it) (cdr it)))))))
  apiwrap-gendefun("GitHub" "ghubp" ((repo . "REPO is a repository alist of the form returned by `ghubp-get-user-repos'.") (branch . "BRANCH is a branch object of the form returned by `ghubp-get-repos-owner-repo-branches-branch'.") (org . "ORG is an organization alist of the form returned by `ghubp-get-user-orgs'.") (thread . "THREAD is a thread object of the form returned by `ghubp-get-repos-owner-repo-comments'.") (issue . "ISSUE is an issue object of the form returned by `ghubp-get-issues'.") (pull-request . "PULL-REQUEST is a pull request object of the form returned by `ghubp-get-repos-owner-repo-pulls'.") (review . "REVIEW is a review object of the form returned by `ghubp-get-repos-owner-repo-pulls-number-reviews'.") (label . "LABEL is a label object of the form returned by `ghubp-get-repos-owner-repo-issues-number-labels'.") (ref . "REF is a string and can be a SHA, a branch name, or a tag name.") (milestone . "MILESTONE is a milestone object.") (user . "USER is a user object.") (user-1 . "USER-1 is a user object.") (user-2 . "USER-2 is a user object.") (key . "KEY is a key object.")) delete "/repos/:owner/:repo/pulls/:number/reviews/:id" "Delete a pending review." "pulls/reviews/#delete-a-pending-review" (repo pull-request review) "/repos/:repo.owner.login/:repo.name/pulls/:pull-request.number/reviews/:review.id" ((pre-process-params . ghubp--pre-process-params) (link . ghubp--make-link) (request . ghubp-request)) (:condition-case (ghubp-catch* (422 (signal 'ghubp-error-review-is-active nil)))))
  (lambda (resource doc link &optional objects internal-resource &rest config) "Define a new DELETE resource wrapper function.\n\nRESOURCE is the API endpoint as written in the GitHub API\ndocumentation.  Along with the backend prefix (from\n`apiwrap-new-backend') and the method (DELETE), this string will be\nused to create the symbol for the new function.\n\nDOC is a specific documentation string for the new function.\nUsually, this can be copied from the GitHub API documentation.\n\nLINK is a link to the GitHub API documentation.\n\nIf non-nil, OBJECTS is a list of symbols that will be used to\nresolve parameters in the resource and will be required arguments\nof the new function.  Documentation for these parameters (from\nthe standard parameters of the call to `apiwrap-new-backend')\nwill be inserted into the docstring of the generated function.\n\nIf non-nil, INTERNAL-RESOURCE is the resource-string used to\nresolve OBJECT to the ultimate call instead of RESOURCE.  This is\nuseful in the likely event that the advertised resource syntax\ndoes not align with the structure of the object it works with.\nFor example, GitHub's endpoint\n\n    GET /repos/:owner/:repo/issues\n\nwould be written as\n\n    (defapiget-<prefix> \"/repos/:owner/:repo/issues\"\n      \"List issues for a repository.\"\n      \"issues/#list-issues-for-a-repository\"\n      (repo) \"/repos/:repo.owner.login/:repo.name/issues\")\n\ndefining a function called `<prefix>-get-repos-owner-repo-issues'\nand taking an object (a parameter called `repo') with the\nstructure\n\n    ((owner (login . \"octocat\"))\n     (name . \"hello-world\")\n\nSee the documentation of `apiwrap-resolve-api-params' for more\ndetails on that behavior.\n\nCONFIG is a list of override configuration parameters.  Values\nset here (notably those explicitly set to nil) will take\nprecedence over the defaults provided to `apiwrap-new-backend'." (apiwrap-gendefun "GitHub" "ghubp" '((repo . "REPO is a repository alist of the form returned by `ghubp-get-user-repos'.") (branch . "BRANCH is a branch object of the form returned by `ghubp-get-repos-owner-repo-branches-branch'.") (org . "ORG is an organization alist of the form returned by `ghubp-get-user-orgs'.") (thread . "THREAD is a thread object of the form returned by `ghubp-get-repos-owner-repo-comments'.") (issue . "ISSUE is an issue object of the form returned by `ghubp-get-issues'.") (pull-request . "PULL-REQUEST is a pull request object of the form returned by `ghubp-get-repos-owner-repo-pulls'.") (review . "REVIEW is a review object of the form returned by `ghubp-get-repos-owner-repo-pulls-number-reviews'.") (label . "LABEL is a label object of the form returned by `ghubp-get-repos-owner-repo-issues-number-labels'.") (ref . "REF is a string and can be a SHA, a branch name, or a tag name.") (milestone . "MILESTONE is a milestone object.") (user . "USER is a user object.") (user-1 . "USER-1 is a user object.") (user-2 . "USER-2 is a user object.") (key . "KEY is a key object.")) 'delete resource doc link objects internal-resource '((pre-process-params . ghubp--pre-process-params) (link . ghubp--make-link) (request . ghubp-request)) config))("/repos/:owner/:repo/pulls/:number/reviews/:id" "Delete a pending review." "pulls/reviews/#delete-a-pending-review" (repo pull-request review) "/repos/:repo.owner.login/:repo.name/pulls/:pull-request.number/reviews/:review.id" :condition-case (ghubp-catch* (422 (signal 'ghubp-error-review-is-active nil))))
  (defapidelete-ghubp "/repos/:owner/:repo/pulls/:number/reviews/:id" "Delete a pending review." "pulls/reviews/#delete-a-pending-review" (repo pull-request review) "/repos/:repo.owner.login/:repo.name/pulls/:pull-request.number/reviews/:review.id" :condition-case (ghubp-catch* (422 (signal 'ghubp-error-review-is-active nil))))
  eval-buffer(#<buffer  *load*-872865> nil "/Users/i078828/.emacs.d/.local/packages/elpa/ghub+-20181023.27/ghub+.el" nil t)  ; Reading at buffer position 24972
  load-with-code-conversion("/Users/i078828/.emacs.d/.local/packages/elpa/ghub+-20181023.27/ghub+.el" "/Users/i078828/.emacs.d/.local/packages/elpa/ghub+-20181023.27/ghub+.el" nil t)
  require(ghub+)
  eval-buffer(#<buffer  *load*> nil "/Users/i078828/.emacs.d/.local/packages/elpa/magithub-20181016.345/magithub.el" nil t)  ; Reading at buffer position 1821
  load-with-code-conversion("/Users/i078828/.emacs.d/.local/packages/elpa/magithub-20181016.345/magithub.el" "/Users/i078828/.emacs.d/.local/packages/elpa/magithub-20181016.345/magithub.el" nil t)
  require(magithub nil nil)
  (progn (use-package-statistics-gather :init 'magithub nil) (setq magithub-clone-default-directory "~/" magithub-preferred-remote-method 'clone_url) (require 'magithub nil nil) (use-package-statistics-gather :config 'magithub nil) (if +magit-hub-enable-by-default nil (advice-add (function magithub-enabled-p) :override (function +magit*hub-enabled-p)) (advice-add (function magithub-settings--format-magithub\.enabled) :override (function +magit*hub-settings--format-magithub\.enabled))) (if +magit-hub-features (progn (magithub-feature-autoinject +magit-hub-features))) t (use-package-statistics-gather :config 'magithub t) (use-package-statistics-gather :init 'magithub t))
  (closure (t) nil (progn (use-package-statistics-gather :init 'magithub nil) (setq magithub-clone-default-directory "~/" magithub-preferred-remote-method 'clone_url) (require 'magithub nil nil) (use-package-statistics-gather :config 'magithub nil) (if +magit-hub-enable-by-default nil (advice-add (function magithub-enabled-p) :override (function +magit*hub-enabled-p)) (advice-add (function magithub-settings--format-magithub\.enabled) :override (function +magit*hub-settings--format-magithub\.enabled))) (if +magit-hub-features (progn (magithub-feature-autoinject +magit-hub-features))) t (use-package-statistics-gather :config 'magithub t) (use-package-statistics-gather :init 'magithub t)))()
  eval-after-load-helper("/Users/i078828/.emacs.d/.local/packages/elpa/magit-20181022.1720/magit.elc")
  run-hook-with-args(eval-after-load-helper "/Users/i078828/.emacs.d/.local/packages/elpa/magit-20181022.1720/magit.elc")
  do-after-load-evaluation("/Users/i078828/.emacs.d/.local/packages/elpa/magit-20181022.1720/magit.elc")
  require(magit nil t)
  (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req))
  (progn (if doom-debug-mode (progn (message "Incrementally loading %s" req))) (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req)) (if reqs (progn (run-with-idle-timer doom-incremental-idle-timer nil (function doom-load-packages-incrementally) reqs t))))
  (if req (progn (if doom-debug-mode (progn (message "Incrementally loading %s" req))) (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req)) (if reqs (progn (run-with-idle-timer doom-incremental-idle-timer nil (function doom-load-packages-incrementally) reqs t)))))
  (let* ((reqs (cl-delete-if (function featurep) packages)) (req (condition-case nil (progn (car-safe (prog1 reqs (setq reqs (cdr reqs))))) (error nil)))) (if req (progn (if doom-debug-mode (progn (message "Incrementally loading %s" req))) (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req)) (if reqs (progn (run-with-idle-timer doom-incremental-idle-timer nil (function doom-load-packages-incrementally) reqs t))))))
  (let ((gc-cons-threshold doom-gc-cons-upper-limit) file-name-handler-alist) (let* ((reqs (cl-delete-if (function featurep) packages)) (req (condition-case nil (progn (car-safe (prog1 reqs (setq reqs (cdr reqs))))) (error nil)))) (if req (progn (if doom-debug-mode (progn (message "Incrementally loading %s" req))) (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req)) (if reqs (progn (run-with-idle-timer doom-incremental-idle-timer nil (function doom-load-packages-incrementally) reqs t)))))))
  (progn (let ((gc-cons-threshold doom-gc-cons-upper-limit) file-name-handler-alist) (let* ((reqs (cl-delete-if (function featurep) packages)) (req (condition-case nil (progn (car-safe (prog1 reqs (setq reqs (cdr reqs))))) (error nil)))) (if req (progn (if doom-debug-mode (progn (message "Incrementally loading %s" req))) (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req)) (if reqs (progn (run-with-idle-timer doom-incremental-idle-timer nil (function doom-load-packages-incrementally) reqs t))))))))
  (if packages (progn (let ((gc-cons-threshold doom-gc-cons-upper-limit) file-name-handler-alist) (let* ((reqs (cl-delete-if (function featurep) packages)) (req (condition-case nil (progn (car-safe (prog1 reqs (setq reqs (cdr reqs))))) (error nil)))) (if req (progn (if doom-debug-mode (progn (message "Incrementally loading %s" req))) (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req)) (if reqs (progn (run-with-idle-timer doom-incremental-idle-timer nil (function doom-load-packages-incrementally) reqs t)))))))))
  (if (not now) (nconc doom-incremental-packages packages) (if packages (progn (let ((gc-cons-threshold doom-gc-cons-upper-limit) file-name-handler-alist) (let* ((reqs (cl-delete-if (function featurep) packages)) (req (condition-case nil (progn (car-safe (prog1 reqs (setq reqs (cdr reqs))))) (error nil)))) (if req (progn (if doom-debug-mode (progn (message "Incrementally loading %s" req))) (if (require req nil t) nil (message "Failed to load '%s' package incrementally" req)) (if reqs (progn (run-with-idle-timer doom-incremental-idle-timer nil (function doom-load-packages-incrementally) reqs t))))))))))
  doom-load-packages-incrementally((magit calendar org-macs org-compat org-faces org-entities org-list org-pcomplete org-src org-footnote org-macro ob org org-agenda org-capture org-clock) t)
  apply(doom-load-packages-incrementally ((magit calendar org-macs org-compat org-faces org-entities org-list org-pcomplete org-src org-footnote org-macro ob org org-agenda org-capture org-clock) t))
  timer-event-handler([t 0 1 500000 nil doom-load-packages-incrementally ((magit calendar org-macs org-compat org-faces org-entities org-list org-pcomplete org-src org-footnote org-macro ob org org-agenda org-capture org-clock) t) idle 0])
`

**Comment by hlissner** [comment] 2018-10-23 08:19
This is caused by a recent, breaking update to the [ghub+](https://github.com/vermiculus/ghub-plus) package, caused by this commit: https://github.com/vermiculus/ghub-plus/commit/b3a90d107bc502259b17ea4f01b0bee148a57428.

Their tests are failing on that commit with the same error, so I'd assume they're aware of it, but you should file a bug report there.

I'll keep this issue open until it's resolved upstream.

**Comment by wedens** [comment] 2018-10-24 03:54
It's fixed in ghub+ now: https://github.com/vermiculus/ghub-plus/issues/13

**Comment by hlissner** [comment] 2018-10-24 04:34
Excellent, and it appears MELPA has pulled the changes, so I'll consider this resolved. 

@prabhu-madanagopal Please update your packages with `bin/doom update` (or `make update`, they both do the same thing).

**Closed by hlissner** 2018-10-24 04:34 UTC
Labels: external

**Comment by prabhu-madanagopal** [comment] 2018-10-24 04:37
Thanks @hlissner . It worked.
