### ISSUE TITLE
Symbol’s function definition is void: ad-Advice-newline-and-indent

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#3816] opened 2020-08-23 23:23 UTC
I git pull commit `e3750db` and enter `org-mode`. When I press ENTER to add a new line, it prompts me:

```
apply: Symbol’s function definition is void: ad-Advice-newline-and-indent
```
Could this be a bug?

**System information:**
<details><pre>

```
emacs   version    27.1
        features   RSVG DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP
        build      Aug 12, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-gnutls --with-modules --with-rsvg)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop e3750dbf6 2020-08-23 18:48:50 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
        path       (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin /usr/local/go/bin /usr/local/MacGPG2/bin /opt/X11/bin /usr/local/opt/gnupg@1.4/libexec/gpgbin ~/bin ~/.pyenv/shims /usr/local/opt/libxml2/bin ~/.cargo/bin /usr/local/bin/gs /Applications/Wireshark.app/Contents/MacOS ~/.rvm/bin /usr/local/anaconda3/bin /usr/local/Cellar/go/1.13/bin /usr/local/opt/tcl-tk/bin /Library/TeX/texbin /usr/local/opt/tcl-tk/bin ~/.emacs.d/bin /usr/local/opt/openssl/bin /usr/local/opt/gnupg@1.4/libexec/gpgbin ~/bin /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims ~/.pyenv/shims /usr/local/opt/libxml2/bin ~/.cargo/bin /usr/local/bin /usr/local/bin/gs /usr/local/go/bin /usr/local/MacGPG2/bin /opt/X11/bin ~/.rvm/bin /usr/local/anaconda3/bin /usr/local/Cellar/go/1.14.3/bin ~/.fzf/bin ~/.nvm/versions/node/v13.8.0/bin/ /Library/TeX/texbin /usr/local/opt/tcl-tk/bin ~/.emacs.d/bin /usr/local/opt/openssl/bin /usr/local/opt/gnupg@1.4/libexec/gpgbin ~/bin /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims ~/.pyenv/shims /usr/local/opt/libxml2/bin ~/.cargo/bin /usr/local/bin /usr/local/bin/gs /usr/local/go/bin /usr/local/MacGPG2/bin /opt/X11/bin ~/.rvm/bin /usr/local/anaconda3/bin /usr/local/Cellar/go/1.14.3/bin ~/.fzf/bin ~/.nvm/versions/node/v13.8.0/bin/ /Library/TeX/texbin /usr/local/opt/tcl-tk/bin ~/.emacs.d/bin /usr/local/opt/openssl/bin /usr/local/opt/gnupg@1.4/libexec/gpgbin ~/bin /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims ~/.pyenv/shims /usr/local/opt/libxml2/bin ~/.cargo/bin /usr/local/bin /usr/local/bin/gs /usr/local/go/bin /usr/local/MacGPG2/bin /opt/X11/bin ~/.rvm/bin /usr/local/anaconda3/bin /usr/local/Cellar/go/1.14.3/bin ~/.fzf/bin ~/.nvm/versions/node/v13.8.0/bin/ /usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0/libexec/emacs/27.1/x86_64-apple-darwin18.7.0)
config  envfile    nil
        elc-files  0
        modules    (:input japanese :completion company (helm +fuzzy) (ivy +fuzzy) :ui workspaces deft doom doom-dashboard modeline doom-quit hl-todo nav-flash neotree treemacs (popup +all +defaults) unicode vc-gutter vi-tilde-fringe (window-select +switch-window +numbers) zen :editor (evil +everywhere) file-templates snippets fold lispy (format +onsave) multiple-cursors rotate-text word-wrap :emacs (dired +icons) electric vc (ibuffer +icons) (undo +tree) :checkers syntax spell grammar :tools (eval +overlay) lsp (lookup +dictionary +docsets) ansible debugger editorconfig make (magit +forge) pass pdf rgb terraform tmux upload :os macos tty :lang common-lisp data emacs-lisp ess hy scheme (javascript +lsp) julia (latex +latexmk +cdlatex +fold) ledger lua (markdown +grip +pandoc) (org +present +habit +babel +pomodoro +journal +attach +capture +export +dragndrop +hugo +gnuplot +ipython +pandoc +noter +brain +roam +pretty) raku plantuml ruby (sh +zsh) :email (wanderlust +gmail) :term eshell vterm :app calendar irc (rss +org) twitter :private myorg misc mylang :config (default +bindings +snippets +evil-commands))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment] 2020-08-23 23:53
Duplicate of #3172.

**Closed by hlissner** 2020-08-23 23:53 UTC
Labels: is:duplicate
