### ISSUE TITLE
Org capture failing to incrementally load in gccemacs on a fresh Doom install

### ISSUE THREAD

**Issue by arozbiz** [hlissner/doom-emacs#4595] opened 2021-01-30 18:22 UTC
**What did you expect to happen?**

**What actually happened?**
On running a clean Doom install, I get this error on startup (and when trying to run an Org capture):

```
DOOM Incrementally loading org-capture
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)
```

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

Here is an image of the backtrace (it disappears whenever I try to select it, so I can't copy and paste it. Apologies.)

![image](https://user-images.githubusercontent.com/4499657/106364535-6111d400-62f5-11eb-806a-6e683bb27473.png)

</pre></details>

**Steps to reproduce:**
Install gccemacs
Install Doom
Run emacs

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /mnt/c/Python39/Scripts/ /mnt/c/Python39/ /mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/ProgramData/chocolatey/bin /mnt/c/Program Files/dotnet/ /mnt/c/Program Files/Git/cmd /mnt/c/Users/$USER/AppData/Local/Microsoft/WindowsApps /mnt/c/Users/$USER/AppData/Local/Pandoc/ /snap/bin /usr/local/libexec/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Jan 30, 2021
        buildopts  --with-nativecomp --with-json 'CFLAGS=-O3 -mtune=native -march=native -fomit-frame-pointer'
        features   CAIRO FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBSELINUX MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK2 ZLIB
        traits     (gui server-running)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -PfEd-DejaVu Sans Mono-normal-normal-normal-*-22-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 5acd41de 2021-01-29 18:48:24 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by arozbiz** [comment] 2021-01-30 18:45
On further searching, I think this is the same error as here? https://github.com/hlissner/doom-emacs/issues/4534

**Comment by MithicSpirit** [comment] 2021-01-30 20:25
Yes, I believe that it is the same thing. AFAIK this is an upstream issue and there is nothing that can be done until the packages are fixed :/

**Comment by hlissner** [comment] 2021-01-30 23:26
Duplicate of #4534

**Closed by hlissner** 2021-01-30 23:26 UTC
Labels: duplicate
