### ISSUE TITLE
Symbol’s function definition is void: org-babel-execute:dot

### ISSUE THREAD

**Issue by andrej1919** [hlissner/doom-emacs#6238] opened 2022-04-03 11:56 UTC
### What did you expect to happen?

I wanted to run simple process diagrams using dot and tables from this [example](https://orgmode.org/worg/org-tutorials/org-dot-diagrams.html). (Case 1)

Since that failed I tried [this example](https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-dot.html), which was another failure (Case 2)

### What actually happened?

**Case 1, Messages buffer:** 
```
executing Emacs-Lisp code block (graph-from-tables)...

(nodes '(("S_start" "start" "ellipse" "green") ("S_fill" "fill form" "" "") ("S_send" "send form" "" "") ("S_complete" "form complete?" "diamond" "yellow") ("S_do" "do task" "" "red") ("S_end" "end" "ellipse" "")))

(graph '(("S_start" "S_fill" "") ("S_fill" "S_send" "") ("S_send" "S_complete" "") ("S_complete" "S_fill" "N") ("S_complete" "S_do" "Y") ("S_do" "S_end" "")))

let: Symbol’s function definition is void: org-babel-execute:dot
```

**Case 2, Messages buffer:**
```
executing Emacs-Lisp code block (make-dot)...

(table '(("S_start" "start" "ellipse" "green") ("S_fill" "fill form" "" "") ("S_send" "send form" "" "") ("S_complete" "form complete?" "diamond" "yellow") ("S_do" "do task" "" "red") ("S_end" "end" "ellipse" "")))

format: Symbol’s function definition is void: first 
```

### Describe your attempts to resolve the issue

1. I tried this:

`(org-babel-do-load-languages
  'org-babel-load-languages
  '((dot . t)))`
It did not work and I also found [this explanation](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#lazy-load-more-than-everything).
2. I tried to copy Graphviz configuration from tecosaur and Diego Zamboni, no success
3. I followed all steps described [here](https://github.com/hlissner/doom-emacs/blob/master/docs/getting_started.org#troubleshoot). All codeblocks evaluated in \*doom:sandbox\* return the same error: `let: Invalid read syntax: "#"` 

### Steps to reproduce

1. Copy tables and code from Case 1 and Case 2 to .org file
2. Evaluate code blocks with `C-c C-c` 

### System Information

https://pastebin.com/5wLYHbJ6

**Comment by andrej1919** [comment] 2022-04-03 12:13
I just tested alternative, [Mermaid](https://emacstil.com/til/2021/09/19/org-mermaid/), which works fine:

![CleanShot 2022-04-03 at 14 10 25](https://user-images.githubusercontent.com/31947650/161427444-8d9b6103-7d68-46bb-8754-e713e73e829c.png)

But I would still prefer Graphviz.

**Comment by hlissner** [comment] 2022-04-03 12:47
> `format: Symbol’s function definition is void: first `

This occurs because the code in Case 2 uses the `first` and `second` functions, both of which are part of the obsolete `cl.el` library, and should be replaced with `cl-first` and `cl-second` (or better, `car` and `cadr`). Correct the snippet to correct this issue.

> let: Symbol’s function definition is void: org-babel-execute:dot

This occurs because you haven't loaded the `ob-dot` library before using this. A simple solution would be to either:

- Add `(require 'ob-dot)` to the top of the src block.
- Or add `(autoload 'org-babel-execute:dot "ob-dot")` to `~/.doom.d/config.el` so Emacs always knows where to find the function, when it is called.

If you're going to use Elisp to generate graphviz dot diagrams, you need to load what you need before you use them.

-----

As this isn't a bug with Doom, I will close it, but feel free to follow up here.

**Closed by hlissner** 2022-04-03 12:47 UTC
Labels: invalid

**Comment by andrej1919** [comment] 2022-04-03 13:12
Thank you and sorry for my begginer's ignorance. Case 2 works. Case 1: neither solution produced result.
Output: 
executing Dot code block...
Wrote /var/folders/9h/_hp4jw052gg1llnxzcy35czw0000gn/T/babel-uRye2j/ob-input-0YF9eb
Babel evaluation exited with code 127
Code block evaluation complete.

**Comment by hlissner** [comment] 2022-04-03 14:15
Hmm, there's no elisp error, so this is likely an issue with the external `dot` program. Try giving it the absolute path to the `dot` program with `:cmd /absolute/path/to/dot`. E.g.

```org
#+name: graph-from-tables
#+HEADER: :var nodes=example-node-table graph=example-graph
#+BEGIN_SRC emacs-lisp :cmd /path/to/dot :file ~/example-diagram.png :colnames yes :exports results
...
#+END_SRC

```

If this works, then the problem is that your `PATH` is out of date in your config. You can regenerate your envvar file by running `doom env` and restarting Emacs.

I also see you have `exec-path-from-shell` installed, which can cause conflicts with Doom's envvar file. I'd recommend removing it, as it is redundant (and slower) than Doom's envvar file.

**Comment by andrej1919** [comment] 2022-04-05 11:01
You were right. It was an issue with external `dot`program. Thanks!
