### ISSUE TITLE
open c file with lsp could lead to emacs freeze

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#4093] opened 2020-10-14 11:47 UTC
**What did you expect to happen?**
open a c/c++ project with ccls doesn't lead to emacs freeze

**What actually happened?**
when opening a c/c++ project with ccls enabled, the emacs freeze

**Steps to reproduce:**
1. open a c/c++ project

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.67-1-MANJARO #1 SMP PREEMPT Wed Sep 23 14:20:18 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/android-ndk /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      8月 29, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> upstream, zero/develop, origin/upstream a776664eb 2020-10-14 01:40:11 -0400
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold format snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang (cc +lsp) data emacs-lisp lua markdown org (python +lsp) (rust +lsp) (sh +zsh) (web +html +css) :email mu4e :config (default +bindings +smartparens) :private (&user prow-edit) (&user prow-c-c++) (&user prow-misc) (&user gtags))
        packages   ((cnfonts) (jinja2-mode) (mu4e-maildirs-extension :disable t) (org-mu4e :disable t) (glsl-mode :disable t) (opencl-mode :disable t) (disaster :disable t) (cuda-mode :disable t) (demangle-mode :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by chengyi** [comment] 2020-10-14 11:50
reset head to db07304c7 fixed this issue.

**Comment by hlissner** [comment] 2020-10-14 18:00
I cannot reproduce this on vanilla Doom.

**Comment by chengyi** [comment] 2020-10-15 03:59
@hlissner 22b6eaed0 may lead this issue

**Comment by hlissner** [comment] 2020-10-15 06:21
Ah, found the issue! As of 1c7fd9c this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by chengyi** [comment] 2020-10-15 07:44
@hlissner seems this issue isn't fixed by 1c7fd9c, still be freezed when open project.

**Comment by hlissner** [comment] 2020-10-15 08:33
Try `(setq lsp-enable-file-watchers nil)`

**Comment by chengyi** [comment] 2020-10-15 08:46
yeah, add 
``` emacs-lisp
(setq! lsp-enable-file-watchers nil)
```
fix this issue.

**Comment by hlissner** [comment] 2020-10-15 20:08
In that case it's [a known limitation of lsp-mode](https://github.com/emacs-lsp/lsp-mode/blob/bd0664027e03b6d03b47ed028ebfdcdbb4523a76/docs/page/limitations.md). It is expected that you turn this off for projects that are large. As this setting is necessary for some clients, I cannot change its default. Since this isn't an issue with Doom I will close the issue.

**Closed by hlissner** 2020-10-15 20:08 UTC
Labels: :lang cc, :tools lsp, invalid, is:external, re:performance, re:stability
