### ISSUE TITLE
doom returns No catch for tag: exit, 255

### ISSUE THREAD

**Issue by DoubleClick7** [hlissner/doom-emacs#4317] opened 2020-11-25 04:05 UTC
**What did you expect to happen?**
I expected `doom`, `doom sync`, `doom doctor` to work.

**What actually happened?**
All of these commands returned `No catch for tag: exit, 255`

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.9.11-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 24 Nov 2020 15:10:03 +0000 x86_64
        path       (~/.local/bin /usr/local/bin ~/bin ~/.emacs.d/bin ~/.local/bin /usr/local/bin ~/bin ~/.emacs.d/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /var/lib/snapd/snap/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Nov 25, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      HEAD -> develop 42d5da83c 2020-10-31 15:16:58 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo indent-guides ligatures minimap (modeline +light) neotree ophints (popup +defaults) vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric ibuffer undo :term eshell shell term vterm :checkers syntax :tools (eval +overlay) lookup magit make rgb lsp :os tty :lang (cc +lsp) (emacs-lisp +lsp) (javascript +lsp) markdown org php (python +lsp) sh (web +lsp) :email (mu4e +gmail) :config (default +bindings +smartparens))
        packages   ((ewal-doom-themes) (with-editor) (ewal) (fira-code-mode) (prettier) (sublimity) (spacemacs-theme) (webpaste) (zone-nyan) (nyan-mode) (evil-commentary) (evil-tutor) (sublime-themes) (cyberpunk-theme) (ample-theme) (ample-zen-theme) (afternoon-theme))
        unpin      (n/a)
        elpa       (with-editor async)
```
</pre></details>

**Comment by hlissner** [comment] 2020-11-25 05:43
Likely a duplicate of #4303 and caused by breaking changes in the native-comp branch. A fix was pushed for this in https://github.com/hlissner/doom-emacs/commit/e4890f6ac952272ba3136cd2d8b4321dd9dc9188. Please update and check if it resolves your issues. You may need to delete `~/.emacs.d/.local/straight` and run `doom sync`, depending on how much damage this breakage did to your local install.

**Comment by askurihin** [comment] 2020-11-25 09:51
I had the same issue, after removing `.local/straight` and running `doom sync`
I have a different issue:

```Wrong type argument: number-or-marker-p, many```

**Comment by DoubleClick7** [comment] 2020-11-25 12:21
After removing `.emacs.d/local/straight`, `doom sync && doom build` return `Symbol’s value as variable is void: comp-deferred-compilation-black-list`.

**Comment by bnjmnt4n** [comment] 2020-11-25 13:05
@DoubleClick7 see #4309. Updating doom or gccemacs should do the trick.

**Comment by folke** [comment] 2020-11-25 14:08
After I recompiled gccemacs and removed `.emacs.d/.local/straight`, I get the following error with every doom command:
`Wrong type argument: number-or-marker-p, many`

**Comment by DoubleClick7** [comment] 2020-11-25 15:54
Ok I deleted .emacs.d and reinstalled doom. But, after `doom install` had been running for sometime, it asked me `Vterm needs `vterm-module' to work.  Compile it now? (y or n)` and entering y or n has no effect, it just keeps asking me

**Comment by hlissner** [comment] 2020-11-25 17:25
So far, three different errors have been reported in here and I can't reproduce any of them on the latest commit of gccemacs. Please make sure:

+ Doom is up-to-date (includes https://github.com/hlissner/doom-emacs/commit/e4890f6ac952272ba3136cd2d8b4321dd9dc9188)
+ You're on a commit of gccemacs after https://github.com/emacs-mirror/emacs/commit/7a8370ed0f1b1d62657e385789ee2f81c5607ec5?

   There's a possibility that the latest commit of gccemacs is unavailable through whatever channel you're installing it from. In which case, revert to the last commit that worked or wait for it to be updated.

**Comment by valrus** [comment] 2020-11-25 18:04
I'm on the latest Doom and gccemacs 718370e. Here's the stack trace for the `Wrong type argument: number-or-marker-p, many` error:

```
❯ bin/doom doctor
DOOM Initializing straight
DOOM Initializing recipes
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p many)
  <(many 4)
  (if (< (cdr (func-arity #'native-compile-async)) 4) (progn (progn (defalias 'doom--native-compile-async-a #'(lambda (orig-fn paths &optional recursively load _selector) (if (fboundp ...) (native--compile-async paths recursively load) (funcall orig-fn paths recursively load)
))) (let ((--dolist-tail-- (list (cons :around ...)))) (while --dolist-tail-- (let ((targets ...)) (let (...) (while --dolist-tail-- ...)) (setq --dolist-tail-- (cdr --dolist-tail--))))))))
  (progn (if (boundp 'comp-deferred-compilation-deny-list) nil (defvaralias 'comp-deferred-compilation-deny-list 'comp-deferred-compilation-black-list)) (if (< (cdr (func-arity #'native-compile-async)) 4) (progn (progn (defalias 'doom--native-compile-async-a #'(lambda (orig-fn paths &optional recursively load _selector) (if ... ... ...))) (let ((--dolist-tail-- (list ...))) (while --dolist-tail-- (let (...) (le
t ... ...) (setq --dolist-tail-- ...))))))) (let ((--dolist-tail-- (list (concat "\\`" (regexp-quote doom-local-dir) ".*/evil-collection-vterm\\.el\\'") (concat "\\`" (regexp-quote doom-local-dir) ".*/jupyter-channel\\.el\\'") (concat "\\`" (regexp-quote doom-local-dir) ".*/with-editor\\.el\\'") (concat "\\`" (regexp-quote doom-autoloads-file) "'")))) (while --dolist-tail-- (let ((entry (car --dolist-tail--))) (if (member entry comp-deferred-compilation-deny-list) comp-deferred-compilation-deny-list (setq comp-deferred-compilation-deny-list (cons entry comp-deferred-compilation-deny-list))) (setq --dolist-tail-- (cdr --dolist-tail--))))))                                              (closure (t) nil (progn (if (boundp 'comp-deferred-compilation-deny-list) nil (defvaralias 'comp-deferred-compilation-deny-list 'comp-deferred-compilation-black-list)) (if (< (cdr (func-arity #'native-compile-async)) 4) (progn (progn (defalias 'doom--native-compile-async-a #'(lambda ... ...)) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))))) (let ((--dolist-tail-- (list (concat "\\`" (regexp-quote doom-local-dir) ".*/evil-collection-vterm\\.el\\'") (concat "\\`" (regexp-quote doom-local-dir) ".*/jupyter-channel\\.el\\'") (concat "\\`" (regexp-quote doom-local-dir) ".*/with-editor\\.el\\'") (concat "\\`" (regexp-quote doom-autoloads-file) "'")))) (while --dolist-tail-- (let ((entry (car --dolist-tail--))) (if (member entry comp-deferred-compilation-deny-list) comp-deferred-compilation-deny-list (setq comp-deferred-compilation-deny-list (cons entry comp-deferred-compilation-deny-list))) (setq --dolist-tail-- (cdr --dolist-tail--)))))))()
  eval-after-load-helper("/Applications/Emacs.app/Contents/Resources/lisp/em...")                                                           do-after-load-evaluation("/Applications/Emacs.app/Contents/Resources/lisp/em...")
  require(comp)                                                                                                                             (progn (require 'comp) (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- ':package))))) (if (straight--native-com
pile-package-p recipe) (let ((inhibit-message t) (message-log-max nil)) (native-compile-async (straight--build-dir package) 'recursively nil #'straight--native-compile-file-p)) (let* ((x (format "^%s" (straight--build-dir package)))) (if (member x comp-deferred-compilation-deny-list) comp-deferred-compilation-deny-list (setq comp-deferred-compilation-deny-list (cons x comp-deferred-compilation-deny-list)))))))
  (if (fboundp 'native-compile-async) (progn (require 'comp) (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- ...))))) (if (straight--native-compile-package-p recipe) (let ((inhibit-message t) (message-log-max nil)) (native-compile-async (straight--build-dir package) 'recursively nil #'straight--native-compile-file-p)) (let* ((x (format "^%s" ...))) (if (member x comp-deferred-compilation-deny-list) comp-deferred-compilation-deny-list (setq comp-deferred-compilation-deny-list (cons x comp-deferred-compilation-deny-list))))
))))                                                                                                                                        straight--native-compile-package((:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "develop" :package "straight" :local-repo "straight.el"))                                                                                                     (progn (straight--run-build-commands recipe) (straight--symlink-package recipe) (straight--compute-dependencies package) (setq straight-
-echo-area-dirty nil) (let* ((dependencies (and t (straight--get-dependencies package)))) (if dependencies (progn (let ((--dolist-tail-- d
ependencies)) (while --dolist-tail-- (let (...) (straight-use-package ... nil nil task) (setq --dolist-tail-- ...)))) (if straight--echo-a
rea-dirty (progn (straight--progress-begin task)))) nil)) (straight--generate-package-autoloads recipe) (straight--byte-compile-package re
cipe) (straight--native-compile-package recipe) (straight--compile-package-texinfo recipe) (straight--run-build-commands recipe 'post) (ru
n-hook-with-args 'straight-use-package-post-build-functions package))
  (prog1 (progn (straight--run-build-commands recipe) (straight--symlink-package recipe) (straight--compute-dependencies package) (setq st
raight--echo-area-dirty nil) (let* ((dependencies (and t (straight--get-dependencies package)))) (if dependencies (progn (let ((--dolist-t
ail-- dependencies)) (while --dolist-tail-- (let ... ... ...))) (if straight--echo-area-dirty (progn (straight--progress-begin task)))) ni
l)) (straight--generate-package-autoloads recipe) (straight--byte-compile-package recipe) (straight--native-compile-package recipe) (strai
ght--compile-package-texinfo recipe) (straight--run-build-commands recipe 'post) (run-hook-with-args 'straight-use-package-post-build-func
tions package)) (if gensym--task-cdr (progn (straight--output "%s...done" gensym--task-cdr))))
  (progn (if gensym--task-car (progn (straight--output "%s..." gensym--task-car))) (prog1 (progn (straight--run-build-commands recipe) (st
raight--symlink-package recipe) (straight--compute-dependencies package) (setq straight--echo-area-dirty nil) (let* ((dependencies (and t
(straight--get-dependencies package)))) (if dependencies (progn (let (...) (while --dolist-tail-- ...)) (if straight--echo-area-dirty (pro
gn ...))) nil)) (straight--generate-package-autoloads recipe) (straight--byte-compile-package recipe) (straight--native-compile-package re
cipe) (straight--compile-package-texinfo recipe) (straight--run-build-commands recipe 'post) (run-hook-with-args 'straight-use-package-pos
t-build-functions package)) (if gensym--task-cdr (progn (straight--output "%s...done" gensym--task-cdr)))))
  (let* ((gensym--task task) (gensym--task-car (if (listp gensym--task) (car gensym--task) gensym--task)) (gensym--task-cdr (if (listp gen
sym--task) (cdr gensym--task) gensym--task))) (progn (if gensym--task-car (progn (straight--output "%s..." gensym--task-car))) (prog1 (pro
gn (straight--run-build-commands recipe) (straight--symlink-package recipe) (straight--compute-dependencies package) (setq straight--echo-
area-dirty nil) (let* ((dependencies (and t ...))) (if dependencies (progn (let ... ...) (if straight--echo-area-dirty ...)) nil)) (straig
ht--generate-package-autoloads recipe) (straight--byte-compile-package recipe) (straight--native-compile-package recipe) (straight--compil
e-package-texinfo recipe) (straight--run-build-commands recipe 'post) (run-hook-with-args 'straight-use-package-post-build-functions packa
ge)) (if gensym--task-cdr (progn (straight--output "%s...done" gensym--task-cdr))))))
  (let ((task (concat cause (if cause (progn straight-arrow)) (format "Building %s" package)))) (let* ((gensym--task task) (gensym--task-c
ar (if (listp gensym--task) (car gensym--task) gensym--task)) (gensym--task-cdr (if (listp gensym--task) (cdr gensym--task) gensym--task))
) (progn (if gensym--task-car (progn (straight--output "%s..." gensym--task-car))) (prog1 (progn (straight--run-build-commands recipe) (st
raight--symlink-package recipe) (straight--compute-dependencies package) (setq straight--echo-area-dirty nil) (let* ((dependencies ...)) (
if dependencies (progn ... ...) nil)) (straight--generate-package-autoloads recipe) (straight--byte-compile-package recipe) (straight--nat
ive-compile-package recipe) (straight--compile-package-texinfo recipe) (straight--run-build-commands recipe 'post) (run-hook-with-args 'st
raight-use-package-post-build-functions package)) (if gensym--task-cdr (progn (straight--output "%s...done" gensym--task-cdr)))))) (setq s
traight--echo-area-dirty t))
  (progn (if straight-safe-mode (progn (error "Building %s not allowed in safe mode" package))) (let ((task (concat cause (if cause (progn
 straight-arrow)) (format "Building %s" package)))) (let* ((gensym--task task) (gensym--task-car (if (listp gensym--task) (car gensym--tas
k) gensym--task)) (gensym--task-cdr (if (listp gensym--task) (cdr gensym--task) gensym--task))) (progn (if gensym--task-car (progn (straig
ht--output "%s..." gensym--task-car))) (prog1 (progn (straight--run-build-commands recipe) (straight--symlink-package recipe) (straight--c
ompute-dependencies package) (setq straight--echo-area-dirty nil) (let* (...) (if dependencies ... nil)) (straight--generate-package-autol
oads recipe) (straight--byte-compile-package recipe) (straight--native-compile-package recipe) (straight--compile-package-texinfo recipe)
(straight--run-build-commands recipe 'post) (run-hook-with-args 'straight-use-package-post-build-functions package)) (if gensym--task-cdr
(progn (straight--output "%s...done" gensym--task-cdr)))))) (setq straight--echo-area-dirty t)))
  (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- ':package))))) (progn (if straight-safe-mode (progn (error "Bui
lding %s not allowed in safe mode" package))) (let ((task (concat cause (if cause (progn straight-arrow)) (format "Building %s" package)))
) (let* ((gensym--task task) (gensym--task-car (if (listp gensym--task) (car gensym--task) gensym--task)) (gensym--task-cdr (if (listp gen
sym--task) (cdr gensym--task) gensym--task))) (progn (if gensym--task-car (progn (straight--output "%s..." gensym--task-car))) (prog1 (pro
gn (straight--run-build-commands recipe) (straight--symlink-package recipe) (straight--compute-dependencies package) (setq straight--echo-
area-dirty nil) (let* ... ...) (straight--generate-package-autoloads recipe) (straight--byte-compile-package recipe) (straight--native-com
pile-package recipe) (straight--compile-package-texinfo recipe) (straight--run-build-commands recipe ...) (run-hook-with-args ... package)
) (if gensym--task-cdr (progn ...))))) (setq straight--echo-area-dirty t))))
  straight--build-package((:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "develop" :package "straigh
t" :local-repo "straight.el") nil)
  (progn (run-hook-with-args 'straight-use-package-pre-build-functions package) (straight--build-package recipe cause))
...
  eval-region(3381 6100)  ; Reading at buffer position 3381
  (progn (insert-file-contents (doom-path repo-dir "bootstrap.el")) (eval-region (search-forward "(require 'straight)") (point-max)))
  (unwind-protect (progn (insert-file-contents (doom-path repo-dir "bootstrap.el")) (eval-region (search-forward "(require 'straight)") (p
oint-max))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents (doom-path repo-dir "bootstrap.el")) (eval-re
gion (search-forward "(require 'straight)") (point-max))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-c
ontents (doom-path repo-dir "bootstrap.el")) (eval-region (search-forward "(require 'straight)") (point-max))) (and (buffer-name temp-buff
er) (kill-buffer temp-buffer)))))
  (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")) (repo-url (concat "http" (if gnutls-verify-error "s") "://gi
thub.com/" (or (plist-get recipe :repo) "raxod502/straight.el"))) (branch (or (plist-get recipe :branch) straight-repository-branch)) (cal
l (if doom-debug-p #'doom-exec-process #'doom-call-process))) (if (file-directory-p repo-dir) nil (message "Installing straight...") (cond
 ((eq straight-vc-git-default-clone-depth 'full) (funcall call "git" "clone" "--origin" "origin" repo-url repo-dir)) ((null pin) (funcall
call "git" "clone" "--origin" "origin" repo-url repo-dir "--depth" (number-to-string straight-vc-git-default-clone-depth) "--branch" strai
ght-repository-branch "--single-branch" "--no-tags")) ((integerp straight-vc-git-default-clone-depth) (make-directory repo-dir t) (let ((d
efault-directory repo-dir)) (funcall call "git" "init") (funcall call "git" "checkout" "-b" straight-repository-branch) (funcall call "git
" "remote" "add" "origin" repo-url) (funcall call "git" "fetch" "origin" pin "--depth" (number-to-string straight-vc-git-default-clone-dep
th) "--no-tags") (funcall call "git" "checkout" "--detach" pin))))) (require 'straight (concat repo-dir "/straight.el")) (if doom-debug-p
(progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing recipes" 0 5 (face font-lock-comment-face)))))) (
let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-cont
ents (doom-path repo-dir "bootstrap.el")) (eval-region (search-forward "(require 'straight)") (point-max))) (and (buffer-name temp-buffer)
 (kill-buffer temp-buffer))))))
  doom--ensure-straight((:host github :repo "raxod502/straight.el" :branch "develop" :local-repo "straight.el" :files ("straight*.el")) "3
277e1c9648b41dd5bfb239c067b8374ed2ec2bb")
  (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (plist-member --cl-rest-- ':recipe)))) (pin (car (cdr (plist-membe
r --cl-rest-- ':pin))))) (doom--ensure-straight recipe pin))
  (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (plist-member --cl
-rest-- ':recipe)))) (pin (car (cdr (plist-member --cl-rest-- ':pin))))) (doom--ensure-straight recipe pin)) (doom--ensure-core-packages p
ackages))
  (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing straight" 0 5 (face fon
t-lock-comment-face)))))) (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car
 (cdr (plist-member --cl-rest-- ...)))) (pin (car (cdr (plist-member --cl-rest-- ...))))) (doom--ensure-straight recipe pin)) (doom--ensur
e-core-packages packages)))
  (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight-recipe-repositories))) (progn (if doom-debug-p (progn (let ((
inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing straight" 0 5 (face font-lock-comment-face)))))) (let ((package
s (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr ...))) (pin (car (cdr ...)))) (doo
m--ensure-straight recipe pin)) (doom--ensure-core-packages packages))))
  doom-initialize-core-packages()
  eval-buffer(#<buffer  *load*-377851> nil "/Users/ianmccowan/.emacs.d/core/core-cli.el" nil t)  ; Reading at buffer position 516
  load-with-code-conversion("/Users/ianmccowan/.emacs.d/core/core-cli.el" "/Users/ianmccowan/.emacs.d/core/core-cli.el" nil t)
  require(core-cli)
  eval-buffer(#<buffer  *load*> nil "/Users/ianmccowan/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 3327
  load-with-code-conversion("/Users/ianmccowan/.emacs.d/bin/doom" "/Users/ianmccowan/.emacs.d/bin/doom" nil t)
  command-line-1(("-scriptload" "bin/doom" "--" "doctor"))
  command-line()
  normal-top-level()
```

**Comment by folke** [comment] 2020-11-25 18:43
I'm also on the gccemacs 7a8370e.

Clean install of doom gives me the same error as @valrus

**Closed** 2020-11-25 19:43 UTC
Labels: re:native-comp, status:backlog, status:unknown

**Comment by hlissner** [comment] 2020-11-25 19:45
Ah, turns out this was a regression _in_ e4890f6. As of 90f16ea this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by DoubleClick7** [comment] 2020-11-26 04:02
Hey! What do I do about this:
```
Vterm needs `vterm-module' to work.  Compile it now? (y or n) y
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
Vterm needs `vterm-module' to work.  Compile it now? (y or n) y
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
  → Building magit → Building git-commit...done
  → Building magit...
Vterm needs `vterm-module' to work.  Compile it now? (y or n) y
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
Vterm needs `vterm-module' to work.  Compile it now? (y or n) y
Vterm needs `vterm-module' to work.  Compile it now? (y or n) y
Vterm needs `vterm-module' to work.  Compile it now? (y or n) n
Vterm needs `vterm-module' to work.  Compile it now? (y or n)
```

**Comment by folke** [comment] 2020-11-26 08:44
@DoubleClick7 I was able to type `y` and it worked in my case.

I just checked the docs and you should be able to set `vterm-always-compile-module` to `t` to skip the question and compile it automatically when needed:
https://github.com/akermu/emacs-libvterm#vterm-always-compile-module

**Comment by DoubleClick7** [comment] 2020-11-26 15:05
> @DoubleClick7 I was able to type `y` and it worked in my case.
> 
> Since that doesn't seem to work for you, I checked the docs and you should be able to set `vterm-always-compile-module` to `t` to skip the question and compile it automatically when needed:
> https://github.com/akermu/emacs-libvterm#vterm-always-compile-module

I am a noob. Do I do that in config.el? Is the syntax `(setq vterm-always-compile 't)`?

**Comment by hlissner** [comment] 2020-11-26 17:38
@DoubleClick7 @folke Sounds like you haven't updated Doom or straight. Do it manually if you have to:

```sh
cd ~/.emacs.d
git pull
doom sync -u
```
