### ISSUE TITLE
[BUG] reference to void function project-file-exists-p!

### ISSUE THREAD

**Issue by iocanel** [hlissner/doom-emacs#1673] opened 2019-08-14 08:22 UTC
**Describe the issue**

Using `java +lsp` when I open a java source file I get an error about `project-file-exists-p!` being a void function.

I expected the java lsp server to be launched instead.

This affects straight branch (not sure about develop branch cause I am having issues with gnu mirrors).

<details><pre>
Debugger entered--Lisp error: (void-function project-file-exists-p!)
  (project-file-exists-p! (or "AndroidManifest.xml" "src/main/AndroidManifest.xml"))
  (if (project-file-exists-p! (or "AndroidManifest.xml" "src/main/AndroidManifest.xml")) (progn (android-mode 1)))
  +java-android-mode-maybe-h()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook java-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook java-mode-hook))
  run-mode-hooks(java-mode-hook)
  java-mode()
</pre></details>

**Steps to reproduce**
1. Install doom from straight branch
2. Enable java +lsp
3. Open any java source file

**System information**
<details><pre>
((emacs
  (version . "26.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Jul 04, 2018")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-mailutils --with-x-toolkit=gtk3 --with-xft --with-xwidgets --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> straight, origin/straight 0c7e6261 2019-08-11 02:05:09 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64")
  (path "~/google-cloud-sdk/bin" "~/.sdkman/candidates/sbt/current/bin" "~/.sdkman/candidates/micronaut/current/bin" "~/.sdkman/candidates/kotlin/current/bin" "~/.sdkman/candidates/java/current/bin" "~/.zplug/bin" "/usr/lib/jvm/default/bin" "~/tools/maven/bin" "~/tools/cxf/bin" "~/tools/vertx/bin" "~/workspace/bin" "~/scripts/arch" "~/scripts" "~/scripts/dev" "~/scripts/install" "~/scripts/k8s" "~/scripts/notify" "~/scripts/sound" "~/scripts/util" "~/scripts/wm" "~/scripts/work" "~/scripts/wrap" "/bin" "/usr/bin" "/usr/local/bin" "/var/lib/snapd/snap/bin" "~/bin" "~/.virtualenvs/bin" "/usr/lib/emacs/26.1/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) lsp magit :lang data emacs-lisp (java +lsp) markdown (org +dragndrop +ipython +pandoc +present) sh :config default)
  (packages "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2019-08-15 19:07
This was resolved in 7d714b7 (see #1674 for more explanation). If that isn't the case, let me know and I will reopen this issue. Thanks for bringing it to my attention.

**Closed by hlissner** 2019-08-15 19:07 UTC
Labels: is:bug, module:core, status:resolved

**Comment by Preve92** [comment] 2019-12-02 11:27
Experiencing the same issue on emacs doom develop branch commit 90c0dd6 "Merge pull request #2133 fom bwignall/typo" when trying _doom install_.

**Comment by hlissner** [comment] 2019-12-02 23:18
@Preve92 I cannot reproduce this. Is this a vanilla Doom config? Can you include the output of `~/.emacs.d/bin/doom info`?
