### ISSUE TITLE
Wrong type argument: listp, #[0 "ÀÁ!" [+org/insert-item below] 

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1474] opened 2019-06-07 01:38 UTC
When I press SPC h k C-RET, report the message:

`Wrong type argument: listp, #[0 "ÀÁ!" [+org/insert-item below] `

Because C-RET, M-RET, etc., the buttons do not work in org mode INSERT mode.

MacOS/doom develop

**Comment by flyingns** [comment] 2019-06-07 07:08
When I set the `:config default` in init.el, I can't use the binding keys of M-RET, C-RET, C-S-RET, etc.

**Comment by hlissner** [comment] 2019-06-07 12:31
This appears to be an issue with [elisp-demos](https://github.com/xuchunyang/elisp-demos). Try disabling it:

```elisp
;; in ~/.doom.d/packages.el
(package! elisp-demos :disable t)
```

After `doom refresh` and restarting Emacs, let me know if that resolves your issue.

**Comment by flyingns** [comment] 2019-06-07 17:29
It seems that this is not the reason, `(package! elisp-demos :disable t)` no problem is solved.

**Comment by hlissner** [comment] 2019-06-10 06:36
I'm almost convinced elisp-demos was the issue. xuchunyang/elisp-demos#2 was merged. Try updating and see if the issue goes away. 

Otherwise, I am unable to reproduce the problem. Please include your `M-x doom/info`.

**Comment by hlissner** [comment] 2019-06-12 17:28
Did the update work?

**Comment by flyingns** [comment] 2019-06-21 14:13
![Screen Shot 2019-06-21 at 22 11 28 ](https://user-images.githubusercontent.com/16456728/59928638-c216cc00-9471-11e9-8897-bf82c6b66149.png)

**Comment by CodyWilson** [comment] 2019-06-21 14:19
<img width="680" alt="Screen Shot 2019-06-21 at 9 17 00 AM" src="https://user-images.githubusercontent.com/6146911/59928920-5b5bc900-9405-11e9-8652-30db68e90594.png">

I was able to recreate the issue. On OSX.

With debug enabled I get the following:
```
Debugger entered--Lisp error: (wrong-type-argument symbolp (args))
  symbol-name((args))
  helpful--format-argument((args))
  mapcar(helpful--format-argument ((args) t))
  -map(helpful--format-argument ((args) t))
  helpful--signature((closure ((args) t) nil (interactive) (+org/insert-item (quote below))))
  #f(compiled-function () (interactive nil) #<bytecode 0x43549429>)()
  apply(#f(compiled-function () (interactive nil) #<bytecode 0x43549429>) nil)
  helpful-update()
  helpful-key([C-return])
  funcall-interactively(helpful-key [C-return])
  call-interactively(helpful-key nil nil)
  command-execute(helpful-key)
```

Doom info:
```
- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 26.2 (May 22, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop 44a5ffad 2019-06-18 17:30:26 +0200)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Darwin 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
  modules:   (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit ophints fill-column hl-todo modeline nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil multiple-cursors rotate-text fold snippets file-templates :emacs dired electric vc :tools eval (lookup +docsets) editorconfig gist macos make (magit +forge) upload flyspell flycheck :term vterm :lang assembly (cc +irony +rtags) data emacs-lisp javascript markdown (org +attach +babel +capture +export +present) php python rust (sh +fish) web :config default)
  packages:  (multi-web-mode wgrep swiper ag wgrep-ag exec-path-from-shell (play-sound :recipe (play-sound :fetcher github :repo leoliu/play-sound-osx)) (zephir-mode :recipe (zephir-mode :fetcher github :repo sergeyklay/zephir-mode)) ac-php-core composer php-runtime php-eldoc)
  exec-path: (/usr/local/opt/php@7.1/sbin/ /usr/local/opt/php@7.1/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/Cellar/cmake/3.10.1/bin/ /usr/local/opt/php@7.1/sbin/ /usr/local/opt/php@7.1/bin/ /usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0/)
  ```
```

**Comment by CodyWilson** [comment] 2019-06-21 14:23
Just remembered I hadn't ran doom upgrade/update in a little while.

Here's everything on what should be the latest.

Debug:
```
Debugger entered--Lisp error: (wrong-type-argument symbolp (args))
  symbol-name((args))
  helpful--format-argument((args))
  mapcar(helpful--format-argument ((args) t))
  -map(helpful--format-argument ((args) t))
  helpful--signature((closure ((args) t) nil (interactive) (+org/insert-item (quote below))))
  #f(compiled-function () (interactive nil) #<bytecode 0x40a8ac05>)()
  apply(#f(compiled-function () (interactive nil) #<bytecode 0x40a8ac05>) nil)
  helpful-update()
  helpful-key([C-return])
  funcall-interactively(helpful-key [C-return])
  call-interactively(helpful-key nil nil)
  command-execute(helpful-key)
```

- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 26.2 (May 22, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop 2e96fce2 2019-06-19 11:37:27 +0200)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Darwin 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
  modules:   (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit ophints fill-column hl-todo modeline nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil multiple-cursors rotate-text fold snippets file-templates :emacs dired electric vc :tools eval (lookup +docsets) editorconfig gist macos make (magit +forge) upload flyspell flycheck :term vterm :lang assembly (cc +irony +rtags) data emacs-lisp javascript markdown (org +attach +babel +capture +export +present) php python rust (sh +fish) web :config default)
  packages:  (multi-web-mode wgrep swiper ag wgrep-ag exec-path-from-shell (play-sound :recipe (play-sound :fetcher github :repo leoliu/play-sound-osx)) (zephir-mode :recipe (zephir-mode :fetcher github :repo sergeyklay/zephir-mode)) ac-php-core composer php-runtime php-eldoc)
  exec-path: (/usr/local/opt/php@7.1/sbin/ /usr/local/opt/php@7.1/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/Cellar/cmake/3.10.1/bin/ /usr/local/opt/php@7.1/sbin/ /usr/local/opt/php@7.1/bin/ /usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0/)
  ```

**Comment by hlissner** [comment] 2019-06-21 15:43
Hmm, this may be an issue with helpful. I'll look into it.

**Comment by hlissner** [comment] 2019-06-28 15:17
After some testing this does appear to be an issue with helpful-key being unable to deal with byte-compiled closures. I've filed an issue for it: https://github.com/Wilfred/helpful/issues/212

I'll keep this issue open until it is addressed.

**Comment by flyingns** [comment] 2019-06-29 14:02
When I updated to fc8354b, I have no such errors at all, thank you very much.

**Closed** 2019-07-13 11:09 UTC
Labels: is:external, module:lang:emacs-lisp, status:resolved
