### ISSUE TITLE
doom upgrade errors with straight.el

### ISSUE THREAD

**Issue by agarciamontoro** [hlissner/doom-emacs#2941] opened 2020-04-20 12:51 UTC
**What did you expect to happen?**
The `doom upgrade` process should succeed.

**What actually happened?**
When doing `doom upgrade`, I got asked what to do with `straight.el`:
```
> Updating packages (this may take a while)...
  > In repository "straight.el", HEAD (on branch "develop") has diverged from branch "master"

       1) Abort
       2) Merge HEAD to branch "master"
       3) Reset branch "master" to HEAD (Recommended)
       4) Reset HEAD to branch "master"
       5) Rebase HEAD onto branch "master" and fast-forward "master" to HEAD

    How to proceed? (1, 2, 3, 4, 5)
```

When choosing the recommended option, 3), the prompt appeared again. If I chose 4) instead, the upgrade did finish, but I still got an error from `straight.el`:

```
  ! (1/239) Encountered error with straight
    x (error Failed to run "git"; see buffer *straight-process*)
      - error: pathspec 'master' did not match any file(s) known to git
      
x Encountered 1 error(s), the offending packages: straight
✓ All 239 packages are up-to-date
✓ Done! Restart Emacs for changes to take effect.
✓ Finished! (74.6748s)
```

I guess this should be the offending commit: https://github.com/hlissner/doom-emacs/commit/c96303830835ed49b6803a5288379891d6ab7cfc

**Steps to reproduce:**
1. Run `doom upgrade`
2. When prompted how to proceed with straight.el, type `3` and hit `Enter`.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 3a5ef316f 2020-04-19 22:04:12 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64")
  (path "~/bin" "~/go/bin" "~/.cargo/bin" "~/.node_modules/bin" "~/.cargo/bin" "~/bin" "~/go/bin" "~/.cargo/bin" "~/.node_modules/bin" "/opt/google-cloud-sdk/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.gem/ruby/2.6.0/bin" "~/.local/bin" "~/.cargo/bin" "~/.npm-global/bin/" "~/.gem/ruby/2.6.0/bin" "~/.local/bin" "~/.cargo/bin" "~/.npm-global/bin/" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy +childframe +icons) :ui doom doom-dashboard doom-quit hl-todo (modeline +light) ophints (popup +all +defaults) (pretty-code +hasklig) treemacs vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term eshell :tools eval lookup lsp magit :lang data elm emacs-lisp (go +lsp) javascript ledger markdown (org +dragndrop +journal +roam) python rst scala sh :app calendar irc :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by brianmcgillion** [comment] 2020-04-20 13:03
Could you try? :
```
rm -rf ~/.emacs.d/.local/straight/repos/straight.el
doom sync
```
It should show "bootstrapping straight". After this `doom upgrade` should work as before

**Comment by agarciamontoro** [comment] 2020-04-20 13:07
@brianmcgillion that works, thank you!

**Comment by hlissner** [comment] 2020-04-21 22:32
This is a duplicate of #2802, #2893, #2899, #2909, #2914, #2918, and #2935.

See #2802 (comment) for a solution.

**Closed by hlissner** 2020-04-21 22:32 UTC
Labels: is:duplicate
