### ISSUE TITLE
org-mode missing link (red link) tries to resolve and is very slow on Windows

### ISSUE THREAD

**Issue by SirRamEsq** [hlissner/doom-emacs#4212] opened 2020-11-04 13:10 UTC
**Summary**
Hi, new user to Doom Emacs, migrating from my own config. I'm having an issue with org mode and the red links:
![image](https://user-images.githubusercontent.com/9139184/98114078-b6635400-1e72-11eb-9e88-14e0247fe03a.png)

The links in red cannot be found by Windows. The links point to a share that can only be accessed when I'm on a VPN and look like:
`[[\\hostname\share\path][Share Link Path]]`
This is expected, as I'm on and off of many VPNs depending on what day it is. Network path's won't always be valid.

I can't seem to find much information on what these red links are or how to disable link resolution. As far as I'm aware, my config in vanilla Emacs didn't try to resolve links and wouldn't show a link as being unable to be resolved and I wouldn't experience these long pauses.

**I've filled out each of the fields for a bug report below, but I think most of the responsibility for this issue lies with Windows. To resolve this bug, I think just adding a clear way to disable automatic link resolution would be enough.**

Very much enjoying Doom Emacs BTW. Thanks so much for putting time into this like you do.

---

**What did you expect to happen?**
When opening an org mode file that contains links, I do not expect Emacs to try to resolve every single link in the org mode file to determine if they exist.

**What actually happened?**
When opening an org mode file that contains links to locations that cannot be found by windows there is a very long pause (about 20 seconds per missing link) while the links try to be resolved. Editing a link will also sometimes trigger this link resolution and Emacs will freeze for 20 seconds while it waits for Windows to respond.

**I suspect on Linux, the link resolution would much faster and wouldn't be an issue. On Windows though, it's very noticable**

**Additional details:**
[Doom Emacs Config](https://github.com/SirRamEsq/DoomEmacsConfig)
Tried running the Emacs profiler for the first time, but it didn't appear to pick anything up. I ran the doom profiler (SPC h T) in an empty org-mode buffer, pasted the missing share link into the buffer, experienced the 20 second pause, then stopped the doom profiler. The only thing that was reported were my actions (key presses) starting the doom profiler.

**Steps to reproduce:**
My Doom Emacs config isn't very heavily configured. On any Windows System, create a new org mode document. Create a link to a missing share. The link should turn red and you will likely experience a long pause while it resolves.

**System information:**
<details><pre>
```
SYSTEM  type       windows-nt
        config     x86_64-w64-mingw32
        shell      ~/emacs-26.1-x86_64/libexec/emacs/26.1/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
        path       (C:\Program Files (x86)\VMware\VMware vSphere CLI\Perl\site\bin C:\Program Files (x86)\VMware\VMware vSphere CLI\Perl\bin C:\Program Files\Java\jre1.8.0_211\bin\ C:\Program Files\Java\jre1.8.0_211\bin\server\ C:\Program Files (x86)\Java\jre1.8.0_211\bin\ C:\Program Files (x86)\Java\jre1.8.0_211\bin\client\ C:\Program Files (x86)\RSA SecurID Token Common C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common C:\Program Files (x86)\Common Files\Oracle\Java\javapath C:\Program Files\Python37\Scripts\ C:\Program Files\Python37\ C:\WINDOWS\system32 C:\WINDOWS C:\WINDOWS\System32\Wbem C:\WINDOWS\System32\WindowsPowerShell\v1.0\ C:\Program Files\PuTTY\ C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\ C:\Program Files (x86)\Symantec\VIP Access Client\ C:\WINDOWS\System32\OpenSSH\ C:\Program Files\dotnet\ C:\Program Files (x86)\Java\jre1.8.0_191\bin C:\Program Files\TortoiseSVN\bin C:\Program Files\MiKTeX 2.9\miktex\bin\x64\ C:\Program Files (x86)\Graphviz2.38\bin C:\Go\bin C:\Program Files\WinMerge C:\bin C:\Program Files (x86)\Lua\5.1 C:\Program Files (x86)\Lua\5.1\clibs C:\Ruby26-x64\bin C:\Users\LloydRyan\AppData\Local\Microsoft\WindowsApps C:\Program Files (x86)\Nmap C:\MinGW\bin C:\Program Files\Git\bin C:\Users\LloydRyan\.dotnet\tools C:\Users\LloydRyan\AppData\Local\Programs\Fiddler C:\Users\LloydRyan\go\bin C:\Program Files\Git\usr\bin C:\nant-0.92\bin C:\Users\LloydRyan\GD C:\Users\LloydRyan\AppData\Local\Microsoft\WindowsApps C:\Lua C:\Users\LloydRyan\emacs-26.1-x86_64\bin C:\Users\LloydRyan\PortablePrograms\fd-v8.1.1-i686-pc-windows-gnu C:\Users\LloydRyan\PortablePrograms\ripgrep-12.1.1-x86_64-pc-windows-gnu C:\Users\LloydRyan\.emacs.d\bin ~/emacs-26.1-x86_64/libexec/emacs/26.1/x86_64-w64-mingw32/)
EMACS   dir        ~/.emacs.d/
        version    26.1
        build      May 30, 2018
        buildopts  --without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3'
        features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 42d5da8 2020-10-31 15:16:58 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang cc common-lisp crystal csharp emacs-lisp fsharp gdscript json (java +meghanada) javascript latex lua markdown org php python rust sh web yaml :config (default +bindings +smartparens))
        packages   ((org-bullets) (highlight-symbol))
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment] 2020-11-04 20:11
Our org module bows out of file-checks for remote paths for performance reasons. The problem is that Emacs does not consider a Windows network share's path a "remote path", so some custom code was needed. 304424d adds this, which should resolve your issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by SirRamEsq** [comment] 2020-11-05 00:03
Wow, thanks for the quick response!

I upgraded with `doom upgrade`

Unfortunately, that didn't seem to do it. I still get the red links and slow file open times with network shares that aren't found

Looking at the commit, it may be that the wrong slash is used?
In the commit a **forward-slash** is used:
` (and IS-WINDOWS (string-prefix-p "//" path))`

But for Windows shares a **back-slash** is used
`[[\\hostname\share\path][Share Link Path]]`

Let me know if I may just be missing something obvious.

**Comment by SirRamEsq** [comment] 2020-11-05 12:14
Made the changes to backslashes and the issue is resolved :)
Added a pull request for this issue

**Comment by hlissner** [comment] 2020-11-06 07:32
With #4212 merged this issue should be resolved. Let me know if that isn't the case and I'll reopen it.

**Closed** 2020-11-06 07:32 UTC
Labels: :lang org, is:bug, re:performance, re:windows

**Comment by SirRamEsq** [comment] 2020-11-07 13:10
We should be good, thanks for making the double backslash "\\\\\\\\" change. I wasn't around yesterday to do it.
