### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by RohitSingh107** [hlissner/doom-emacs#5012] opened 2021-05-08 14:04 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.

### What did you expect to happen?

I just tried to upgrade as usual

### What actually happened?

╰─λ .emacs.d/bin/doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to .emacs.d/.local/doom.error.log

### Steps to reproduce

I just tried to upgrade as usual.

### System Information

https://pastebin.com/1yQtsWbQ

**Comment by iyefrat** [comment] 2021-05-08 14:26
See:
https://github.com/hlissner/doom-emacs/issues/4950#issuecomment-829944410

**Comment by hlissner** [comment] 2021-05-08 16:37
Duplicate of #4950

**Closed by hlissner** 2021-05-08 16:37 UTC
Labels: delete me, duplicate

**Comment by hlissner** [comment] 2021-05-08 16:40
Please don't check ` I have searched the issue tracker for similar issues (the closed issues too)` if you haven't actually done it. This is getting ridiculous.

![image](https://user-images.githubusercontent.com/510883/117546844-88fe8b00-affa-11eb-90e5-f15cd421187d.png)
