### ISSUE TITLE
Magit broken on Emacs 29

### ISSUE THREAD

**Issue by glennsl** [hlissner/doom-emacs#5950] opened 2022-01-03 16:04 UTC
### What did you expect to happen?

When I press `SPC g g`, I expect the magit overview screen to open.

### What actually happened?

Emacs hangs for a bit, then the following error pops up:

```
Error (magit-mode-hook): Error running hook "turn-on-magit-gitflow" because: (error code-review-pretty-milestone is already defined as something else than a generic function)
```

Also, from messages:
```
Failed to load magit package incrementally, because: (void-variable code-review-comment-insert-lines)
```

Might be related to #5940 

### Steps to reproduce

1. Open Emacs
2. Open a file or project in a git repository
3. Press `SPC g g`

### System Information

https://pastebin.com/F627SD1a

**Comment by glennsl** [comment] 2022-01-03 16:13
Downgrading to emacs 27 fixes the issue. Unfortunately there's no 28 in the Arch repositories.

**Comment by hlissner** [comment] 2022-01-03 17:50
I just bumped the `:tools magit` module, which includes an update to `code-review`. Please update Doom and see if that resolves your issue.

**Comment by hlissner** [comment] 2022-01-03 17:53
Actually, this is a duplicate of #5940. Please follow up there.

**Closed by hlissner** 2022-01-03 17:53 UTC
Labels: duplicate, delete me
