### ISSUE TITLE
Python: trailing whitespace after newline 

### ISSUE THREAD

**Issue by s8v** [hlissner/doom-emacs#498] opened 2018-03-31 08:51 UTC
### Observed behavior
Inserting newline after empty string don't remove trailing whitespace.
This behavior breaks indentation on inserting snippets like `ife`.

[video describing the problem](https://yadi.sk/i/LYm0ADic3Tw8Sr)

### Expected behavior

Inserting newline removes trailing whitespace.

I tried to investigate the problem, but found that the newline key bind to standard `newline-and-indent`. This function calls `delete-horizontal-space` that works fine separately, but not working together. 
I hope it was the right direction.

### System information

<details>
<summary>Click to expand</summary>

```
Doom Doctor
Emacs v25.3.1
Doom v2.0.9 (7590c46f)
shell: /bin/zsh
Compiled with:
  JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  MODULES
uname -a:
  Darwin MacBook-Air-Aleksandr.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec
  17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

----

test-emacs
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar

----
Attempt to load DOOM: success! Loaded v2.0.9
test-modules
Loading /Users/Aleksandr/.emacs.d/modules/feature/snippets/packages.el (source)...

----
Everything seems fine, happy Emacs’ing!
```
</details>

**Comment by hlissner** [comment] 2018-03-31 21:50
I've pushed [a fix](https://github.com/hlissner/emacs-snippets/commit/d8e2cd84a6ccfef0d4fddb71c4ce98618cd38e8d) to the [emacs-snippets repo](https://github.com/hlissner/emacs-snippets) to address your `ife` snippet issue.

As for the newline issue, I'm afraid this is a quirk of `python-mode`, not Doom, and I'm not entirely certain that the behavior is undesireable. I will occasionally separate groups of logic with a newline, and I don't want the second newline to be dedented. I see this in code in the wild as well, and wouldn't want the indenter to break it.

Two things to note:

+ You can press backspace on an empty line to dedent it. It has been modified to delete whitespace N spaces at a time (where N = `tab-width`) if you're at the beginning of the line.
+ python-mode properly indents lines that follow a keyword that commonly ends a block, like `pass` or `return`.

All that said, this may give you want you want, without touching the indentation logic:

```elisp
  (defun +python/newline-and-indent ()
    "TODO"
    (interactive)
    (let ((context (python-indent-context)))
      (newline-and-indent)
      (if (and (eq (car context) :after-line)
               (> (count-lines (cdr context) (point)) 1))
        (doom/backward-delete-whitespace-to-column)
        t)))
  (map! :map python-mode-map [remap newline] #'+python/newline-and-indent)
```

Let me know if that helps!

**Comment by s8v** [comment] 2018-04-01 10:53
@hlissner, thanks you for your advice, your snippet works a little bit wrong, but I'll try to fix it myself.
I looked at how newline works in default emacs, and it looks like I'm expecting.
![gif](https://media.giphy.com/media/vwt2lbmdCZSEFf4HUa/giphy.gif)
In default emacs is used `newline` not `newline-and-indent`, i tried to replace
```
   ;; [remap newline]          #'newline-and-indent
      [remap newline]          #'newline
```
But this works not like default emacs.
![gif2](https://media.giphy.com/media/7IYwxsDxyB7GXRhjCp/giphy.gif)

@robbert-vdh, yes, it looks like the easiest solution.

**Comment by hlissner** [comment] 2018-04-18 22:38
Ah, what you're seeing is the result of `electric-indent-mode`, which will automatically reindent the line if any of the keys in `electric-indent-chars` are pressed (enter is one of them).

Doom disables `electric-indent-mode` because not all languages have good indentation support (and instead, remap `newline` to `newline-and-indent`.

However, you should get the same behavior if you use `newline-and-indent` or `newline`+`electric-indent-mode`, so I'm not sure I follow what the issue is.

**Comment by hlissner** [comment] 2018-08-03 10:48
Closing this in preparation for the 2.1 release. Feel free to reopen if the issue persists.

**Closed by hlissner** 2018-08-03 10:48 UTC
Labels: config, external
