### ISSUE TITLE
Could not find package bibtex-completion in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)

### ISSUE THREAD

**Issue by jingnanshi** [hlissner/doom-emacs#2935] opened 2020-04-19 01:48 UTC
**What did you expect to happen?**

Just upgraded doom with `doom upgrade` to commit `5d51d4e4a662410679a5678fcc3f5251a8f33a66`. Then I enabled the `biblio` module, and run `doom/reload`. 

**What actually happened?**
`Could not find package bibtex-completion in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)`

**Additional details:**
Backtrace:
https://gist.github.com/jingnanshi/d5558fd88d227be39f22f69896cf43b7

**Steps to reproduce:**
As described aboe

**System information:**
```
Package error: (error Could not find package bibtex-completion in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 5d51d4e4a 2020-04-18 21:08:41 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64")
  (path "~/miniconda3/condabin" "/usr/local/MATLAB/R2019a/bin" "~/.cargo/bin" "~/.local/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/.rvm/bin" "~/packages/fzf/bin" "~/.rvm/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :term shell term :checkers syntax :tools biblio (eval +overlay) lookup lsp magit pdf :lang data emacs-lisp (latex +latexmk +fold +cdlatex) markdown (org +journal +dragndrop +roam) (python +conda +lsp) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
```

**Comment by hlissner** [comment] 2020-04-19 01:53
This is a duplicate of #2893, #2899, #2909, #2914, and #2918.

See https://github.com/hlissner/doom-emacs/issues/2802#issuecomment-606654151 for a solution.

**Closed by hlissner** 2020-04-19 01:53 UTC
Labels: is:duplicate

**Comment by jingnanshi** [comment] 2020-04-19 01:58
@hlissner Thank you!
