### ISSUE TITLE
Failed to load org-agenda and org-capture package incrementally in gccemacs.

### ISSUE THREAD

**Issue by AllenDang** [hlissner/doom-emacs#4549] opened 2021-01-21 05:11 UTC
**What did you expect to happen?**
Start emacs, open any project, no error message.

**What actually happened?**
Error message in Message buffer.
```
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
Failed to load org-agenda package incrementally, because: (wrong-number-of-arguments (3 . 4) 2)
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
Failed to load org-capture package incrementally, because: (wrong-number-of-arguments (3 . 4) 2)
```
And BTW, SPC h r r doesn't work and report below error.
```
run-hooks: Symbol’s function definition is void: nil
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
define-obsolete-function-alias: Wrong number of arguments: (3 . 4), 2
```

**Additional details:**
I'm using latest doom and latest gccemacs.

**Comment by hlissner** [comment] 2021-01-21 05:12
Duplicate of #4534

**Closed by hlissner** 2021-01-21 05:12 UTC
Labels: duplicate
