### ISSUE TITLE
Cannot open attachments from email view in mu4e

### ISSUE THREAD

**Issue by kuba-orlik** [hlissner/doom-emacs#5027] opened 2021-05-10 10:07 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for solutions.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When I open an email message in mu4e, I used to be able to press `o` to open one of the attachments. 

### What actually happened?

Today after upgrading Doom I can no longer do that, there's only the option to save the attachment, and then I have to open it manually OR I can use the mouse (ugh) to click the name of the attachment. Also, the attachment list is displayed differently than it used to be:

![image](https://user-images.githubusercontent.com/2697916/117642741-f3910180-b187-11eb-94fb-242ff4dfe5ac.png)

### Describe your attempts to resolve the issue

I've tried looking for a function in M-x that would reproduce this functionality, but came empty-handed

### Steps to reproduce

1. Open emacs
2. Open mu4e
3. navigate to a single message that contains an attachment
4. press `o`

### System Information

https://pastebin.com/9yyPjqnW

**Comment by tecosaur** [comment] 2021-05-10 10:13
Out of curiosity, have you tried the mu4e branch? https://github.com/hlissner/doom-emacs/pull/3971

**Comment by kuba-orlik** [comment] 2021-05-10 10:31
I haven't

**Comment by benbovy** [comment] 2021-08-09 12:53
I stumbled upon this too after upgrading to mu 1.6.1 then 1.62 (MacOS, homebrew) and using the now merged Doom's `mu4e` module.

- press `A` anywhere or with the cursor on an attachment in a mu4e view buffer: `command-execute: Wrong type argument: commandp, mu4e-view-attachment-action`
- press `o` anywhere in a mu4e view buffer: `command-execute: Wrong type argument: commandp, mu4e-view-open-attachment`
- press `o`, `e` or any action key on an attachment in a mu4e view buffer: prompt for choosing the location where to save the file but then nothing (no internal buffer or external program opened).

The issue is only when using the gnus-based message viewer (default since mu 1.6). When reverting to the old view using `(setq mu4e-view-use-old t)` I don't have any problem for saving/opening attachments.

I'm not sure if it's a mu4e issue or a doom/mu4e configuration issue. I haven't seen anything reported in the [mu repo](https://github.com/djcb/mu). My personal configuration on top of doom/mu4e doesn't do anything fancy.

> the attachment list is displayed differently than it used to be

It looks different indeed whether the gnus-based message viewer or the legacy mu-based viewer is used.

**Comment by benbovy** [comment] 2021-08-09 14:22
It might not be an issue after all: there are some things no longer supported with gnus-based views (e.g., https://github.com/djcb/mu/issues/1941#issuecomment-799467183). [gnus MIME shortcuts](https://www.gnu.org/software/emacs/manual/html_node/gnus/Using-MIME.html) are good to know too...

Still, pressing `A` in a gnus message viewer tries to execute `mu4e-view-attachment-action` instead of `mu4e-view-mime-part-action`. I suspect some conflicts with evil commands?

**Comment by eddiegroves** [comment] 2021-08-11 22:48
I have the same issue too, thanks for the work around @benbovy (manually running `mu4e-view-mime-part-action`)

**Comment by tecosaur** [comment] 2021-08-31 13:13
I'm thinking this is probably the best solution for now.
```lisp
  (map! :map mu4e-view-mode-map
        :ne "A" #'mu4e-view-mime-part-action
        :ne "p" #'mu4e-view-save-attachments)
```
I'll make a PR at some point.

**Closed** 2021-09-14 22:59 UTC
Labels: 1. bug, needs-triage
