### ISSUE TITLE
doom build throws error

### ISSUE THREAD

**Issue by DoubleClick7** [hlissner/doom-emacs#4194] opened 2020-11-01 13:54 UTC
**What did you expect to happen?**
`doom build` to build all packages successfully

**What actually happened?**
Just after building orgit, it throws an [error](https://pastebin.com/1UuUz1Mg)

**Additional details:**
Messages at startup:
> /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
> Failed to load git-commit package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
> Failed to load magit package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
> Failed to load org package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
> Failed to load org-agenda package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
> Failed to load org-capture package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
> 

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.9.1-zen2-1-zen #1 ZEN SMP PREEMPT Sun, 18 Oct 2020 02:45:20 +0000 x86_64
        path       (~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /var/lib/snapd/snap/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Oct 26, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (server-running)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 471028c 2020-10-27 23:47:59 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo indent-guides ligatures minimap (modeline +light) neotree ophints (popup +defaults) vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric ibuffer undo :term eshell shell term vterm :checkers syntax :tools (eval +overlay) lookup magit make :os tty :lang cc emacs-lisp javascript markdown org python sh :email (mu4e +gmail) :config (default +bindings +smartparens))
        packages   ((ewal-doom-themes) (with-editor) (ewal) (fira-code-mode) (prettier) (sublimity) (spacemacs-theme) (webpaste) (zone-nyan) (nyan-mode) (evil-commentary) (evil-tutor) (sublime-themes) (cyberpunk-theme) (ample-theme) (ample-zen-theme) (afternoon-theme))
        unpin      (n/a)
        elpa       (with-editor async)

</pre></details>

**Comment by innerout** [comment] 2020-11-01 14:07
Can you delete `/home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc` and try building again?

**Comment by DoubleClick7** [comment] 2020-11-01 14:09
> Can you delete `/home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc` and try building again?

Didn't work : {

**Comment by innerout** [comment] 2020-11-01 16:03
Can you delete all .elc files in .emacs.d and build?

**Comment by hlissner** [comment] 2020-11-01 19:09
Duplicate of #4171. See https://github.com/hlissner/doom-emacs/issues/4171#issuecomment-718141943

**Closed by hlissner** 2020-11-01 19:09 UTC
Labels: duplicate
