### ISSUE TITLE
Doom upgrade abort: In repository parseclj, failed to get status

### ISSUE THREAD

**Issue by archaic** [hlissner/doom-emacs#6230] opened 2022-04-01 08:29 UTC
### What did you expect to happen?

When I run doom upgrade, it should run to completion

### What actually happened?

doom upgrade

```
  ✓ (101/215) code-review: ccc3795 -> 85ab208 [6 commit(s)]
          5063249 Prevent void-variable errors
          9ee58a2 Update GitHub Enterprise documentation to add full configuration
          2a31732 Update CONTRIBUTORS and CHANGELOG
          a7e3d7b fix:minor typo in a prompt to the user
          b70f054 Add entries to CONTRIBUTORS and CHANGELOG
          cae2f19 Clarify GitHub docs
      ✓ (110/215) irony-mode: 5063d6b -> 870d157 [1 commit(s)]
          870d157 Fixed typo
      > In repository "parseclj", failed to get status:

        Failed to get unambiguous name for "main"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1)
```

### Steps to reproduce

1. Open terminal
2. ensure clojure is not commented in init.el
3. doom upgrade

### System Information

https://pastebin.com/tDptstfG

**Comment by rakanalh** [comment] 2022-04-01 08:50
Started facing the same error yesterday:
```
~/.emacs.d/bin/doom -y upgrade
- Confirmations auto-accept enabled
  > Preparing to upgrade Doom Emacs and its packages...
  - A new version of Doom Emacs is available!

    Old revision: 86901cca7d (14 hours ago)
    New revision: ff31427687 (6 hours ago)

  Link to diff: https://github.com/hlissner/doom-emacs/compare/86901cca7dcdbd3a0bb091eae307b89794fbc827...ff31427687f7e0dee00d9ee6e12975d1048dff53
  > Upgrading Doom Emacs...
    > Cleaning .elc files
      - No elc files to clean
    - From https://github.com/hlissner/doom-emacs
     * [new branch]        master     -> _upgrade_master
     * [new branch]        master     -> _upgrade/master
  - Reloading Doom Emacs
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
    > Updating packages (this may take a while)...
      x The package manager threw an error.
      x Last 25 lines of straight's error log:
        $ cd /home/rakan/.emacs.d/.local/straight/repos/rust-playground/
        $ git merge-base --is-ancestor master origin/master
        [Return code: 0]
        $ cd /home/rakan/.emacs.d/.local/straight/repos/rust-playground/
        $ git merge-base --is-ancestor origin/master master
        [Return code: 0]
        $ cd /home/rakan/.emacs.d/.local/straight/repos/rust-playground/
        $ git rev-parse HEAD
        5a117781dcb66065bea7830dd73618008fc34949
        [Return code: 0]
        $ cd /home/rakan/.emacs.d/.local/straight/repos/rust-playground/
        $ git log --oneline --no-merges 5a117781dcb66065bea7830dd73618008fc34949 \^5a117781dcb66065bea7830dd73618008fc34949
        [Return code: 0]
        $ cd /home/rakan/.emacs.d/.local/straight/repos/protobuf/
        $ git rev-parse HEAD
        b5a35bcc7e4cc4ff00eb105449b300fca3a8b0d2
        [Return code: 0]
        $ cd /home/rakan/.emacs.d/.local/straight/repos/protobuf/
        $ git config --get remote.origin.url
        https://github.com/google/protobuf.git
        [Return code: 0]
        $ cd /home/rakan/.emacs.d/.local/straight/repos/protobuf/
        $ git fetch origin
        fatal: couldn't find remote ref refs/heads/master
        [Return code: 128]
      ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

**Comment by harabat** [comment] 2022-04-01 12:24
@archaic this is a recurrent bug. 

Deleting the guilty package (`rm -rf ~/.emacs.d/.local/straight/repos/parseclj`) or straight in its entirety before rerunning `upgrade` is the common solution to these.

**Comment by hlissner** [comment] 2022-04-01 13:17
Duplicate of pinned issue: https://github.com/hlissner/doom-emacs/issues/4984

**Closed by hlissner** 2022-04-01 13:17 UTC
Labels: duplicate, delete me
