### ISSUE TITLE
Fresh install on Fedora 31 is nearly unusable [BUG] 

### ISSUE THREAD

**Issue by pepperblue** [hlissner/doom-emacs#2137] opened 2019-12-02 11:53 UTC
**Describe the issue**
- What did you expect to happen?
Default Installation is usable with which-key popup and evil-keybindings

- What actually happened?
Installation runs fine, doom-emacs starts without errors but keybindings are mostly broken
  * pressing `SPC` does not open pop-up with key-mappings
  * pressing `SPC SPC` has no visible result etc.

- Do you have screenshots/casts of your issue?
![screenshot](https://user-images.githubusercontent.com/3543271/69956640-d1aa3e80-1500-11ea-8fe8-73e316aaffbf.png)

- What commands are bound to any keys you've referenced? (use `SPC h k` to
  inspect keys)
Pressing `SPC h k` makes cursor jump to dashboard-entries, no keybindings are displayed

- Can you include a link to your private config?
It' s a fresh installalation - no private config

- Were any warnings or errors logged to \*Messages\* (`SPC h e` or `M-x
  view-echo-area-messages` will open it).
Same effect as `SPC h k`

**Steps to reproduce**
1. `sudo dnf copr enable jaroslav/emacs`
2. `sudo dnf install emacs`
3. `git clone https://github.com/hlissner/doom-emacs ~/.emacs.d`
4. `.emacs.d/bin/./doom install`
<details><pre>
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...
Installing Doom Emacs!

> Creating .doom.d/
  ✓ Created .doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping

Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
^C[schunk@linux ~]git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
Klone nach '/home/schunk/.emacs.d' ...
remote: Enumerating objects: 148, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 71724 (delta 76), reused 82 (delta 41), pack-reused 71576
Empfange Objekte: 100% (71724/71724), 17.89 MiB | 1.74 MiB/s, Fertig.
Löse Unterschiede auf: 100% (50219/50219), Fertig.
[schunk@linux ~]$ .emacs.d/bin/./doom install
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...
Installing Doom Emacs!

> Creating .doom.d/
  ✓ Created .doom.d/
- Creating .doom.d/init.el
✓ Done!
- Creating .doom.d/config.el
✓ Done!
- Creating .doom.d/packages.el
✓ Done!

Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...
Building straight...
Cloning use-package...
Building use-package...
Building use-package → Building bind-key...

Building use-package...
Cloning emacs-async...
Building async...
Cloning gcmh...
Building gcmh...
Generate an env file? (see `doom help env` for details) (y or n) y
> Generating envvars file at "~/.emacs.d/.local/env"
- Scraping shell environment
  ✓ Successfully generated "~/.emacs.d/.local/env"
Installing plugins
> Installing & building packages...
  → Cloning emacs-dotenv-mode...
  → Building dotenv-mode...
  → Cloning auto-minor-mode...
  → Building auto-minor-mode...
  → Cloning all-the-icons.el...
  → Building all-the-icons...
  → Building all-the-icons → Cloning emacs-memoize...
  → Building all-the-icons → Building memoize...

  → Building all-the-icons...
  → Cloning emacs-hide-mode-line...
  → Building hide-mode-line...
  → Cloning highlight-numbers...
  → Building highlight-numbers...
  → Building highlight-numbers → Cloning parent-mode...
  → Building highlight-numbers → Building parent-mode...

  → Building highlight-numbers...
  → Cloning rainbow-delimiters...
  → Building rainbow-delimiters...
  → Cloning restart-emacs...
  → Building restart-emacs...
  → Cloning better-jumper...
  → Building better-jumper...
  → Cloning dtrt-indent...
  → Building dtrt-indent...
  → Cloning helpful...
  → Building helpful...
  → Building helpful → Cloning dash.el...
  → Building helpful → Building dash...
  → Building helpful → Building dash-functional...
  → Building helpful → Cloning s.el...
  → Building helpful → Building s...
  → Building helpful → Cloning f.el...
  → Building helpful → Building f...
  → Building helpful → Cloning elisp-refs...
  → Building helpful → Building elisp-refs...
  → Building helpful → Building elisp-refs → Cloning loop.el...
  → Building helpful → Building elisp-refs → Building loop...

  → Building helpful → Building elisp-refs...
  → Building helpful...
  → Cloning pcre2el...
  → Building pcre2el...
  → Cloning smartparens...
  → Building smartparens...
  → Cloning emacs-so-long...
  → Building so-long...
  → Cloning undo-tree...
  → Building undo-tree...
  → Cloning ws-butler...
  → Building ws-butler...
  → Cloning xclip...
  → Building xclip...
  → Cloning projectile...
  → Building projectile...
  → Building projectile → Cloning pkg-info...
  → Building projectile → Building pkg-info...
  → Building projectile → Building pkg-info → Cloning epl...
  → Building projectile → Building pkg-info → Building epl...

  → Building projectile → Building pkg-info...
  → Building projectile...
  → Cloning general.el...
  → Building general...
  → Cloning emacs-which-key...
  → Building which-key...
  → Cloning company-mode (for company)...
  → Building company...
  → Cloning emacs-company-dict...
  → Building company-dict...
  → Cloning prescient.el (for company-prescient)...
  → Building company-prescient...
  → Building company-prescient → Building prescient...

  → Building company-prescient...
  → Cloning amx...
  → Building amx...
  → Cloning swiper (for ivy)...
  → Building ivy...
  → Building counsel...
  → Building counsel → Building swiper...

  → Building counsel...
  → Cloning counsel-projectile...
  → Building counsel-projectile...
  → Building ivy-hydra...
  → Building ivy-hydra → Cloning hydra...
  → Building ivy-hydra → Building hydra...
  → Building ivy-hydra → Building hydra → Building lv...

  → Building ivy-hydra → Building hydra...
  → Building ivy-hydra...
  → Cloning ivy-rich...
  → Building ivy-rich...
  → Cloning Emacs-wgrep (for wgrep)...
  → Building wgrep...
  → Cloning emacs-doom-themes...
  → Building doom-themes...
  → Cloning emacs-solaire-mode...
  → Building solaire-mode...
  → Cloning hl-todo...
  → Building hl-todo...
  → Cloning doom-modeline...
  → Building doom-modeline...
  → Building doom-modeline → Cloning shrink-path.el...
  → Building doom-modeline → Building shrink-path...

  → Building doom-modeline...
  → Cloning emacs-anzu...
  → Building anzu...
  → Cloning emacs-evil-anzu...
  → Building evil-anzu...
  → Building evil-anzu → Cloning evil...
  → Building evil-anzu → Building evil...
  → Building evil-anzu → Building evil → Cloning goto-chg...
  → Building evil-anzu → Building evil → Building goto-chg...

  → Building evil-anzu → Building evil...
  → Building evil-anzu...
  → Cloning nav-flash...
  → Building nav-flash...
  → Cloning evil-goggles...
  → Building evil-goggles...
  → Cloning emacs-git-gutter-fringe...
  → Building git-gutter-fringe...
  → Building git-gutter-fringe → Cloning emacs-git-gutter...
  → Building git-gutter-fringe → Building git-gutter...
  → Building git-gutter-fringe → Cloning fringe-helper.el...
  → Building git-gutter-fringe → Building fringe-helper...

  → Building git-gutter-fringe...
  → Cloning vi-tilde-fringe...
  → Building vi-tilde-fringe...
  → Cloning ace-window...
  → Building ace-window...
  → Building ace-window → Cloning avy...
  → Building ace-window → Building avy...

  → Building ace-window...
  → Cloning persp-mode.el...
  → Building persp-mode...
  → Cloning evil-args...
  → Building evil-args...
  → Cloning evil-easymotion...
  → Building evil-easymotion...
  → Cloning evil-embrace.el...
  → Building evil-embrace...
  → Building evil-embrace → Cloning embrace.el...
  → Building evil-embrace → Building embrace...
  → Building evil-embrace → Building embrace → Cloning expand-region.el...
  → Building evil-embrace → Building embrace → Building expand-region...

  → Building evil-embrace → Building embrace...
  → Building evil-embrace → Cloning evil-surround...
  → Building evil-embrace → Building evil-surround...

  → Building evil-embrace...
  → Cloning evil-escape...
  → Building evil-escape...
  → Cloning evil-exchange...
  → Building evil-exchange...
  → Cloning evil-indent-plus...
  → Building evil-indent-plus...
  → Cloning evil-nerd-commenter...
  → Building evil-nerd-commenter...
  → Cloning evil-numbers...
  → Building evil-numbers...
  → Cloning evil-snipe...
  → Building evil-snipe...
  → Cloning evil-textobj-anyblock...
  → Building evil-textobj-anyblock...
  → Cloning evil-traces...
  → Building evil-traces...
  → Cloning evil-visualstar...
  → Building evil-visualstar...
  → Cloning exato...
  → Building exato...
  → Cloning evil-quick-diff...
  → Building evil-quick-diff...
  → Cloning evil-collection...
  → Building evil-collection...
  → Building evil-collection → Cloning annalist.el...
  → Building evil-collection → Building annalist...

  → Building evil-collection...
  → Cloning yasnippet...
  → Building yasnippet...
  → Cloning evil-vimish-fold...
  → Building evil-vimish-fold...
  → Building evil-vimish-fold → Cloning vimish-fold...
  → Building evil-vimish-fold → Building vimish-fold...

  → Building evil-vimish-fold...
  → Cloning evil-multiedit...
  → Building evil-multiedit...
  → Building evil-multiedit → Cloning iedit...
  → Building evil-multiedit → Building iedit...

  → Building evil-multiedit...
  → Cloning evil-mc...
  → Building evil-mc...
  → Cloning rotate-text.el...
  → Building rotate-text...
  → Cloning auto-yasnippet...
  → Building auto-yasnippet...
  → Cloning doom-snippets...
  → Building doom-snippets...
  → Cloning diredfl...
  → Building diredfl...
  → Cloning dired-git-info...
  → Building dired-git-info...
  → Cloning diff-hl...
  → Building diff-hl...
  → Cloning dired-rsync...
  → Building dired-rsync...
  → Cloning fd-dired...
  → Building fd-dired...
  → Cloning ibuffer-projectile...
  → Building ibuffer-projectile...
  → Cloning ibuffer-vc...
  → Building ibuffer-vc...
  → Cloning git-link...
  → Building git-link...
  → Cloning git-timemachine...
  → Building git-timemachine...
  → Building git-timemachine → Cloning transient...
  → Building git-timemachine → Building transient...

  → Building git-timemachine...
  → Cloning git-modes (for gitconfig-mode)...
  → Building gitconfig-mode...
  → Building gitignore-mode...
  → Cloning emacs-quickrun...
  → Building quickrun...
  → Cloning eros...
  → Building eros...
  → Cloning flycheck...
  → Building flycheck...
  → Building flycheck → Cloning let-alist...
  → Building flycheck → Building let-alist...

  → Building flycheck...
  → Cloning flycheck-popup-tip...
  → Building flycheck-popup-tip...
  → Building flycheck-popup-tip → Cloning popup-el (for popup)...
  → Building flycheck-popup-tip → Building popup...

  → Building flycheck-popup-tip...
  → Cloning dumb-jump...
  → Building dumb-jump...
  → Cloning ivy-xref...
  → Building ivy-xref...
  → Cloning dash-docs...
  → Building dash-docs...
  → Cloning counsel-dash...
  → Building counsel-dash...
  → Cloning magit...
  → Building magit...
  → Building magit → Building git-commit...
  → Building magit → Building git-commit → Cloning with-editor...
  → Building magit → Building git-commit → Building with-editor...

  → Building magit → Building git-commit...
  → Building magit...
  → Cloning forge...
  → Building forge...
  → Building forge → Cloning closql...
  → Building forge → Building closql...
  → Building forge → Building closql → Cloning emacsql (for emacsql-sqlite)...
  → Building forge → Building closql → Building emacsql-sqlite...
  → Building forge → Building closql → Building emacsql-sqlite → Building emacsql...

  → Building forge → Building closql → Building emacsql-sqlite...
  → Building forge → Building closql...
  → Building forge → Cloning ghub...
  → Building forge → Building ghub...
  → Building forge → Building ghub → Cloning treepy.el...
  → Building forge → Building ghub → Building treepy...

  → Building forge → Building ghub...
  → Building forge → Cloning markdown-mode...
  → Building forge → Building markdown-mode...

  → Building forge...
  → Cloning magit-gitflow...
  → Building magit-gitflow...
  → Building magit-gitflow → Cloning magit-popup...
  → Building magit-gitflow → Building magit-popup...

  → Building magit-gitflow...
  → Cloning magit-todos...
  → Building magit-todos...
  → Cloning evil-magit...
  → Building evil-magit...
  → Cloning graphql-mode...
  → Building graphql-mode...
  → Cloning json-mode...
  → Building json-mode...
  → Building json-mode → Cloning json-reformat...
  → Building json-mode → Building json-reformat...
  → Building json-mode → Cloning json-snatcher...
  → Building json-mode → Building json-snatcher...

  → Building json-mode...
  → Cloning jsonnet-mode...
  → Building jsonnet-mode...
  → Cloning yaml-mode...
  → Building yaml-mode...
  → Cloning csv-mode...
  → Building csv-mode...
  → Cloning dhall-mode...
  → Building dhall-mode...
  → Building dhall-mode → Cloning reformatter.el...
  → Building dhall-mode → Building reformatter...

  → Building dhall-mode...
  → Cloning protobuf-mode...
  → Building protobuf-mode...
  → Cloning highlight-quoted...
  → Building highlight-quoted...
  → Cloning macrostep...
  → Building macrostep...
  → Cloning overseer.el...
  → Building overseer...
  → Cloning elisp-def...
  → Building elisp-def...
  → Cloning elisp-demos...
  → Building elisp-demos...
  → Cloning flycheck-cask...
  → Building flycheck-cask...
  → Cloning emacs-buttercup...
  → Building buttercup...
  → Cloning markdown-toc...
  → Building markdown-toc...
  → Cloning edit-indirect...
  → Building edit-indirect...
  → Cloning evil-markdown...
  → Building evil-markdown...
  → Cloning org (for org-plus-contrib)...
  → Building org-plus-contrib...
  → Cloning emacs-htmlize...
  → Building htmlize...
  → Cloning org-bullets...
  → Building org-bullets...
  → Cloning org-fancy-priorities...
  → Building org-fancy-priorities...
  → Cloning org-yt...
  → Building org-yt...
  → Cloning ox-clip...
  → Building ox-clip...
  → Building ox-clip → Building org...

  → Building ox-clip...
  → Cloning toc-org...
  → Building toc-org...
  → Cloning org-cliplink...
  → Building org-cliplink...
  → Cloning evil-org-mode (for evil-org)...
  → Building evil-org...
  → Cloning orgit...
  → Building orgit...
  → Cloning org-download...
  → Building org-download...
  → Cloning ob-ipython...
  → Building ob-ipython...
  → Cloning centered-window-mode (for centered-window)...
  → Building centered-window...
  → Cloning org-tree-slide...
  → Building org-tree-slide...
  → Cloning org-re-reveal...
  → Building org-re-reveal...
  → Cloning ob-async...
  → Building ob-async...
  → Cloning ox-pandoc...
  → Building ox-pandoc...
  → Building ox-pandoc → Cloning ht.el...
  → Building ox-pandoc → Building ht...

  → Building ox-pandoc...
  → Cloning company-shell...
  → Building company-shell...
  → Cloning ace-link...
  → Building ace-link...
  → Cloning drag-stuff.el...
  → Building drag-stuff...
  ✓ Installed & built 93 packages
Regenerating autoloads files
> Checking core autoloads file
  > Regenerating core autoloads file
    ✓ Scanned 68 file(s)
    ✓ Generated new autoloads.el
    ✓ Expanded module autoload paths
    ✓ Generated autodefs
    ✓ Cleaned up autoloads
  > Byte-compiling .local/autoloads.el...
    ✓ Compiled .local/autoloads.el
> Checking package autoloads file
  > Regenerating package autoloads file
    ✓ Cached package state
    ✓ Package autoloads included
    ✓ Expanded module autoload paths
    ✓ Removed load-path/auto-mode-alist entries
  > Byte-compiling .emacs.d/.local/autoloads.pkg.el...
    ✓ Compiled .emacs.d/.local/autoloads.pkg.el
Download and install all-the-icon's fonts? (y or n) y

Contacting host: raw.githubusercontent.com:443
Contacting host: raw.githubusercontent.com:443
Fonts downloaded, updating font cache... <fc-cache -f -v> 
 Successfully installed ‘all-the-icons’ fonts to ‘/home/schunk/.local/share/fonts/’!
✓ 
Finished! Doom is ready to go!

Before you doom yourself, there are a few things you should know:

1. Whenever you edit your doom! block in ~/.doom.d/init.el or modify your
   modules, run:

     bin/doom refresh

   This will ensure all needed packages are installed, all orphaned packages are
   removed, and your autoloads files are up to date. This is important! If you
   forget to do this you will get errors!

2. If something inexplicably goes wrong, try `bin/doom doctor`

   This will diagnose common issues with your environment and setup, and may
   give you clues about what is wrong.

3. Use `bin/doom upgrade` to update Doom. Doing it any other way may require
   additional work. When in doubt, run `bin/doom refresh`.

4. Check out `bin/doom help` to see what else `bin/doom` can do (and it is
   recommended you add ~/.emacs.d/bin to your PATH).

5. You can find Doom's documentation via `M-x doom/help` or `SPC h D`.

Have fun!

✓ Finished! (370.4895s)
</pre></details>
5. `.emacs.d/bin/./doom doctor`
<details><pre>
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
! ~/.emacs.d/.local/straight/build/org-plus-contrib/org-version.elc is out-of-date
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 34 modules
  ✓ Detected 134 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...

There are 1 warnings!

✓ Finished! (1.7820s)
</pre></details>
6. `emacs`

**System information**
<details><pre>
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2")
  (build . "Nov 20, 2019")
  (buildopts "--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 90c0dd6b3 2019-12-01 22:46:45 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-redhat-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.3.12-300.fc31.x86_64 #1 SMP Thu Nov 21 22:52:07 UTC 2019 x86_64")
  (path "~/.local/bin" "~/bin" "/usr/share/Modules/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "/usr/libexec/emacs/26.3/x86_64-redhat-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by Emantor** [comment] 2019-12-02 11:56
Very likely duplicate of #2135

**Comment by pepperblue** [comment] 2019-12-02 12:05
Fix in #2135 seems to work for me also.

**Comment by hlissner** [comment] 2019-12-02 21:37
I'll close this as a duplicate of #2135, which was resolved earlier today.

**Closed by hlissner** 2019-12-02 21:37 UTC
Labels: is:duplicate
