### ISSUE TITLE
doom reports "doom: 7: [: Illegal number:" after every command

### ISSUE THREAD

**Issue by sc0ttwad3** [hlissner/doom-emacs#3835] opened 2020-08-25 18:33 UTC
Suddenly after updating doom-emacs this morning—via my regular `doom upgrade`, `doom sync` and `doom doctor` sequence—_every_ `doom <command>` runs, but _now_, always with the last line error message. For example, using `version` for simplicity:

```
❯ doom version
Doom v2.0.9 (HEAD -> develop ce2cabf07 2020-08-25 06:07:47 -0400)
doom: 7: [: Illegal number:
```

Looking into the first ten lines of  `~/.emacs.d/bin/doom`, the 7th line does start with the left bracket `[` of an equivalence test, yet has the matching right `]`. Which to my Emacs beginner eyes looks syntactically correct, as does the rest of the line. 

```
#!/usr/bin/env sh
:; set -e # -*- mode: emacs-lisp; lexical-binding: t -*-
:; case "$EMACS" in *term*) EMACS=emacs ;; *) EMACS="${EMACS:-emacs}" ;; esac
:; export __DOOMPOST="${TMPDIR:-/tmp}/doom.sh"
:; $EMACS --version >/dev/null 2>&1 || { >&2 echo "Can't find emacs in your PATH"; exit 1; }
:; $EMACS --no-site-file --script "$0" -- "$@" || __DOOMCODE=$?
:; [ "$__DOOMCODE" -eq 128 ] && { "$__DOOMPOST" "$0" "$@"; __DOOMCODE=$?; }
:; exit $__DOOMCODE

```

**System information:**
<details><pre>

```
SYSTEM  type       gnu/linux
│       config     x86_64-pc-linux-gnu
│       shell      /usr/bin/zsh
│       uname      Linux 4.19.121-microsoft-standard #1 SMP Fri Jun 19 21:06:10 UTC 2020 x86_64
│       path       (. ~/bin ~/.local/bin ~/.emacs.d/bin ~/scripts ~/.cargo/bin ~/.skim/bin /usr/local/bin /usr/bin /bin ~/.go/bin ~/projects/gopath/bin /mnt/c/Windows/System32 /usr/local/sbin /usr/local/bin /u$
EMACS   dir        ~/.emacs.d/
│       version    26.3
│       build      Mar 26, 2020
│       buildopts  --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-p$
│       features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBS$
│       traits     (envvar-file)
DOOM    dir        ~/dotfiles/.doom.d/
│       version    2.0.9
│       build      HEAD -> develop ce2cabf07 2020-08-25 06:07:47 -0400
│       elc-files  0
│       modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo indent-guides ligatures modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select $
│       packages   (n/a)
│       unpin      (n/a)
│       elpa       (slime)
```
</details>

**Comment by hlissner** [comment] 2020-08-25 18:54
Duplicate of #3833 and #3831. Fixed in 239516a.

**Closed by hlissner** 2020-08-25 18:54 UTC
Labels: is:duplicate
