### ISSUE TITLE
sh-mode in yasnippet seems to be broken

### ISSUE THREAD

**Issue by michaelbaecker** [hlissner/doom-emacs#6199] opened 2022-03-17 07:32 UTC
### What did you expect to happen?

I have added a new snippet to yasnippets:
~/.doom.d/snippets/sh-mode/bashheader
```
# -*- mode: snippet -*-
# key: bashheader
# name: bashheader
# --

${1:`(file-name-base
     (or (buffer-file-name)
     (buffer-name)))`} {
     $0
}
```

This should result in a filename of the buffer.

### What actually happened?

Adding this to a Shell Script results in an error:
`_Symbol’s value as variable is void`

The same code works as a ruby snippet.

### Describe your attempts to resolve the issue

I tried to add this to the ~/.doom.d/config.el and did a "doom sync"

```
(use-package yasnippet
  :straight t
  :config
  (yas-global-mode 1))
```

### Steps to reproduce

1. Open Emacs
2. Create a new snippet with the content
```
# -*- mode: snippet -*-
# key: bashheader
# name: bashheader
# --
${1:`(file-name-base
     (or (buffer-file-name)
     (buffer-name)))`} {
     $0
}
```
3. Saving as sh-mode snippet
4. Restart emacs
5. Create a new Script.sh
6. Adding the snippet from above

### System Information

https://pastebin.com/9WBiAR1v

**Comment by hlissner** [comment] 2022-03-19 15:05
I cannot reproduce this in vanilla Doom, so this must be an unrelated issue with your config. Please double check the rest of your config.

I will close this as it is not a Doom issue, but feel free to follow up here.

**Closed by hlissner** 2022-03-19 15:05 UTC
Labels: invalid, delete me

**Comment by sincebyte** [comment] 2025-04-23 01:45
In fact it is . It seems that in sh mode the company-backend made complete file name as the highest hierarchy, so it cause the error blew.

### Steps to reproduce

Create a snippet like this:
```
# -*- mode: snippet -*-
# name: kill
# key: kill
# --
ps -ef | grep $0`(yank)` | awk '{print $2}' | xargs kill -9
```
And then in sh mode , type kill the error message show me 
```
Company: backend (company-shell company-files) error "Opening directory: Not a directory, /Library/TeX/texbin/pdflatex" with args (candidates kill )
```

**Comment by hlissner** [comment] 2025-04-23 21:19
@sincebyte Can you produce [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85) from the error?

**Comment by sincebyte** [comment] 2025-04-25 01:16
```
Debugger entered--Lisp error: (file-error "Opening directory" "Not a directory" "/Library/TeX/texbin/pdflatex")
  directory-files("/Library/TeX/texbin/pdflatex")
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_1>("/Library/TeX/texbin/pdflatex")
  #f(compiled-function (it) #<bytecode -0x96da5055cce0418>)("/Library/TeX/texbin/pdflatex")
  -mapcat(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_1> ("/Library/TeX/texbin/pdflatex" "/Applications/Emacs.app/" "/Users/van/Library/pnpm" "/opt/homebrew/opt/sphinx-doc/bin" "/usr/local/sbin" "/Users/van/.pyenv/shims" "/Users/van/.m2/go/bin" "/usr/local/go/bin" "/Users/van/soft/git-graph" "/opt/homebrew/bin/" "/usr/bin" "/opt/local/bin" "/opt/local/sbin" "/Library/TeX/texbin" "/Users/van/soft/mongodb-5.0.6/bin" "/Users/van/soft/lein" "/usr/local/bin" "/usr/sbin" "/Users/van/soft/jdk/jdk-17.0.6.jdk/Contents/Home/bin" "/Users/van/soft/apache-maven-3.6.1/bin" "/opt/homebrew/opt/mysql-client/bin" "/opt/homebrew/bin//sbcl" "/Users/van/.docker/bin" "/Users/van/.cargo/bin" "/usr/local/bin" "/System/Cryptexes/App/usr/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/share/dotnet" "/usr/local/go/bin" "/Library/TeX/texbin" "/opt/homebrew/Cellar/emacs-plus@31/31.0.50/libexec/emacs/31.0.50/aarch64-apple-darwin23.6.0/"))
  company-shell--build-cache()
  company-shell--fetch-candidates()
  company-shell(candidates #("kill" 0 4 (face (font-lock-type-face) ws-butler-chg chg fontified t)) "")
  company--multi-backend-adapter-candidates((company-shell company-files) 2 nil)
  company--multi-backend-adapter((company-shell company-files) candidates #("kill" 0 4 (face (font-lock-type-face) ws-butler-chg chg fontified t)) "")
  apply(company--multi-backend-adapter (company-shell company-files) (candidates #("kill" 0 4 (face (font-lock-type-face) ws-butler-chg chg fontified t)) ""))
  company-call-backend-raw(candidates #("kill" 0 4 (face (font-lock-type-face) ws-butler-chg chg fontified t)) "")
  company--fetch-candidates(#("kill" 0 4 (face (font-lock-type-face) ws-butler-chg chg fontified t)) "")
  company-calculate-candidates(#("kill" 0 4 (face (font-lock-type-face) ws-butler-chg chg fontified t)) nil "")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer run.local.sh> #<window 3 on run.local.sh> 484 925)
  apply(company-idle-begin (#<buffer run.local.sh> #<window 3 on run.local.sh> 484 925))
  timer-event-handler([t 26634 57968 219362 nil company-idle-begin (#<buffer run.local.sh> #<window 3 on run.local.sh> 484 925) nil 0 nil])

```

**Comment by hlissner** [comment] 2025-04-25 01:34
@sincebyte That error seems to suggest that you have `/Library/TeX/texbin/pdflatex` in your `$PATH` (or at least in your `exec-path`), which an invalid entry. I'm not aware of Doom doing this, so I suspect your shell config. Do you have an `export PATH="/Library/TeX/texbin/pdflatex:$PATH"` line in your `.bash_profile` or `.zshenv`?

**Comment by hlissner** [comment] 2025-04-25 01:39
@sincebyte In any case, the error isn't caused by Doom. I could argue that it's the `company-shell` package's responsibility to remove non-directories from `exec-path` before operating on it, but `$PATH` should only have directories to begin with.

Here is a workaround you can use for the time being, but it only silences the error. You may get this error again if another package, elsewhere, makes the same assumption about `exec-path` only containing directories.

```elisp
;;; add to $DOOMDIR/config.el
(defadvice! fixed-company-shell--build-cache (fn &rest args)
  :around #'company-shell--build-cache
  (let ((exec-path (cl-remove-if-not #'file-directory-p exec-path)))
    (apply fn args)))
```

Alternatively, you could switch to the `:completion corfu` module. At some point next year I intend to slowly phase out company module (and company-mode support, in general), so it might be wise to switch over eventually, in any case.

**Comment by sincebyte** [comment] 2025-04-25 01:42
thanks ,I think I’ve figured out what's happen.
`:completion corfu` I will try it.
