### ISSUE TITLE
In python-mode install python-pycompile

### ISSUE THREAD

**Issue by davidh38** [hlissner/doom-emacs#5118] opened 2021-05-31 10:35 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Not that error to occur.

### What actually happened?

```
    payload = """{
    ^
IndentationError: expected an indented block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/py_compile.py", line 209, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.8/py_compile.py", line 150, in compile
    raise py_exc
__main__.PyCompileError: Sorry: IndentationError: expected an indented block (loginProblemsAndCauses.py, line 156)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/py_compile.py", line 218, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/py_compile.py", line 213, in main
    if quiet < 2:
NameError: name 'quiet' is not defined

Try installing a more recent version of python-pycompile, and please open a bug report if the issue persists in the latest release.  Thanks!
SPC m e ESC is undefined

at code which states:
payload = """{
    "schemas": [
 """
```

### Describe your attempts to resolve the issue

installing python-pycompile with apt-get, which did not work

### Steps to reproduce

```
payload = """{
    "schemas": [
 """
```

in python-mode scroll up and down or do anything

### System Information

https://pastebin.com/dgDW8ZAf

**Comment by hlissner** [comment] 2021-05-31 15:09
Can't reproduce your issue. `pycompile` is included with python, nothing you can do but install a newer version of python 3. Despite the rest of the error message, it's telling you that it `expected an indented block` on the problematic line. Try fixing that.

Otherwise, add this to your config to disable pycompile as a syntax checker:

```elisp
(after! flycheck
  (add-to-list 'flycheck-disabled-checkers 'python-pycompile))
```

Because this is not a Doom issue so I will close it.

-----

In the future please learn how to use [code fences](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). Your output and code is unreadable otherwise.

**Closed by hlissner** 2021-05-31 15:09 UTC
Labels: delete me, invalid
