### ISSUE TITLE
WAI or Bug? "SPC m" in org mode is not localleader key.

### ISSUE THREAD

**Issue by pspencil** [hlissner/doom-emacs#4247] opened 2020-11-11 02:36 UTC
I am actually not sure if this is working as intended or a bug.

**What did you expect to happen?**
I set local leader key to ",". It works correctly in elisp mode. By working correctly, I mean:
- pressing "," triggers local leader bindings
- pressing "SPC m" is undefined.

**What actually happened?**
However, in org mode, all the "SPC m" bindings remains and "," is still mapped to evil-snipe repeat or something. 

**Additional details:**
- Include a link to your private config
  - https://github.com/pspencil/doom.d
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
 - "," is mapped to evil-snipe-repeat-reverse in org mode.
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
`(setq doom-localleader-key ",")`
Press "," in org mode.

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.19.154-1-MANJARO #1 SMP Fri Oct 30 10:25:08 UTC 2020 x86_64
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.emacs.d/bin/ /home/$USERpencil/perl5/bin ~/.local/bin /home/$USERpencil/perl5/bin ~/.local/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /bin /opt/google/chrome/ ~/go/bin ~/matlab/bin ~/.gem/ruby/2.7.0/bin ~/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /bin /opt/google/chrome/ ~/go/bin ~/matlab/bin ~/.gem/ruby/2.7.0/bin ~/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 7205b72 2020-11-06 21:16:04 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +fuzzy +icons) :ui doom doom-dashboard doom-quit fill-column hl-todo (ligatures +extra +hasklig) modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config literate (default +bindings +smartparens))
        packages   ((keyfreq) (org-bullets))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment] 2020-11-11 02:37
Working as intended. Duplicate of https://github.com/hlissner/doom-emacs/issues/4242

**Closed by hlissner** 2020-11-11 02:37 UTC
Labels: duplicate

**Comment by betaprior** [comment] 2020-11-20 08:44
@hlissner I believe this is NOT working as intended and is a regression. `,` as localleader works seems to work for all major modes I tried *except* org, but it used to work just fine there as well. Please reopen.

**Comment by pspencil** [comment] 2020-11-20 10:45
Actually, it seems to start working for me without me doing anything. I suspect an update fixes it but I am not sure.
