### ISSUE TITLE
doom upgrade failure with persp-mode.el

### ISSUE THREAD

**Issue by kprav33n** [hlissner/doom-emacs#4116] opened 2020-10-20 00:35 UTC
I ran `doom upgrade` and it fails to complete the upgrade due to an error with persp-mode.el

**What did you expect to happen?**
Upgrade to complete successfully.

**What actually happened?**
```
❯ ~/.emacs.d/bin/doom -d upgrade
- DEBUG=1
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    ✓ No packages need rebuilding
  > Updating recipe repos...
  > Updating packages (this may take a while)...
    > In repository "persp-mode.el", HEAD (on branch "remove-byte-compile") is ahead of branch "master"

         1) Abort
         2) Fast-forward branch "master" to HEAD

      How to proceed? (1, 2) 2
    > In repository "persp-mode.el", HEAD (on branch "remove-byte-compile") is ahead of branch "master"

         1) Abort
         2) Fast-forward branch "master" to HEAD

      How to proceed? (1, 2) 2
    > In repository "persp-mode.el", HEAD (on branch "remove-byte-compile") is ahead of branch "master"

         1) Abort
         2) Fast-forward branch "master" to HEAD

      How to proceed? (1, 2) 2
    > In repository "persp-mode.el", HEAD (on branch "remove-byte-compile") is ahead of branch "master"

         1) Abort
         2) Fast-forward branch "master" to HEAD

      How to proceed? (1, 2) 1

! Aborted

      ! Script was abruptly aborted! Run 'doom sync' to repair inconsistencies
```

**Additional details:**

```
❯ ~/.emacs.d/bin/doom version
Doom v2.0.9 (HEAD -> develop 9929883bf 2020-10-19 01:25:47 -0400)
```

```
❯ emacs --version
GNU Emacs 27.1
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**System information:**
<details><pre>
❯ ~/.emacs.d/bin/doom info
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.8.0-23-generic #24-Ubuntu SMP Fri Oct 9 16:32:13 UTC 2020 x86_64")
  (path "~/.nix-profile/bin" "~/anaconda3/condabin" "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/bin" "~/go/bin" "/snap/bin" "~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/snap/emacs/current/usr/libexec/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Aug 26, 2020")
  (buildopts . "--prefix= --prefix=/snap/emacs/current/usr --with-xwidgets --with-x-toolkit=gtk3 --without-xaw3d --with-modules --with-cairo 'CFLAGS= -isystem/build/emacs/parts/emacs/install/usr/include -O2' 'CPPFLAGS= -isystem/build/emacs/parts/emacs/install/usr/include' 'LDFLAGS= -L/build/emacs/parts/emacs/install/lib -L/build/emacs/parts/emacs/install/usr/lib -L/build/emacs/parts/emacs/install/lib/x86_64-linux-gnu -L/build/emacs/parts/emacs/install/usr/lib/x86_64-linux-gnu'")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 9929883bf 2020-10-19 01:25:47 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo ligatures modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor evil file-templates fold snippets :emacs dired electric ibuffer undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :os (tty +osc) :lang cc emacs-lisp (go +lsp) json markdown org python rst rust sh yaml :config (default +bindings +smartparens))
  (packages (wakatime-mode))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2020-10-20 00:38
Duplicate of #4038. See https://github.com/hlissner/doom-emacs/issues/4038#issuecomment-704121797

**Closed by hlissner** 2020-10-20 00:38 UTC
Labels: duplicate

**Comment by kprav33n** [comment] 2020-10-24 03:54
Thanks @hlissner. I confirm that the workaround mentioned by the comment in #4038 helped.
