### ISSUE TITLE
doom don't work ,Warning: Package cl is deprecated

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#4297] opened 2020-11-21 01:34 UTC
**System information:**
<details><pre>
```
SYSTEM  type       darwin
	config     x86_64-apple-darwin19.5.0
	shell      /bin/zsh
	uname      Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 x86_64
	path       (./bin ~/bin /usr/local/sbin ~/.dotfiles/bin /opt/homebrew/bin /usr/local/bin ~/hsg/flutter/bin ~/.pyenv/bin /usr/local/heroku/bin /go/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin ~/.emacs.d/bin /Applications/Emacs.app/Contents/MacOS/Emacs ~/hsg/hugo/dotfiles/swift-sh/bin /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Nov 14, 2020
	buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
	features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/hsg/hugo/iDoom.d/
	version    2.0.9
	build      grafted, HEAD -> develop, origin/develop, origin/HEAD 110d70b 2020-11-19 00:50:57 -0500
	elc-files  0
	modules    (:input chinese :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term shell :tools docker (eval +overlay) :checkers syntax spell :tools (lookup +docsets) lsp :os macos :tools (magit +forge) tmux upload :lang (cc +lsp) data emacs-lisp markdown (org +dragndrop +hugo +ipython +pandoc +pomodoro +present) plantuml sh (&user swift +lsp) :app (rss +org) :boyer (&user my-org) :config (default +snippets +bindings +commands +smartparens))
	packages   ((lsp-sourcekit) (swift-helpful) (swift-playground-mode))
	unpin      (n/a)
	elpa       (n/a)
```
</pre></details>

![截屏2020-11-21 上午9 33 05](https://user-images.githubusercontent.com/4022953/99864113-922aa580-2bdc-11eb-8464-e27bc8972655.png)

**Comment by hlissner** [comment] 2020-11-21 01:39
Duplicate of #3372.

Please us github search in the future.

**Closed by hlissner** 2020-11-21 01:39 UTC
Labels: duplicate

**Comment by iT-Boyer** [comment] 2020-11-21 02:52
I install emacs27 on Macmini ARM
```
arch -x86_64 brew tap d12frosted/emacs-plus
arch -x86_64 brew install emacs-plus
```
Is this warning causing the doom to fail to load?
Why is there no such information:
```
Doom loaded 222 packages across 50 modules in 9.230s
```

**Comment by hlissner** [comment] 2020-11-21 04:09
Try launching Emacs in debug mode: `emacs --debug-init`

**Comment by iT-Boyer** [comment] 2020-11-21 04:17
emacs --degbug-init
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "all$
  require(all-the-icons)
  eval-buffer(#<buffer  *load*-553830> nil "/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." n$
  load-with-code-conversion("/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." "/Users/boyer/.e$
  require(doom-modeline-core)
  eval-buffer(#<buffer  *load*> nil "/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." nil t)  $
  load-with-code-conversion("/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." "/Users/boyer/.e$
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
Package cl is deprecated
```

**Comment by hlissner** [comment] 2020-11-21 04:22
This means one of the needed packages are missing. Try deleting `~/.emacs.d/.local/straight/repo/all-the-icons` then run `doom sync`.

**Comment by iT-Boyer** [comment] 2020-11-21 04:38
YES,
1. I delete `all-the-icons.el` then run `doom sync`
```sh
$ ls ~/.emacs.d/.local/straight/repos/all-the-icons.el
Cask                   all-the-icons-faces.el fonts
LICENSE                all-the-icons.el       logo.png
README.md              data                   test
```
2. `emacs --debug-init`
print the same info:
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "all$
  require(all-the-icons)
  eval-buffer(#<buffer  *load*-553830> nil "/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." n$
  load-with-code-conversion("/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." "/Users/boyer/.e$
  require(doom-modeline-core)
  eval-buffer(#<buffer  *load*> nil "/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." nil t)  $
  load-with-code-conversion("/Users/boyer/.emacs.d/.local/straight/build-27.1/d..." "/Users/boyer/.e$
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
Package cl is deprecated
```

**Comment by iT-Boyer** [comment] 2020-11-21 04:46
I delete this cache:`~/.emacs.d/.local/straight/build-27.1` then `doom sync`.
this ok.
thanks.

**Comment by iT-Boyer** [comment] 2020-11-23 10:48
after update emacs27 ，the icon shows this way, I don't know what caused the error.
![截屏2020-11-23 下午6 40 49](https://user-images.githubusercontent.com/4022953/99953358-1dae5d00-2dbc-11eb-8517-2e38d09bc2c0.png)
