### ISSUE TITLE
Emacs 27.1 no longer able to open gpg encrypted files

### ISSUE THREAD

**Issue by krupalweb** [hlissner/doom-emacs#4948] opened 2021-04-29 17:42 UTC
**What did you expect to happen?**

Open a fileName.gpg to prompt me to enter password

**What actually happened?**

`epg-context--make: GPG error: "no usable configuration", OpenPGP`

**Additional details:**

**Steps to reproduce:**
1. Debian 10 - upgrade Emacs from 26.1 to 27.1 using buster-backports
2. Try to open a gpg encrypted file.
3. The above error occurs.

**System information:**

<details>

```
emacs   version    27.1
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Feb 09, 2021
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-cairo --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/emacs/emacs=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, tag: kcOldPoint, origin/develop, origin/HEAD 578e7f068 2020-07-14 00:08:27 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.10.0-0.bpo.5-amd64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64
        path       (~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/games /usr/games /usr/lib/emacs/27.1/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs (dired +ranger) undo vc :term eshell :checkers syntax spell :tools (eval +overlay) lookup magit pdf :lang cc common-lisp emacs-lisp latex ledger lua markdown (org +roam +gnuplot) python sh :config (default +bindings +smartparens))
        packages   ((org-edna) (calfw) (calfw-org) (calfw-cal) (writeroom-mode) (jupyter) (lsp-mode) (lsp-ui) (lsp-ivy) (helm-lsp))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2021-04-29 17:55
I cannot reproduce this on 26.3 or 27.1, on Arch, NixOS, or macOS. I don't have a debian machine/VM to test this on at the moment. 

I will close this until I have more leads or a reason to suspect this is a Doom issue and not a GPG configuration issue.

**Closed by hlissner** 2021-04-29 17:55 UTC
Labels: status:unknown

**Comment by krupalweb** [comment] 2021-04-29 18:19
Hi, thanks for getting back!

The files are symmetrically encrypted. It was definitely working with no epg specific configs in my private config before upgrading emacs 27.1 and now it isn't.

Just ran  `emacs -q` and the problem persists. So I believe now that this is not a Doom issue. This is such a frustrating situation, there's barely any information anywhere across the web pertaining to this. I've tried using epg-config.elc from the old version, changing epg-gpg-program nothing's working.
