### ISSUE TITLE
Continuation of #4759, save-place-find-file-hook don't behave correctly

### ISSUE THREAD

**Issue by HyunggyuJang** [hlissner/doom-emacs#4774] opened 2021-03-11 00:28 UTC
**What did you expect to happen?**
After `saveplace` got loaded, I expected `save-place-find-file-hook` to be added to `find-file-hook`.

**What actually happened?**
Please refer https://github.com/hlissner/doom-emacs/issues/4759#issuecomment-794654891

**Additional details:**
```elisp
(after! saveplace
  (add-hook 'find-file-hook 'save-place-find-file-hook t))
```
will do the job for me; yet it is an impromptu solution.

**Steps to reproduce:**
1. Put the following debugging code to your private config.el
   ```elisp
   (defadvice! does-it-run? (&rest _)
     :before #'save-place-find-file-hook
     (message "It ran in %s!" (current-buffer)))
   ```
2. Close your doom instance and re-open it.
3. Launch Org agenda by hitting `SPC n a a`
4. Now `save-place-find-file-hook` is nowhere in `find-file-hook`
   The debug code doesn't emit message anymore afterwards even if visit files not yet loaded as buffers.

**System information:**

https://pastebin.com/76Tptzfr

**Comment by hlissner** [comment] 2021-03-11 00:33
Duplicate of #4759

**Closed by hlissner** 2021-03-11 00:33 UTC
Labels: duplicate
