### ISSUE TITLE
Doom sync/build consumes all system resources

### ISSUE THREAD

**Issue by skrat** [hlissner/doom-emacs#6137] opened 2022-02-21 02:53 UTC
### What did you expect to happen?

I should be able to put the process in background with Ctrl-Z and resume when I go to bed because the system is unusable while it is "Natively compiling 1820 files..."

I suggest you either make it use just one CPU per default, or at least make it suspendable. Please excuse the tone but it's truly infuriating to have my workstation disabled for 1+ hours. Thank you

### What actually happened?

System un-responsive for 1+ hour

### Describe your attempts to resolve the issue

Ctrl+Z

### Steps to reproduce

```doom build```

### System Information

https://pastebin.com/ytdbbRun

**Comment by hlissner** [comment] 2022-02-21 02:58
You can change how many cores are used by setting the `NUMBER_OF_PROCESSES` envvar. e.g. 

```sh
NUMBER_OF_PROCESSORS=1 doom sync
```

Or by throwing this into `~/.doom.d/init.el`:

```elisp
(setq native-comp-async-jobs-number 1)
```

I'm working on a rewrite of the CLI as part of #4273, which will introduce some switches to control it in the future. As such as I'll consider this a duplicate of that issue and close this one.

**Closed by hlissner** 2022-02-21 02:58 UTC
Labels: duplicate
