### ISSUE TITLE
doom sync - Could not find package org-superstar

### ISSUE THREAD

**Issue by FranciscoJRSantos** [hlissner/doom-emacs#3326] opened 2020-06-07 18:21 UTC
**What did you expect to happen?**
I expected dooms-emacs to sync.

**What actually happened?**
An error occurred reporting "Could not find package org-superstar in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)"

<img width="1235" alt="Screenshot 2020-06-07 at 19 14 12" src="https://user-images.githubusercontent.com/25421850/83976712-95aec680-a8f3-11ea-8772-7bb9ce1b74b5.png">

**System information:**

<img width="1436" alt="Screenshot 2020-06-07 at 19 15 56" src="https://user-images.githubusercontent.com/25421850/83976704-892a6e00-a8f3-11ea-806e-5904de6909a4.png">

**Notes**
I apologize if this is not an actual bug, but instead a product of my inability to debug doom 😬

**Comment by hlissner** [comment] 2020-06-07 18:29
This is a duplicate of #3320, #2909 ad #2802. See https://github.com/hlissner/doom-emacs/issues/2802#issuecomment-606654151 for workaround.

Github's issue tracker has a search bar, by the way:

![image](https://user-images.githubusercontent.com/510883/83976947-4e144480-a8cb-11ea-870c-eecc1d1a1402.png)

**Closed by hlissner** 2020-06-07 18:29 UTC
Labels: is:duplicate
