### ISSUE TITLE
Could not install some packages during `make install`

### ISSUE THREAD

**Issue by BenJWard** [hlissner/doom-emacs#606] opened 2018-05-23 15:11 UTC
### Observed behavior

When I tried to install doom-emacs with make install on my OSX system, several packages could not
be installed:

```sh
N82106:.emacs.d bward$ make install
Looking for packages to install...
8 packages will be installed:

+ auth-password-store (ELPA)
+ centered-window-mode (ELPA)
+ emacs-snippets (QUELPA)
+ help-fns+ (ELPA)
+ ob-redis (ELPA)
+ org-plus-contrib (QUELPA)
+ ox-reveal (ELPA)
+ php-extras (QUELPA)

Proceed? (y or n) y
Installing emacs-snippets
  FATAL ERROR: (wrong-type-argument) Wrong type argument: arrayp, nil
Installing php-extras
  FATAL ERROR: (wrong-type-argument) Wrong type argument: arrayp, nil
Installing ox-reveal
  FATAL ERROR: (error) Need package ‘org-20150330’, but only 9.1.13 is available
Installing centered-window-mode
  FATAL ERROR: (error) Package ‘centered-window-mode-’ is unavailable
Installing ob-redis
  FATAL ERROR: (error) Package ‘ob-redis-’ is unavailable
Installing org-plus-contrib
  FATAL ERROR: (wrong-type-argument) Wrong type argument: arrayp, nil
Installing auth-password-store
  FATAL ERROR: (error) Package ‘auth-password-store-’ is unavailable
Installing help-fns+
  FATAL ERROR: (error) Package ‘help-fns+-’ is unavailable
Finished!
```

### Expected behavior

For all packages to be installed.

### Steps to reproduce

```sh
# Fresh install of emacs...
rm -rf .emacs.d .spacemacs.d
rm .spacemacs .emacs
brew reinstall emacs-plus
brew link --overwrite emacs-plus
git clone https://github.com/hlissner/.emacs.d ~/.emacs.d
cd .emacs.d
make install
```

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.1, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /bin/zsh
Compiled with:
  JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB
  TOOLKIT_SCROLL_BARS NS MODULES
uname -a:
  Darwin N82106 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar 5 22:24:32
  PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

----

test-emacs
test-windows
test-fonts
Warning: couldn’t find material-design-icons.ttf font in /Users/bward/Library/Fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find weathericons.ttf font in /Users/bward/Library/Fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find octicons.ttf font in /Users/bward/Library/Fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find fontawesome.ttf font in /Users/bward/Library/Fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find file-icons.ttf font in /Users/bward/Library/Fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find all-the-icons.ttf font in /Users/bward/Library/Fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Warning: BSD tar detected
  QUELPA (through package-build) uses the system tar to build plugins,
  but it expects GNU tar. BSD tar *could* cause errors during package
  installation or updating from non-ELPA sources. MacOS users can
  install gnu-tar via homebrew: brew install gnu-tar

----
There were issues!

Hopefully these can help you find problems. If not, run this doctor again with DEBUG=1:

  DEBUG=1 make doctor

And file a bug report with its output at https://github.com/hlissner/.emacs.d/issues
```
</details>

**Comment by hlissner** [comment] 2018-05-23 18:59
This is a duplicate of #494. 

Please switch to develop (and don't forget to copy the new init.example.el). These issues have been fixed and are due to be merged into master soon.

**Closed by hlissner** 2018-05-23 18:59 UTC
