### ISSUE TITLE
`+term/toggle` issue with Emacs keybindings popup

### ISSUE THREAD

**Issue by intpl** [hlissner/doom-emacs#1485] opened 2019-06-12 13:24 UTC
`+term/toggle` is broken in my setup. whenever I open it and press space so the Emacs keybindings list popup shows up, it breaks and I cannot close it (the popup). I personally remapped it back to `+term/here`, because the other one is crippled. this happens in `term`, don't know about `eshell` or `vterm` 

steps to reproduce:
1. SPC o t
2. SPC -> [wait...] -> keybindings popup shows up
4. Try to close it <-- issue

having that said, I absolutely love your work! i use Doom for a couple of months now and love it. keep up the good work :)

env:
Linux Ubuntu
Emacs 27.0.50 compiled with flags: --with-modules --with-mailutils

**Comment by hlissner** [comment] 2019-06-12 14:57
I can't reproduce this, unless I add a step in between steps 1 and 2: press ESC to switch away from insert state to normal state, but then this is expected behavior. In normal mode, SPC is the default leader key.

Could you supply your `M-x doom/info`?

**Comment by intpl** [comment] 2019-06-12 15:14
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 27.0.50 (cze 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD b1ecd683 2019-06-11 18:11:51 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) tabbar treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term term :tools direnv editorconfig eval flycheck flyspell (lookup +docsets) magit pdf rgb tmux upload :lang common-lisp crystal data erlang elixir emacs-lisp go (haskell +intero) javascript markdown (org +attach +babel +capture +export +habit +present +protocol) php python rest ruby rust (sh +fish) web :config default)
  packages:  (rvm robe yari goto-gem projectile-rails ruby-tools company-tabnine auto-complete zoom graphql-mode graphql company-flx evil-anzu (evil-snipe :disable t) (solaire-mode :disable t) (forge :disable t) (evil-escape :disable t))
  exec-path: (~/.rvm/rubies/ruby-2.5.3/bin/ ~/.rvm/gems/ruby-2.5.3/bin ~/.rvm/gems/ruby-2.5.3@global/bin ~/.rvm/rubies/ruby-2.5.3/bin ~/.cargo/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.rvm/bin /usr/local/libexec/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```

thanks for replying so quickly. I forgot about mentioning ESC. what do you mean it is expected behavior? it ruins everything and i have to restart Emacs. how do I exit when i want to cancel command after typing something? Ctrl-g does not work. and even when I properly execute a command, the popup window stays there. i do copy-paste, searching with regexp, traversing buffer etc in normal mode inside terminal window and i want to be able to use normal mode there.

**Comment by hlissner** [comment] 2019-06-12 17:07
So the problem is you can't close the popup? Do none of these methods work?

- Press `SPC o t` again (while the popup is selected)
- `C-w c` (`delete-window`)
- `zx` (`kill-current-buffer`)
- Typing `exit` in your shell and press enter

**Comment by intpl** [comment] 2019-06-12 20:48
> So the problem is you can't close the popup? 
Exactly

> Do none of these methods work?
first three methods give me this error: 
```Window #<window 10 on *which key*> has the same size bottom as window #<window 8 on *doom:term-popup> but no common parent```

last one (just 'exit' from term') brings this (different window numbers even though everything is the same):
```error in process sentinel: Window #<window 8 on *which-key* has same side bottom as window #<window 6 on *doom:term-popup*> but no common parent```

problem remains and i have to restart emacs

also, here is my configuration directory, but i can't think of anything that could had influence on this error: https://github.com/intpl/.doom.d

i also have error in startup of Doom:
```Error in Doom startup hook: doom|init-theme, (void-function make-xpm)```
but i guess that's something unrelated?

**Comment by hlissner** [comment] 2019-06-12 21:59
c9305a5 should fix your void-function make-xpm error. It's never a good idea to debug an issue when other errors exist. 

However, I still cannot reproduce these errors. Please update and see if c9305a5 somehow fixes your window closing issue as well.

**Comment by intpl** [comment] 2019-06-13 06:37
updated, issue seems to be fixed. thank you very much!
i also reported something new i noticed: https://github.com/hlissner/doom-emacs/issues/1487

**Closed** 2019-06-13 07:28 UTC
Labels: is:bug, module:emacs:term, re:interface, status:resolved-indirectly
