### ISSUE TITLE
Running doom sync -u causes error: RPC failed; curl 18 transfer closed

### ISSUE THREAD

**Issue by ribaricplusplus** [hlissner/doom-emacs#4366] opened 2020-12-03 22:47 UTC
Hello,

First of all thank you for creating Doom Emacs, it's awesome. I am new to Doom Emacs and I'm sorry if I'm doing something silly incorrectly.

**What did you expect to happen?**
Expected to sync up the configuration after making changes to `.doom.d/init.el` with `doom sync -u`.

**What actually happened?**
Got an error when running `doom sync -u`.
But just `doom sync`  worked fine when no repositories had to be fetched.

![Screenshot](https://user-images.githubusercontent.com/43731400/101097317-45be6d00-35c1-11eb-8937-bf553bc107e3.png)

**Additional details:**

My `init.el` file: https://gist.github.com/ribaricplusplus/9c88401eaa2c9510106b6a6e10bc15c8
My `config.el` file: https://gist.github.com/ribaricplusplus/ea0d8f7c574c8cb3d688bf7e9649e001
`.emacs.d/.local/doom.error.log`: 
[doom.error.log](https://github.com/hlissner/doom-emacs/files/5639382/doom.error.log)

**System information:**

git v2.29.2

<details><pre>
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/bash
	uname      Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64
	path       (~/.emacs.d/bin /sbin ~/.cargo/bin ~/.config/composer/vendor/bin ~/.cargo/bin ~/.emacs.d/bin /sbin ~/.nvm/versions/node/v14.12.0/bin ~/.cargo/bin ~/.config/composer/vendor/bin /usr/local/bin /usr/bin /bin /usr/local/games /usr/games /usr/lib/emacs/27.1/x86_64-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Nov 08, 2020
	buildopts  --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-cairo --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-6jKC2B/emacs-27.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      grafted, HEAD -> develop f622d51 2020-12-01 18:09:43 -0500
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools editorconfig (eval +overlay) lookup lsp magit :lang cc emacs-lisp (json +lsp) (javascript +lsp) markdown org (php +lsp) sh (web +css +html) yaml :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (s dash-functional dash ag)
```
</pre></details>

**Comment by hlissner** [comment] 2020-12-03 22:54
This is simply a networking issue. The connection dropped due to external factors: a poor connection? Server went down? Hard to guess, but I'm afraid the only thing you can do is try again.

**Comment by ribaricplusplus** [comment] 2020-12-03 23:01
Thank you for the quick response.

My network is fine so if network is the problem I guess it must be one of the servers that packages are being fetched from.

I'll try to investigate further.

**Comment by RyanGreenup** [comment] 2020-12-04 01:07
I’m having the same issue; so if you figure it out I’d really appreciate it if you could post back.

**Comment by hlissner** [comment] 2020-12-04 01:10
Do either of you have a `~/.curlrc` file
? You may have some incompatible setting in it if you do.

**Comment by hlissner** [comment] 2020-12-04 01:12
Or. .gitconfig file with an `insteadOf` rule for rerouting HTTPS git urls to SSH?

**Comment by danielgolf** [comment] 2020-12-04 01:53
I experienced the same issue right now. I have neither a special curl or git setting.

**Comment by flatwhatson** [comment] 2020-12-04 01:54
I'm also experience this problem, no `.curlrc` and nothing relevant to connectivity in `.gitconfig`.

Running `doom -d sync -u` it's clear that the failure occurs intermittently, failing on a different repo on repeated runs.  Running `git fetch origin` a few times manually in the repo directory shows the same behavior with intermittent failures.

I'm not sure there's much doom could do here, except perhaps implement some high-level retry mechanism?

**Comment by ribaricplusplus** [comment] 2020-12-04 03:57
I "fixed" it by running
~~~
 for (( i=0 ; 20 - i ; ++i )); do doom sync; sleep 5; done
~~~
And going off doing something else for a while.

**Comment by RyanGreenup** [comment] 2020-12-04 07:01
> Or, a `.gitconfig` file with an `insteadOf` rule rerouting HTTPS git urls to SSH?

No, I don't.

**Comment by zeronone** [comment] 2020-12-04 09:24
Using old version of `git` helped in my case.

**Comment by danielgolf** [comment] 2020-12-04 09:28
Downgrading git is actually a bad option. At least not persistent - But maybe this is an important hint: could that issue be related to any particular git cli options used by doom?

**Comment by Sarkosos** [comment] 2020-12-04 12:35
Same issue but with trying to install doom using ` ~/.emacs.d/bin/doom install`.

**Comment by utrack** [comment] 2020-12-04 16:18
(almost) same here: 
```
.emacs.d on develop .‍
❯ bin/doom upgrade                                                                                                                         2020-12-04 19:18:37
> Preparing to upgrade Doom Emacs and its packages...
x There was an unexpected error
  Message: error
  Data: (error . "Failed to fetch from upstream")
  Backtrace:
    (signal error ("Failed to fetch from upstream"))
    (error "Failed to fetch from upstream")
    (doom-cli-upgrade nil nil)
    (#[257 "\302\236A\303\236A\211\203 \304\305\306\"\210\307\310\31
    (funcall #[257 "\302\236A\303\236A\211\203 \304\305\306\"\210\30
    (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-ta
    (let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (
    (doom-cli-execute "upgrade")
    (apply doom-cli-execute "upgrade" nil)
    (if (apply #'doom-cli-execute command args) (progn (run-hooks 'doom-cli-po
! Extended backtrace logged to .local/doom.error.log
```

**Comment by ribaricplusplus** [comment] 2020-12-04 18:27
My git version is 2.29.2

**Comment by danielgolf** [comment] 2020-12-04 18:36
`doom sync -u` worked for me two, a few seconds ago. But `doom upgrade` is still throwing an error.

**Comment by hlissner** [comment] 2020-12-04 20:20
> could that issue be related to any particular git cli options used by doom?

Unlikely. If it were the case, reports would be much more consistent and it'd be an issue for [straight.el](https://github.com/raxod502/straight.el#the-recipe-format) too (which does 99% of the heavy lifting with `git`), but I don't see any open issues for them.

> Maybe we can reopen this issue? Until it is solved?

I don't think this is something Doom can address. I suspect it's weirdness on github or gitlab's end (possibly a CDN failure). At the very least, all reports (between here and Discord) are too consistently inconsistent for me to suspect anything but a networking issue -- nor can I reproduce it.

Most folks get around it by trying until it works. Worst case scenario it half-downloads a package update, leaving it in a broken state ([something already being worked on elsewhere](https://github.com/hlissner/doom-emacs/issues/4273)), in which case you'll need to delete the package by hand in `~/.emacs.d/.local/straight/repos/PACKAGE` and rerun `doom sync`.

Otherwise, afraid there's little I can do here, but we can leave it open until a new lead comes to light or the issue goes away.

**Comment by hlissner** [comment] 2020-12-04 20:22
> In repository "emacs-websocket", HEAD (on branch "master") is ahead of default branch "main"

@RyanGreenup This is an unrelated issue. See https://github.com/hlissner/doom-emacs/issues/3435

**Comment by RyanGreenup** [comment] 2020-12-04 22:19
> I just sucessfully executed `doom up` after experiencing the `RPC failed; curl 18 [...]` issue for the last 12 hours or so.

Yeah same here, deleting `~/.emacs.d` and then reinstalling from scratch works now, seemingly a server/cdn was down yesterday.

<details><pre>
rm -rf ~/.emacs.d
git clone https://github.com/hlissner/doom-emacs
~/.emacs.d/bin/doom install
</pre><details>

**Comment by hlissner** [comment] 2020-12-11 07:15
Seems the issue has disappeared. Since this is most likely a github/gitlab issue, I will close this.

**Closed by hlissner** 2020-12-11 07:15 UTC
Labels: re:networking, re:packages, status:unknown
