### ISSUE TITLE
Error loading hook "js"

### ISSUE THREAD

**Issue by CGenie** [hlissner/doom-emacs#5184] opened 2021-06-16 17:08 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

I expect `*.js` files to open with no errors.

### What actually happened?

When opening a `*.js` file, I get the following message:

```
Error (js-mode-hook): Error running hook "js" because: (error Autoloading file /usr/share/emacs/27.2/lisp/progmodes/js.elc failed to define function js)
```

### Steps to reproduce

Just open any `*.js` file.

### System Information

https://ynh.mmksoft.uk/privatebin/?b9ce1ed102dd6270#AEq4gktAJ8JhuwYvKpEr3mAuQQc4snkNDkY63LySRkTy

**Comment by hlissner** [comment] 2021-07-08 18:38
1. I can't reproduce your issue.
2. 1. Can't see your system info. Please use pastebin and only pastebin, as its pastes never expire.
3. Please [provide a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error), as was requested in the issue template.

I have marked this as incomplete and closed this because it is too little information to act on. I will reopen it if/when that changes.

**Closed by hlissner** 2021-07-08 18:38 UTC
Labels: 1. bug, incomplete
