### ISSUE TITLE
Files in docs/ directory referenced from README.md are missing

### ISSUE THREAD

**Issue by zakkak** [hlissner/doom-emacs#1861] opened 2019-10-08 22:07 UTC
More specifically the following links are all broken in `develop`.

```
[docs:wiki]: docs/index.org
[docs:wiki-quickstart]: docs/getting-started.org
[docs:wiki-modules]: docs/modules.org
[docs:wiki-customization]: docs/customize.org
[docs:contributing]: docs/contribute.org
[docs:faq]: docs/faq.org
```

I see that some of the referenced files match those of the wiki.
Is there anyway I could help with that?

**Comment by hlissner** [comment] 2019-10-08 22:50
This is a duplicate of #1755, #1856 and #1771. My apologies for the current state of the documentation -- I'm aware of the broken links, but am waiting until I finish the new documentation to fill it out.

**Closed by hlissner** 2019-10-08 22:50 UTC
Labels: is:duplicate
