### ISSUE TITLE
[regression] unable to rebind evil-repeat-find-char-reverse without disabling evil-snipe

### ISSUE THREAD

**Issue by betaprior** [hlissner/doom-emacs#4291] opened 2020-11-20 08:15 UTC
**What did you expect to happen?**

Before 77fbde957 it was possible to rebind repeated search movements for searches aliased by evil-snipe (e.g., `f/F`).

**What actually happened?**

It is very common to bind `,` as `doom-localleader-key`. However, this breaks `evil-repeat-find-char-reverse` unless rebound to a different key. This, however, fails to work because of evil-snipe overrides. So currently you have to pick two out of three behaviors (use comma as localleader, use evil-snipe, have working repeat-find-char-reverse), which is unfortunate, since these are all pretty commonly used. A workaround is to paste the code removed in 77fbde957 into a personal config, but this of course is ugly.

**Comment by hlissner** [comment] 2020-11-21 01:28
Duplicate of #4242

**Closed by hlissner** 2020-11-21 01:28 UTC
Labels: duplicate
