### ISSUE TITLE
Problems with certificates and vterm when upgrading

### ISSUE THREAD

**Issue by simonallfrey** [hlissner/doom-emacs#6064] opened 2022-01-30 15:37 UTC
### What did you expect to happen?

I run doom upgrade, it upgrades without ssl certificate errors and vterm compiles automatically on first usage 

### What actually happened?

The upgrade hangs at:

 fatal: unable to access 'https://codeberg.org/joostkremers/visual-fill-column.git/': server certificate verification failed. CAfile: none CRLfile: none
        [Return code: 128]

(and later, when I resolved this)
vterm-module-compile hangs with no output

### Describe your attempts to resolve the issue

The certificate problem is resolved with:

git config --global http.sslverify false

vterm-module.so can be compiled separately from doom installation directory:

cd .local/straight/build-29.0.50/vterm/build
cmake ..
make

### Steps to reproduce

run doom upgrade

M-x vterm

### System Information

https://pastebin.com/J8ggNeVc

**Comment by hlissner** [comment] 2022-01-30 17:09
Unfortunately, this is not a Doom issue. It seems like an issue with your local CA certificates. I cannot reproduce the issue so I'm afraid I can't advise further. In any case, since this cannot be addressed on Doom's end I will close this.

**Closed by hlissner** 2022-01-30 17:09 UTC
Labels: invalid, delete me
