### ISSUE TITLE
[BUG] Error in post-command-hook (+doom-dashboard-reposition-point-h): (user-error "No more buttons")

### ISSUE THREAD

**Issue by graves** [hlissner/doom-emacs#2024] opened 2019-11-07 15:41 UTC
**Describe the issue**
Upon enabling python mode in init.el, running doom refresh, and opening any new file I am unable to edit the file. Pressing "i" (insert) gives the error in the title.

`condition-case: Error in a Doom startup hook: +doom-dashboard-init-h, (error "fancy-battery is not a defined segment")
Loading /home/luvshrimps/.emacs.d/.local/cache/recentf...done
evil-forward-char: End of buffer
Error in post-command-hook (+doom-dashboard-reposition-point-h): (user-error "No more buttons")
evil-backward-char: Beginning of buffer
evil-signal-at-eob: End of buffer`

is what i see in the view-echo-area-messages.

<details><pre>
Debugger entered--Lisp error: (error "fancy-battery is not a defined segment")
  signal(error ("fancy-battery is not a defined segment"))
  error("%s is not a defined segment" fancy-battery)
  doom-modeline--prepare-segments((misc-info mu4e github debug fancy-battery " " major-mode process))
  doom-modeline-def-modeline(project (bar window-number buffer-default-directory) (misc-info mu4e github debug fancy-battery " " major-mode process))
  (progn (use-package-statistics-gather :config (quote doom-modeline) nil) (defvar mouse-wheel-down-event nil) (defvar mouse-wheel-up-event nil) (size-indication-mode 1) (column-number-m$
  (closure (t) nil (progn (use-package-statistics-gather :config (quote doom-modeline) nil) (defvar mouse-wheel-down-event nil) (defvar mouse-wheel-up-event nil) (size-indication-mode 1)$
  eval-after-load-helper("/home/luvshrimps/.emacs.d/.local/straight/build/doom-modeline/doom-modeline.elc")
  run-hook-with-args(eval-after-load-helper "/home/luvshrimps/.emacs.d/.local/straight/build/doom-modeline/doom-modeline.elc")
  do-after-load-evaluation("/home/luvshrimps/.emacs.d/.local/straight/build/doom-modeline/doom-modeline.elc")
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
</pre></details>

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XAW3D XPM JPEG TIFF GIF PNG SOUND NOTIFY GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM THREADS")
  (build . "Oct 16, 2019")
  (buildopts "")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 957e1dd08 2019-10-15 22:24:57 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 4.19.60-06185-g54aa50936831 #1 SMP PREEMPT Wed Aug 14 01:17:34 PDT 2019 x86_64")
  (path "~/.config/versions/node/v10.16.3/bin" "~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/local/games" "/usr/sbin" "/usr/bin" "/usr/games" "/sbin" "/bin" "~/.local/bin" "~/.emacs.d/bin" "/usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric vc :tools eval flycheck (lookup +docsets) lsp magit :lang data emacs-lisp markdown python (rust +lsp) sh :app irc :config (default +bindings +smartparens))
  (packages treemacs-evil treemacs-projectile treemacs-magit treemacs-icons-dired doom-themes gist)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2019-11-07 17:51
This is a duplicate of #1951. The `+doom-dashboard-reposition-point-h` is a smokescreen. The real cause is the earlier error: `(error "fancy-battery is not a defined segment")`. See #1951 for a solution.

**Closed by hlissner** 2019-11-07 17:51 UTC
Labels: is:duplicate
