### ISSUE TITLE
[BUG] :ui popup causes bug with racket--send-to-definition

### ISSUE THREAD

**Issue by Herbsi** [hlissner/doom-emacs#2096] opened 2019-11-21 18:10 UTC
Using `:ui popup` together with `racket-mode` causes buggy behavior when updating a definition via `racket-send-definition`.

Instead of updating the definition, I get an error message and the function now does not work in the Racket REPL anymore.

The issue disappears when I disable `:ui (popup +all +defaults)` in my `init.el` and run `doom re`. 

There's also an issue open at the `racket-mode` github. [Link.](https://github.com/greghendershott/racket-mode/issues/407)

<details><pre>
Debugger entered--Lisp error: (args-out-of-range #<buffer *Racket REPL*> 20 68)
  process-send-region(#<process Racket REPL> 20 68)
  comint-send-region(#<process Racket REPL> 20 68)
  racket--send-region-to-repl(20 68)
  racket-send-definition(nil)
  funcall-interactively(racket-send-definition nil)
  call-interactively(racket-send-definition nil nil)
  command-execute(racket-send-definition)
</pre></details>

**Steps to reproduce**
1. Open a file
For example:

```racket
#lang racket

(define (hello-world)
    (print "hello, world"))
```

2. Run racket-run
This opens the REPL and executing `(hello-world)` prints "hello, world".

3. Change the definition of `(hello-world)` to
```racket
(define (hello-world)
    (print "hello, world!"))
```
4. Execute `(racket-send-definition)` with the point inside the parenthesis of `define`.

5. Receive `Args out of range: #<buffer *Racket REPL#>, 20, 68.

Trying `(hello-world)` in the REPL now does nothing.

In `*Messages*` the following error shows up: `comint-send-region: Args out of range: #<buffer *Racket REPL*>, 20, 68`.

**System information**
<details><pre>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Nov 20, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/Users/herwig/.brew/share/emacs/site-lisp --infodir=/Users/herwig/.brew/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/Users/herwig/.brew/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 83090894d 2019-11-21 00:50:25 -0500
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
        path       (~/.brew/bin/ ~/.local/bin/ ~/.brew/sbin/ ~/.emacs.d/bin/ ~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/share/dotnet/ ~/.dotnet/tools/ /usr/local/MacGPG2/bin/ ~/.emacs.d/bin/ ~/.emacs.d/cask/bin/ ~/.local/share/cargo/bin/ ~/.local/share/pyenv/shims/ ~/.local/share/pyenv/bin/ /usr/local/sbin/ ~/.dotfiles/bin/ ~/.local/share/dotfiles/base.macos.topic/bin/ ~/.local/share/dotfiles/shell.git.topic/bin/ ~/.brew/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.7.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) (ivy +childframe +fuzzy) :ui doom doom-dashboard doom-quit fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) lispy multiple-cursors rotate-text snippets :emacs (dired +icons) electric vc :term eshell :tools debugger editorconfig eval flycheck flyspell (lookup +docsets) lsp macos magit :lang (cc +lsp) common-lisp data emacs-lisp (haskell +lsp) latex (org +dragndrop +ipython) python racket (rust +lsp) (sh +fish) :config (default +bindings +evil-commands))
        packages   (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment] 2019-11-21 19:12
Can you reproduce this in vanilla Emacs? (see https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox for how)

**Comment by Herbsi** [comment] 2019-11-22 11:21
How do I enable just `:ui popup` in Vanilla Emacs?

Running `doom/sandbox`, then `(require 'racket-mode)` and finally the steps outlined above do not reproduce the issue for me.

**Comment by greghendershott** [comment] 2019-11-22 20:41
Hi, Racket Mode author here.

I'm only skimming [the popup README](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/popup/README.org) but I noticed mention of `display-buffer-alist` as well as the second example "popup rule" `("^\\*" :select t)`. Does that mean that anytime `display-buffer` is called, not only will the buffer be displayed in a window, but it will also change the currently selected window to that?

If so, that might explain the problem? Racket Mode uses `comint-send-region` which calls `process-send-region` to copy some text from the selected `.rkt` buffer to the `*Racket REPL*` comint buffer. `process-send-region` takes the _target_ process/buffer as an argument. The _source_ is not specified; it is the selected window's buffer.

Something else Racket Mode does, is display the REPL and move to the end of the buffer, _before_ the send-region.

So if Doom Emacs is causing the "display" to mean "display and also select", that might explain this?

@Herbsi what if you try adding a [`set-popup-rule!`](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/popup/README.org#configuration) to exclude `"*.rkt"` buffers? I'm not sure the exact syntax but maybe @hlissner could help with that?

---

[I suppose I could also look at changing Racket Mode to do the `display-buffer` _after_ the `comint-send-region`. That would probably avoid this problem. OTOH this is the first such issue in many years, and, I don't know if that might cause some other, new problem(s).]

**Comment by greghendershott** [comment] 2019-11-22 21:19
@Herbsi Alternatively I just [commented](https://github.com/greghendershott/racket-mode/issues/407#issuecomment-557697970) with a potential little patch you could try if you're comfortable.

**Comment by hlissner** [comment] 2019-11-23 00:20
> Does that mean that anytime display-buffer is called, not only will the buffer be displayed in a window, but it will also change the currently selected window to that?

@greghendershott Only if the buffer's name starts with an asterix.

> what if you try adding a set-popup-rule! to exclude "*.rkt" buffers? I'm not sure the exact syntax but maybe @hlissner could help with that?

That should work. @Herbsi give this a try:

```elisp
(after! racket-mode
  (set-popup-rule! "^\\*Racket REPL\\*" :select #'ignore))
```

While the `(after! racket-mode ...)` isn't strictly necessary at this time, I may add this (or another popup rule) to the `:lang racket` module. If/when I do so, the `after!` will ensure your rule has precedence over mine (principle of least surprise).

**Comment by Herbsi** [comment] 2019-11-23 07:17
> ```
> (after! racket-mode
>  ;; Passing `#'ignore` to `:select` tells the popup manager to not do any focus
> ;; management. `nil` would focus the origin window while `t` would focus the
>  ;; new popup window.
>  (set-popup-rule! "^\\*Racket REPL\\*" :select #'ignore))
> ```

@hlissner The popup rule did not fix my issue, but @greghendershott 's "patch" did.

**Comment by greghendershott** [comment] 2019-11-26 20:40
@hlissner It looks like I'll be able to fix this in Racket Mode itself, e.g. [this commit](https://github.com/greghendershott/racket-mode/commit/914c73ecd1166c9bc4fa227bb7051c87ade0030b). It seems reasonable to fix it on my end -- I just didn't realize that `display-buffer` could possibly also change the selected window and current buffer; now I know. So unless @Herbsi disagrees you could probably close this issue here.

**Comment by Herbsi** [comment] 2019-11-27 07:05
[The commit](https://github.com/greghendershott/racket-mode/commit/914c73ecd1166c9bc4fa227bb7051c87ade0030b) fixes the issue for me, so I have no problem with closing this issue.

**Closed** 2019-12-02 08:29 UTC
Labels: :lang racket, :tools eval, :ui popup, help wanted, status:investigating
