### ISSUE TITLE
doom successfully installs `all-the-icons.el` but couldn't sync: forces me to select abort

### ISSUE THREAD

**Issue by Dentrax** [hlissner/doom-emacs#5158] opened 2021-06-09 07:25 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Since doom installed the target font successfully at:
```
$ ls  /Users/furkan.turkal/Library/Fonts/

all-the-icons.ttf
...
```
... doom sync shouldn't have error out: `In repository "all-the-icons.el", failed to get status`?

And forces me to select `Abort`, since there is no other choice:
```
1) Abort

        How to proceed? (1)
```

### What actually happened?

Upgrade command throws this error:

```
> Updating packages (this may take a while)...
      > In repository "all-the-icons.el", failed to get status:

        Failed to get unambiguous name for "master"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) ^C
        ! Script was abruptly aborted! Run 'doom sync' to repair inconsistencies
```

### Describe your attempts to resolve the issue

1. Install doom
```bash
$ doom install

> Executing 'doom install' with Emacs 27.2 at 2021-06-09 10:09:05
  Installing Doom Emacs!

  > Creating .doom.d/
    ✓ Created .doom.d/
  ! init.el already exists, skipping
  ! config.el already exists, skipping
  ! packages.el already exists, skipping
  - Envvar file already exists, skipping
  ...
  ...
  ...
  Download and install all-the-icon's fonts? (y or n) y
    Contacting host: raw.githubusercontent.com:443
    Contacting host: raw.githubusercontent.com:443
    Contacting host: raw.githubusercontent.com:443
    Fonts downloaded, updating font cache... <fc-cache -f -v>
     Successfully installed `all-the-icons' fonts to `/Users/furkan.turkal/Library/Fonts/'!
  ✓
  Finished! Doom is ready to go!
```

2. Upgrade

```bash
$ doom upgrade

> Executing 'doom upgrade' with Emacs 27.2 at 2021-06-09 10:09:23
  > Preparing to upgrade Doom Emacs and its packages...
  ✓ Doom is already up-to-date!
  ...
  ...
  ...
  > Updating packages (this may take a while)...
      > In repository "all-the-icons.el", failed to get status:

        Failed to get unambiguous name for "master"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) ^C
        ! Script was abruptly aborted! Run 'doom sync' to repair inconsistencies
```

3. It says `Run 'doom sync' to repair inconsistencies`, but it completes the sync with success already

```
$ doom sync

> Executing 'doom sync' with Emacs 27.2 at 2021-06-09 10:20:24
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Purging orphaned packages (for the emperor)...
      - No builds to purge
      - Skipping elpa packages
      - Skipping repos
      - Skipping regrafting
    > (Re)generating autoloads file...
      > Generating autoloads file...
      > Byte-compiling autoloads file...
      ✓ Generated .local/autoloads.27.2.elc
    - Restart Emacs or use 'M-x doom/reload' for changes to take effect
  ✓ Finished in 5.8627s
```

Similar to this https://github.com/hlissner/doom-emacs/issues/5065, but I already installed that font under `/Users/furkan.turkal/Library/Fonts/` path.

https://github.com/hlissner/doom-emacs/issues/2517#issuecomment-584297346 this didn't work for me. :(

### Steps to reproduce

1. `$ doom upgrade`
2. See the error: 
```
In repository "all-the-icons.el", failed to get status:

        Failed to get unambiguous name for "master"
        fatal: Needed a single revision
```

### System Information

https://paste.ubuntu.com/p/G69htDchjN/

**Comment by joaquinlpereyra** [comment] 2021-06-09 12:27
See #4984 which seems similar and see if (the fix)[https://github.com/hlissner/doom-emacs/issues/4984#issuecomment-832842879] helps.

**Comment by Dentrax** [comment] 2021-06-09 13:04
Thanks!

Removing `~/.emacs.d/.local/straight/repos/gcmh` did not fix the problem, but:

```
$ rm -rf ~/.emacs.d/.local/straight
$ doom sync
$ doom upgrade
```

...fixed the problem. I had to remove the entire `straight` directory. :(

**Comment by hlissner** [comment] 2021-09-28 09:25
Duplicate of https://github.com/hlissner/doom-emacs/issues/4984

> Removing ~/.emacs.d/.local/straight/repos/gcmh did not fix the problem, but:

The error was complaining about all-the-icons, not gcmh.

**Closed by hlissner** 2021-09-28 09:25 UTC
Labels: duplicate, delete me
