### ISSUE TITLE
Doom update and doom install failing with lastest updates

### ISSUE THREAD

**Issue by teehemkay** [hlissner/doom-emacs#5807] opened 2021-11-21 16:36 UTC
### What did you expect to happen?

When I did `doom up` I expected doom to update

<details>
<summary>doom up</summary>

```
❯ doom up
> Executing 'doom upgrade' with Emacs 27.2 at 2021-11-21 12:36:28
  > Preparing to upgrade Doom Emacs and its packages...
  - A new version of Doom Emacs is available!
  
    Old revision: df64e5024b (7 days ago)
    New revision: 407cf56a04 (9 hours ago)
  
  Link to diff: https://github.com/hlissner/doom-emacs/compare/df64e5024b036ffeadf26226a7fa28473d270ba0...407cf56a04424f7165f360c604e3db5769f99a79
View the comparison diff in your browser? (y or n) n
Proceed with upgrade? (y or n) y
  > Upgrading Doom Emacs...
    > Cleaning .elc files
      - No elc files to clean
    - From https://github.com/hlissner/doom-emacs
     * [new branch]          develop    -> _upgrade_develop
     * [new branch]          develop    -> _upgrade/develop
  - Reloading Doom Emacs
> Executing 'doom upgrade -p' with Emacs 27.2 at 2021-11-21 12:36:36
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/hacking/doom-emacs/.local/env"
      ✓ Successfully generated "~/hacking/doom-emacs/.local/env"
    > Installing packages...
      > Updating recipe repos...
        ✓ melpa updated (43726f8 -> db77988)
          - $ cd /Users/tmk/hacking/doom-emacs/.local/straight/repos/melpa/
          $ git config --get remote.origin.url
          
          https://github.com/melpa/melpa.git
          
          [Return code: 0]
          
          $ cd /Users/tmk/hacking/doom-emacs/.local/straight/repos/melpa/
          $ git fetch origin
          
          From https://github.com/melpa/melpa
             43726f8e..db77988a  master     -> origin/master
        ✓ gnu-elpa-mirror updated (870aae4 -> 7eed1d9)
          - $ cd /Users/tmk/hacking/doom-emacs/.local/straight/repos/gnu-elpa-mirror/
          $ git config --get remote.origin.url
          
          https://github.com/emacs-straight/gnu-elpa-mirror.git
          
          [Return code: 0]
          
          $ cd /Users/tmk/hacking/doom-emacs/.local/straight/repos/gnu-elpa-mirror/
          $ git fetch origin
          
          From https://github.com/emacs-straight/gnu-elpa-mirror
             870aae4..7eed1d9  master     -> origin/master
        ✓ emacsmirror-mirror updated (5bcbacb -> 371e4a0)
          - $ cd /Users/tmk/hacking/doom-emacs/.local/straight/repos/emacsmirror-mirror/
          $ git config --get remote.origin.url
          
          https://github.com/emacs-straight/emacsmirror-mirror.git
          
          [Return code: 0]
          
          $ cd /Users/tmk/hacking/doom-emacs/.local/straight/repos/emacsmirror-mirror/
          $ git fetch origin
          
          From https://github.com/emacs-straight/emacsmirror-mirror
             5bcbacb..371e4a0  master     -> origin/master
      > Cloning consult-dir...
      - Checked out consult-dir: 08f543ae6acbfc1ffe579ba1d00a5414012d5c0b
      > Building consult-dir...
      > Building spinner...
      > Building map...
      > Building queue...
      ✓ Installed 4 packages
    > (Re)building packages...
      - No packages need rebuilding
    > Updating packages (this may take a while)...
      ✓ (28/275) vertico: cd3c400 -> 75f33e3 [35 commit(s)]
          75f33e3 Introduce vertico--metadata-get
          9479c5d Version 0.15
          0df38cf vertico--recompute-candidates: Minor simplification
          d646722 vertico-flat/grid-mode: Copy string properties when shrinking string
          99e6d90 vertico-grid-mode: Set completion predicate
          5c10607 Fix indexed mode (Fix #151)
          665660f Autoload vertico-repeat to improve error message
          6b0ea6b vertico-grid-mode: Improve alignment
          ad2ba13 vertico-grid/flat-mode: Add check
          3e16230 vertico-grid/flat-mode: Allow toggling between vertical/grid/flat mode
          cdc3334 Remove while-no-input-ignore-events workaround (#150)
          5624aaf Minor simplification
          371e264 vertico-grid-mode: Compute numbers of columns
          d42f315 vertico-grid: Minor improvements
          42aca1f README updates
          298379e Ensure that vertico-mouse+buffer works
          94e399e vertico-buffer: Mark as read-only
          804d8ca Add vertico-grid-mode extension
          3c33998 Update version bounds
          3dd5794 README: Update paragraph about child frames
          [...]
      ✓ (30/275) consult: 166e3b0 -> 57dc1ad [25 commit(s)]
          57dc1ad Adjust consult--grep-match-regexp in order to support -[ABC] grep options (Fix #466)
          7708dc7 consult-completion-in-region: insert initial text for file completion (#463)
          3b18b04 README: Minor improvement
          39f41ed consult--format-location: Only append colon if STR is non-nil (Fix #460)
          e8f4d9d consult-flymake: Sort by severity
          e10775a README: Update link to @bdarcus' citar
          56a6a9f README: Update links
          901b12f README: Update links
          0bd4b40 README: Add link to consult-projectile
          8bc1f05 Update changelog
          9229b5a Internal renamings
          b56bd11 Rename consult-isearch to consult-isearch-history
          ae2761e  Make menu-item :fiter functions pure functions (#453)
          b903bce Minor readme updates
          6769f21 README: Fix typo
          04d9cb0 README: Minor update
          e0c3b2c Update list of completion UIs, in particular add @protesilaos' mct.el
          67fa3a2 consult-register-store: Add support to create file register value
          d8c925b consult-register: Add support for file values (Fix #449)
          3715f73 README: Add link to all-the-icons-completion
          [...]
```
</details>

### What actually happened?

Instead I got the following error

```
      x There was an unexpected error
        Message: Wrong type argument
        Error: (wrong-type-argument stringp arrayp)
        Backtrace:
          (string-match "\n" arrayp 0)
          (split-string arrayp "\n")
          (let ((parts (split-string string "\n"))) (while (equal (car parts) "") (s...
          (straight--split-and-trim arrayp 2)
          (format "In repository %S, failed to get status:\n\n%s" local-repo (straig...
          (straight--popup-raw (format "In repository %S, failed to get status:\n\n%...
          (cond (failure (straight--popup-raw (format "In repository %S, failed to g...
          (let* ((--cl-rest-- status) (left-ref (car (cdr (plist-member --cl-rest-- ...
          (let ((status (straight-vc-git--compare-and-canonicalize default-branch "H...
          (straight-vc-git--ensure-head-at-branch "embark" nil)
      ! Extended backtrace logged to ~/hacking/doom-emacs/.local/doom.error.log
```

[extended backtrace](https://pastebin.com/mfzLaJVJ)

### Describe your attempts to resolve the issue

I then tried to do a clean `doom install` 

<details>
<summary>`doom install`</summary>

```
❯ doom install
> Installing straight...
  > Cloning use-package...
> Executing 'doom install' with Emacs 27.2 at 2021-11-21 15:16:37
  Installing Doom Emacs!
  
  > Creating .config/doom/
    ✓ Created .config/doom/
  ! init.el already exists, skipping
  ! config.el already exists, skipping
  ! packages.el already exists, skipping
Generate an envvar file? (see `doom help env` for details) (y or n) y
  > Generating envvars file at "~/hacking/doom-emacs/.local/env"
    ✓ Successfully generated "~/hacking/doom-emacs/.local/env"
  Installing plugins
  > Installing packages...
    > Building straight...
    - Checked out use-package: a7422fb8ab1baee19adb2717b5b47b9c3812a84c
    > Building use-package...
    > Building use-package > Building bind-key...
    > Building use-package...
    > Updating recipe repos...
    > Cloning auto-minor-mode...csmirror-mirror...
    - Checked out auto-minor-mode: 17cfa1b54800fdef2975c0c0531dad34846a5065
    > Building auto-minor-mode...
    > Cloning gcmh...
    - Checked out gcmh: 0089f9c3a6d4e9a310d0791cf6fa8f35642ecfd9
    > Building gcmh...
    > Cloning explain-pause-mode...
    - Checked out explain-pause-mode: 2356c8c3639cbeeb9751744dbe737267849b4b51
    > Building explain-pause-mode...
    > Cloning all-the-icons.el...
    > Building all-the-icons...
    > Cloning emacs-hide-mode-line...
    > Building hide-mode-line...
    > Cloning highlight-numbers...
    - Checked out highlight-numbers: 8b4744c7f46c72b1d3d599d4fb75ef8183dee307
    > Building highlight-numbers...
    > Building highlight-numbers > Cloning parent-mode...
    > Building highlight-numbers > Building parent-mode...
    > Building highlight-numbers...
    > Cloning rainbow-delimiters...
    - Checked out rainbow-delimiters: d576e6694ad3a3e88b2bb1363305b38fa364c149
    > Building rainbow-delimiters...
    > Cloning restart-emacs...
    - Checked out restart-emacs: 1607da2bc657fe05ae01f7fdf26f716eafead02c
    > Building restart-emacs...
    > Cloning better-jumper...
    - Checked out better-jumper: 7f328a886ba4dd01993d269eee01c8ee3d0ddf52
    > Building better-jumper...
    > Cloning dtrt-indent...
    - Checked out dtrt-indent: 9714f2c5f1c9b7c21e732df8c15a870a88caba84
    > Building dtrt-indent...
    > Cloning helpful...
    - Checked out helpful: 7e4b1f0d5572a4e2b8ee7a9b084ef863d0315a73
    > Building helpful...
    > Building helpful > Cloning dash.el...
    > Building helpful > Building dash...
    > Building helpful > Cloning s.el...
    > Building helpful > Building s...
    > Building helpful > Cloning f.el...
    > Building helpful > Building f...
    > Building helpful > Cloning elisp-refs...
    > Building helpful > Building elisp-refs...
    > Building helpful...
    > Cloning pcre2el...
    - Checked out pcre2el: 0b5b2a2c173aab3fd14aac6cf5e90ad3bf58fa7d
    > Building pcre2el...
    > Cloning smartparens...
    - Checked out smartparens: 2834c66c4f09778d0c57e99886c329188eed591a
    > Building smartparens...
    > Cloning ws-butler...
    - Checked out ws-butler: 572a10c11b6cb88293de48acbb59a059d36f9ba5
    > Building ws-butler...
    > Cloning projectile...
    - Checked out projectile: 7f64570d3e6829d767d340c8584f3e4f3472ee81
    > Building projectile...
    > Cloning project...
    - Checked out project: a546cce47c434b0b4bf24bf1d5ed6e4623492072
    > Building project...
    > Building project > Cloning xref...
    > Building project > Building xref...
    > Building project...
    > Cloning general.el...
    > Building general...
    > Cloning emacs-which-key...
    > Building which-key...
    > Cloning company-mode (for company)...
    > Building company...
    > Cloning emacs-company-dict...
    > Building company-dict...
    > Cloning company-box...
    - Checked out company-box: 156f65cfbf690ed84e0e84f90277d665d873ff24
    > Building company-box...
    > Building company-box > Building dash-functional...
    > Building company-box > Cloning frame-local...
    > Building company-box > Building frame-local...
    > Building company-box...
    > Cloning vertico...
    - Checked out vertico: 75f33e36204f8a72d0b8cde81e04d3350a848981
    > Building vertico...
    > Cloning orderless...
    - Checked out orderless: 62f71c34baca0b7d0adeab4a1c07d85ffcee80d9
    > Building orderless...
    > Cloning consult...
    - Checked out consult: 57dc1adfdc0feafc71c6f418ff7aa1adbe47a5fd
    > Building consult...
    > Cloning consult-dir...
    - Checked out consult-dir: 08f543ae6acbfc1ffe579ba1d00a5414012d5c0b
    > Building consult-dir...
    > Cloning consult-flycheck...
    - Checked out consult-flycheck: 92b259e6a8ebe6439f67d3d7ffa44b7e64b76478
    > Building consult-flycheck...
    > Building consult-flycheck > Cloning flycheck...
    - Checked out flycheck: 784f184cdd9f9cb4e3dbb997c09d93e954142842
    > Building consult-flycheck > Building flycheck...
    > Building consult-flycheck > Building flycheck > Cloning pkg-info...
    > Building consult-flycheck > Building flycheck > Building pkg-info...
    > Building consult-flycheck > Building flycheck > Building pkg-info > Cloning epl...
    > Building consult-flycheck > Building flycheck > Building pkg-info > Building epl...
    > Building consult-flycheck > Building flycheck > Building pkg-info...
    > Building consult-flycheck > Building flycheck...
    > Building consult-flycheck...
    > Cloning embark...
    - Checked out embark: 5b34b2b60370cea5ad9da5931856667a6fae0501
    > Building embark...
    > Building embark-consult...
    > Cloning marginalia...
    - Checked out marginalia: 678b6528f3905e624b01daf787461d8c7e06ec0f
    > Building marginalia...
    > Cloning Emacs-wgrep (for wgrep)...
    > Building wgrep...
    > Cloning all-the-icons-completion...
    - Checked out all-the-icons-completion: a0f34d68cc12330ab3992a7521f9caa1de3b8470
    > Building all-the-icons-completion...
    > Cloning emacs-doom-themes...
    > Building doom-themes...
    > Cloning emacs-solaire-mode...
    > Building solaire-mode...
    > Cloning emacs-emojify...
    > Building emojify...
    > Building emojify > Cloning ht.el...
    > Building emojify > Building ht...
    > Building emojify...
    > Cloning hl-todo...
    - Checked out hl-todo: 42f744ffb513cf2b95517144c64dbf3fc69f711a
    > Building hl-todo...
    > Cloning minimap...
    - Checked out minimap: ed7490652a676c0510ed57d5366c445de20a370b
    > Building minimap...
    > Cloning anzu...
    - Checked out anzu: bdb3da5028935a4aea55c40769bc191a81afb54e
    > Building anzu...
    > Cloning evil-anzu...
    - Checked out evil-anzu: d3f6ed4773b48767bd5f4708c7f083336a8a8a86
    > Building evil-anzu...
    > Building evil-anzu > Cloning evil...
    - Checked out evil: 07aba40dd32c667f36eb1ad244f859983a077d12
    > Building evil-anzu > Building evil...
    > Building evil-anzu > Building evil > Cloning goto-chg...
    > Building evil-anzu > Building evil > Building goto-chg...
    > Building evil-anzu > Building evil...
    > Building evil-anzu...
    > Cloning nav-flash...
    - Checked out nav-flash: 2e31f32085757e1dfdd8ec78e9940fd1c88750de
    > Building nav-flash...
    > Cloning evil-goggles...
    - Checked out evil-goggles: 08a22058fd6a167f9f1b684c649008caef571459
    > Building evil-goggles...
    > Cloning treemacs...
    - Checked out treemacs: 63e2bc207a2a4a36a3eebbe994353cb4845ad2de
    > Building treemacs...
    > Building treemacs > Cloning ace-window...
    - Checked out ace-window: c7cb315c14e36fded5ac4096e158497ae974bec9
    > Building treemacs > Building ace-window...
    > Building treemacs > Building ace-window > Cloning avy...
    - Checked out avy: e92cb37457b43336b765630dbfbea8ba4be601fa
    > Building treemacs > Building ace-window > Building avy...
    > Building treemacs > Building ace-window...
    > Building treemacs > Cloning pfuture...
    > Building treemacs > Building pfuture...
    > Building treemacs > Cloning hydra...
    > Building treemacs > Building hydra...
    > Building treemacs > Building hydra > Building lv...
    > Building treemacs > Building hydra...
    > Building treemacs > Cloning cfrs...
    > Building treemacs > Building cfrs...
    > Building treemacs > Building cfrs > Cloning posframe...
    > Building treemacs > Building cfrs > Building posframe...
    > Building treemacs > Building cfrs...
    > Building treemacs...
    > Building treemacs-evil...
    > Building treemacs-projectile...
    > Building treemacs-magit...
    > Building treemacs-magit > Cloning magit...
    - Checked out magit: aba0a596115b42fbd60347d893bcc319020ce5a2
    > Building treemacs-magit > Building magit...
    > Building treemacs-magit > Building magit > Building git-commit...
    > Building treemacs-magit > Building magit > Building git-commit > Cloning transient...
    > Building treemacs-magit > Building magit > Building git-commit > Building transient...
    > Building treemacs-magit > Building magit > Building git-commit > Cloning with-editor...
    > Building treemacs-magit > Building magit > Building git-commit > Building with-editor...
    > Building treemacs-magit > Building magit > Building git-commit...
    > Building treemacs-magit > Building magit > Building magit-section...
    > Building treemacs-magit > Building magit...
    > Building treemacs-magit...
    > Building treemacs-persp...
    > Building treemacs-persp > Cloning persp-mode.el...
    > Building treemacs-persp > Building persp-mode...
    > Building treemacs-persp...
    > Cloning unicode-fonts...
    - Checked out unicode-fonts: e3942fe40b418bfb2dc4e73633e09195437fef01
    > Building unicode-fonts...
    > Building unicode-fonts > Cloning font-utils...
    > Building unicode-fonts > Building font-utils...
    > Building unicode-fonts > Building font-utils > Cloning persistent-soft...
    > Building unicode-fonts > Building font-utils > Building persistent-soft...
    > Building unicode-fonts > Building font-utils > Building persistent-soft > Cloning pcache...
    > Building unicode-fonts > Building font-utils > Building persistent-soft > Building pcache...
    > Building unicode-fonts > Building font-utils > Building persistent-soft > Cloning list-utils...
    > Building unicode-fonts > Building font-utils > Building persistent-soft > Building list-utils...
    > Building unicode-fonts > Building font-utils > Building persistent-soft...
    > Building unicode-fonts > Building font-utils...
    > Building unicode-fonts > Cloning ucs-utils...
    > Building unicode-fonts > Building ucs-utils...
    > Building unicode-fonts...
    > Cloning git-gutter-fringe...
    - Checked out git-gutter-fringe: 4f19866494fa1debfa319382913e39a153431634
    > Building git-gutter-fringe...
    > Building git-gutter-fringe > Cloning git-gutter...
    > Building git-gutter-fringe > Building git-gutter...
    > Building git-gutter-fringe > Cloning fringe-helper.el...
    > Building git-gutter-fringe > Building fringe-helper...
    > Building git-gutter-fringe...
    > Cloning vi-tilde-fringe...
    - Checked out vi-tilde-fringe: f1597a8d54535bb1d84b442577b2024e6f910308
    > Building vi-tilde-fringe...
    > Cloning evil-args...
    - Checked out evil-args: 758ad5ae54ad34202064fec192c88151c08cb387
    > Building evil-args...
    > Cloning evil-easymotion...
    - Checked out evil-easymotion: f96c2ed38ddc07908db7c3c11bcd6285a3e8c2e9
    > Building evil-easymotion...
    > Cloning evil-embrace.el...
    > Building evil-embrace...
    > Building evil-embrace > Cloning embrace.el...
    > Building evil-embrace > Building embrace...
    > Building evil-embrace > Building embrace > Cloning expand-region.el...
    > Building evil-embrace > Building embrace > Building expand-region...
    > Building evil-embrace > Building embrace...
    > Building evil-embrace > Cloning evil-surround...
    - Checked out evil-surround: 282a975bda83310d20a2c536ac3cf95d2bf188a5
    > Building evil-embrace > Building evil-surround...
    > Building evil-embrace...
    > Cloning evil-escape...
    - Checked out evil-escape: 819f1ee1cf3f69a1ae920e6004f2c0baeebbe077
    > Building evil-escape...
    > Cloning evil-exchange...
    - Checked out evil-exchange: ac50f21b29b6e3a111e10a9e88ae61c907ac5ee8
    > Building evil-exchange...
    > Cloning evil-indent-plus...
  ```
</details>

But I also got an error message:

```
x There was an unexpected error
      Message: Wrong type argument
      Error: (wrong-type-argument arrayp nil)
      Backtrace:
        (substring nil 0 0)
        (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
        (shell-quote-argument nil)
        (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
        (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name direct...
        (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file...
        (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (exp...
        (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n...
        (let* ((result result) (exit (car result)) (invoked (numberp exit)) (succe...
        (let ((directory x6) (result x4) (args x2) (program x0)) (let* ((result re...
    ! Extended backtrace logged to ~/hacking/doom-emacs/.local/doom.error.log
```

[extended backtrace](https://pastebin.com/3QzLBK7U)

### Steps to reproduce

1. clone `doom` repository
2. run `doom install`

### System Information

https://pastebin.com/uQyTyTMR

**Comment by hlissner** [comment] 2021-11-21 16:55
Duplicate of https://github.com/hlissner/doom-emacs/issues/5207. 

See https://github.com/hlissner/doom-emacs/issues/5207#issuecomment-877750996.

**Closed by hlissner** 2021-11-21 16:55 UTC
Labels: duplicate

**Comment by teehemkay** [comment] 2021-11-21 17:06
Thanks for the quick reply.
I'll try updating again.
