### ISSUE TITLE
Can't open org-id link because it hasn't loaded yet

### ISSUE THREAD

**Issue by alarsyo** [hlissner/doom-emacs#2892] opened 2020-04-12 16:55 UTC
**What did you expect to happen?**

Pressing `RET` on a `org-id` link in org mode should take me to the destination.

**What actually happened?**

If org-id hasn't been used yet, it doesn't know what to do with the `id:xxxxxx-xxx-xxx-xxxxx` link. Emacs prompts me with `No match - create this as a new heading? (y or n)`.

**Additional details:**

If I call `M-x org-id-goto`, for example, then cancel it with `ESC`, *then* pressing `RET` on an `id` works. So I'm guessing this has to do with `org-id` not being loaded when I try to access a link and it fails.

**Steps to reproduce:**

1. Create a `.org` file, create some entry, give this entry an id with `M-x org-id-store-link` and then insert this link.
2. Close emacs, start a new session, go to the file, press RET on the link: doesn't work
3. launch `M-x org-id-goto`, cancel the prompt, press RET on the link: it works!

**System information:**
<details>

```
emacs   version    27.0.90
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Apr 09, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -flto -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 24e35b95d 2020-04-10 02:04:00 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.31-1-lts #1 SMP Wed, 08 Apr 2020 08:29:49 +0000 x86_64
        path       (/usr/local/texlive/2019/bin/x86_64-linux ~/.local/gcc-arm/bin ~/.node_modules/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.cargo/bin ~/.local/bin ~/go/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.cargo/bin ~/.local/bin ~/go/bin /usr/lib/emacs/27.0.90/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select :editor (evil +everywhere) fold snippets :emacs dired vc :checkers syntax :tools lookup lsp magit :lang cc data emacs-lisp markdown nix (org +journal) (rust +lsp) sh :config literate (default +bindings))
        packages   ((solaire-mode :disable t) (org-bullets :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2020-04-12 17:20
This is a duplicate of #2643

`org-id` needs to be added to `org-modules`:

```elisp
(add-to-list 'org-modules 'org-id)
```

This is the case for vanilla org-mode as well.

**Closed by hlissner** 2020-04-12 17:20 UTC
Labels: is:duplicate
