### ISSUE TITLE
Org Agenda is broken

### ISSUE THREAD

**Issue by deshmukhs** [hlissner/doom-emacs#4998] opened 2021-05-07 10:13 UTC
What I expect to see:

On `SPC o A a` expect to see an agenda
...

What actually happens:

It produces an error --- `(invalid-function (date date))`
...

**Additional details:**
Backtrace `SPC h d d` is as follows:
https://pastebin.com/HW5ykn5v

**System information:**
https://pastebin.com/U17HVwX6

**Comment by faustoUrtiz** [comment] 2021-05-07 15:38
I had the same problem. I asked for help in Reddit r/DoomEmacs tobbe2064 replyied: "Had the same problem. Did a doom clean and build and that seems to have resolved the problem".  It solved the issue in my case!

**Comment by hlissner** [comment] 2021-05-07 17:20
Duplicate of #4862.

Please remember to search our issuer tracker before reporting issues. You'll sometimes find your issue already resolved.

**Closed by hlissner** 2021-05-07 17:20 UTC
Labels: duplicate
