### ISSUE TITLE
Upgrade Error - Message: Symbol's function definition is void

### ISSUE THREAD

**Issue by liambresnahan** [hlissner/doom-emacs#4983] opened 2021-05-05 03:39 UTC
**What did you expect to happen?**
On running `doom upgrade` from the command line or `M-x` + `doom/upgrade` I expected to be upgraded.

**What actually happened?**
On running I get this error:

`> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to .local/doom.error.log`

**Additional details:**
This is a very vanilla setup, I've just been getting into emacs/doom so not a lot of changes. 

I can provide the error log if useful

**System information:**
`generated    May 04, 2021 20:37:08
distro       MacOS 11.3 Darwin 20.4.0 x86_64
emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/
doom         2.0.9 HEAD -> develop, origin/develop, origin/HEAD b65d8ae3a 2021-05-04 16:37:05 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/zsh
features     NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP
traits       gui server-running envvar-file custom-file
custom       package-selected-packages
modules      :completion company ivy :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term term :checkers syntax (spell +flyspell) grammar :tools ansible docker (eval +overlay) lookup magit make pdf tmux upload :os macos tty :lang emacs-lisp json javascript markdown (org +pretty) python rest sh yaml :config (default +bindings +smartparens)
packages     (evil-tutor) (org-bullets)
elpa         shrink-path s f doom-modeline dash all-the-icons`

**Comment by brendan-t** [comment] 2021-05-05 04:04
I'm getting this too with gccemacs

**Comment by hlissner** [comment] 2021-05-05 04:08
Duplicate of #4950

**Closed by hlissner** 2021-05-05 04:08 UTC
Labels: delete me, duplicate
