### ISSUE TITLE
gccemacs errors on start because of doom's hack with `comp-deferred-compilation-black-list`

### ISSUE THREAD

**Issue by kiprasmel** [hlissner/doom-emacs#4316] opened 2020-11-25 03:09 UTC
**What did you expect to happen?**
I setted up gccemacs (`28.0.50`) [as suggested in the FAQ](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#why-is-emacsdoom-slow). I expected `doom sync` to work.

**What actually happened?**
I tried `./.emacs.d/bin/doom sync`, but always ended up like this:

```sh
$ ./.emacs.d/bin/doom sync
Symbol’s value as variable is void: comp-deferred-compilation-black-list
```

(errored almost instantly)

I grepped for the `comp-deferred-compilation-black-list` string, found some matches, and in particular, in `.emacs.d/core/core.el`, L288-L295:

https://github.com/hlissner/doom-emacs/blob/c83e5e75e24706a0d6c15f3156d33b1c4f9dc365/core/core.el#L288-L296

hehe, the `HACK` keyword suggested some ideas, so I commented this whole block out, and then I no longer got any errors and everything worked.

**Additional details:**
- Include a link to your private config

default with a few packages enabled in init.el: https://github.com/kiprasmel/voidrice/tree/18f05b872d99df9fada5af28f326759bae390087/.config/doom

- Include any warnings or errors

```sh
$ journalctl --user -u emacs
-- Logs begin at Sat 2020-04-25 00:49:38 EEST, end at Wed 2020-11-25 05:03:06 EET. --
Nov 25 04:38:02 arch-usb2 systemd[1264]: Starting Emacs text editor...
Nov 25 04:38:02 arch-usb2 emacs[341687]: Warning: due to a long standing Gtk+ bug
Nov 25 04:38:02 arch-usb2 emacs[341687]: https://gitlab.gnome.org/GNOME/gtk/issues/221
Nov 25 04:38:02 arch-usb2 emacs[341687]: Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Nov 25 04:38:02 arch-usb2 emacs[341687]: Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Nov 25 04:38:02 arch-usb2 emacs[341687]: Warning (initialization): An error occurred while loading ‘/home/kipras/.emacs.d/init.el’:
Nov 25 04:38:02 arch-usb2 emacs[341687]: Error in Doom Emacs core: Doom is in an incomplete state, run 'doom sync' on the command line to repair it
Nov 25 04:38:02 arch-usb2 emacs[341687]: To ensure normal operation, you should investigate and remove the
Nov 25 04:38:02 arch-usb2 emacs[341687]: cause of the error in your initialization file.  Start Emacs with
Nov 25 04:38:02 arch-usb2 emacs[341687]: the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
Nov 25 04:38:02 arch-usb2 emacs[341687]: Starting Emacs daemon.
Nov 25 04:38:02 arch-usb2 systemd[1264]: Started Emacs text editor.

```

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.78-1-lts #1 SMP Wed, 18 Nov 2020 19:51:49 +0000 x86_64
        path       (~/.yarn/bin ~/.config/yarn/global/node_modules/.bin ~/.cabal/bin ~/.ghcup/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin ~/.local/bin/statusbar ~/.local/bin/cron ~/.local/bin/i3cmds ~/.local/bin/ ~/.cargo/bin ~/go/bin ~/.gem/ruby/2.6.0/bin ~/.dotnet/tools ~/.gem/ruby/2.7.0/bin ~/builds/DataGrip-2019.3.2/bin /opt/resolve/bin ~/.cabal/bin ~/.ghcup/bin /opt/depot_tools /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Nov 25, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        font       #<font-object -CTDB-FuraCode Nerd Font Mono-normal-normal-normal-*-22-*-*-*-*-0-iso10646-1>
        theme      doom-one
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD c83e5e7 2020-11-21 14:09:08 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard (emoji +unicode) hl-todo modeline ophints (popup +defaults) treemacs vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric ibuffer undo vc :term eshell shell term vterm :checkers syntax :tools docker lookup lsp magit make pdf rgb :lang cc common-lisp emacs-lisp (haskell +dante) json javascript latex markdown org python sh web yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by bnjmnt4n** [comment] 2020-11-25 03:26
This is due to recent changes in gccemacs’ API. See #4309 for a PR which updates doom to use the newer API.

**Comment by hlissner** [comment] 2020-11-26 17:18
Duplicate of #4309, which was merged.

**Closed by hlissner** 2020-11-26 17:18 UTC
Labels: duplicate
