### ISSUE TITLE
Packages missing from Doom

### ISSUE THREAD

**Issue by orangemn6** [hlissner/doom-emacs#4982] opened 2021-05-05 03:34 UTC
**What did you expect to happen?**
I expected Doom to have neotree and vterm preinstalled

**What actually happened?**
the packages were working the first time I launched doom, but once I restarted emacs they were gone and unavailable in package-install.

**Additional details:**

Using emacs 26.3

**Steps to reproduce:**
1. Open emacs
2. try to launch neotree
3. neotree not found
4. try to install neotree
5. can't find package

**System information:**
https://pastebin.com/skSaAgvD

**Comment by hlissner** [comment] 2021-05-05 03:37
Enable one of the `:ui neotree` or `:ui treemacs` [modules](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules). Do not use `package-install`. Doom has its own [package manager](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#package-management).

From your `M-x doom/info` it seems you've been using package.el. I suggest you delete all those packages and install them with `package!` statements, then run `doom sync -p` and restart Emacs.

As this is not a bug, I will close this, but feel free to follow up here.

**Closed by hlissner** 2021-05-05 03:37 UTC
Labels: invalid

**Comment by orangemn6** [comment] 2021-05-05 23:27
@hlissner completely unrelated, but where can I put global-bind-key lisp code? I am pretty new to emacs.

**Comment by hlissner** [comment] 2021-05-05 23:33
> @hlissner completely unrelated, but where can I put global-bind-key lisp code? I am pretty new to emacs.

In `~/.doom.d/config.el`. See https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#configure
