### ISSUE TITLE
Installation freezes on compiling a native file

### ISSUE THREAD

**Issue by andreypudov** [hlissner/doom-emacs#6252] opened 2022-04-06 06:51 UTC
### What did you expect to happen?

Installation should be completed succesfully.

### What actually happened?

~/.emacs.d/bin/doom install

...
    > Cloning drag-stuff.el...
    > Building drag-stuff...
    > Cloning link-hint.el...
    > Building link-hint...
    > Cloning expand-region.el...
    > Building expand-region...
    > Natively compiling 1 files...

### Describe your attempts to resolve the issue

I have tried to remove all customization I did in .doom scripts.

### Steps to reproduce

1. git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
2. ~/.emacs.d/bin/doom install

> Executing 'doom info' with Emacs 28.1 at 2022-04-06 08:49:38
    generated    Apr 06, 2022 08:49:38
      system       Ubuntu 21.10 Linux 5.13.0-39-generic x86_64
      emacs        28.1 master 6ddcb0e17 ~/.emacs.d/ -> ~/.emacs.d/
      doom         3.0.0-dev grafted, HEAD -> master, origin/master, origin/HEAD b42d7af 2022-04-05 00:05:31 +0200 ~/.doom.d/ -> ~/.doom.d/
      shell        /usr/bin/zsh
      features     ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB
      traits       batch
      modules      :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold parinfer snippets :emacs (dired +icons) electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang (csharp +lsp +dotnet) emacs-lisp (go +lsp) json (javascript +lsp) markdown (org +pretty) sh :config (default +bindings +smartparens)
      packages     (all-the-icons-ivy-rich) (password-generator)

### System Information

Ubuntu 21.10

**Comment by hlissner** [comment] 2022-04-06 16:38
Duplicate of #5592. [Read this](https://github.com/hlissner/doom-emacs/issues/5592#issuecomment-945919856) for workaround.

**Closed by hlissner** 2022-04-06 16:38 UTC
Labels: duplicate, delete me
