### ISSUE TITLE
Matching paren is deleted twice.

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#3418] opened 2020-06-19 18:19 UTC
**What did you expect to happen?**
In `smartparens-mode`, with `|` being the point.
```
((|))
;; DEL
(|)
```

**What actually happened?**
```
((|))
;; DEL
(|
```

**Additional details:**
- This seems to be an interaction between `sp-autodelete-pair` and `+default--delete-backward-char-a`.
- Setting `sp-autodelete-pair` to `nil` fixes this specific problem, but disabled autodeletion of more complex pairs.
- Reproduces in `M-x doom/sandbox C-c C-p`.

**Comment by hlissner** [comment] 2020-06-19 19:30
Duplicate of #3268

**Closed by hlissner** 2020-06-19 19:30 UTC
Labels: is:duplicate
