### ISSUE TITLE
julia lsp connection problem

### ISSUE THREAD

**Issue by isentropic** [hlissner/doom-emacs#3119] opened 2020-05-14 08:36 UTC
**What actually happened?**
...
![image](https://user-images.githubusercontent.com/24591123/81911842-c9eeda00-9608-11ea-8101-df381a74630a.png)

**Additional details:**
Julia lsp stopped working after update (I'm not sure what is the previous version I used)
I followed the instructions from https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/julia/README.org
to install it. I tried both 
```
;; ~/.doom.d/config.el
(setq lsp-julia-default-environment "~/.julia/environments/v1.0")
;; and
(setq lsp-julia-package-dir nil)
```
Emacs discovers julia binary properly as I can send lines to repl via `C-Ret` in edit mode. I checked the `LanguageServer.jl` installation too. Connection to server is never established the process hangs with 'connecting to julia lsp...` and never connects, the crashes as in the screenshot

**Steps to reproduce:**
Follow instuctions from 
https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/julia/README.org

**Comment by isentropic** [comment] 2020-05-14 08:37
Perhaps @AlexLewandowski could help out with this?

**Comment by AlexLewandowski** [comment] 2020-05-14 21:10
I think you made a mistake in the link for "Steps to reproduce" it just points to the Julia module README.

Without knowing your setup, I would guess you're using the latest version of LanguageServer.jl. The package is developed for VS Code first, which means it's compatibility with other LSP implementations varies. Since LanguageServer.jl#2.0.0, there have been many changes that introduced issues in third-party LSP packages (Like Emacs, Sublime, etc.). There are issues currently open to address this, and hopefully it will be cleared up soon.

For now, I suggest using the language-server bundled with `lsp-julia`.

**Comment by isentropic** [comment] 2020-05-15 03:04
I understand what you mean but still, there is something wrong. Content of my packages.el
```
(package! lsp-julia :recipe (:host github :repo "non-jedi/lsp-julia"))
```
config.el and init.el are I believe irrelevant as long as I have lsp enabled: both julia flag and lsp module.

`julia` bin points to `julia1.4` on my system, however, `.../environments/v1.0/` exists

Is there anything I'm doing wrong? This stopped working after a recent update though.

**Comment by AlexLewandowski** [comment] 2020-05-15 04:45
Ah, by "recent update" do you mean a recent update to Julia 1.4? The version of LanguageServer.jl bundled with `lsp-julia` is old and not currently compatible with Julia 1.4. [Here is the open issue](https://github.com/non-Jedi/lsp-julia/issues/20) discussing this, and some patches you can apply if Julia 1.4 is necessary. Otherwise, Julia 1.3 should work and hopefully the [linting issue](https://github.com/emacs-lsp/lsp-mode/issues/1680) with LanguageServer.jl#2.0.0 will be fixed soon

**Comment by isentropic** [comment] 2020-05-15 09:12
@AlexLewandowski thank you ever so much, now it all works out. For those having this issue, easiest way to to have `julia` point to julia1.0.5 lts

**Comment by gdkrmr** [comment] 2020-05-15 09:48
See https://github.com/non-Jedi/lsp-julia/issues/20

**Closed** 2020-05-15 10:27 UTC
Labels: is:bug
