### ISSUE TITLE
Error in process filter: Symbol's function definition is void :number

### ISSUE THREAD

**Issue by khmelevskii** [hlissner/doom-emacs#5560] opened 2021-10-02 19:27 UTC
### What did you expect to happen?

When I try to select ClojureScript REPL I expect to select REPL without error

### What actually happened?

When I try to select ClojureScript REPL I have the following error:
`Error in process filter: Symbol's function definition is void :number`.

This problem appeared after last upgrade.

### Steps to reproduce

1. Open Emacs
2. cider-jack-in-cljs
3. select `shadow-cljs`
4. cider-connect-sibling-cljs
5. when select any repl I have an error

### System Information

https://pastebin.com/HetrL8XW

**Comment by hlissner** [comment] 2021-10-02 20:06
Duplicate of #5561

**Closed by hlissner** 2021-10-02 20:06 UTC
Labels: duplicate, delete me
