### ISSUE TITLE
org-insert-last-stored-link doesn't work with org-id-store-link

### ISSUE THREAD

**Issue by evb-gh** [hlissner/doom-emacs#3085] opened 2020-05-10 23:51 UTC
**What did you expect to happen?**
`org-insert-last-stored-link` (`SPC m l S`) to paste a link stored with `org-id-store-link` (`SPC m l i`)

**What actually happened?**
`No link to insert` message is displayed.

**Steps to reproduce:**
1. Create note with (`SPC X n`)
2. Got to note 
3. Store note link with `org-id-store-link` (`SPC m l i`)
4. Insert link with `org-insert-last-stored-link` (`SPC m l S`)

**System information:**
<details><pre>
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      Mar 26, 2020
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 68547cfb9 2020-05-10 05:33:31 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-7626-generic #30~1588169883~20.04~bbe668a-Ubuntu SMP Wed Apr 29 21:00:02 UTC  x86_64
        path       (~/.emacs.d/bin ~/Downloads/monero ~/.local/bin ~/Downloads/monero ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games ~/.fzf/bin /usr/lib/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell :checkers syntax spell grammar :tools (eval +overlay) lookup lsp magit pdf :lang data emacs-lisp javascript markdown org sh :config (default +bindings +smartparens))
        packages   ((anki-editor))
        unpin      (n/a)
        elpa       (n/a)
```</pre></details>

**Comment by hlissner** [comment] 2020-05-11 03:43
Have you added `org-id` to `org-modules`?

```elisp
(after! org
  (add-to-list 'org-modules 'org-id))
```

**Comment by evb-gh** [comment] 2020-05-11 04:14
Tried adding the code above to `config.el` (do update and restart) but still getting the same result (`No link to insert`).

**Comment by hlissner** [comment] 2020-05-11 09:24
I can reproduce the issue, but I'm unsure if this is an org bug or my misunderstanding of how org-id is intended to work. Looking into the source of `org-id-store-link`, the former stores these links in the `org-store-link-plist` variable, but `org-insert-link` never consults this variable (it checks `org-stored-links` instead, which is where `org-store-link` stores its links). I don't see where the `org` package actually uses `org-store-link-plist`, for that matter.

I'll keep looking.

**Comment by evb-gh** [comment] 2020-05-11 17:20
Is there a different way to paste that id link?

**Comment by hlissner** [comment] 2020-05-12 02:33
I think one of these will do what you want:

```elisp
(after! org
  (setq org-id-link-to-org-use-id 'use-existing))
```

Or

```elisp
(defadvice! +org--store-id-link-a (link)
  :filter-return #'org-id-store-link
  (when (and link org-store-link-plist)
    (add-to-list 'org-stored-links
                 (list (plist-get org-store-link-plist :link)
                       (plist-get org-store-link-plist :description))))
  link)
```

**Comment by evb-gh** [comment] 2020-05-13 00:14
Thank you @hlissner, always appreciate your prompt replies/help. I found a solution to my problem so you can decide if you want to keep this issue open or close it.

**Comment by hlissner** [comment] 2020-05-14 04:03
> I found a solution to my problem

What solution did you find? Or was it a workaround?

**Comment by evb-gh** [comment] 2020-05-17 17:19
I need to be able to reference/link notes from the same file and maybe other files as well. I thought it would be a good idea to reference them using unique `id`'s. Having a unique `id` for every note seems more solid. Also referencing these notes should be a friction less process, that is why want to have those keyboard shortcuts. Because my elisp-fu is almost non existent (I can copy paste some code and tape it together) I'm using what is already available and working. That is `org-store-link`.

**Comment by hlissner** [comment] 2020-05-18 22:25
Understood. I'm glad you found a solution. In that case I'll close this issue.

**Closed by hlissner** 2020-05-18 22:25 UTC
Labels: :lang org, is:question, re:elisp, status:resolved
