### ISSUE TITLE
Error on doom sync in Emacs 27.1

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#4558] opened 2021-01-22 12:49 UTC
**What did you expect to happen?**
To run `doom sync` successfully.

**What actually happened?**
I get the error 

```
      Message: Symbol's value as variable is void
      Data: (void-variable . comp-native-version-dir)
      Backtrace:
        (concat comp-native-version-dir "/" (file-name-nondirectory (comp-el-to-el
        (doom--eln-file-name "/home/abdo/Work/Projects/dotfiles/emacs/.emacs.d/.lo
        (let* ((eln-name (doom--eln-file-name file)) (eln-file (doom--find-eln-fil
        (doom--eln-file-outdated-p "/home/abdo/Work/Projects/dotfiles/emacs/.emacs
        (if want-native-compile (doom--eln-file-outdated-p file))
        (or (if want-byte-compile (doom--elc-file-outdated-p file)) (if want-nativ
        (if (or (if want-byte-compile (doom--elc-file-outdated-p file)) (if want-n
        (while (consp --cl-var--) (setq file (car --cl-var--)) (if (or (if want-by
        (let* ((outdated nil) (--cl-var-- (doom-files-in build-dir :match "\\.el$"
        (or (file-newer-than-file-p repo-dir build-dir) (file-exists-p (straight--
    ! Extended backtrace logged to .local/doom.error.log
```

**Steps to reproduce:**
1. Update Doom to latest version
2. Run `doom sync`

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64
        path       (~/perl5/bin ~/.cargo/bin ~/.local/share/texlive//bin/x86_64-linux ~/.local/bin ~/.local/opt/llvm/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.local/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/Work/Projects/dotfiles/emacs/.emacs.d/
        version    27.1
        build      Sep 14, 2020
        buildopts  --prefix=/home/abdo/.local/ --with-json --with-modules --with-harfbuzz --with-compress-install --with-threads --with-included-regex --with-zlib --with-sound=alsa --without-gconf --with-mailutils --with-xft --with-xml2 --with-cairo --with-gconf --with-xwidgets --without-toolkit-scroll-bars 'CFLAGS=-O3 -mtune=native -march=native -fomit-frame-pointer -I/usr/lib/gcc/x86_64-linux-gnu/9/include/ -L/usr/lib/gcc/x86_64-linux-gnu/9'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GCONF GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running)
DOOM    dir        ~/Work/Projects/dotfiles/emacs/.config/doom/
        version    2.0.9
        font       #<font-object -DAMA-Ubuntu Mono-normal-normal-normal-*-17-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      HEAD -> develop 2ad1eab6e 2021-01-18 19:59:18 -0500
        elc-files  0
        modules    (:completion ivy :ui doom hl-todo modeline window-select :emacs dired ibuffer undo :checkers spell :tools magit pdf :os tty :lang emacs-lisp (latex +latexmk) markdown yaml :email mu4e :config literate (default +bindings) :my-apps (&user org) (&user org-agenda) (&user email) (&user dired) (&user latex) (&user shell) (&user magit) :my-completion (&user ivy) :my-emacs (&user wind-mgmt) (&user paren))
        packages   ((hungry-delete) (openwith) (origami) (lsp-origami) (el-patch) (explain-pause-mode :disable t) (selectrum) (focus) (ace-jump-mode) (iedit) (aggressive-indent) (eglot) (flyspell-correct))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by honza** [comment] 2021-01-24 22:21
I'm also experiencing this

**Comment by haji-ali** [comment] 2021-01-25 10:04
I tried debugging this and found that the error is in `doom-cli-packages-build` [here](https://github.com/hlissner/doom-emacs/blob/fd7073240c5f71ba64b9b990f840edc4d7c52138/core/cli/packages.el#L312) where the package `org-mode` has the value `(:not autoloads)` as the `build` (not sure why). Then the [this line](https://github.com/hlissner/doom-emacs/blob/fd7073240c5f71ba64b9b990f840edc4d7c52138/core/cli/packages.el#L350) inverts the value of `build` causing the file to be built naitvely even though my Emacs 27.1 does not support native building.

**Comment by honza** [comment] 2021-01-25 13:10
I switched from the latest `native-comp` branch of emacs to `2.70.x` and now it works again.

**Comment by cdegroot** [comment] 2021-01-27 01:11
Duplicate of https://github.com/hlissner/doom-emacs/issues/4534 AFAICT

**Comment by haji-ali** [comment] 2021-01-27 07:02
I am running Emacs 27.1 without native compilation support

**Closed** 2021-01-27 08:01 UTC
Labels: is:bug

**Comment by hlissner** [comment] 2021-01-27 08:02
This was a case of over-aggressive negation, causing native-comp code to run for non-gccemacs users. As of 47f222a this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention.
