### ISSUE TITLE
counsel-find-file fallback to find-file

### ISSUE THREAD

**Issue by 00yk** [hlissner/doom-emacs#5857] opened 2021-12-02 09:43 UTC
### Describe your request

By looking at modules/completion/ivy/config.el and modules/completions/ivy/README.org, I saw that ``find-file`` is remapped to ``counsel-find-file``.
Is it possible to add a keymap for the original find-file while not messing up the ``counsel-find-file`` keymap?
Or is it possible to add a condition check for counsel-find-file, so that downstream users can modify the fallback behaviors on their needs? Thanks in advance for any ideas.
Currently, I maintained a patch file to the doom emacs repo. 
```patch
diff --git a/modules/completion/ivy/config.el b/modules/completion/ivy/config.el
index 2999e5c59..cc994b47b 100644
--- a/modules/completion/ivy/config.el
+++ b/modules/completion/ivy/config.el
@@ -191,7 +191,7 @@ results buffer.")
     [remap evil-show-registers]      #'counsel-evil-registers
     [remap evil-show-marks]          #'counsel-mark-ring
     [remap execute-extended-command] #'counsel-M-x
-    [remap find-file]                #'counsel-find-file
+    ;; [remap find-file]                #'counsel-find-file
     [remap find-library]             #'counsel-find-library
     [remap imenu]                    #'counsel-imenu
     [remap info-lookup-symbol]       #'counsel-info-lookup-symbol

```

### Briefly explain its use-case

1. When using tramp, ``find-file`` on a remote server is noticeably faster than ``counsel-find-file``, and I want to use ``find-file`` on a remote server with a keymap, rather than invoking the original ``find-file`` with M-x. At least in my experience, I saw a roughly 50% speed gain using ``find-file`` compared to ``counsel-find-file``.

**Comment by hlissner** [comment] 2021-12-02 13:43
You only need to undo the remapping from your private config: `(map! [remap find-file] nil)`.

If you want the remapping to be dynamic, you can adjust it by either writing your own dispatcher:

```elisp
(map! [remap find-file] (cmd! (call-interactively (if CONDITION #'counsel-find-file #'find-file))))
```

Or using Doom's `cmds!` macro:

```elisp
(map! [remap find-file] (cmds! CONDITION #'counsel-find-file
                               #'find-file)))
```

(`map!` isn't absolutely necessary here, it's just the most concise. `global-set-key`, `define-key!`, etc will work too)

-----

As this is a support request, and not a bug report or feature request, I will close this and mark it for deletion. Please use [the Discord](https://doomemacs.org/discord) for support in the future.

**Closed by hlissner** 2021-12-02 13:43 UTC
Labels: invalid, delete me
