### ISSUE TITLE
Company not working with java

### ISSUE THREAD

**Issue by asmodeus812** [hlissner/doom-emacs#6207] opened 2022-03-19 19:19 UTC
### What did you expect to happen?

When i open a java project which i add with SPC p a then open it with SPC p p and select a java file from the project. Jdtls starts and runs in the buffer, lsp as well. I can jump around source code within the project or jump in sources from java core or spring for example. 

### What actually happened?

Once i try to type java code such as List|stop here  or new Array|stop here| nothing is suggested. Same issue with local variables which are already defined, i start to type the name of the variable nothing is proposed. Further more sometimes the complete window is shown but it contains garbage, i.e completely unrelated functions/symbols to what i am writing in the buffer. 
Writing the start of List suggests something completely unrelated
![image](https://user-images.githubusercontent.com/15955811/159135291-550428cc-e92f-477c-a45a-8c8a95017c1e.png)
When i start typing new Array, it shows no completions found even if i force with ctrl spc. 
![image](https://user-images.githubusercontent.com/15955811/159135306-0a1cffec-e4a5-470c-a48f-b378a6d6e93a.png)
Starting to write this variable consumerProperties is even weirder if i write co|stop the variable is suggested at the top. If i write con|stop it vanishes from the list and garbage is shown
![image](https://user-images.githubusercontent.com/15955811/159135447-0112e2dc-4a0e-4906-83a0-2876334a69f2.png)

### Describe your attempts to resolve the issue

```
(setq create-lockfiles nil
      make-backup-files nil
      tramp-default-method "ssh"

      evil-shift-width 2
      evil-default-state 'normal
      evil-move-cursor-back nil
      evil-want-Y-yank-to-eol t
      evil-want-C-i-jump t
      evil-want-C-w-delete t
      evil-want-C-u-delete t
      evil-want-C-u-scroll t
      evil-want-C-d-scroll t
      evil-auto-indent t
      evil-indent-convert-tabs t
      evil-move-beyond-eol t
      evil-track-eol t
      evil-backspace-join-lines t
      evil-want-fine-undo t
      evil-undo-system 'undo-redo
      evil-show-paren-range 0
      evil-echo-state t

      gc-cons-threshold (* 300 1024 1024)
      read-process-output-max (* 3 1024 1024)
      lsp-restart 'auto-restart
      lsp-enable-folding nil
      lsp-idle-delay 0.1
      lsp-enable-links nil
      lsp-log-io nil

      helm-autoresize-mode t
      helm-buffer-max-length nil
      helm-autoresize-max-height 25
      helm-autoresize-min-height 25
      helm-case-fold-search 'smart
      helm-split-window-state 'horizontal
      helm-split-window-default-side 'below
      helm-window-prefer-horizontal-split t

      treemacs-indentation                     1
      treemacs-space-between-root-nodes        nil
      treemacs-indentation-string              " "
      treemacs-wide-toggle-width               55
      treemacs-width                           35
      treemacs-width-increment                 1
      treemacs-show-hidden-files               t
      treemacs-expand-after-init               t
      treemacs-follow-after-init               t
      treemacs-show-cursor                     nil
      treemacs-default-visit-action            'treemacs-visit-node-close-treemacs

      projectile-enable-caching t
      projectile-indexing-method 'alien
      projectile-completion-system 'helm
      projectile-sort-order 'recently-active
      projectile-after-switch-project-hook #'treemacs-add-and-display-current-project

      company-idle-delay 0
      company-selection-wrap-around t
      company-minimum-prefix-length 1

      lsp-lens-enable t
      lsp-restart 'auto-restart
      lsp-keep-workspace-alive t
      lsp-headerline-breadcrumb-enable nil

      lsp-use-lsp-ui t
      lsp-ui-peek-enable t
      lsp-ui-peek-always-show t

      lsp-ui-doc-delay 0.2
      lsp-ui-doc-show-with-mouse t
      lsp-ui-doc-show-with-cursor nil

      lsp-ui-sideline-enable t
      lsp-ui-sideline-show-hover nil
      lsp-ui-sideline-show-symbol nil
      lsp-ui-sideline-show-diagnostics t
      lsp-ui-sideline-show-code-actions nil

      lsp-clients-clangd-args '("-j=4" "--header-insertion-decorators=0" "--clang-tidy" "--background-index" "-log=error")

      lsp-java-format-enabled t
      lsp-java-format-comments-enabled t
      lsp-java-format-settings-profile "GoogleStyle"
      lsp-java-format-settings-url "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml"

      lsp-java-code-generation-hash-code-equals-use-java7objects t
      lsp-java-code-generation-hash-code-equals-use-instanceof t
      lsp-java-code-generation-to-string-list-array-contents t
      lsp-java-code-generation-generate-comments t
      lsp-java-save-action-organize-imports t
      lsp-java-code-generation-use-blocks t

      lsp-java-maven-download-sources t
      lsp-java-import-gradle-enabled t
      lsp-java-import-maven-enabled t

      lsp-java-vmargs '("-XX:+UseParallelGC" "-XX:GCTimeRatio=4" "-XX:AdaptiveSizePolicyWeight=90" "-Xmx2048m" "-Xms256m"))
```

### Steps to reproduce

My configuration for packages is as follows

<snip> (redundant with M-x doom/info)

### System Information

https://pastebin.com/TXPmphiW

**Comment by hlissner** [comment] 2022-03-19 19:44
If you've confirmed that the server is running and `*lsp-log*` shows no errors or warnings, then this is most likely a local configuration issue. I.e. Your LSP client needs additional configuration (E.g. through some manner of project files). As I am not a Java developer, I won't be much help investigating this in any depth, but as Doom does very little beyond connecting the parts -- and the parts appear to all be working in isolation -- then I'm inclined to suspect Doom is not the issue.

You could try unpinning the java module's packages (maybe lsp-mode too):

```elisp
;; in $DOOMDIR/packages.el
(unpin! (:lang java) (:tools lsp))
```

Then run `doom sync -u` and restart Emacs.

If that doesn't work, you'll have better luck seeking help from either [lsp-mode](https://github.com/emacs-lsp/lsp-mode) (they have a Discord), its [documentation for Java](https://emacs-lsp.github.io/lsp-java/), or the project page for whichever Java LSP client you are using.

That said, since this issue is unactionable, I will close it, but feel free to follow up here. I will reopen it if I later discover Doom is truly the cause.

**Closed by hlissner** 2022-03-19 19:44 UTC
Labels: invalid
