### ISSUE TITLE
Golang coding environment high time delay

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#1245] opened 2019-03-12 06:39 UTC
As described in the title, perhaps not restricted to the language. But after I set up my environment I found that code navigation and completion are quite slow.

**Comment by andyafter** [comment] 2019-03-12 06:43
delay at typing, formating, error checking and etc.

**Comment by hlissner** [comment] 2019-03-12 06:59
Is it possible you've enabled the new `:ui indent-guides` module? It's known to cause slowdowns.

If not, try profiling Emacs with `SPC h t` to start, then again to stop and see a report.

Otherwise, please include your `M-x doom/info`.

**Comment by andyafter** [comment] 2019-03-12 10:13
![image](https://user-images.githubusercontent.com/3354145/54192232-6e9bf600-44f2-11e9-8d33-aed3de89f9a8.png)
Here is what I logged with a couple definition jumping. Seems that file opening in general might be taking the time. Any idea about that?

**Comment by ccressent** [comment] 2019-03-12 19:39
Something similar to what you are describing happened to me a week or 2 ago. Doing anything in a buffer (moving up and down, inserting text, ...) would become incredibly slow and get slower and slower over time. This happened in both go-mode and org-mode buffers.

I spent a bit of time trying to profile and slowly disable minor modes, to no avail. In the end, I noticed that killing such a slow buffer (`SPC b k`) and opening the file again to create a fresh buffer solved the issue temporarily. Have you tried that?

Ultimately, I upgraded to Emacs 27 and upgraded Doom and the problem doesn't seem to be showing its head anymore...

**Comment by hlissner** [comment] 2019-03-13 05:35
@ccressent I believe you're describing a bug that snuck into solaire-mode for a couple days. [I've long since fixed that upstream](https://github.com/hlissner/emacs-solaire-mode/commit/acfe106704e5a7a54e2282cbae838b9e3ae8a042).

@andyafter That small snapshot of the profiler report is too small to glean anything from it. That said, it occurs to me that Emacs has to spawn a shell to run those external processes; it is possible your shell config is slow to start up (easily the case if you use a tool like pyenv, rbenv or any *env manager, with a line like `rbenv --init` in your shell config -- you can get around this by adding `--no-rehash` to it).

**Comment by hlissner** [comment] 2019-04-02 05:12
@andyafter Does this occur in other major modes, or only go-mode?

**Comment by hlissner** [comment] 2019-07-13 12:57
@andyafter Is this still an issue?

**Comment by jahkeup** [comment] 2019-08-14 18:26
I've seen my golang editing experience impacted in a similar manner, but don't have hard evidence or info to share or to even say its the "same" issue per-se. If I can confirm and pin down an issue in my setup I'll report back here :+1:

**Comment by ccressent** [comment] 2019-08-16 18:10
I've also started to be impacted by really slow completion and go to definition times since my last doom update a week or so ago. That also _seems_ to coincide with my project moving to using Go modules.
 
Sorry it's just anecdotal, and unfortunately I won't have time to profile and try to pinpoint the root cause for at least a few weeks... but it sounds like there might be something to unearth here.

**Comment by honza** [comment] 2020-04-09 19:03
I experience this, too.

**Comment by honza** [comment] 2020-04-09 19:44
`SPC h t` seems to have been removed since the comment above was made. How can I run this profiling today?

**Comment by doansson** [comment] 2020-04-15 07:45
@honza `SPC h T`

I'm experiencing a lot of delay after setup (go +lsp). I can't even open a specific go file on my system, emacs hangs. I waited 5min before killing emacs.
Tell me if you need more data for the profiler.

![](https://i.imgur.com/b1pm2HX.png)
How can I export my profiler result instead of doing a screenshot ?

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      aoû 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 1cb753cbb 2020-04-14 19:27:33 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.6.4-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 13 Apr 2020 12:21:24 +0000 x86_64
        path       (~/bin ~/go/bin /usr/local/sbin ~/bin ~/go/bin /usr/local/bin ~/bin ~/go/bin /usr/bin ~/bin ~/go/bin /opt/cuda/bin ~/bin ~/go/bin /var/lib/flatpak/exports/bin ~/bin ~/go/bin /usr/lib/jvm/default/bin ~/bin ~/go/bin /usr/bin/site_perl ~/bin ~/go/bin /usr/bin/vendor_perl ~/bin ~/go/bin /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp go markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by doansson** [comment] 2020-04-15 09:24
I remove all the Go packages and the delays are gone but as soon I reinstall gocode, the delays reappear.
I saw on gocode's page that gopls is recommended way forward. In the module doc I read:
`lsp Enables integration for the gopls LSP server.`

But I'm not sure how to set it up with doom since since it seems it needs gocode.
`eldoc error: (file-missing Searching for program No such file or directory gocode`

**Comment by doansson** [comment] 2020-04-15 10:23
Some folks helped me on Discord.
I had `go +lsp` instead of `(go +lsp)` :facepalm: 

You need to have gopls installed:
`GO111MODULE=on go get golang.org/x/tools/gopls@latest`

after that everything work and it isn't slow.
Thanks to jara and Moussx for the help

**Comment by hlissner** [comment] 2020-04-18 02:30
It seems that a couple packages in the non-LSP Go stack is no longer maintained, and is falling out of vogue in favor of gopls. As of e62f64d I've changed the docs and defaults to encourage +lsp use. I do need some help from go users to update the README however. As I'm not a go programmer, I don't know which of these tools are necessary to install with gopls present. Any advice would be appreciated!

**Closed** 2020-04-18 02:31 UTC
Labels: :lang go, is:external, re:performance, status:has-workaround, status:nofix

**Comment by honza** [comment] 2020-04-27 20:39
My slowness was caused by the `pretty-code` module. Disabling it made everything suddenly *very* fast.

**Comment by kujohn** [comment] 2020-12-02 00:19
I am getting this issue as well, there are some other go projects that doesn't have this slowness while another encounter this issue.
