### ISSUE TITLE
Backspace isn't working?

### ISSUE THREAD

**Issue by Alfar435** [hlissner/doom-emacs#3110] opened 2020-05-13 02:37 UTC
When in insert mode backspace does not work.

Buffer showed message attached in picture.

<img width="626" alt="Screen Shot 2020-05-12 at 10 33 48 PM" src="https://user-images.githubusercontent.com/65266649/81765058-e6700280-94a0-11ea-977e-0da18838735c.png">

I don't think this is user error so hopefully this is the right way to report this.

Thanks!

**Comment by hlissner** [comment] 2020-05-13 02:41
My bad. This was caused by some carelessness in 82ddc8633. This should be fixed as of a7c2cba. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Closed** 2020-05-13 02:40 UTC
Labels: is:bug

**Comment by Alfar435** [comment] 2020-05-13 02:45
Awesome! Thanks for the quick response.
