### ISSUE TITLE
`d d` does not a folded org tree when there is no newline at the end

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#4753] opened 2021-03-08 10:42 UTC
**What did you expect to happen?**
Typing `d d` in normal mode on a line with a folded org tree deletes it, even if the last heading on the tree is at the end of the buffer with no newline.

**What actually happened?**
Nothing happens (no error is raised, and the tree remains).

**Additional Information**
- `d $` deletes the tree
- `y y` does not yank the tree
- adding a newline at the end of the buffer results in `d d` working as expected

**Steps to reproduce:**
1. Create an org file with the following
```org
* Test
** folded (do not include a new line after this heading)
```
2. Fold the tree (`TAB` on the `* Tree` line)
3. Type `d d`

**System information:**
I cannot run `doom-info` at the moment, I get the following backtrace:
```
➜ bin/doom info
x There was an unexpected error
  Message: Args out of range
  Data: (args-out-of-range . "")
  Backtrace:
    (substring "" 0 9)
    (list emacs-version emacs-repository-branch (substring (or emacs-repositor
    (delq nil (list emacs-version emacs-repository-branch (substring (or emacs
    (cons 'emacs (delq nil (list emacs-version emacs-repository-branch (substr
    (cons (cons 'emacs (delq nil (list emacs-version emacs-repository-branch (
    (cons (cons 'distro (list (doom-system-distro-version) (sh "uname" "-msr")
    (cons (cons 'generated (format-time-string "%b %d, %Y %H:%M:%S")) (cons (c
    (progn (fset #'symlink-path vnew) (ignore symlink-path) (cons (cons 'gener
    (unwind-protect (progn (fset #'symlink-path vnew) (ignore symlink-path) (c
    (let* ((vnew #'(lambda (file) (let ((truefile (file-truename file))) (form
! Extended backtrace logged to .local/doom.error.log
```

Here is my previous doom info, the only change is that I’m at commit cf44c43 on branch develop:
```
SYSTEM  info       ("Arch Linux" . Linux 5.11.2-arch1-1 x86_64)
        shell      /bin/zsh
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.opam/4.10.0/bin ~/bin ~/go/bin ~/.opam/4.10.0/bin ~/.nvm/versions/node/v10.21.0/bin ~/bin ~/go/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    (27.1 Aug 28, 2020)
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    (2.0.9 HEAD -> develop 5d9efe89b 2021-03-04 16:42:27 -0500)
        font       #
        theme      leuven
        modules    (:input (layout +bepo) :completion (company +childframe) (ivy +icons) :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs (dired +icons) electric undo vc :term eshell :checkers syntax (spell +flyspell) :tools (eval +overlay) lookup magit make (pass +auth) pdf :lang coq data emacs-lisp javascript latex ledger lua markdown ocaml (org +gnuplot +roam +noter +pretty) sh :email notmuch :app calendar irc (rss +org) :config literate (default +bindings +smartparens))
        packages   ((ebdb) (emojify) (org-review) (xah-replace-pairs) (org-ref) (gnuplot) (ts) (magit-todos :disable t) (elpher) (org-roam-bibtex) (leuven-theme) (unicode-fonts) (beacon) (xah-math-input) (lexic :recipe (:host github :repo tecosaur/lexic)))
        unpin      (org-ref)
        elpa       (n/a)
```

**Comment by hlissner** [comment] 2021-03-08 15:28
Duplicate of #2447

**Closed by hlissner** 2021-03-08 15:28 UTC
Labels: duplicate

**Comment by brabalan** [comment] 2021-03-08 15:36
Thanks, I applied the workaround suggested there.
