### ISSUE TITLE
yas error in org capture templates

### ISSUE THREAD

**Issue by rgrinberg** [hlissner/doom-emacs#1527] opened 2019-07-01 05:56 UTC
Happens when I type anything after a capture and hit the space button:

```
Debugger entered--Lisp error: (wrong-type-argument overlayp nil)
  overlay-start(nil)
  yas--snapshot-overlay-location(nil 40 103)
  yas--auto-fill()
  internal-auto-fill()
  self-insert-command(1)
  org-self-insert-command(1)
  funcall-interactively(org-self-insert-command 1)
  call-interactively(org-self-insert-command nil nil)
  command-execute(org-self-insert-command)
```

**Comment by hlissner** [comment] 2019-07-01 09:16
This appears to be a duplicate of https://github.com/hlissner/doom-emacs/issues/1401.

**Closed by hlissner** 2019-07-01 09:16 UTC
Labels: is:duplicate
