### ISSUE TITLE
LSP error when file path begins with `//`

### ISSUE THREAD

**Issue by osenvosem** [hlissner/doom-emacs#4224] opened 2020-11-06 13:13 UTC
When I open Doom it starts from the path `//` (filesystem root, with double slashes for some reason)

![Screenshot 2020-11-06 at 16 02 25](https://user-images.githubusercontent.com/6762673/98369883-bae26500-204a-11eb-813e-1277412ba61e.jpg)

if then I open some file, it causes an error in LSP mode

![Screenshot 2020-11-06 at 16 04 16](https://user-images.githubusercontent.com/6762673/98369910-c5046380-204a-11eb-90eb-b782a853b253.jpg)

If I restart the editor using `SPC q r`, it will restart in the user home folder

![Screenshot 2020-11-06 at 16 09 56](https://user-images.githubusercontent.com/6762673/98369986-e2393200-204a-11eb-99b0-81012537f053.jpg)

and in this case, there is no error.

That seems to be a bug.

**Comment by wraithm** [comment] 2020-11-08 22:05
I'm experiencing something similar. I'm also on macos.

**Comment by innerout** [comment] 2020-11-14 09:48
Can you post your `doom info` report?

**Comment by hlissner** [comment] 2020-11-15 13:22
> When I open Doom it starts from the path // (filesystem root, with double slashes for some reason)

Sounds like an issue with the method you're using to launch emacs. Please include your `M-x doom/info` and some steps to reproduce. In the future _please do not ignore our issue template_.

**Comment by osenvosem** [comment] 2020-11-15 14:10
@hlissner I reinstalled doom and now can't reproduce the issue (steps are simple, just open doom). But I'm not the only one who experienced this issue.

Here is my doom/info:

<details>
<pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
        path       (/var/folders/1t/d2tthcgx6pqd831qg5nbc5vm0000gn/T/fnm_multishell_40948_1605426778958/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /usr/local/opt/mongodb-community@4.2/bin ~/.gem/ruby/2.6.0/bin ~/Library/Android/sdk/emulator ~/.cargo/bin /usr/local/sbin ~/.config/doom.d/bin ~/.fzf/bin /usr/local/Cellar/emacs-plus@27/HEAD-109eb1e/libexec/emacs/27.1.50/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/Dropbox/appdata/.config/doom.d/
        version    27.1.50
        build      Nov 10, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/HEAD-109eb1e/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/HEAD-109eb1e --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running chemacs envvar-file)
DOOM    dir        ~/Dropbox/appdata/.config/doom/
        version    2.0.9
        font       #<font-spec nil nil JetBrains Mono nil nil nil nil nil 14 nil nil nil nil>
        theme      doom-one
        build      HEAD -> develop aa02dc14a 2020-11-14 18:42:31 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo ligatures minimap modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp (json +lsp) (javascript +lsp) markdown org rest sh (web +lsp) yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre>
</details>

**Comment by wraithm** [comment] 2020-11-16 16:01
I am still experiencing weird issues with the path being `//` on boot. Here's my doom info:

```
SYSTEM  type       darwin
	config     x86_64-apple-darwin18.7.0
	shell      /bin/zsh
	uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
	path       (~/.local/venv/bin ~/.cabal/bin ~/.ghcup/bin /usr/local/opt/llvm@6/bin /usr/local/opt/sqlite/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin ~/.local/bin ~/.cargo/bin ~/.fzf/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Aug 12, 2020
	buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
	features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER
	traits     (batch envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop 92c9127b8 2020-11-07 00:20:07 -0500
	elc-files  0
	modules    (:completion company (ivy +fuzzy +prescient) :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe :editor (evil +everywhere) file-templates snippets :emacs dired electric ibuffer undo vc :term eshell vterm :checkers syntax :tools ansible (eval +overlay) lookup (lsp +peek) (magit +forge) terraform :os macos :lang cc data emacs-lisp (haskell +lsp) json (javascript +lsp) markdown (org +gnuplot +pandoc) python sh web yaml :config (default +bindings))
	packages   ((rg) (ix) (dash-at-point) (vagrant-tramp) (logstash-conf) (exec-path-from-shell) (haskell-snippets) (ormolu) (dhall-mode) (bazel-mode))
	unpin      (n/a)
	elpa       (n/a)
```

**Comment by wraithm** [comment] 2020-11-16 16:58
Btw, I noticed that if I start doom on the commandline (GUI or `-nw`), it seems fine. If I start GUI doom (as a client connecting to a server or just standalone GUI), then Doom starts in `//`.

**Comment by the-cobalt** [comment] 2020-11-17 03:45
@wraithm 
> Btw, I noticed that if I start doom on the commandline (GUI or -nw), it seems fine. If I start GUI doom (as a client connecting to a server or just standalone GUI), then Doom starts in //.

Hmm, I know that if you start Emacs from the Emacs.app in the application menu (haven't used MacOS in a while so sorry if something is wrong here) it's isolated somewhat. Maybe this is a byproduct of that?

**Comment by tam5** [comment] 2020-11-17 13:59
It seems like a change from emacs26 -> emacs27, and not related at all to doom.

I found this https://github.com/d12frosted/homebrew-emacs-plus/issues/220 which led me to this: https://lists.gnu.org/archive/html/help-gnu-emacs/2020-04/msg00232.html.

I'm not sure what proper solution is, but 

```elisp
(setq default-directory "~/")
```
in config seems to do the trick.

**Comment by wraithm** [comment] 2020-11-17 17:07
@tam5 Thanks! That fixed my issue.

@hlissner Maybe Doom should do `(setq default-directory "~/")` in Emacs if the version is 27 and on macOS?

**Comment by hlissner** [comment] 2020-11-21 00:04
This issue stems from the fact that some builds of Emacs (on macOS) will launch Emacs in an isolated environment, where the "current working directory" is `/` or `//`. Emacs (and Doom) are working as intended here, by setting `default-directory` to the directory Emacs was started from. That it wasn't started from the directory you are expecting I consider a bug with the method being used to launch it.

Setting `default-directory` in your private config is an acceptable workaround, but not an acceptable solution upstream, because it interferes with folks with sane launchers, that want to open Emacs "from" a directory. This especially harms terminal users.

Since this isn't a Doom issue I will close this issue.

**Closed by hlissner** 2020-11-21 00:04 UTC
Labels: :os macos, is:external, status:backlog

**Comment by wraithm** [comment] 2020-11-21 01:18
Awesome! Thanks. Keep up the great work! I absolutely love Doom.
