### ISSUE TITLE
`SPC t i` and `SPC t h` does not work

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1396] opened 2019-05-09 19:35 UTC
`SPC t i` (`indent guides`) does not work when `indent-guides` module is disabled, with error (`command-execute: Wrong type argument: commandp, highlight-indent-guides-mode`). This by itself is fine, however this option shouldn't even appear when `indent-guides` module is disabled.

`SPC t h` (`impatient mode` does not work with error (`command-execute: Wrong type argument: commandp, +impatient-mode/toggle`).

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (mai 03, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop e173fcbd 2019-05-06 22:13:31 -0400)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 4.19.40 #1-NixOS SMP Sun May 5 12:42:41 UTC 2019 x86_64
  modules:   (:completion company (ivy +fuzzy) :ui doom hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric eshell imenu term vc :tools ansible docker eval flycheck (lookup +docsets) magit make rgb terraform :lang cc clojure data elixir emacs-lisp hy javascript markdown nix (org +attach +babel +capture +export +habit +present +protocol) python ruby (sh +zsh) web :config default)
  packages:  (flymd lispyville sort-words uuidgen xterm-color (frame-fns :recipe (frame-fns :fetcher github :repo emacsmirror/frame-fns)) (frame-cmds :recipe (frame-cmds :fetcher github :repo emacsmirror/frame-cmds)) (zoom-frm :recipe (zoom-frm :fetcher github :repo emacsmirror/zoom-frm)))
  exec-path: (~/dev/nu/ios-cli ~/dev/nu/nucli ~/dev/nu/nudev ~/.npm-packages/bin ~/.emacs.d/bin ~/.local/bin /nix/store/xf59s14j0x8l34agxiq6n1rn54wia3b1-kitty-0.13.3/bin /nix/store/4y5lv3a8s42wd0w0wga9sfflf6x0s5wg-imagemagick-6.9.9-34/bin /nix/store/k1gmlgblqqywmnzqxzlm0a2473r14zx5-xsel-unstable-2018-01-10/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/thiagoko/bin /nix/store/fmy7gm1sz3bdi3crnhb5id7a01xwfgn3-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```

**Comment by hlissner** [comment] 2019-05-09 20:06
This is expected (albeit undesirable) behavior. This is technically a duplicate of #1312. You'll find an explanation of the problem and why it hasn't been addressed (and may not be addressed) [in this answer](https://github.com/hlissner/doom-emacs/issues/1312#issuecomment-480650364).

+ To fix `SPC t i`, enable the `:ui indent-guides` module.
+ To fix `SPC t h`, enable the `:collab impatient-mode` module.

**Closed by hlissner** 2019-05-09 20:06 UTC
