### ISSUE TITLE
had to comment module in init.el  to use custom recipe for included package

### ISSUE THREAD

**Issue by dingowizard** [hlissner/doom-emacs#6115] opened 2022-02-15 16:31 UTC
### What did you expect to happen?

After following instructions at [Changin a recipe for an included package](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#changing-a-recipe-for-an-included-package), I expected that I could use my own version of the package by adding a '(package! ..)' line in packages.el and running 'doom sync -u'

### What actually happened?

The custom recipe was not used.

### Describe your attempts to resolve the issue

I commented out the line for the module in init.el, then ran 'doom sync -u". After this my package recipe was used.

### Steps to reproduce

1. add "(package! lsp-mode :recipe (:host github :repo "razzmatazz/lsp-mode" :branch "lsp-fsharp-installation-update"))"
to packages.el
2. run 'doom sync -u'

### System Information

https://pastebin.com/NZmMppez

**Comment by hlissner** [comment] 2022-02-15 18:50
You need to unpin or de-pin the package. e.g.

```lisp
(package! lsp-mode
  :recipe (:host github
           :repo "razzmatazz/lsp-mode"
           :branch "lsp-fsharp-installation-update"))
(unpin! lsp-mode)
```

This is a known issue and will be fixed with #4273. I'll treat this as a duplicate of that issue and close this, but feel free to follow up here.

**Closed by hlissner** 2022-02-15 18:50 UTC
Labels: duplicate
