### ISSUE TITLE
Having problems with ivy/counsel

### ISSUE THREAD

**Issue by vharish** [hlissner/doom-emacs#291] opened 2017-12-16 18:07 UTC
Hi. I am having problems getting counsel to work with the default setup as described in the README. 
```
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
cd ~/.emacs.d
cp init.example.el init.el  # maybe edit init.el
make install
```

I tried this with emacs 25.3 both on Ubuntu and MacOS High Sierra. The counsel commands does not seem to be working. Hitting `M-x` gives the following errors. 
`Wrong type argument: commandp, counsel-M-x`
Similarly for other counsel commands. `counsel-projectile-find-file` etc. 

Please let me know if you need any other information.

**Comment by dswinters** [comment] 2017-12-16 19:40
I am having the same issue on MacOS Sierra since updating recently. Currently working around this by adding `(require 'counsel)` to my private init.el.

**Comment by hlissner** [comment] 2017-12-17 06:26
This is actually a duplicate of #286, so I'm closing this issue.

That said, your issue is caused by my misunderstanding of `use-package`'s :defer and :after mechanics, which was fixed recently in the `develop` branch as part of #286 in https://github.com/hlissner/doom-emacs/commit/9d81bc5a8b1be7ae03dd595cea2170dbb8edab2d.

As of an hour ago, this fix is now merged into `master`, so updating Doom should resolve this. 

If it doesn't, please refer to #286.

**Closed by hlissner** 2017-12-17 06:26 UTC

**Comment by vharish** [comment] 2017-12-17 09:49
@hlissner  @dswinters Sure. Thanks for the help.
