### ISSUE TITLE
Wrong ligature symbols when using pretty-code module

### ISSUE THREAD

**Issue by Althorion** [hlissner/doom-emacs#797] opened 2018-08-10 16:38 UTC
### Observed behavior

Ligatures are not showing correctly. For example, typing `<= != ->` shows with `(setq doom-font (font-spec :family "Fira Code" :size 14))` in `config.el` and `(pretty-code +fira)` as:
![firaemacs](https://user-images.githubusercontent.com/2023640/43969817-ac47ddea-9ccb-11e8-8b0e-6300ee74cda3.png)
Or with `(setq doom-font (font-spec :family "Iosevka" :size 14))` and `(pretty-code +iosevka)`:
![iosevkaemacs](https://user-images.githubusercontent.com/2023640/43969859-cbc0e7e8-9ccb-11e8-8bcc-7fcabc9ebff1.png)

### Expected behavior

That’s how it should look (nvim in kitty using Fira Code):
![firanvim](https://user-images.githubusercontent.com/2023640/43969971-27dc32da-9ccc-11e8-91f8-212d778d03b5.png)

### Steps to reproduce

1. Set `pretty-code` module with ligatures from Fira Code or Iosevka (I don’t have Pragmata Pro font, so I can’t check for that).
2. Open any file with `pretty-code` turned on (lisp files will do, so a config file for example is a nice candidate).
3. Type some ligatures.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-solus-linux-gnu)
- Emacs: 26.1 (Jul 20, 2018)
- Doom: 2.0.9 (develop e33cb446aa9803577df7ba66c60e76da8e5b3f56)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux solus 4.17.11-84.current #1 SMP PREEMPT Sat Jul 28 13:53:22 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) (pretty-code +iosevka) vc-gutter vi-tilde-fringe window-select :emacs ediff electric eshell imenu term vc :tools gist magit :lang data emacs-lisp latex markdown (org +attach +babel +capture +export +present) python rust sh web :config)
  packages:  n/a
  exec-path: (~/bin /sbin /bin /usr/sbin /usr/bin /usr/local/bin /snap/bin /usr/lib64/emacs/emacs/26.1/x86_64-solus-linux)
  ```
```
</details>

**Comment by hlissner** [comment] 2018-08-10 16:55
This is a duplicate of #695. You have to use a forked version of iosevka and co for these ligatures to work. Refer to that thread for a download link to these fonts, as well as instructions on how to build them yourself.

Sorry for the lack of documentation on the subject, this will be resolved soon!

**Closed by hlissner** 2018-08-10 16:55 UTC
Labels: duplicate

**Comment by Althorion** [comment] 2018-08-10 17:16
Using custom font helped, thanks. But doesn’t the fact that it happens for (at least) two different fonts (not only Iosevka, but also Fira Code) suggest that’s something that should be changed with Emacs and not the fonts themselves?

**Comment by ar1a** [comment] 2018-08-15 05:08
I think Fira Code has it's own compilation for emacs ligatures too. I haven't used Fira Code for ages so I don't have the compiled fonts, but googling found me this file: https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip

You'd have to use the font "Fira Code Symbol" for the ligature though, the module is set to it by default - 
https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/pretty-code/+fira.el#L3

**Comment by jsravn** [comment] 2019-10-24 13:34
Maybe it'd be nice if the +iosevka module also downloaded the custom fonts? Similar to `all-the-icons.ttf`, etc.

**Comment by hlissner** [comment] 2019-10-24 17:46
I'll accept a PR for a `+pretty-code/install-iosevka-font` command.
