### ISSUE TITLE
F# mode with LSP is very slow

### ISSUE THREAD

**Issue by ohmree** [hlissner/doom-emacs#4153] opened 2020-10-25 19:22 UTC
**What did you expect to happen?**
I expected to be able to edit F# files comfortably.

**What actually happened?**
Any code window that has a F# buffer open becomes unbearably slow.  
Upon killing the F# buffer and/or switching to a different buffer (e.g. an elisp one) the editor becomes usable again.

**Additional details:**
- Include a link to your private config (https://github.com/ohmree/dotfiles/tree/main/.doom.d)
- I should mention that the profiler says the vast majority of the CPU time is spent on `command-execute` but I can't get it (the profiler) to show me what exactly calls it so much.

**Steps to reproduce:**
1. Enable `:tools lsp` and `:lang (fsharp +lsp)`.
2. Install `fsac` using `lsp-install-server`.
3. Open a F# file.

**System information:**
<pre>
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.9.1-zen2-1-zen #1 ZEN SMP PREEMPT Sun, 18 Oct 2020 02:45:20 +0000 x86_64
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin ~/.roswell/bin ~/.local/bin ~/.luarocks/bin ~/.cargo/bin ~/.yarn/bin /usr/local/sbin /usr/local/bin /usr/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Sep 25, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-pgtk --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -flto -fuse-linker-plugin -fuse-ld=gold -g -flto -fuse-linker-plugin -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 PGTK XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (daemon server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop d807a7513 2020-10-06 17:16:37 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo hydra ligatures minimap modeline nav-flash ophints (popup +defaults) tabs treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) lispy multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax spell grammar :tools (debugger +lsp) editorconfig (eval +overlay) gist (lookup +docsets) lsp (magit +forge) rgb :lang (cc +lsp) (clojure +lsp) common-lisp (csharp +unity +lsp) emacs-lisp (fsharp +lsp) (javascript +lsp) markdown org (rust +lsp) sh web :config (default +bindings +smartparens))
        packages   ((sly-named-readtables) (sly-quicklisp) (sly-asdf) (gnu-apl-mode) (company-tabnine) (pkgbuild-mode) (counsel-dash) (meson-mode))
        unpin      (dap-mode lsp-mode treemacs)
        elpa       (sly-quicklisp sly-asdf sly popup)
```
</pre></details>

**Comment by hlissner** [comment] 2020-10-29 07:03
Does `(setq-hook! 'fsharp-mode-hook company-idle-delay nil)` fix it?

**Comment by ohmree** [comment] 2020-10-30 14:33
I don't use F# anymore but I have faced similar issues with Rust, `setq-hook!`ing the variable for `rustic-mode` didn't help at all (at least not that I can tell).

It's so bad that sometimes I need to terminate Emacs.

I also tried eglot which is much faster but is very (very!) unreliable when it comes to keeping a steady connection to the language server (again, subjectively). I had to constantly call `M-x eglot` to reconnect and then do something like `SPC c a` or `K` on something, and then Emacs blocked for a while either it displayed the desired results or I ran out of patience and `C-g`'d it.

**Comment by adwhit** [comment] 2020-10-31 11:15
I have the same problem, I think. With Rust + LSP, after using it for a while it becomes unusably slow and emacs is pinned to 100% CPU (however `rust-analyzer` CPU usage is very low). I would be happy to help diagnose but would need some instruction.

**Comment by hlissner** [comment] 2020-11-02 05:40
This may also be caused by file watchers in larger projects. Try `(after! lsp-mode (setq lsp-enable-file-watchers nil))`

**Comment by ohmree** [comment] 2020-11-12 13:30
That doesn't seem to do too much, I still occasionally need to kill Emacs when working on Rust projects.

It might be performing a bit better though, I don't know how to measure accurately.

**Comment by adwhit** [comment] 2020-11-22 16:07
FYI I updated to from emacs 26.3 to 27.1 and it _seems_ to be working better now. I wonder if the problem was due to the lsp-server sending payload that were too large for the old json parser to keep up with (27.1 has a much-improved native parser). Will keep an eye on it.

**Comment by ohmree** [comment] 2020-11-22 16:46
I'm on emacs HEAD with nativecomp and pgtk ([this pkgbuild](https://aur.archlinux.org/packages/emacs-pgtk-native-comp-git/)) so that's probably not the issue for me.

**Comment by erasmas** [comment] 2020-11-29 20:24
I'm having the same issue when trying to open a file in an F# project with LSP. I can't figure out from sampling the `SPC SPC` what causing it to be so slow. 

Profiler report:
```
- command-execute                                                                            198417  99%
 - call-interactively                                                                        198315  99%
  - funcall-interactively                                                                    198315  99%
   - counsel-find-file                                                                       106099  53%
    - counsel--find-file-1                                                                   106099  53%
     - ivy-read                                                                              106099  53%
      - apply                                                                                106099  53%
       - ivy-posframe--read                                                                  106099  53%
        - apply                                                                              106099  53%
         - #<compiled 0x251ed0d>                                                             106099  53%
          - read-from-minibuffer                                                             105822  53%
           + ivy--queue-exhibit                                                               60258  30%
           - command-execute                                                                  45554  22%
            - call-interactively                                                              45554  22%
             - funcall-interactively                                                          45554  22%
              - counsel-find-file                                                             45553  22%
               - counsel--find-file-1                                                         45553  22%
                - ivy-read                                                                    45553  22%
                 - apply                                                                      45553  22%
                  - ivy-posframe--read                                                        45553  22%
                   - apply                                                                    45553  22%
                    - #<compiled 0x251ed0d>                                                   45553  22%
                       read-from-minibuffer                                                   45550  22%
                     + #<compiled 0x78e291>                                                       1   0%
              + handle-focus-in                                                                   1   0%
           + minibuffer-inactive-mode                                                             3   0%
          + ivy--reset-state                                                                    273   0%
          + ivy--compute-extra-actions                                                            1   0%
          + #<compiled 0x13440e5>                                                                 1   0%
   - counsel-projectile-switch-project                                                        92213  46%
    - ivy-read                                                                                92199  46%
     - apply                                                                                  92199  46%
      - ivy-posframe--read                                                                    92199  46%
       - apply                                                                                92199  46%
        - #<compiled 0x251ed0d>                                                               92199  46%
         - ivy-call                                                                           92110  46%
          - +workspaces-switch-to-project-h                                                   92109  46%
           - let                                                                              92094  46%
            - if                                                                              92094  46%
             - progn                                                                          92094  46%
              - unwind-protect                                                                92094  46%
               - if                                                                           92094  46%
                - if                                                                          92065  46%
                 - funcall                                                                    92065  46%
                  - doom-project-find-file                                                    92065  46%
                   - let*                                                                     92064  46%
                    - cond                                                                    92061  46%
                     - call-interactively                                                     92061  46%
                      - funcall-interactively                                                 92061  46%
                       - counsel-file-jump                                                    92061  46%
                        - ivy-read                                                            92056  46%
                         - apply                                                              92056  46%
                          - ivy-posframe--read                                                92056  46%
                           - apply                                                            92056  46%
                            - #<compiled 0x251ed0d>                                           92056  46%
                             - read-from-minibuffer                                           92045  46%
                              + ivy--queue-exhibit                                               18   0%
                              + redisplay_internal (C function)                                   3   0%
                              + minibuffer-error-function                                         3   0%
                             + #<compiled 0x7909b1>                                               1   0%
                        + counsel--find-return-list                                               5   0%
                    + doom-project-root                                                           3   0%
                     if                                                                           1   0%
                + save-current-buffer                                                            15   0%
                + condition-case                                                                 14   0%
           + load-with-code-conversion                                                           15   0%
         + read-from-minibuffer                                                                  67   0%
         + ivy--reset-state                                                                       7   0%
         + #<compiled 0x7a8965>                                                                   3   0%
    + projectile-prepend-project-name                                                             7   0%
    + projectile-project-p                                                                        7   0%
   + doom/toggle-profiler                                                                         3   0%
 + autoload-do-load                                                                              65   0%
+ ...                                                                                           319   0%
+ timer-event-handler                                                                            94   0%
+ redisplay_internal (C function)                                                                 6   0%
+ #<compiled 0x1fc01ec3c429>                                                                      1   0%

```

System info:
```
SYSTEM  type       gnu/linux
config     x86_64-pc-linux-gnu
shell      /run/current-system/sw/bin/fish
uname      Linux 5.4.77 #1-NixOS SMP Tue Nov 10 20:13:20 UTC 2020 x86_64
path       (/run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/3mkvcfxhc32xh6jbh2bkgfmxp6qij07w-emacs-27.1/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
version    27.1
build      Nov 29, 2020
buildopts  --prefix=/nix/store/3mkvcfxhc32xh6jbh2bkgfmxp6qij07w-emacs-27.1 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBEXIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
version    2.0.9
build      HEAD -> develop, origin/develop, origin/HEAD b91a1b3e7 2020-11-29 14:49:14 -0500
elc-files  0
modules    (:completion (company +childframe) (ivy +childframe +icons) :ui doom doom-dashboard hl-todo (modeline +light) nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools direnv editorconfig (eval +overlay) :checkers syntax spell :tools (lookup +docsets) lsp magit :lang clojure data emacs-lisp (fsharp +lsp) (haskell +dante) markdown nix (org +dragndrop +ipython +present) purescript (python +pyenv) sh yaml :config (default +bindings +smartparens))
packages   ((kibit-helper) (browse-at-remote))
unpin      (n/a)
elpa       (n/a)
```

Adding `(setq-hook! 'fsharp-mode-hook company-idle-delay nil)` didn't fix the issue for me.

**Comment by erasmas** [comment] 2020-11-29 20:35
Surprisingly, disabling `+icons` for `:ivy`, as suggested [here](https://github.com/hlissner/doom-emacs/issues/3718#issuecomment-672909979), fixed the issue for me. So, in my case the issue was not related to LSP. :partying_face:

**Comment by nbfalcon** [comment] 2020-12-10 19:47
Can you try `unpin`ing `lsp-mode`, `lsp-treemacs` and `lsp-ivy`, then syncing your config? The bug may have been fixed in master. Also, what does the slowness look like? I.e. do you have to wait for characters to appear, does switching buffers take a long time?

**Comment by nbfalcon** [comment] 2020-12-10 19:48
@ohmree do `M-x lsp-diagnose` and post the output.

**Comment by nbfalcon** [comment] 2020-12-10 19:49
Native `json` makes a huge difference for `lsp-mode`.

**Comment by ohmree** [comment] 2020-12-10 19:50
Is the `read-process-output-max` bit supposed to be like that?

```
Checking for Native JSON support: OK
Using company-capf: OK
Check emacs supports `read-process-output-max': OK
Check `read-process-output-max' default has been changed from 4k: ERROR
Byte compiled against Native JSON (recompile lsp-mode if failing when Native JSON available): OK
`gc-cons-threshold' increased?: OK
Using gccemacs with emacs lisp native compilation (https://akrl.sdf.org/gccemacs.html): OK
```

**Comment by nbfalcon** [comment] 2020-12-10 22:33
@ohmree DOOM should be setting `read-process-output-max` to 1MB, and it is set to that value in my environment. Try setting that variable to `(* 1024 1024)`. This might improve performance, depending on the server.

**Comment by nbfalcon** [comment] 2020-12-10 22:33
@ohmree DOOM should be setting `read-process-output-max` to 1MB, and it is set to that value in my environment. Try setting that variable to `(* 1024 1024)`. This might improve performance, depending on the server.

**Comment by nbfalcon** [comment] 2020-12-10 22:33
@ohmree DOOM should be setting `read-process-output-max` to 1MB, and it is set to that value in my environment. Try setting that variable to `(* 1024 1024)`. This might improve performance, depending on the server.

**Comment by hlissner** [comment] 2020-12-11 07:26
@ohmree Is Doom up-to-date? [Doom changes read-process-output-max for you](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/config.el#L37), so I can only imagine you're on a commit of Doom that predates that optimization.

**Comment by ohmree** [comment] 2020-12-12 11:15
Turns out doom was quite out of date, I tend to forget about updates when something just works.

So I tried doing `M-x doom-upgrade` and it results in an error:

```
-*- mode: compilation; default-directory: "~/code/rust/frick-dmca-client/.github/workflows/" -*-
Comint started at Sat Dec 12 13:01:52

/home/ohmree/.emacs.d/bin/doom -y upgrade
- Confirmations auto-accept enabled
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

  Old revision: d807a7513d (10 weeks ago)
  New revision: 1fba2ea303 (12 hours ago)

> Upgrading Doom Emacs...
  > Cleaning .elc files
    - No elc files to clean
  - From https://github.com/hlissner/doom-emacs
   * branch                develop    -> FETCH_HEAD
   * [new branch]          develop    -> _upgrade/develop
- Reloading Doom Emacs
Symbol’s value as variable is void: comp-deferred-compilation-deny-list

Comint exited abnormally with code 255 at Sat Dec 12 13:02:04
```

After that I tried running `doom upgrade` from the CLI, before and after restarting the Emacs systemd service and the only output I get is `Symbol’s value as variable is void: comp-deferred-compilation-deny-list`

Adding to that, when I start Emacs it's completely blank, no packages whatsoever.

Moving my `.emacs.d`, re-cloning doom and running `doom` installs `straight` and then results in the same error regarding `comp-deferred-compilation-deny-list`, and after that I get just the error when I run `doom`.

I also tried moving my `doom.d` temporarily to no avail - I get the same result.

**Comment by nbfalcon** [comment] 2020-12-12 17:01
@ohmree great! Does `lsp-mode` work fast enough now?

**Comment by hlissner** [comment] 2020-12-12 17:45
> Symbol’s value as variable is void: comp-deferred-compilation-deny-list

Duplicate of #3901, #4400, and #4417. Update gccemacs.

> I switched to emacs-gcc-wayland-devel-bin from the AUR and all seems to be well now

In that case, I'll assume this is resolved. Some LSP performance updates were deployed in October and November; [one of which was a memory leak](https://github.com/hlissner/doom-emacs/commit/1c7fd9c220b3a3cbe2295238f3a81e0453f7c3ee) which likely caused your issue since you were on an older version of commit according to your `M-x doom/info`.

**Closed by hlissner** 2020-12-12 17:45 UTC
Labels: :lang fsharp, :tools lsp, re:performance, status:investigating

**Comment by ohmree** [comment] 2020-12-13 11:07
> @ohmree great! Does `lsp-mode` work fast enough now?

It definitely feels faster and I no longer have to kill Emacs every once in a while because the UI becomes unresponsive, thanks a bunch for the help!
