### ISSUE TITLE
Which-key popup too small in emacsclient

### ISSUE THREAD

**Issue by TheSirC** [hlissner/doom-emacs#6264] opened 2022-04-07 06:44 UTC
### What did you expect to happen?

When typing <kbd>SPC</kbd> <kbd>w</kbd>, the which-key popup should have all of his lines visible.

### What actually happened?

When typing <kbd>SPC</kbd> <kbd>w</kbd>, the which-key popup is cropped but only using emacsclient.
![bug-hydra](https://user-images.githubusercontent.com/11771227/162135533-f2f7af17-54c0-4b79-97e3-852a72b7c452.png)

### Describe your attempts to resolve the issue

I searched in the `which-key` repository and there is an [issue upstream open](https://github.com/justbur/emacs-which-key/issues/306) for this problem but [the workaround given](https://github.com/justbur/emacs-which-key/issues/306#issuecomment-979285333) that seems to make consensus is not applicable (to my understanding) to this situation : 
as Doom is activating which-key how is this fix supposed to work ? How would I adapt it in the case of Doom ?

### Steps to reproduce

1. Connect to a Emacs daemon with a client
2. Type <kbd>SPC</kbd> <kbd>w</kbd>
3. See the bottom line cropped

### System Information

https://pastebin.com/w2yJnbHK

**Comment by noisycomputation** [comment] 2022-04-13 18:50
This may be a duplicate of #5622.

In any event, there are two workarounds:

- [This](https://github.com/hlissner/doom-emacs/issues/5622#issuecomment-946760888) worked for me, but I no longer use it in favor of
- [Adding a line to the which-key window](https://github.com/justbur/emacs-which-key/issues/231#issuecomment-627503184).

The possible crash issue deters me more than advising a which-key function because I might not immediately realize the origin of the crash when it happens, and that could lead to wasted time chasing it down. Upstream changes causing the advice to fail or malfunction _ought_ to be easier to identify.

I'm curious, are you using Wayland? I'm running a pgtk emacs (like you), and this issue only happens in Wayland sessions. When I run emacs in an X11 session, the spacing is perfect without the workaround. This could be useful information for upstream to resolve the issue, because it might have something to do with the limited ability of applications to know things about window positioning in Wayland. (This paragraph is a note for @hlissner, who will know better how to frame it to the `which-key` folks if the hunch is correct.)

**Comment by TheSirC** [comment] 2022-04-13 18:58
> This may be a duplicate of #5622.

It seems to be the same issue indeed ! Weird I could have sworn I searched thoroughly... Thanks ! 

>     * [Adding a line to the which-key window](https://github.com/justbur/emacs-which-key/issues/231#issuecomment-627503184).

That's the exact kind of answer I was searching for ! Thanks !
 
> The possible crash issue deters me more than advising a which-key function because I might not immediately realize the origin of the crash when it happens, and that could lead to wasted time chasing it down. Upstream changes causing the advice to fail or malfunction _ought_ to be easier to identify.

I share this analysis and approve of the conclusion !
 
> I'm curious, are you using Wayland? 

I am sorry to report that _I am not_ !

> (This paragraph is a note for @hlissner, who will know better how to frame it to the `which-key` folks if the hunch is correct.)

Should close this then ?

**Comment by noisycomputation** [comment] 2022-04-13 20:03
Glad I could help.

> Should close this then ?

Yes sir, no objections from here.

**Closed** 2022-04-17 15:57 UTC
Labels: 1. bug, needs-triage
