### ISSUE TITLE
Evil delete/change/yank (`d`/`c`/`y`) forward (`f`) to space does not include space

### ISSUE THREAD

**Issue by mplanchard** [hlissner/doom-emacs#6041] opened 2022-01-26 02:10 UTC
### What did you expect to happen?

Evil commands operating forward to space, e.g. `d f SPC`, should move up to and including the space, matching forward motion, e.g. `f SPC`, which moves to the space.

For example, with the text below, and the cursor in the indicated position:

```
here is some text
        ^
```

Pressing `d f SPC` should result in

```
here is text
```

The same should apply to changing (`c`) and yanking (killing in emacs parlance) (`y`).

### What actually happened?

Commands operating forward to a space, e.g. `d f SPC`, act only up to the space, not including the space itself, matching the expected behavior for `t` rather than `f`.

For example, with the text below and the cursor in the indicated position:

```
here is some text
        ^
```

Pressing `d f SPC` yields (note the extra space):

```
here is  text
```

This seems to happen regardless of major mode (including both text and fundamental mode), and can be replicated in the doom sandbox plus modules minus private config, but not vanilla doom. My colleague has also seen this issue on a fresh install of doom emacs, running emacs from the terminal rather than in GUI mode.

Note that this does _not_ affect forward motion, e.g. `f SPC`. That behaves as expected, moving the cursor to the next space character.

### Describe your attempts to resolve the issue

I verified that the issue doesn't seem to be coming from the default behavior of evil or any of the evil packages included by default in Doom by:

- Running emacs with `-q`, loading `evil` manually, and verifying the `d f SPC` behaves as expected
- Running emacs via doom's sandbox with vanilla doom, I enabled the following modes:
  - `evil`
  - `evil-escape-mode`
  - `evil-goggles-mode`
  - `evil-lion-mode`
  - `evil-markdown-mode`
  - `evil-mc-mode`
  - `evil-org-mode`
  - `evil-snipe-mode`
  - `evil-surround-mode`
  - `evil-tex-mode`
  - `evil-traces-mode`
  - `evil-vimish-fold-mode`
  - `evil-visualstar-mode`
  - After enabling each mode, I tested `d f SPC` and saw that it behaved as expected
- Running emacs via doom sandbox mode with doom + modules - private config. Here, the issue is present.

I also grepped through `~/.emacs.d` looking for settings that might be relevant, but I wasn't able to find anything obvious.

### Steps to reproduce

1. Open doom emacs
2. Open sandbox (`SPC h E`)
3. Open doom + modules - private config (`C-c C-p`)
4. Open any editable file
5. See that `d f SPC` does not delete up to and including the space

### System Information

https://pastebin.com/t2wX8771

**Comment by mplanchard** [comment] 2022-01-26 02:22
Update: i've actually traced this to `evil-snipe-override-mode`. Disabling that mode restores the expected behavior. I will open an issue there, too, but it would be nice if doom's default config did not trigger this.

**Comment by mplanchard** [comment] 2022-01-26 02:57
For now I have disabled with this line in my config:

```elisp
;; disable evil-snipe-override mode, which causes `d f SPC' and similar commands
;; to delete up to but not including the space
(add-hook! 'doom-first-input-hook ;; this is the mode that enables it
           :append ;; add to end of list so that ours executes last
           #'(lambda () (evil-snipe-override-mode -1)))
```

**Comment by hlissner** [comment] 2022-01-27 14:52
Duplicate of https://github.com/hlissner/evil-snipe/issues/86

**Closed by hlissner** 2022-01-27 14:52 UTC
Labels: duplicate, delete me

**Comment by hlissner** [comment] 2022-01-27 14:53
> For now I have disabled with this line in my config:

The hook can be more simply removed instead:

```elisp
(remove-hook 'doom-first-input-hook #'evil-snipe-override-mode)
```
