### ISSUE TITLE
[BUG] doom refresh failure (error (void-function sp-point-in-string))

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#2299] opened 2020-01-03 10:13 UTC
**What did you expect to happen?**
...

**What actually happened?**
...

**Additional details:**

<details><pre>
doom refresh
> Synchronizing your config with Doom Emacs...
  > (Re)generating core autoloads...
    > Generating core autoloads...
    > Byte-compiling core autoloads file...
    ✓ Generated .local/autoloads.elc
  > Installing & building packages...
    ✓ No packages need to be installed
  > (Re)building packages...
    ✓ No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating package autoloads...
    > Generating package autoloads...
x There was an unexpected error:
  Type: void-function
  Message:
    Symbol's function definition is void
  Data:
    sp-point-in-string

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d refresh

If you file a bug report, please include it!

</pre></details>

**Steps to reproduce:**
1. cd ~/.emacs.d
2. git pull
3. doom refresh

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP")
  (build . "Jan 03, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-1420906/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-1420906 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --without-pop --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop 8ff15c2ae 2020-01-03 02:44:29 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/coreutils/libexec/gnubin" "/usr/local/opt/gnu-tar/libexec/gnubin" "/usr/local/opt/openssl/bin" "/usr/local/lib/ruby/gems/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-remote-branch" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-machine" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/brew" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/osx" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/local/Cellar/emacs-plus/HEAD-1420906/libexec/emacs/27.0.60/x86_64-apple-darwin19.2.0"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :input chinese :completion company (ivy +prescient +fuzzy +childframe) :ui doom doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter (window-select +numbers) workspaces centered-cursor :editor file-templates lispy multiple-cursors rotate-text snippets :emacs (dired +ranger) electric (ibuffer +icons) vc :term eshell :tools docker editorconfig (eval +overlay) (flycheck +childframe) lookup lsp macos magit (youdao +childframe) :lang data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) (kotlin +lsp) markdown (org +dragndrop +hugo +ipython +pandoc +present +pomodoro +journal) plantuml rest (scala +lsp) sh (web +lsp) :config (default +bindings +smartparens))
  (packages "(fcitx :disable t)" "(pangu-spacing :disable t)" "(tide :disable t)" "(liberime-config :recipe (:host github :repo \"merrickluo/liberime\" :files (\"liberime-config.el\" \"src\" \"CMakeLists.txt\" \"Makefile\")))" "(company-english-helper :recipe (:host github :repo \"cxb811201/company-english-helper\"))" "(insert-translated-name :recipe (:host github :repo \"manateelazycat/insert-translated-name\"))" cal-china-x exec-path-from-shell hungry-delete "(go-impl :recipe (:host github :repo \"cxb811201/emacs-go-impl\"))" go-fill-struct sqlup-mode dap-mode)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2020-01-03 10:25
Sorry about that. This was caused by 8ff15c2ae, but should be fixed in 11676b0. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!

**Closed** 2020-01-03 10:24 UTC
Labels: is:regression, re:bin/doom, status:resolved
