### ISSUE TITLE
Unable to `doom sync` because package was not found

### ISSUE THREAD

**Issue by rzikm** [hlissner/doom-emacs#3220] opened 2020-05-26 06:21 UTC
**What did you expect to happen?**
Doom sync/upgrade upgrades the distribution

**What actually happened?**

```
❯ doom -d sync
- Debug mode on
> Synchronizing your config with Doom Emacs...

DOOM Initializing package.el
DOOM Initializing straight.el
←[31mx There was an unexpected error:←[0m
  ←[1mType:←[0m error
  ←[1mMessage:←[0m
    error
  ←[1mData:←[0m
    "Could not find package org-superstar in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)"

```

link to config:
https://github.com/rzikm/.doom.d

**System information:**
<details><pre>
❯ doom info
((emacs
  (version . "27.0.60")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP")
  (build . "Dec 28, 2019")
  (buildopts "--without-dbus --host=x86_64-w64-mingw32 --without-compress-install -C 'CFLAGS=-O2 -static -g3'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 101cd5019 2020-05-26 01:39:52 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . windows-nt)
  (config . "x86_64-w64-mingw32")
  (shell . "C:/Program Files/Emacs/x86_64/libexec/emacs/27.0.60/x86_64-w64-mingw32/cmdproxy.exe")
  (uname . "n/a")
  (path "c:/Program Files/ConEmu/ConEmu/Scripts" "C:/Program Files/ConEmu" "C:/Program Files/ConEmu/ConEmu" "C:/Python38/Scripts/" "C:/Python38/" "C:/Program Files/Oculus/Support/oculus-runtime" "C:/Python37/Scripts/" "C:/Python37/" "C:/Program Files (x86)/Common Files/Oracle/Java/javapath" "C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/" "C:/Program Files/Intel/Intel(R) Management Engine Components/iCLS/" "C:/Windows/system32" "C:/Windows" "C:/Windows/System32/Wbem" "C:/Windows/System32/WindowsPowerShell/v1.0/" "C:/Windows/System32/OpenSSH/" "C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL" "C:/Program Files/Intel/Intel(R) Management Engine Components/DAL" "C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT" "C:/Program Files/Intel/Intel(R) Management Engine Components/IPT" "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common" "C:/Program Files/Microsoft SQL Server/110/Tools/Binn/" "C:/ProgramData/chocolatey/bin" "C:/Program Files/Microsoft Windows Performance Toolkit/" "C:/Program Files/Git/cmd" "C:/Program Files (x86)/IncrediBuild" "C:/WINDOWS/system32" "C:/WINDOWS" "C:/WINDOWS/System32/Wbem" "C:/WINDOWS/System32/WindowsPowerShell/v1.0/" "C:/WINDOWS/System32/OpenSSH/" "C:/Program Files (x86)/Visual Leak Detector/bin/Win32" "C:/Program Files (x86)/Visual Leak Detector/bin/Win64" "C:/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin" "C:/Program Files/Java/jdk1.8.0_221/bin" "C:/Program Files/LLVM/bin" "C:/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin" "C:/Program Files (x86)/Gpg4win/../GnuPG/bin" "C:/Program Files/dotnet/" "C:/Program Files/TortoiseGit/bin" "C:/Program Files/TortoiseSVN/bin" "~/.cargo/bin" "~/scoop/shims" "~/AppData/Local/Microsoft/WindowsApps" "~/Documents/bin" "C:/Program Files/CMake/bin" "~/AppData/Local/Microsoft/WindowsApps" "~/.dotnet/tools" "C:/Program Files/Emacs/x86_64/bin" "~/AppData/Local/Pandoc/" "~/.emacs.d/bin" "." "c:/Program Files/Emacs/x86_64/libexec/emacs/27.0.60/x86_64-w64-mingw32"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company helm :ui doom doom-dashboard doom-quit fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell term :checkers syntax :tools (eval +overlay) gist (lookup +docsets) lsp magit make :lang cc csharp data emacs-lisp fsharp latex markdown (org +dragndrop +present) php python rst rust sh web :email (mu4e +gmail) :app calendar :config (default +bindings +smartparens))
  (packages (undo-tree) (hydra) (git-timemachine) (evil-collection) (pos-tip) (company) (counsel) (company-quickhelp) (company-web) (yasnippet) (yasnippet-snippets) (cmake-mode) (markdown-mode) (flymd) (impatient-mode) (edit-server) (which-key) (iedit) (yaml-mode) (powershell) (column-enforce-mode) (smerge-mode) (color-theme-sanityinc-tomorrow) (dap-mode) (multi-term) (powerline) (powerline-evil))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2020-05-26 06:36
This is a duplicate of #2802 and #2909. See #2802 (comment) for workaround.

**Closed by hlissner** 2020-05-26 06:36 UTC
Labels: is:duplicate
