### ISSUE TITLE
Doom upgrade fails: ... Emacs-wgrep ... Failed to get unambiguous name for "master" ...

### ISSUE THREAD

**Issue by mcbloch** [hlissner/doom-emacs#5120] opened 2021-05-31 17:26 UTC
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Upgrading doom to the latest version.

### What actually happened?

When I run `doom upgrade` I get the following error

```
 ~/.emacs.d > doom upgrade
> Executing 'doom upgrade' 2021-05-31 19:20:22
  > Preparing to upgrade Doom Emacs and its packages...
  ✓ Doom is already up-to-date!
  Doom is up-to-date!
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
      ✓ melpa updated (7f4e68f -> 147ae74)
        - $ cd /home/maxime/.emacs.d/.local/straight/repos/melpa/
        $ git config --get remote.origin.url
        
        https://github.com/melpa/melpa.git
        
        [Return code: 0]
        
        $ cd /home/maxime/.emacs.d/.local/straight/repos/melpa/
        $ git fetch origin
        
        From https://github.com/melpa/melpa
           7f4e68f6..147ae745  master     -> origin/master
    > Updating packages (this may take a while)...
      > In repository "Emacs-wgrep", failed to get status:
      
        Failed to get unambiguous name for "master"
        fatal: Needed a single revision
```

### Describe your attempts to resolve the issue

I ran the upgrade commands multiple times as sometimes suggested. Also ran sync in between multiple times.

### Steps to reproduce

1. Open a command line
2. Checkout to the latest develop commit (atm `9ff0bf8851f2f4cd16b65e59e166a16c33c1c9c2`)
3. Run `doom upgrade`

### System Information

https://pastebin.com/1azxfuW1

**Comment by hlissner** [comment] 2021-05-31 17:27
Duplicate of https://github.com/hlissner/doom-emacs/issues/4984

**Closed by hlissner** 2021-05-31 17:27 UTC
Labels: duplicate
