### ISSUE TITLE
emacs-websocket cannot be upgrade

### ISSUE THREAD

**Issue by MrMic** [hlissner/doom-emacs#4376] opened 2020-12-05 17:52 UTC
**What did you expect to happen?**
...
upgrade process with: ~/.emacs.d/bin/doom upgrade

**What actually happened?**
...
Crash because  emacs-websocket upgrade:
In repository "emacs-websocket", HEAD (on branch "master") is ahead of default branch "te origin
    "

**Comment by gagbo** [comment] 2020-12-05 17:57
Can you put your `doom info`, as stated in the issue template please ? There have been a few issues related to straight/git/github/cli recently and having exact commit information at least is mandatory.

**Comment by MrMic** [comment] 2020-12-05 17:58
Sure:

~/.emacs.d/bin/doom info
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64
	path       (~/miniconda3/bin ~/miniconda3/condabin /usr/local/Cellar/ctags/5.8_1/bin/ctags ~/miniconda3/bin ~/FLUTTER/flutter/bin /usr/lib/jvm/java-1.14.0-openjdk-amd64/bin ~/bin /usr/local/bin /usr/local/sbin /bin /usr/bin /usr/sbin /sbin /opt/X11/bin ~/.cargo/bin ~/.local/bin ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/GO/bin /bin ~/.cargo/bin /usr/lib/emacs/27.1/x86_64-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      sept. 19, 2020
	buildopts  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --program-suffix=27 --with-modules --with-file-notification=inotify --with-mailutils --with-harfbuzz --with-json --with-x=yes --with-x-toolkit=gtk3 --with-lcms2 --with-cairo --with-xpm=yes --with-gif=yes --with-gnutls=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xwidgets 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs27-bifpWT/emacs27-27.1~1.git86d8d76aa3=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop d88e0795b 2020-12-02 17:58:10 -0500
	elc-files  0
	modules    (:completion (company +childframe) helm (ivy +fuzzy +icons +prescient) :ui deft doom doom-dashboard doom-quit hl-todo indent-guides (ligatures +iosevka) modeline nav-flash ophints (popup +all +defaults) tabs treemacs unicode vc-gutter vi-tilde-fringe (window-select +switch-window +numbers) workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors parinfer rotate-text snippets :emacs (dired +icons) electric ibuffer (undo +tree) vc :term eshell :checkers syntax spell grammar :tools (docker +lsp) (eval +overlay) gist (lookup +dictionary +docsets) lsp (magit +forge) pdf rgb upload :os tty :lang common-lisp data (dart +lsp +flutter) emacs-lisp json (javascript +lsp) (markdown +grip) (org +dragndrop +gnuplot +pomodoro +journal +hugo +jupyter +present +roam) (python +lsp +pyright +conda) (sh +lsp +fish) (web +lsp) (yaml +lsp) :app calendar :config (default +bindings +smartparens))
	packages   ((prettier) (prettier-js) (web-beautify) (dracula-theme) (gruvbox-theme) (soothe-theme) (sublime-themes) (wakatime-mode) (indium) (org-bullets) (org-super-agenda) (org-fancy-priorities) (company-tabnine) (vue-mode) (kubernetes) (kubernetes-evil) (zeal-at-point))
	unpin      (n/a)
	elpa       (zenburn-theme yasnippet-snippets yasnippet tablist solarized-theme pdf-tools org monokai-theme let-alist htmlize dash color-theme-modern clues-theme auto-dictionary)
```

**Comment by hlissner** [comment] 2020-12-05 20:33
Duplicate of #3435

**Closed by hlissner** 2020-12-05 20:33 UTC
Labels: duplicate
