### ISSUE TITLE
Doom-modeline spawns a lot of TTY processes in Elixir mode.

### ISSUE THREAD

**Issue by lastgosumatt** [hlissner/doom-emacs#5895] opened 2021-12-14 07:14 UTC
### What did you expect to happen?

1. Open *.ex file
2. Open another *.ex file
3. Doom-modeline shows Elixir version.

### What actually happened?

1. Open *.ex file
2. Open another *.ex file
3. Doom-modeline spawns a lot of TTY processes.
![2021-12-14-100623_screenshot](https://user-images.githubusercontent.com/82309361/145950530-2cdba478-1f9e-4219-b07d-a7adb41ddada.png)

### Steps to reproduce

1. Open *.ex file
2. Open another *.ex file
3. Doom-modeline spawns a lot of TTY processes.

### System Information

https://pastebin.com/1x9UhbAr

**Comment by nandofarias** [comment] 2021-12-15 13:27
Hey @lastgosumatt, the new version of Elixir 1.13.1 was released a couple of hours ago, and I think it has a fix for that.

Extracted from the [changelog](https://github.com/elixir-lang/elixir/releases/tag/v1.13.1):

> [IEx] Make sure the --version flag halts IEx

Would you mind giving it a try? I'm curious to know if this was the root cause.

**Comment by lastgosumatt** [comment] 2021-12-15 15:36
> Would you mind giving it a try? I'm curious to know if this was the root cause.
Sure, but I usually wait till it comes to arch-linux repo, I think it should be soon, otherwise I can build from source

**Comment by nandofarias** [comment] 2021-12-15 16:57
Thank you! It's a way to solve the issue for those who can upgrade, but I still think the issue is valid and the `iex --version` calls should be replaced to use the `elixir --version` if possible.

**Comment by hlissner** [comment] 2022-01-03 18:24
This was an upstream issue (with [doom-modeline](https://github.com/seagle0128/doom-modeline)), which was fixed in https://github.com/seagle0128/doom-modeline/commit/371ad23360e8b3cf16710cb13a85482938704746. I bumped doom-modeline in 783424 which should resolve your issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Closed** 2022-01-03 18:23 UTC
Labels: :ui modeline, 1. external, 2. status:confirmed
