### ISSUE TITLE
Slow load time over ssh using tramp/dired/opening files

### ISSUE THREAD

**Issue by prajwaljpj** [hlissner/doom-emacs#3909] opened 2020-09-07 19:12 UTC
I have been using doom emacs for about 6 months now and I'm extremely happy with it. However, now i have started working on remote servers and doom seems to be extremely slow(10-20 sec) while using tramp.Dired/saving/loading/git for a file takes about the same time.
Any suggestions?

**Comment by yubrshen** [comment] 2020-09-10 06:11
I'm having similar slowness with ssh for file and shell access, also the shell will get destroyed after awhile. Please direct to some advise, if this is a solved problem. Thanks!

**Comment by petr-tik** [comment] 2021-02-23 23:57
Not sure if original posters have the same problem, but I saw this description on reddit and I realised that's the problem I am experiencing on my work computer (cannot provide logs sadly). 

https://www.reddit.com/r/emacs/comments/lp8bjb/tramp_keeps_reopening_connections_doom_emacs/

is there any reason why tramp keeps reopening connections?

**Comment by hlissner** [comment] 2021-02-25 23:12
Doom configures TRAMP quite minimally, so I'm not sure what could be causing this and cannot reproduce the issue. Is it still a problem on the latest version of Doom, on Emacs 27.1 or HEAD? If so, please include your `M-x doom/info`.

**Comment by prajwaljpj** [comment] 2021-02-26 11:42
My `M-x doom/info`

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64
        path       (~/.pyenv/bin/pyenv ~/.virtualenvs/ttsapi/bin ~/.pyenv/shims ~/.pyenv/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.fzf/bin ~/.local/bin /usr/local/go/bin ~/work/go/bin /usr/local/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 13, 2020
        buildopts  
        features   XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil monospace nil nil nil nil nil 14 nil nil nil nil>
        theme      doom-one
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 0c92564 2020-12-15 04:14:40 -0500
        elc-files  0
        modules    (:completion company (ivy +fuzzy +childframe +icons) :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs (dired +icons) electric (ibuffer +icons) undo vc :term eshell :checkers syntax :tools (eval +overlay) lookup (lsp +peek) magit pdf :lang (cc +lsp) data emacs-lisp (go +lsp) json (javascript +lsp) latex markdown (org +brain +dragndrop +jupyter +pandoc +present) (python +lsp +pyenv +ipython) sh :email (mu4e +gmail) :app calendar :config (default +bindings +smartparens))
        packages   ((virtualenvwrapper) (flow-minor-mode) (js-react-redux-yasnippets) (lsp-python-ms))
        unpin      (n/a)
        elpa       (n/a)
```

Here is what speed-ed up Tramp in my case:
1) As @petr-tik mentioned, configuring your ssh to login to a remote server only once helps reduce the latency by half
You can configure for each server 
```shell
Host user@xxx.xx.xx.xxx
    IdentityFile /path/to/your/key.pem
```
OR all together
```shell
Host *
  ControlMaster auto
  ControlPath ~/.ssh/master-%r@%h:%p
  # ControlPersist 30
  ForwardAgent yes
  ServerAliveInterval 60
```

2) Added this to my config.el. Im not really good at elisp so forgive me I cannot explain what this does exactly but it helped me. Out of all the tramp internal/external methods(rcp, ssh, scp, rsync), I found `scp` to work best in my case. I've heard `rcp` is the fastest. I found more info [here](https://www.gnu.org/software/emacs/manual/html_node/tramp/External-methods.html#External-methods)
```elisp
(after! tramp
  (setq tramp-inline-compress-start-size 1000)
  (setq tramp-copy-size-limit 10000)
  (setq vc-handled-backends '(Git))
  (setq tramp-verbose 1)
  (setq tramp-default-method "scp")
  (setq tramp-use-ssh-controlmaster-options nil)
  (setq projectile--mode-line "Projectile")
  (setq tramp-verbose 1))
```

I'm sure there are other ways to make it even faster which I haven't explored yet.

**Comment by roryk** [comment] 2021-02-26 14:27
Thank you @prajwaljpj, Tramp has been completely unusable for me for a long time, hopefully those tips help.

**Comment by hlissner** [comment] 2021-05-25 17:28
Since OPs issue seems to have resolved his issue and this issue is too open ended and not directly actionable, I'll close this. This can be further discussed [on the Discourse](https://discourse.doomemacs.org), once it's up.

**Closed by hlissner** 2021-05-25 17:28 UTC
Labels: 1. discussion, 2. status:unknown, re:performance, re:remote
