### ISSUE TITLE
Force upgrade gets stuck where sync has its impassable prompt

### ISSUE THREAD

**Issue by xeruf** [hlissner/doom-emacs#5827] opened 2021-11-24 18:49 UTC
### What did you expect to happen?

`doom upgrade --force` should recreate broken repositories, or at least throw an error.

### What actually happened?

It hangs indefinitely:
```sh
❯ doom sync -u
> Executing 'doom sync -u' with Emacs 27.2 at 2021-11-24 19:16:31
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.local/state/emacs/env"
      ✓ Successfully generated "~/.local/state/emacs/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
    > Updating packages (this may take a while)...
      > In repository "visual-fill-column", failed to get status:
      
        Failed to get unambiguous name for "main"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) 1

! Aborted

        ! Script was abruptly aborted! Run 'doom sync' to repair inconsistencies

❯ doom --yes upgrade --force
- Confirmations auto-accept enabled
  > Preparing to upgrade Doom Emacs and its packages...
  ✓ Doom is already up-to-date!
  Doom is up-to-date!
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.local/state/emacs/env"
      ✓ Successfully generated "~/.local/state/emacs/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
    > Updating packages (this may take a while)...
      > (198/257) Fetching visual-fill-column...
```

### Describe your attempts to resolve the issue

As this is the same issue as in #4984, I know to work around it by deleting the offending repo.
However, this seems a quite nasty error to me.

**Comment by hlissner** [comment] 2021-11-24 19:34
Duplicate of #4984

Explanation: https://github.com/hlissner/doom-emacs/issues/4984#issuecomment-832842879

> As this is the same issue as in #4984, I know to work around it by deleting the offending repo.
> However, this seems a quite nasty error to me.

Please don't create a duplicate issue. In https://github.com/hlissner/doom-emacs/issues/4984#issuecomment-832842879 I explain this is a recognized issue and a fix is in the works (in #4273).

**Closed by hlissner** 2021-11-24 19:34 UTC
Labels: duplicate, delete me
