### ISSUE TITLE
vim normal mode commands now keep track of position in current line for line commands (in latex mode)

### ISSUE THREAD

**Issue by benneti** [hlissner/doom-emacs#4757] opened 2021-03-08 15:06 UTC
**What did you expect to happen?**
gcj should comment this line and the following similar yj should yank both lines.
For me now (at least in latex mode) what really happens is that it comments only the region from point to the corresponding character in the next line. 

**What actually happened?**
original text: 
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```
assuming point is at the fourth x gcj results in
```
xxx% xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
% yyy
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```
yank (yj) leads to
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
yyy
```

**Additional details:**
- https://cloud.tissot.de/gitea/benneti/doom
- evilnc-comment-operator 
- evil-yank 
- no warnings or messages

**Steps to reproduce:**
1. write some lines (in `LaTeX-mode`)
2. go into a line that has a non empty next line, and to a point before the end of the next line (see example)
3. `yj`

**System information:**
  generated  Mar 08, 2021 16:03:24
     distro  NixOS 21.05.20210306.102eb68 (Okapi) Linux 5.11.2 x86_64
      emacs  28.0.50 master bf1741073 ~/.config/emacs/
       doom  2.0.9 HEAD -> develop cf44c43f4 2021-03-07 14:33:11 -0500 ~/.config/doom/
      shell  /run/current-system/sw/bin/zsh
   features  CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM GTK3 ZLIB
     traits  batch server-running
    modules  :completion company (ivy +icons) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) ligatures unicode vc-gutter vi-tilde-fringe (window-select +numbers +switch-window) :editor (evil +everywhere) file-templates fold rotate-text snippets word-wrap :emacs (dired +ranger +icons) electric (ibuffer +icons) undo vc :term vterm :checkers syntax (spell +everywhere) grammar :tools direnv editorconfig (eval +overlay) lookup (lsp +eglot) magit (pass +auth) pdf biblio :lang (cc +lsp) data emacs-lisp (julia +lsp) (latex +latexmk +cdlatex +fold) markdown nix (org +jupyter +dragndrop +pandoc +pretty +ref +roam) (python +lsp) sh :email mu4e :config (default +bindings +smartparens)
   packages  (company-statistics) (company-quickhelp) (academic-phrases) (org-ref) (latex-preview-pane :disable) (org-ql) (svg-tag-mode :recipe (:host github :repo rougier/svg-tag-mode :branch main :files (svg-tag-mode.el))) (langtool-ignore-fonts :recipe (:host github :repo cjl8zf/langtool-ignore-fonts :files (langtool-ignore-fonts.el))) (org-appear :recipe (:host github :repo awth13/org-appear)) (org-caldav) (mixed-pitch)
       elpa  zmq vterm tablist pdf-tools let-alist

**Comment by hlissner** [comment] 2021-03-08 15:28
Duplicate of #2447

**Closed by hlissner** 2021-03-08 15:28 UTC
Labels: duplicate
