### ISSUE TITLE
Jump to definition does not work on typescript files

### ISSUE THREAD

**Issue by jvalkeejarvi** [hlissner/doom-emacs#5737] opened 2021-11-05 12:59 UTC
### What did you expect to happen?

Pressing `g d` on a typescript file uses tide for resolving the definition.

### What actually happened?

Pressing `g d` on a typescript file uses some other method (xref?) for resolving the definition.

`tide-jump-to-definition` works fine.

### Steps to reproduce

1. Open Emacs
2. Open a typescript file
3. Move cursor over a typescript variable/method
4. Press `g d`

### System Information

https://pastebin.com/kPTu2Ckd

**Comment by thekondr** [comment] 2021-11-06 09:12
The problem happens because in [one of the recent xref changes](https://github.com/emacs-straight/xref/commit/f54d327c8fd3fe2371e2d262218f4cd93d03954a) `xref--marker-ring` has been removed. But [it is still used](https://github.com/hlissner/doom-emacs/blob/bac7ccb970847125919ce32043dce84cfcca16b8/modules/tools/lookup/autoload/lookup.el#L191) by `+lookup--xref-show` to determine success of xref lookup.

A simple workaround works for me until the issue is fixed in doom emacs:

```elisp
(defadvice! workaround--+lookup--xref-show (fn identifier &optional show-fn)
  :override #'+lookup--xref-show
  (let ((xrefs (funcall fn
                        (xref-find-backend)
                        identifier)))
    (when xrefs
      (funcall (or show-fn #'xref--show-defs)
               (lambda () xrefs)
               nil)
      (if (cdr xrefs)
          'deferred
        t))))
```

**Comment by jvalkeejarvi** [comment] 2021-11-08 06:42
Thanks a lot for the workaround. Seems to work fine.

**Closed** 2021-11-21 18:04 UTC
Labels: 1. bug, needs-triage
