### ISSUE TITLE
company-box selection box opens in the wrong direction

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#722] opened 2018-06-24 08:02 UTC
### Observed behavior
The completion box opens to the top covering the current line.
<img width="421" alt="screen shot 2018-06-24 at 16 50 23" src="https://user-images.githubusercontent.com/1908865/41817149-2c8e79bc-77d0-11e8-84e5-be53049775bb.png">

### Expected behavior
- Disabling `company-box` fixes the problem. But it no longer uses the childframes feature.
<img width="313" alt="screen shot 2018-06-24 at 16 50 35" src="https://user-images.githubusercontent.com/1908865/41817153-3c127410-77d0-11e8-95c0-dbaf2aa4dada.png">

### System information

- Using haskell with +intero.

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin17.5.0)
- Emacs: 26.1 (May 30, 2018)
- Doom: 2.0.9 (develop f112a2a83f96bc7f887fa47f884aea3ae95ba901)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 1
  uname -a:  Darwin LF02Q331602A90M.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline evil-goggles hl-todo nav-flash neotree (popup +all +defaults) tabbar unicode vi-tilde-fringe vc-gutter window-select pretty-code :editor :emacs ediff electric eshell imenu term vc :tools gist macos make magit pdf tmux upload wakatime :lang (cc +irony +rtags) common-lisp clojure data erlang elixir elm emacs-lisp go (myhaskell +intero) javascript lua markdown nix ocaml (org +attach +babel +capture +export +present) perl purescript python rest ruby rust scala sh swift web :collab :config)
  packages:  n/a
  exec-path: (~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.gem/bin/ ~/.cargo/bin/ ~/.local/bin/ ~/bin/ ~/Library/Android/sdk/tools/ ~/Library/Android/sdk/platform-tools/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin17.5.0/)
  ```
</details>

**Comment by hlissner** [comment] 2018-06-27 17:38
I cannot reproduce this. This may be a MacOS specific issue; childframes appear to be less stable on MacOS than on Windows or Linux.

**Comment by sondr3** [comment] 2018-07-03 20:47
I'm not using `doom-emacs`, but I'm using a lot of ideas from both you and Spacemacs, and I am having some serious issues with child frames on my High Sierra computer, with `company-box` and my Emacs in fullscreen `company-box` keeps opening black windows on my computer and it's seriously annoying. I've had to disable it for now.

**Comment by hlissner** [comment] 2019-02-28 22:54
@zeronone Sorry for the late reply. Are you still experiencing this issue?

**Comment by Nollo** [comment] 2019-03-28 15:09
What is the version of emacs you use?

I had issue with tooltip not well displayed when using emacs-plus whereas it works fine with emacs-mac port

**Comment by zeronone** [comment] 2019-03-29 03:39
Sorry for late reply, I moved to `emacs-mac` port. It seems to be fine now.

**Comment by hlissner** [comment] 2019-04-02 03:48
Since this is an Emacs/MacOS that cannot be resolved from Doom (as far as I know), I'll close this thread. If you find any evidence to the contrary, please let me know here!

**Closed by hlissner** 2019-04-02 03:48 UTC
Labels: is:bug, module:completion:company, re:macos, status:wontfix
