### ISSUE TITLE
[HOWTO] use treemacs keybindings (not working out-of-the-box)

### ISSUE THREAD

**Issue by verajosemanuel** [hlissner/doom-emacs#2140] opened 2019-12-02 17:07 UTC
I want to navigate one folder up in treemacs (documentation says "u" is the key) but I can't move outside the tree. I must stay in the path I opened treemacs.

Example:

If I call treemacs in /home/jose/documents  I can move and open any file in any folder but can't go up if I enter any of them.

In Neotree I noticed there's links to parent folder ( .. )

**Comment by hlissner** [comment] 2019-12-02 23:26
- The <kbd>h</kbd> will move the root up one level. 
- <kbd>l</kbd> will move the root down.

See https://github.com/Alexander-Miller/treemacs#general-keybinds for more.

Hope that helps!

**Comment by verajosemanuel** [comment] 2019-12-03 07:38
Tried that too. Not working

**Comment by hlissner** [comment] 2019-12-03 08:44
I cannot reproduce that. Both `h`/`l` work as intended in treemacs for me. Please include your `M-x doom/info` and check the \*Messages\* buffers for warnings or errors when opening treemacs (press `SPC h e` to open the \*Messages\* buffer).

**Comment by myrgy** [comment] 2019-12-03 10:20
just press `?` on treemacs. It will show  keybindings.

**Comment by verajosemanuel** [comment] 2019-12-03 10:42
Example:

I open folder .emacs.d from my home folder

/home/jose/,emacs.d

place te cursor on .emacs.d and press "u"

"there is no parent to move up to"

Requested info:

**SPC h e**
Not working. messages buffer is not opened.

**M-x doom/info** 
```
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS
        build      oct 14, 2019
        buildopts  ()
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 90c0dd6b3 2019-12-01 22:46:45 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64
        path       (~/.local/bin/ ~/bin/ /usr/local/mysql/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ ~/.fzf/bin/ /usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm ivy :ui neotree doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit pass pdf :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) python sh :app calendar (rss +org) write :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>


```

**Comment by verajosemanuel** [comment] 2019-12-03 10:47
Read messages buffer via **M-x buffer-menu**

```

Loading /home/jose/doom-emacs/.emacs.d/init.el (source)...done
Doom loaded 231 packages across 45 modules in 0.973s
custom-initialize-reset: Symbol’s function definition is void: battery-update
Open org-agenda (org-agenda)
Recently opened files (recentf-open-files)
Open project (projectile-switch-project)
Loading /home/jose/doom-emacs/.emacs.d/.local/cache/recentf...done
Setting up indent for shell type sh
Indentation variables are now local.
Indentation setup for shell type sh
Analyzing the buffer...done
Guessing...done
Local rules set
Note: sh-basic-offset, tab-width, evil-shift-width adjusted to 4
Note: indent-tabs-mode adjusted to t
evil-forward-char: End of line
Quit [3 times]
evil-forward-char: End of line
Commands: d, s, x, u; f, o, 1, 2, m, v; ~, %; q to quit; ? for help.

```

**Comment by hlissner** [comment] 2019-12-03 10:49
> custom-initialize-reset: Symbol’s function definition is void: battery-update

See #2135

**Comment by verajosemanuel** [comment] 2019-12-03 10:58
issued **doom update** but still not working. Can navigate up to parent folder.

**Comment by hlissner** [comment] 2019-12-03 11:01
Why are you using `u`? I said...

> - <kbd>h</kbd> will move the root up one level. 
> - <kbd>l</kbd> will move the root down.

**Comment by verajosemanuel** [comment] 2019-12-03 11:05
oh my!

sorry

**Comment by hlissner** [comment] 2019-12-03 18:29
No worries! I'll assume h/l are working and close this. Let me know if that isn't the case.

**Closed by hlissner** 2019-12-03 18:29 UTC
Labels: is:duplicate

**Comment by colonelrascals** [comment] 2019-12-04 17:42
@hlissner I claim there is an issue with the navigation keybindings, I am noticing the same issue in dired/deer.
