### ISSUE TITLE
Search lines matching two or more patterns

### ISSUE THREAD

**Issue by Zenoe** [hlissner/doom-emacs#5385] opened 2021-08-16 08:02 UTC
### Describe your request

After updating to the latest configuration. I found 'search-project' could not perform searching for lines matching 2 and more patterns. I used to rely 'counsel-rg' to do the searching job, but it's disappeard in the new version. 

### Briefly explain its use-case

1. press 'SPC /' in a project
2. press two words "aa bb" to search for lines contain both "aa" and "bb", 
3. the result shows only lines of pattern: "xxx aa bb xxx", but not "aa xxx bb"

**Comment by WhatDothLife** [comment] 2021-08-16 08:59
It would help to know which search engine you have enabled. Ivy, helm, ...? Then read the respective README.org.

**Comment by hlissner** [comment] 2021-08-16 15:47
Not a bug; it's just that the syntax for vertico has changed. `#aa#bb` should work for you. However, it only supports two patterns.

In any case, since this is not a Doom bug I'll close this. In the future, please use bug report form, not the feature request form. This was clearly not a feature request.

**Closed by hlissner** 2021-08-16 15:47 UTC
Labels: invalid, delete me

**Comment by iyefrat** [comment] 2021-08-16 15:53
> the result shows only lines of pattern: "xxx aa bb xxx", but not "aa xxx bb"

this should work after #5353 gets merged
