### ISSUE TITLE
Can't open project without VCS

### ISSUE THREAD

**Issue by m0nhawk** [hlissner/doom-emacs#2404] opened 2020-01-22 16:51 UTC
**What did you expect to happen?**
List of files in project should be opened.

**What actually happened?**
It doesn't do anything and still in the "Switch to project" state.

**Additional details:**
<details>

```
(setq evil-default-state 'emacs)
(evil-set-initial-state 'org-mode 'emacs)
(setq doom-leader-key "SPC"
      doom-leader-alt-key "M-m"
      doom-localleader-key "SPC m"
      doom-localleader-alt-key "C-c l")
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
(add-to-list 'default-frame-alist '(fullscreen . fullheight))
(set-file-template! "\\.org$" :trigger "__tpl.org" :mode 'org-mode)
(setq doom-font (font-spec :family "Fira Code" :size 16))
(setq doom-theme 'doom-nord)
(after! org
  (setq org-directory "~/Dropbox/org/")
  (setq org-agenda-files (list org-directory))
  (add-to-list 'org-agenda-files "~/Folder/org/")
  (setq org-default-notes-file (concat org-directory "notes.org"))

  (setq org-capture-templates '(
                              ("p" "Protocol" entry (file+headline org-default-notes-file "Inbox")
                                  "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
                              ("L" "Protocol Link" entry (file+headline org-default-notes-file "Inbox")
                                  "* %? [[%:link][%:description]] \nCaptured On: %U")
                              ("m" "Simple note" entry (file+headline org-default-notes-file "Notes")
                                  "** %i%?")
                              ))

  (setq org-todo-keywords
      '((sequence "TODO(t!)" "DOINGNOW(d!)" "BLOCKED(b@/!)" "DELEGATED(D@/!)" "FOLLOWUP(f@)" "|" "CANCELLED(c@)" "DONE(F!)")))

  (defun org-capture-note (note)
    "Create a new frame and run org-capture."
    (interactive)
    (org-capture-string note "m")
    (x-focus-frame nil)
    )
  (setq org-enable-table-editor 'optimized
    org-agenda-start-on-weekday nil
    org-agenda-skip-scheduled-if-deadline-is-shown t
    org-agenda-skip-deadline-prewarning-if-scheduled (quote pre-scheduled)
    org-agenda-skip-scheduled-if-done t
    org-agenda-skip-deadline-if-done t
    org-agenda-span 14
    org-agenda-compact-blocks t
    org-agenda-show-all-dates nil
    org-deadline-warning-days 365
    org-agenda-show-future-repeats nil)
)
(setq display-line-numbers-type nil)
```
</details>

**Steps to reproduce:**
1. Add some project with only `.projectile` with SPC p a
2. Select this project with SPC p p

**System information:**
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Nov 17, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 8a01ef908 2020-01-20 20:17:43 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /bin/zsh
        uname      Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
        path       (~/.cargo/bin ~/go-workspace/bin ~/var/sqoop-1.4.7.bin__hadoop-2.6.0/bin /usr/local/opt/binutils/bin /usr/local/opt/grep/libexec/gnubin /usr/local/opt/gnu-which/libexec/gnubin /usr/local/opt/gnu-tar/libexec/gnubin /usr/local/opt/gnu-sed/libexec/gnubin /usr/local/opt/gnu-indent/libexec/gnubin /usr/local/opt/findutils/libexec/gnubin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/make/libexec/gnubin /usr/local/opt/ncurses/bin ~/.gem/ruby/2.6.0/bin /usr/local/opt/protobuf@2.5/bin /Library/TeX/texbin /usr/local/sbin /usr/local/bin ~/.local/bin /usr/local/opt/openssl@1.1/bin /usr/local/Cellar/pyenv-virtualenv/1.1.3/shims ~/.pyenv/shims ~/.pyenv/bin ~/.bin /usr/local/opt/fzf/bin /usr/local/MacGPG2/bin /Library/TeX/texbin . /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin /usr/local/opt/hadoop/bin /usr/local/opt/hadoop/sbin /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax spell grammar :tools editorconfig (eval +overlay) (lookup +docsets) macos magit make pdf :lang data emacs-lisp latex markdown (org +capture +dragndrop +pandoc +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2020-01-23 06:48
This is a duplicate of #2261 and #1974. Doom looks for `.project` files, not `.projectile` files.

See https://github.com/hlissner/doom-emacs/issues/1974#issuecomment-546977542 for an explanation.

**Closed by hlissner** 2020-01-23 06:48 UTC
Labels: is:duplicate
