### ISSUE TITLE
Problems finding gnu and melpa

### ISSUE THREAD

**Issue by zcaudate** [hlissner/doom-emacs#279] opened 2017-12-01 22:44 UTC
I'm on osx with GNU Emacs 25.3.1

------------
```
make install
Contacting host: elpa.gnu.org:443
Failed to download ‘gnu’ archive.
Contacting host: melpa.org:443
Package refresh done
Failed to download ‘melpa’ archive.
Eager macro-expansion failure: (error "Package ‘persistent-soft-’ is unavailable")
Eager macro-expansion failure: (error "Package ‘persistent-soft-’ is unavailable")
Package ‘persistent-soft-’ is unavailable
make: *** [.local/autoloads.el] Error 255
```

**Comment by hlissner** [comment] 2017-12-04 18:49
What does `make doctor` say?

**Comment by zcaudate** [comment] 2017-12-05 01:18
```
DOOM Doctor
Running Emacs v25.3.1, commit fd56896e257888bc343fa692e3a377cdc4892881

Compiled with:
  NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES
uname -a:
  Darwin chapterhouse.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep
  29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

Attempt to load DOOM: failed
  (Cannot open load file No such file or directory quelpa)

----

test-emacs
test-windows
test-fonts
test-gnutls
test-tls
Rejected https://elpa.gnu.org
  (error "Certificate validation failed elpa.gnu.org, verification code
  142")

Rejected https://melpa.org
  (error "Certificate validation failed melpa.org, verification code
  142")

Rejected https://self-signed.badssl.com (a good thing!)
  (error "Certificate validation failed self-signed.badssl.com,
  verification code 142")

Rejected https://wrong.host.badssl.com/ (a good thing!)
  (error "Certificate validation failed wrong.host.badssl.com,
  verification code 142")

test-tar
Warning: BSD tar detected
  QUELPA (through package-build) uses the system tar to build plugins,
  but it expects GNU tar. BSD tar *could* cause errors during package
  installation or updating from non-ELPA sources.  MacOS users can
  install gnu-tar via homebrew: brew install gnu-tar

====
Have some debug information:

  + byte-compiled files:
    n/a

  + exec-path:
    /Users/chris/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Users/chris/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku
    /Users/chris/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmuxinator
    /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9
    /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_9
    /Applications/Emacs.app/Contents/MacOS/libexec
    /Applications/Emacs.app/Contents/MacOS/bin

  + PATH:
    /Users/chris/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Users/chris/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku
    /Users/chris/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmuxinator
    /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9
    /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_9


----
There were issues!
```

**Comment by hlissner** [comment] 2017-12-05 06:07
Ah, this is a duplicate of #80.

If the advice in that thread doesn't work for you, you can forgo TLS verification entirely with the `INSECURE` env var, e.g. `INSECURE=1 make install`.

**Closed by hlissner** 2017-12-05 06:07 UTC
