### ISSUE TITLE
doom upgrade failed with unexpected error 

### ISSUE THREAD

**Issue by i3d** [hlissner/doom-emacs#5004] opened 2021-05-07 20:11 UTC
doom upgrade encountered the following error:

This happens on both MacOS and Linux

doom upgrade                                                                                                
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.doomemacs.d/.emacs.d/.local/env"
    ✓ Successfully generated "~/.doomemacs.d/.emacs.d/.local/env"
Package cl is deprecated
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to .doomemacs.d/.emacs.d/.local/doom.error.log

**What did you expect to happen?**
it should not fail.

**What actually happened?**
failed with the above message.

**Additional details:**

  1. Grab output from `M-x doom/info` or `~/.emacs.d/bin/doom info`,
  2. Paste it into pastebin.com,
  3. Paste URL above this commented block.
  https://pastebin.com/77TXSu2n
[doom.error.log](https://github.com/hlissner/doom-emacs/files/6443902/doom.error.log)

**Comment by hlissner** [comment] 2021-05-07 20:25
Duplicate of #4950.

**Closed by hlissner** 2021-05-07 20:25 UTC
Labels: delete me, duplicate
