### ISSUE TITLE
Clang-tidy configuration file does not work with emacs-lsp

### ISSUE THREAD

**Issue by K1ngst0m** [hlissner/doom-emacs#6347] opened 2022-04-30 06:45 UTC
### What did you expect to happen?

The editor's clang-tidy output should follow the `$HOME/.clang-tidy` rules. 

### What actually happened?

Whatever I changed my `$HOME/.clang-tidy`, the editor always shows the same output.

### Describe your attempts to resolve the issue

1. Execute `lsp-restart-workspace`
2. Restart emacs. 
3. Delete other `clang-tidy` in the parent directory except `$HOME/.clang-tidy`.

### Steps to reproduce

For example, I want to hide the diagnostic output like "Parameter name 'xx' is too short, expected at least 3 characters `[readability-identifier-length]`" in clang-tidy

And this is my current `clang-tidy --list-checks  | grep readability-identifier-length` output:

```shell
> clang-tidy --list-checks  | grep readability-identifier-length                
    
readability-identifier-length
```

and in emacs, `flycheck-list-errors` shows:
![image|690x34](https://discourse.doomemacs.org/uploads/default/original/2X/d/d1112086e4554f1ca9c44c8c33ac108bc1a753e7.png)

Now I'm adding `-readability-identifier-length` to my `$HOME/.clang-tidy` file's Checks arguments list to disable checking it:

```config
Checks: 
'-*,
clang-analyzer-*,
readability-*,
modernize-*,

-clang-analyzer-osx*,
-readability-identifier-length
'
``` 

And below is my current output:
```shell
> clang-tidy --list-checks  | grep readability-identifier-length                 
>        
```
The check is hidden, so the config file should work after changing, but my `flycheck-list-errors` output does not change, no matter if I execute `lsp-restart-workspace` or restart emacs. 

And I've confirmed that there is no other `clang-tidy` in the parent directory except `$HOME/.clang-tidy`.

### System Information

https://pastebin.ubuntu.com/p/bhNpBztqbj/

**Comment by hlissner** [comment] 2022-04-30 10:36
Duplicate of https://discourse.doomemacs.org/t/clang-tidy-configuration-file-does-not-work-with-emacs-lsp/2593

Please don't crosspost. One post, on our Discourse, is enough. This issue will be reopened if your issue is confirmed there.

**Closed by hlissner** 2022-04-30 10:36 UTC
Labels: duplicate, delete me
