### ISSUE TITLE
fonts issue on MacOS

### ISSUE THREAD

**Issue by huyiqun** [hlissner/doom-emacs#5994] opened 2022-01-13 11:30 UTC
### What did you expect to happen?

No font issue after a clean install.

Should be able to specify fonts that are correctly installed on the system by using `setq doom-font`.

### What actually happened?

- After a clean install, without any modification to the private config files, run `doom doctor`, there should not be any font issues.

Tried a clean installation and got the following output:
```
[...]
Download and install all-the-icon's fonts? (y or n) y
    Contacting host: raw.githubusercontent.com:443
    Contacting host: raw.githubusercontent.com:443
    Contacting host: raw.githubusercontent.com:443
    Fonts downloaded, updating font cache... <fc-cache -f -v> 
     Successfully installed `all-the-icons' fonts to `/Users/un/Library/Fonts/'!
  ✓ 
  Finished! Doom is ready to go!
  
  But before you doom yourself, here are some things you should know:
  
  1. Don't forget to run 'doom sync', then restart Emacs, after modifying
     ~/.doom.d/init.el or ~/.doom.d/packages.el.
  
     This command ensures needed packages are installed, orphaned packages are
     removed, and your autoloads/cache files are up to date. When in doubt, run
     'doom sync'!
  
  2. If something goes wrong, run `doom doctor`. It diagnoses common issues with
     your environment and setup, and may offer clues about what is wrong.
  
  3. Use 'doom upgrade' to update Doom. Doing it any other way will require
     additional steps. Run 'doom help upgrade' to understand those extra steps.
  
  4. Access Doom's documentation from within Emacs via 'SPC h d h' or 'C-h d h'
     (or 'M-x doom/help')
  
  Have fun!
  
  ✓ Finished in 7m39s
```
which shows that all default fonts should have been installed correctly. Run `doom doctor` right after and got:
```
> Executing 'doom doctor' with Emacs 27.2 at 2022-01-13 06:12:16
  The doctor will see you now...
  
  > Checking your Emacs version...
  > Checking for Doom's prerequisites...
  > Checking for Emacs config conflicts...
  > Checking for great Emacs features...
  > Checking for private config conflicts...
  > Checking for stale elc files...
  > Checking for problematic git global settings...
  > Checking Doom Emacs...
    ✓ Initialized Doom Emacs 21.12.0-alpha
    ✓ Detected 30 modules
    ✓ Detected 118 packages
    > Checking Doom core for irregularities...
      ! Warning: couldn't find "material-design-icons.ttf" font
      ! Warning: couldn't find "weathericons.ttf" font
      ! Warning: couldn't find "octicons.ttf" font
      ! Warning: couldn't find "fontawesome.ttf" font
      ! Warning: couldn't find "file-icons.ttf" font
      ! Warning: couldn't find "all-the-icons.ttf" font
    > Checking for stale elc files in your DOOMDIR...
    > Checking your enabled modules...
[...]
```
Also checked in the Font Book app, and all these seemingly installed fonts are all empty.

- Installed custom fonts on MacOS, which is listed in both `fc-list` and `(print(font-family-list))` in emacs to show that they are installed correctly, but using `(setq doom-font (font-spec :family "DankMono Nerd Font" :size 12))` in `config.el` gives the `font not available error`.
<img width="579" alt="image" src="https://user-images.githubusercontent.com/10877536/149322264-27e4cb4b-e557-4276-9a1c-09378659a29f.png">

### Describe your attempts to resolve the issue

Tried clean installation a couple of time.

Found the other issue which reports the same problem. I made sure that `(setq doom-font (font-spec :family "DankMono Nerd Font" :size 12))` has the correct `weight` flag (if not omitted) and tried all different legitimate values for it.

### Steps to reproduce

1st issue:
1. Do a clean install of Doom Emacs (I am on MacOS 12.1)
2. Run `doom doctor`

2nd issue:
1. Add `(setq doom-font (font-spec :family "DankMono Nerd Font" :size 12))` in `config.el`
2. Open `emacs`

### System Information

https://pastebin.com/udKcb6DB

**Comment by ErnestDong** [comment] 2022-01-22 14:29
try <kbd>M-x</kbd> then `all-the-icons-install-font`

**Comment by hlissner** [comment] 2022-01-27 16:04
Unfortunately, there is nothing Doom can do to fix for you. It is not a Doom issue. If Emacs can't find a font, then the font, evidently, does not exist, or isn't being referred to by the correct name or with the correct weight. Or maybe you're using a sandboxed Emacs installed from flatpak or snap? In which case Emacs may not be able to see your system fonts.

In any case, I can't reproduce it (having tried a couple nerd fonts on my own system and four other test systems, on MacOS, two Linux distros, and Windows), so signs point to a local issue, but I'm afraid that's all I can determine.

I'll close this since it's not a Doom issue, but feel free to follow up here.

**Closed by hlissner** 2022-01-27 16:04 UTC
Labels: invalid, delete me

**Comment by huyiqun** [comment] 2022-01-29 06:49
@hlissner Thanks for getting back! I installed Emacs using macports - would that be the reason to the issue?

I also did not install the fonts myself, those are installed during the installation of doom emacs. So I assume this process should have no problem, but after the installing command, what I see in the fonts book look like:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/10877536/151650819-44989478-2aa7-4057-b500-21fba1dd8712.png">
for all of these listed ones (i.e. empty). I feel like these are the real behind. Could it be something related to my system? By I also just installed a clean MacOS (btw, I am on 12.1).

**Comment by mtwomey** [comment] 2022-02-22 05:32
@huyiqun 

I found this issue, because I had the identical issue on my mac. It turns out, fc-config (which I had installed via brew), wasn't seeing fonts which are installed in `~/Library/fonts`. I don't think it looks there, it only looks in `/Library/fonts`.

I learned you have a choice of where you install fonts on the mac using Font Book:

![image](https://user-images.githubusercontent.com/7715262/155068913-41fbada2-756c-4700-900a-e0cb08286502.png)

I changed this to "Computer", reinstalled the fonts and then fc-list now sees the fonts and the warning is gone from `doom doctor`.
