### ISSUE TITLE
Restart and Restore replaces one of the buffers with doom dashboard

### ISSUE THREAD

**Issue by ArtemSmaznov** [hlissner/doom-emacs#5255] opened 2021-07-11 16:59 UTC
### What did you expect to happen?

When I do a `SPC q r` or `M-x doom/restart-and-restore` I expect to get all the windows restored

### What actually happened?

One of the windows gets replaced by the doom dashboard.
If emacs was restarted while having only 1 window then it will be repalaced by the doom dashboard

There are no errors and buffers are still loaded in the background and I can switch to them. It is just quite inconvenient.
Also I can restore the session by pressing `SPC q l` and all windows restore just fine with that.

### Describe your attempts to resolve the issue

I have reverted to the default config by emptying the config.el - no difference
I have tied on a different machine which did not update to the latest development branch (commit 273168509 develop Merge pull request #5152 from cnr/org-tree-slide-hide-blocks) - issue resolved
I have updated that machine to the latest doom emacs - issue started happening again

The bug must have been introduces some time after commit `2731685095d1e6101b3215aa689426e1834ce00f` as it is the one I was one on my second machine when the issue wasn't happening

### Steps to reproduce

Single Window:
1. Open Emacs
2. Open any buffer
2. Execute `doom/restart-and-restore` or press `SPC q r`
3. Emacs restarts
4. I see the dashboard instead of my last buffer

Multi-Window:
1. Open Emacs
2. Open any buffer
3. Do a window split
2. Execute `doom/restart-and-restore` or press `SPC q r`
3. Emacs restarts
4. I see the dashboard instead of one of my last buffers

### System Information

https://pastebin.com/gu45vd2s

**Comment by hlissner** [comment] 2021-07-11 17:24
There are two common causes for this issue:

1. You've changed `uniquify-buffer-name-style` to a non-nil value. Persp-mode (the plugin we use for session management) is incompatible with any non-nil value for this variable, otherwise you get name collisions that result in lost buffers when sessions are saved/loaded. The workaround for this is `(setq uniquify-buffer-name-style nil)`
2. Or you're trying to save buffers that cannot be persisted (e.g. special buffers like magit, terminals, etc). The workaround for this is to define specialized save/load logic for those buffers with the `persp-def-buffer-save/load` function.

In any case, neither issue can be solved on Doom's end, and must be addressed [upstream](https://github.com/Bad-ptr/persp-mode.el).

I have plans to replace persp-mode with eyebrowse + desktop (or tab-bar-mode on Emacs 27+) -- which don't suffer from these particular problems (but do have other issues) -- but for the time being I'll close this issue since it isn't directly actionable. Thanks for bringing it to my attention.

**Comment by ArtemSmaznov** [comment] 2021-07-11 17:40
@hlissner I can confirm that uniquify-buffer-name-style is set to nil in my config.
Also this is the behavior with all buffers - README.org, Init.el, etc

**Comment by ArtemSmaznov** [comment] 2021-07-11 19:13
If it helps I think I have narrowed it down to commit 044a1a5 - that is when the issue started happening

**Comment by hlissner** [comment] 2021-07-11 22:01
I cannot reproduce your issue, and there is nothing in 044a1a5 that ought to affect `persp-mode` in this way, so an unrelated error is likely short circuiting your config at startup. Please check your \*Messages\* buffer for errors or warnings when trying to restore your session.

**Comment by ArtemSmaznov** [comment] 2021-07-12 17:24
Interesting, I expected it to be easily reproducible.
I have tried completely wiping my config and reinstalling doom from scratch (deleted both doom and emacs config folders) and to try with full stock config but sadly still the same result:
After I open emacs, `SPC f P` and select `config.el` and then doing a `SPC q r`, it still reloads to the dashboard buffer.
All I get in the Messages buffer is `Loading /home/artem/.config/emacs/.local/cache/recentf...done`

**Comment by ArtemSmaznov** [comment] 2021-07-12 19:33
does this mean that you managed to reproduce it?

**Comment by hlissner** [comment] 2021-07-12 20:01
Yes, I've tracked down the issue and fixed it in 5c741cb. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Closed** 2021-07-12 20:01 UTC
Labels: 1. bug, 2. status:confirmed, :core lib, :ui workspaces

**Comment by ArtemSmaznov** [comment] 2021-07-12 20:07
Yeap it is fixed for me, thanks
