### ISSUE TITLE
Error with file creation and error with `load-theme`

### ISSUE THREAD

**Issue by The-BigDaddy** [hlissner/doom-emacs#464] opened 2018-03-17 03:23 UTC
### Observed behavior

1. Startup, attempt to creating a new file va `C-x C-f` and typing in the name of the file get the error "Wrong type argument: arrayp, nil". Looking in the `*Messages*` buffer I see the full error is 

    yas-expand-snippet: Wrong type argument: arrayp, nil

2. When doing `M-x load-theme` and selecting `doom-nord` I get the error "Symbol's function definition void: highlight-numbers-mode". 

### Expected behavior

Uh for a file to be created, and then for the `doom-nord` theme to be loaded.

### System information

<details>
<summary>Click to expand</summary>

```
Replace this line with the output of *one* of these commands:

+ DOOM Doctor
Running Emacs v25.3.1, commit fatal: Not a git repository (or any of the parent directories): .git

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS
  LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
  MODULES XWIDGETS
uname -a:
  Linux void 4.14.26_1 #1 SMP PREEMPT Tue Mar 13 12:42:54 UTC 2018
  x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision fatal: Not a git repository (or any of the parent directories): .git

----

test-emacs
test-windows
test-fonts
Warning: couldn’t find material-design-icons.ttf font in /home/bigdaddy/.local/share/fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find weathericons.ttf font in /home/bigdaddy/.local/share/fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find octicons.ttf font in /home/bigdaddy/.local/share/fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find fontawesome.ttf font in /home/bigdaddy/.local/share/fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find file-icons.ttf font in /home/bigdaddy/.local/share/fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
Warning: couldn’t find all-the-icons.ttf font in /home/bigdaddy/.local/share/fonts/
  You can install it by running ‘M-x all-the-icons-install-fonts’ within
  Emacs.

  This could also mean you’ve installed them in non-standard locations,
  in which case, ignore this warning.
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```
</details>

**Comment by hlissner** [comment] 2018-03-17 03:26
Are you using `master` or `develop`?

**Comment by The-BigDaddy** [comment] 2018-03-17 03:29
`master`. I checked to see if there was anything I could see in the `modules/feature/snippets/config.el` file that was an easy fix but I didn't see anything.

**Comment by hlissner** [comment] 2018-03-17 03:32
If you haven't invested too much time in a config for `master`, would you mind trying to `develop` branch instead? I intend to merge it into `master` soon, and a great many issues have been fixed in it.

Just keep in mind you'll need to update your init.el to reflect the changes in `init.example.el`.

**Comment by The-BigDaddy** [comment] 2018-03-17 03:38
Oh wait. God dammit, sorry I'm on `develop`.

**Comment by hlissner** [comment] 2018-03-17 04:28
No worries. What commit are you on?

**Comment by hlissner** [comment] 2018-03-17 06:29
Hmm, I'm unable to reproduce it and need more information: could you run `M-x doom/info` in Emacs and paste the results here? Also, I assume you've tried running `make`?

**Comment by The-BigDaddy** [comment] 2018-03-17 06:43
All the `doom/info` stuff is up in the post under System Information. I think I know how to fix the issue on my end, so let me try a few things here real quick...it's mostly that I thought I could be clever and copy over some of what you have and modify some of the base packages for my needs (i.e. replacing modules like the ones for Go and Typescript with ones for Idris and Kotlin). 😝 But I'm realizing what a pain an the ass that makes it for myself, especially if I ever want to contribute anything useful. Really thought I could personalize it more that way but again, it's bigger pain than just having stuff in a seperate module...

**Comment by hlissner** [comment] 2018-03-17 06:55
Understandable. If you make any headway with your kotlin or idris modules, let me know. I'd be happy to include them.

> All the doom/info stuff is up in the post under System Information.

Actually, on develop, `make doctor` and `doom/info` (or `make info`) have diverged. `doom/info` produces more useful diagnostic information about your session than the doctor.

`make doctor` is there to help the users diagnose issues, while `make info` and `doom/info` are for my convenience to help me debug your bug reports.

**Comment by The-BigDaddy** [comment] 2018-03-17 07:02
Ah, well being that I'm now fixing this via doing it the sane way I'll probably get back to you if I have the same issue (probably won't happen, but still). It's seperate from this issue (it's more of a discussion point on modules), but what functions do you look to autoload for modules? REPLs, type-under-cursor type stuff and such?

**Closed** 2018-03-24 10:25 UTC
Labels: invalid
