### ISSUE TITLE
`doom upgrade` fails at "Updating recipe repos..." with "There was an unexpected error"

### ISSUE THREAD

**Issue by yeongsheng-tan** [hlissner/doom-emacs#4968] opened 2021-05-03 02:36 UTC
Ran `doom upgrade` and it failed at:
```
❯ doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Compiling your literate config...
  - Tangled 0 code blocks from config.org.gKpEFl
  - Restarting...
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
Package cl is deprecated
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

**What did you expect to happen?**
`doom upgrade` to pull latest git revisions and update packages and links and build of packages updates successfully

**What actually happened?**
```
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

**Additional details:**

1. ~/.doom.d/config.el
```
(setq user-full-name "Tan Yeong Sheng"
      user-mail-address "tanyeongsheng@gmail.com")
(setq doom-font (font-spec :family "JetBrains Mono" :size 13))
(setq doom-theme 'doom-laserwave)
(setq org-directory "~/org/")
(setq display-line-numbers-type t)
(setq projectile-project-search-path '("~/code" "~/odd-e_code" "~/ruckus_code" "~/titansoft_code"))

(add-hook! reason-mode
  (add-hook 'before-save-hook #'refmt-before-save nil t))
(add-hook! js2-mode 'prettier-js-mode
  (add-hook 'before-save-hook #'refmt-before-save nil t))
(map! :ne "M-/" #'comment-or-uncomment-region)
(map! :ne "SPC / r" #'deadgrep)
(map! :ne "SPC n b" #'org-brain-visualize)
(map! :ne "SPC k" #'save-buffer)
```

2. ~/.doom.d/init.el
```
(doom! :input

       :completion
       (company +childframe)          ; the ultimate code completion backend
       (ivy
        +icons
        +prescient)        ; a search engine for love and life

       :ui
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji +ascii     ; Adds emoji support to Emacs
        +github
        +unicode)
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       hydra
       indent-guides     ; highlighted indent columns
       (modeline +light) ; snazzy, Atom-inspired modeline, plus API
       nav-flash         ; blink cursor line after big motions
       ophints           ; highlight the region an operation acts on
       (popup
        +all
        +defaults)       ; tame sudden yet inevitable temporary windows
       (ligatures +extra); ligatures or substitute text with pretty symbols
       treemacs          ; a project drawer, like neotree but cooler
       unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       (window-select
        +switch-window
        +numbers)        ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       multiple-cursors  ; editing in many places at once
       rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to

       :emacs
       (dired +icons)    ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       (ibuffer +icons)  ; interactive buffer management
       (undo +tree)      ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax            ; tasing you for every semicolon you forget
       spell             ; tasing you for misspelling mispelling
       grammar           ; tasing grammar mistake every you make

       :tools
       ansible
       (debugger +lsp)   ; FIXME stepping through code, to help you add bugs
       direnv
       (docker +lsp)
       editorconfig      ; let someone else argue about tabs vs spaces
       (eval +overlay)   ; run code, run (also, repls)
       gist              ; interacting with github gists
       (lookup
        +dictionary
        +docsets)        ; navigate your code and its documentation
       (lsp +peek)       ;Installation and configuration of language server protocol client (lsp-mode or eglot)
       (magit
        +forge)          ; a git porcelain for Emacs
       make              ; run make tasks from Emacs
       pdf               ; pdf enhancements
       rgb               ; creating color strings
       terraform         ; infrastructure as code
       tmux              ; an API for interacting with tmux
       upload            ; map local to remote projects via ssh/ftp

       :lang
       crystal           ; ruby at the speed of c
       data              ; config/data formats
       (elixir +lsp)     ; erlang done right
       (elm +lsp)        ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       (erlang +lsp)     ; an elegant language for a more civilized age
       (ess +lsp)        ; emacs speaks statistics
       (haskell +dante)  ; a language that's lazier than I am
       (json +lsp)       ; At least it ain't XML
       (java
        +meghanada
        +eclim
        +lsp)            ; the poster child for carpal tunnel syndrome
       (javascript +lsp) ; all(hope(abandon(ye(who(enter(here))))))
       kotlin            ; a better, slicker Java(Script)
       (latex
        +latexmk
        +cdlatex
        +fold)           ; writing papers in Emacs has never been so fun
       (lua
        +fennel
        +moonscript)     ; one-based indices? one-based indices
       (markdown +grip)  ; writing docs for people to ignore
       nix               ; I hereby declare "nix geht mehr!"
       (org              ; organize your plain life in plain text
        +brain
        +dragndrop       ; drag & drop files/images into org buffers
        +gnuplot         ; who doesn't like pretty pictures
        +hugo            ; use Emacs for hugo blogging
        +ipython
        +journal
        +jupyter         ; ipython/jupyter support for babel
        +noter
        +pandoc          ; export-with-pandoc support
        +present         ; using org-mode for presentations
        +pretty)         ; yessss my pretties! (nice unicode symbols)
       raku              ;
       (ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       scheme            ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       (web +lsp)        ; the tubes
       (yaml +lsp)       ; JSON, but readable

       :email

       :app
       calendar
       twitter           ; twitter client https://twitter.com/vnought

       :config
       literate
       (default +bindings +smartparens)

       :os
       macos             ;Improve Emacs’ compatibility with macOS
       (tty +osc))       ;Improves the terminal Emacs experience
```

3. ~/.doom.d/packages.el
```
(package! ob-elixir)
(package! ob-typescript)
(package! indium)
(package! reason-mode)
(package! prettier-js)
(package! org-fancy-priorities)
(package! move-text)
(package! vue-mode)
(package! origami)
(package! deadgrep)
(package! dart-mode)
(package! sql-indent)
(package! org-brain)
(package! ascii-art-to-unicode)
(package! wakatime-mode)
```

4. [`doom upgrade` backtrace](https://pastebin.com/mbXkCC6Y)

**Steps to reproduce:**
1. From zsh shell in macOS Big Sur 11.3, run `doom upgrade`
2. See error:
```
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

**System information:**
[doom info](https://pastebin.com/10R91Jxj)

**Comment by hlissner** [comment] 2021-05-03 02:56
Duplicate of #4950

**Closed by hlissner** 2021-05-03 02:56 UTC
Labels: delete me, duplicate
