### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by adbrown101** [hlissner/doom-emacs#2136] opened 2019-12-02 09:18 UTC
After running doom upgrade today emacs starts and throws an error (void function battery-update).
Possibly related to issue 1951.
<details><pre>
Debugger entered--Lisp error: (void-function battery-update)
  battery-update()
  doom-modeline-override-battery-modeline()
  run-hooks(doom-modeline-mode-hook doom-modeline-mode-on-hook)
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
</pre></details>

**Steps to reproduce**
1. enable ui: modeline in ~/.doom.d/init.el
2. doom refresh
3. start emacs
4. error ocurs
5. disable ui:modelone
6. doom refresh
7. error disappears
8. re-enable ui:modeline causes error to reappear.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB LUCID X11 XDBE XIM MODULES THREADS LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--with-x-toolkit=athena --without-toolkit-scroll-bars --without-dbus --without-gconf --without-gsettings --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --bindir=/usr/bin --mandir=/usr/share/man --infodir=/usr/share/info --localstatedir=/var --with-file-notification=inotify --with-modules --with-jpeg --with-tiff --with-gif --with-png --with-xpm --with-rsvg --without-imagemagick --with-xml2 --with-gnutls --with-sound --with-m17n-flt --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu 'CFLAGS=-fno-PIE -mtune=generic -O2 -pipe   -g' 'CPPFLAGS=   ' 'LDFLAGS=-no-pie -Wl,--as-needed    '")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 90c0dd6b3 2019-12-01 22:46:45 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-unknown-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64")
  (path "~/.emacs.d/bin" "~/.cask/bin" "/c/utils/scripts/perl_scripts/symphony" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/opt/texlive/2019/bin/x86_64-linux" "/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn" "/usr/libexec/emacs/26.3/x86_64-unknown-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +ranger +icons) electric ibuffer vc :tools docker editorconfig eval flycheck (flyspell +hunspell) (lookup +docsets) magit pass pdf :lang data emacs-lisp latex markdown (org +attach +babel +capture +export +habit +pandoc +present +protocol) perl sh web :config literate (default +bindings +smartparens))
  (packages sql-indent ox-hugo minions)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2019-12-02 09:20
Duplicate of #2135

**Closed by hlissner** 2019-12-02 09:20 UTC
Labels: is:duplicate
