### ISSUE TITLE
How to unmap keymap prefix set via map!

### ISSUE THREAD

**Issue by gabeos** [hlissner/doom-emacs#814] opened 2018-08-17 23:39 UTC
Hey, thanks for all your work on this. Very strongly appreciated. 

I was just wondering if there's a good way to unmap prefixes set via map!. For my specific case, I use mercurial rather than git for most things, and would like to reclaim "SPC g" for other keybindings without sacrificing the rest of the default configuration or forking it into my own config. I'm having trouble understanding how the map! macro sets it up, so thought I'd ask. 

If not, would you be open to adding an feature request for a function to do so? Or, alternatively, make the keybindings somewhat more modularized so specific chunks can be disabled.

**Comment by DonHugo69** [comment] 2018-08-18 06:55
I have a very similar question and I hope it is fine if I add it here to @gabeos question: 

I would like to remove the keybindings set up by DOOM for a module/major mode and then set up my own ones on top of the ones defines by the package itself.

racket-mode will be used as an example.

DOOM's keybindings are defined in the `module/lang/racket/config.el` via the 
```
(def-package! racket-mode
....
:config
....
(map!
...)
```
block which sets up the keybindings after racket-mode has been loaded.

My keybindings are defined in `doom.d/keys/+keys_rackets.el` and loaded via `(load! "/keys/keys_racket.el")` in the `doom.d/config.el`.

What works best so far is doing the following in the `+keys_racket.el`

```
(after! racket-mode
  (map!
   :map racket-mode-map
   :localleader
   "" nil
   ;; the above removes all keys after "SPC m"
   :nv "s" #'racket-run)
...
)
```

The good thing is, that the keys after `SPC m` are removed. However, instead of `s - racket-run` I see `s - eval` which is the prefix defined in the original configuration in [DOOM's module](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/racket/config.el). But pressing `SPC m s` correctly runs racket so it is just the displayed name of the keybind. Using `:desc "racket run" :nv "s" #'racket-run` correctly names and binds the key to the command. However, this would mean that all modified keybinds need a description in order to have function and description in line and no left overs from DOOM's definitons. 

Other things I tried:

- Using `(setq racket-mode-map (make-sparse-keymap))` will remove all keybindings and descriptions but also all keybinds set up by the author of the package which I would like to keep
- Trying to intercept the original keybinds via 
```
(def-package-hook! racket-mode
....
(set-keymap-parent my-racket-mode-map racket-mode-map)
t)
```
in my `doom.d/init.el`. But when using `:post-init` and `pre-config` the keymap is not available yet and after `:post-config` the modifications are already made. It appears also to be a quite complicated solution to a simple problem.

I can think of two solutions:

- Have the keybindings optional for each module via a `+bindings` flag in the `init.el` like the keybindings defined in `config` module. So one could copy the ones one likes and change the rest.
- Maybe easier (?) would be to modify `map!` in a way that a separate keymap gets created for the `localleader` keybinds. I think [bind-key.el](https://github.com/jwiegley/use-package/blob/master/bind-key.el) could do that.

```
;; To set up a prefix map, use `:prefix-map' and `:prefix' arguments (both are
;; required)
;;
;;    (bind-keys :prefix-map my-customize-prefix-map
;;               :prefix "C-c c"
;;               ("f" . customize-face)
;;               ("v" . customize-variable))
```
Then one could clear the prefix-map via `(make-sparse-keymap)` and set up the own ones.

**Comment by hlissner** [comment] 2018-08-18 11:37
> I was just wondering if there's a good way to unmap prefixes set via map!. For my specific case, I use mercurial rather than git for most things, and would like to reclaim "SPC g" for other keybindings without sacrificing the rest of the default configuration or forking it into my own config. I'm having trouble understanding how the map! macro sets it up, so thought I'd ask.

@gabeos To unset `SPC g`, bind it to nil:

```elisp
(map! :leader :nv "g" nil)
```

Afterwards, you can set new keybinds on `SPC g`, e.g.

```elisp
(map! :leader
      :nv "g" nil
      (:prefix "g"
        :n "a" #'some
        :v "b" #'other
        :n "c" #'commands))
```

`map!` is just syntactic sugar for `define-key`, `global-set-key`, `evil-define-key` and `evil-define-key*`. If you'd like to see how the macro expands, put your cursor over a `map!` call and run `M-x macrostep-expand`.

> The good thing is, that the keys after SPC m are removed. 

@DonHugo69 You are doing it correctly, the problem is...

> However, instead of s - racket-run I see s - eval which is the prefix defined in the original configuration in DOOM's module. But pressing SPC m s correctly runs racket so it is just the displayed name of the keybind.

What you're seeing is a limitation of the `map!` macro, which will be fixed when Doom adopts [general](https://github.com/noctuid/general.el) (closer to the end of the month). `:desc` simply should not be used for buffer-local or localleader keys, it has no awareness of major/minor modes or evil states. Descriptions are global. The general package gets around this somehow.

Actually, it is a mistake that the `lang/racket` module is using :desc at all. I'll correct that. 

Otherwise, I'm afraid there is little that can be done to fix this until we switch to general. The good news is this is simply an aesthetic problem and doesn't affect functionality.

> Maybe easier (?) would be to modify map! in a way that a separate keymap gets created for the localleader keybinds

Once Doom adopts general, a number of big changes will take place. For one, leader and localleader keys will be on their own keymaps (to make it easier to have multiple leader/localleader prefix keys and/or change their prefixes).

**Comment by DonHugo69** [comment] 2018-08-19 17:46
Thanks a lot for the (as usual) answer and clarification @hlissner !
I hope general.el won't give you further trouble (I think the implementation was planned since March?)!

**Comment by HaoZeke** [comment] 2018-08-19 23:29
Another option is to simply load general and start using it... I've managed to configure 'markdown' specific bindings that way..

**Comment by DonHugo69** [comment] 2018-08-20 08:27
@HaoZeke 
True, but the use of `general.el` resulted in the same issue:

> However, instead of s - racket-run I see s - eval which is the prefix defined in the original configuration in DOOM's module. But pressing SPC m s correctly runs racket so it is just the displayed name of the keybind.

But that is fixed now.

**Comment by HaoZeke** [comment] 2018-08-20 08:36
@DonHugo69 Have you used the `:which-key` thing with general?

For me I get the right displayed name like so:

```lisp
(nmap
  :prefix "SPC"
  :keymaps 'markdown-mode-map
  "m" '(ignore t :wk "Markdown Commands")
  "m i" '(ignore t :wk "Insert")
  "m i i" '(markdown-insert-image :wk "Image")
  "m i l" '(markdown-insert-link :wk "Link")
  "m i c" '(markdown-insert-gfm-code-block :wk "Github Code Block"))
```

**Comment by hlissner** [comment] 2018-08-22 01:07
> By the way: Will the map! syntax (e.g. :after or :mode) stay the same?

I've only just started digging into general, so I don't have specifics yet, but I am pretty certain there will be breaking changes to `map!`.

**Comment by hlissner** [comment] 2018-08-30 22:41
I'll consider this resolved. Feel free to continue using this thread if you'd like to follow up!

**Closed by hlissner** 2018-08-30 22:41 UTC
Labels: question

**Comment by OrionRandD** [comment] 2020-06-22 00:37
I am trying to remap other-window to switch-window.
I tried this in  config.el  

;;; switch-window

(map! :other-window "g" nil)
 
(use-package! switch-window
  :config
    (setq switch-window-input-style 'minibuffer)
    (setq switch-window-increase 4)
    (setq switch-window-threshold 2)
    (setq switch-window-shortcut-style 'qwerty)
    (setq switch-window-qwerty-shortcuts
        '("a" "s" "d" "f" "j" "k" "l" "i" "o"))
  :bind
    ([remap other-window] . switch-window))

But, did not work :(
