### ISSUE TITLE
Non-functional 'org-agenda-refile mapping in non-evil emacs configuration

### ISSUE THREAD

**Issue by shartf** [hlissner/doom-emacs#3633] opened 2020-07-27 10:00 UTC
**What did you expect to happen?**

In **non-evil** emacs while using org-agenda the "C-c C-w" keychord is shown as being mapped to org-agenda-refile. However, nothing happens if the "C-c C-w" is pressed - the last part of keychord is not activated. Function can still be called directly with M-x and works fine. 

**Steps to reproduce:**
1. Open org-agenda
2. Select an entry
3. Press "C-c C-w"

**Comment by hlissner** [comment] 2020-07-28 21:22
I cannot reproduce this in vanilla Emacs (with evil disabled). `C-c C-w` invokes a refile completion prompt as expected, so long as the cursor is over a todo item.

![image](https://user-images.githubusercontent.com/510883/88723363-b5de5300-d0f6-11ea-9b04-99a468b6342c.png)

If I do it over a date heading it says `Command not allowed in this line`. Is this what you're experiencing?

---

In the future, please do not omit your `M-x doom/info`.

**Comment by shartf** [comment] 2020-07-29 08:10
That is interesting...

I am doing it with cursor placed on an entry, so it should work. I have also searched my ~/.doom.d/ for "C-w" and "org-agenda-refile". Nothing is returned, so I have not reassigned it accidentally. 
I also have deleted ~/.emacs.d/ and pulled it again, just in case. Had no effect on the mentioned behavior.  

Here is my doom/info: 
<details>

```
emacs   version    27.0.91
        features   RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Jul 28, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/HEAD-b71b8b1/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/HEAD-b71b8b1 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/HEAD-b71b8b1 --with-gnutls --with-no-title-bars --with-rsvg --with-json)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 9c1a356 2020-07-28 20:08:32 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
        path       (/usr/local/bin /usr/local/sbin /usr/local/opt/openssl@1.1/bin ~/.rbenv/shims /usr/local/opt/sqlite/bin ~/.gem/bin ~/.nvm/versions/node/v10.15.1/bin /usr/local/bin /opt/local/bin /opt/local/sbin ~/bin /Applications/Postgres.app/Contents/Versions/latest/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /Library/Apple/usr/bin /Applications/Privileges.app/Contents/Resources /usr/local/opt/fzf/bin /usr/local/Cellar/emacs-mac/HEAD-b71b8b1/libexec/emacs/27.0.91/x86_64-apple-darwin19.6.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :tools debugger (eval +overlay) :checkers syntax spell :tools (lookup +docsets) macos magit pdf rgb :lang clojure data emacs-lisp ess javascript latex markdown (org +dragndrop +pandoc +pomodoro) python rest sh web :email mu4e :app calendar :config (default +bindings +smartparens))
        packages   ((langtool) (taskpaper-mode) (vlf) (org-super-agenda) (org-fancy-priorities) (org-superstar) (flyspell-lazy) (ess-view) (doct) (mu4e-alert) (dash-at-point) (color-identifiers-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2021-05-25 17:21
As I've yet to reproduce this and have been unable to produce additional leads, I'll close this a private configuration problem. If you have new leads, feel free to follow up here.

**Closed by hlissner** 2021-05-25 17:21 UTC
Labels: invalid
