### ISSUE TITLE
Recent performance hit in develop ?

### ISSUE THREAD

**Issue by aminb** [hlissner/doom-emacs#361] opened 2018-01-15 17:54 UTC
It seems like there might have been a performance hit to Doom's startup time some time in the last week or two. On my laptop the reported Doom startup time used to be about `0.5`-`0.6` seconds, whereas recently it's gone up to `1.0`-`1.3` seconds, and I think it does feel slower. I haven't kept an eye `develop` recently so I'm not sure about the cause.

P.S. also just noticed that the startup time displayed on the Doom dashboard is initially 0.00s and is only updated if I switch to another window or resize Emacs.

**Comment by hlissner** [comment] 2018-01-15 19:10
Three things have happened recently:

1. I've made the benchmark less naive and more accurate by taking more of startup into account in https://github.com/hlissner/doom-emacs/commit/47d15fdf8ac6db00d10eb53e375e2fd430c6ed63 (#353) -- no actual performance is lost, but the reported time is ~40-50% slower.
2. I undid a `load-path` performance optimization in https://github.com/hlissner/doom-emacs/commit/2b98e550e8b85d760a9cac172dcf4d6c3c307361 (read commit message for more details). This cost Doom roughly 10% in startup time.
3. You could be seeing slowdowns caused by the recent Meltdown patch. If you haven't followed the meltdown debacle, these patches could cause a general performance hit of up to 30% for things that cause a lot of system calls (something like Emacs does a lot of, especially on startup).
  + It's in Arch Linux as of 4.14.11-1
  + It's on MacOS as of 10.13.2  if you haven't followed the story, could mean a general performance hit of up to 30% for most intel CPUs in the last decade). I noticed ~15% slower startup after this update.

> P.S. also just noticed that the startup time displayed on the Doom dashboard is initially 0.00s and is only updated if I switch to another window or resize Emacs.

This is a bug I am aware of. The dashboard has recently been changed to initialize sooner. Unfortunately, it's so much sooner that the benchmark doesn't exist yet. I already have a fix for this ready to commit.

**Comment by aminb** [comment] 2018-01-15 21:05
Ah gotcha! It seems like I noticed a combination of all three :P (but mostly 1 I guess). Thanks for clarifying that.

>  I already have a fix for this. It will be up soon.

Great! Looking forward to it.

**Comment by hlissner** [comment] 2018-01-30 08:57
Sorry, I forgot to follow up! I posted the fix the dashboard issue a while ago, so I'll consider this issue resolved. I'll keep it open it is merged into `master`.

**Comment by aminb** [comment] 2018-01-30 14:10
No worries, and thanks!

**Closed** 2018-08-02 15:18 UTC
Labels: bug, discussion, fixed in develop
