### ISSUE TITLE
evil-inner-curly cannot be repeated

### ISSUE THREAD

**Issue by forty** [hlissner/doom-emacs#4949] opened 2021-04-29 20:22 UTC
**What did you expect to happen?**

Starting from this file:
```
{
{
// cursor here
}
}
```
`vi{i{`  or `v2i{` should select everything from the first bracket to the last bracket.

**What actually happened?**

Only the text inside the internal brackets is selected

**Additional details:**

- Using the latest develop
- This works as expected when using evil test `make terminal`, so I guess there is something wrong with Doom
- This works fine with parenthesis
- This works fine with `va{a{`

**Steps to reproduce:**

Starting from this file:
```
{
{
// cursor here
}
}
```
Type `vi{i{` 

**System information:**

`doom info` does not work here for some reasons

```
$ emacsclient -e '(emacs-version)'
"GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)\n of 2020-03-26, modified by Debian"
$ emacsclient -e '(evil-version)'
"Evil version 1.14.0"
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by hlissner** [comment] 2021-04-29 20:30
I can reproduce this in vanilla Emacs + evil [in Doom's sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox), so this is an evil issue. Please report it [upstream](https://github.com/emacs-evil/evil).

As this isn't a Doom issue, I will close this, but feel free to follow up here.

> doom info does not work here for some reasons

In the future, please explain how `M-x doom/info` failed for you.

**Comment by forty** [comment] 2021-04-29 20:42
I just tried in the Doom's sandbox, with
```
(require 'evil)
(evil-mode 1)
```
and vanilla emacs (C-c C-c) and I *cannot* reproduce the issue.


Here is the error I get with `doom info`
```
$ ~/.doom-emacs.d/bin/doom info
x There was an unexpected error
  Message: Symbol's value as variable is void
  Data: (void-variable . emacs-repository-branch)
  Backtrace:
    (list emacs-version emacs-repository-branch (and (stringp emacs-repository
    (delq nil (list emacs-version emacs-repository-branch (and (stringp emacs-
    (cons (quote emacs) (delq nil (list emacs-version emacs-repository-branch 
    (list (cons (quote generated) (format-time-string "%b %d, %Y %H:%M:%S")) (
    (progn (fset (function symlink-path) vnew) (ignore symlink-path) (list (co
    (unwind-protect (progn (fset (function symlink-path) vnew) (ignore symlink
    (let* ((vnew (function (lambda (file) (format "%s%s" (abbrev-path file) (i
    (let ((symlink-path (symbol-function (function symlink-path)))) (let* ((vn
    (progn (fset (function abbrev-path) vnew) (ignore abbrev-path) (let ((syml
    (unwind-protect (progn (fset (function abbrev-path) vnew) (ignore abbrev-p
! Extended backtrace logged to .local/doom.error.log
```

**Comment by forty** [comment] 2021-04-29 20:47
(as I noted in the report, I also tried with evil's own "sandbox" https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md and cannot reproduce either).

**Comment by forty** [comment] 2021-04-29 20:48
(I can open a separate but report for the `doom info` issue if you'd like)

**Comment by hlissner** [comment] 2021-04-29 20:50
> I can reproduce this in vanilla Emacs

Oops, meant to say I **can't**. I'll reopen this once I find more leads.

> (I can open a separate but report for the doom info issue if you'd like)

No need. A fix is already in the works.

**Comment by forty** [comment] 2021-04-29 20:56
I tested a bit more now that I discovered Doom's sandbox :) (that's pretty cool) and I can NOT repro with `vanilla Emacs` and `vanilla Doom` but I CAN with `Doom + modules - your private config`

**Comment by hlissner** [comment] 2021-04-29 21:15
Huh. I can repro this in vanilla Emacs and vanilla Doom. I can also repro this in vanilla (neo)vim, so I'm inclined to call this intended behavior.

**Comment by hlissner** [comment] 2021-04-29 21:22
EDIT: Was able to repro this in evil's `make terminal` too. Perhaps this is a 26.x issue? Could you try installing 27.x instead?

**Comment by forty** [comment] 2021-04-29 21:28
Hum I will try. But it works as I expected in my vim too, so maybe I did not explain my issue well enough. I will make a recording

**Comment by forty** [comment] 2021-04-29 21:42
https://user-images.githubusercontent.com/421352/116622160-89d15600-a944-11eb-8f15-ff9411a38e6b.mp4

**Comment by forty** [comment] 2021-04-29 21:43
I did try with emacs 27, and I have the same behavior as with emacs 26.

**Comment by forty** [comment] 2021-04-29 21:49
During my tests, I noticed that if the line is blank between the inner brackets, the behavior from both evil and vim is to select the outer bracket content directly. I'm not sure why, but this is fine. The test for this reports needs to be done with the `// cursor here` comment included (I did not realize that initially sorry)

**Comment by hlissner** [comment] 2021-04-29 22:16
Ah, the inconsistency in my tests were the blank lines. I was testing with

```
{
{
// comment here
}
}
```

Not

```
{ 

{

// comment here

}

}
```

With the latter. I'm able to see the correct behavior in vanilla Emacs, but not Doom, and I've narrowed down the issue to `evil-want-visual-char-semi-exclusive`, which [Doom sets to `t`, but evil defaults to `nil`](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/config.el#L36). This is a setting that's been in Doom for more than 4 years, so the reason for it is lost. `(setq evil-want-visual-char-semi-exclusive nil)` should fix the issue. I'll remove the setting from Doom's module shortly.

**Comment by hlissner** [comment] 2021-04-29 22:19
And done. As of 437c33a this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention! And for all your input! It helped me zero in on the cause pretty quickly!

**Closed** 2021-04-29 22:18 UTC
Labels: :editor evil, is:bug

**Comment by forty** [comment] 2021-04-29 22:34
Wonderful :) I can confirm both issues are now fixed on my side too. Thanks a lot for the quick resolution, I was happy to help :)
