### ISSUE TITLE
(projectile-project-root) returns incorrect value

### ISSUE THREAD

**Issue by leoalekseyev** [hlissner/doom-emacs#3288] opened 2020-06-03 13:50 UTC
**What did you expect to happen?**
Run (projectile-project-root) visiting non-project buffer, expect to get nil.

**What actually happened?**
Returns the last project visited. Furthermore, it resulted in visible breakage of doom-modeline path entry (since it relies on projectile to display buffer path information).

**Additional details:**
This appears related to #3205 but that fix seems to not be effective here.  

When I traced through `(projectile-project-root)` in edebug it was clear that somehow the cache gets into a bad state (i.e. variable `projectile-project-root-cache` contains entry for non-project files), and M-x projectile-invalidate-cache was not effective in removing the bad cache values and the associated mode line breakage; I had to restart Emacs.

Note also that this behavior doesn't happen with plain emacs (`emacs -Q`) with only projectile loaded.

Attached is a repro that clearly shows wrong project names in ivy buffer and as eval results.  None of the org files in this example belong to projects yet they are reported to belong to project "projectile" (since that was the last project visited).

Below the gif is a screenshot demonstrating the doom-modeline breakage due to incorrectly reported project root. The incorrect buffer names will persist until I restarting Emacs, which is quite annoying.

![projectile-bug](https://user-images.githubusercontent.com/338250/83644811-8849b300-a566-11ea-9871-936d0b6d68a4.gif)

![image](https://user-images.githubusercontent.com/338250/83663771-f9e12b80-a57d-11ea-8701-8c3988c6970a.png)

**Comment by hlissner** [comment] 2020-06-04 23:44
I believe the cause of this is the same as 60ca118, which I just pushed a fix for. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!

**Closed by hlissner** 2020-06-04 23:44 UTC
Labels: is:duplicate

**Comment by leoalekseyev** [comment] 2020-06-04 23:53
Appears to be working, thanks!
