### ISSUE TITLE
Error connecting to ClojureScript REPL: (void-function :number)

### ISSUE THREAD

**Issue by caleb** [hlissner/doom-emacs#5541] opened 2021-09-30 15:21 UTC
### What did you expect to happen?

I hit `SPC m C` and selected my host/port and `shadow` as the REPL type and then get connected to the REPL

### What actually happened?

When I tried connecting to my REPL like usual, I get this error

```
Debugger entered--Lisp error: (void-function :number)
  :number(0)
  parseclj-lex--leaf-token-value(((:token-type . :keyword) (:form . ":deps") (:pos . 31)))
  parseedn-reduce-leaf((((:token-type . :lbrace) (:form . "{") (:pos . 30))) ((:token-type . :keyword) (:form . ":deps") (:pos . 31)) ((:tag-readers (shadow/env . identity))))
  parseclj-parser(parseedn-reduce-leaf parseedn-reduce-branch ((:tag-readers (shadow/env . identity))))
  parseedn-read(((shadow/env . identity)))
  cider--shadow-get-builds()
  cider-shadow-cljs-init-form()
  cider-cljs-repl-form(shadow)
  cider--update-cljs-init-function((:project-dir "~/Projects/mojo_tools/frontend/" :host "localhost" :port 9000 :cljs-repl-type shadow))
  cider-connect-cljs(nil)
  funcall-interactively(cider-connect-cljs nil)
  call-interactively(cider-connect-cljs nil nil)
  command-execute(cider-connect-cljs)
```

This is like the previous issue #4539

### Describe your attempts to resolve the issue

I removed my `~/.emacs.d` directory and reinstalled doom but the issue still happens.

I am on the latest commit of doom

### Steps to reproduce

1. Open a ClojureScript project in Emacs
2. Hit `SPC m C`
3. Select `localhost:9000` or your shadow script host
4. Select `shadow`

### System Information

https://pastebin.com/6UYx8gpG

**Comment by hlissner** [comment] 2021-10-02 20:07
Duplicate of #5561

**Closed by hlissner** 2021-10-02 20:07 UTC
Labels: duplicate, delete me
