### ISSUE TITLE
"Local variables entry is missing the suffix" error when installing packages

### ISSUE THREAD

**Issue by rzikm** [hlissner/doom-emacs#2637] opened 2020-02-29 16:09 UTC
**What did you expect to happen?**
Using cc module, or *-posframe packages and running `doom sync` should work.

**What actually happened?**
Error during compilation of the affected packages(s),
```
error: (Local variables entry is missing the suffix)
```
full output available below.

**Additional details:**
Currently running emacs 26.3, but I have tried 27 and 28 with same result.
I have tried reinstalling doom from scratch.
On my work PC, I have exactly the same setup, but there it works correctly. I was unable to find any similar issues on the internet.

repo link: https://github.com/rzikm/.doom.d/
running `doom -d sync` produces following output
<details><pre>- Debug mode on
> Synchronizing your config with Doom Emacs...
  > (Re)generating core autoloads...
    > Generating core autoloads...
    - Scanning core/autoload/buffers.el
    - Scanning core/autoload/cache.el
    - Scanning core/autoload/cli.el
    - Scanning core/autoload/config.el
    - Scanning core/autoload/debug.el
    - Scanning core/autoload/files.el
    - Scanning core/autoload/fonts.el
    - Scanning core/autoload/format.el
    - Scanning core/autoload/help.el
    - Scanning core/autoload/packages.el
    - Scanning core/autoload/plist.el
    - Scanning core/autoload/projects.el
    - Scanning core/autoload/scratch.el
    - Scanning core/autoload/sessions.el
    - Scanning core/autoload/text.el
    - Scanning core/autoload/themes.el
    - Scanning core/autoload/ui.el
    - Scanning modules/app/calendar/autoload.el
    - Scanning modules/app/irc/autoload/irc.el
    - Scanning modules/app/irc/autoload/settings.el
    - Scanning modules/app/regex/autoload/export.el
    - Scanning modules/app/regex/autoload/regex.el
    - Scanning modules/app/rss/autoload.el
    - Scanning modules/app/twitter/autoload.el
    - Scanning modules/checkers/spell/autoload.el
    - Scanning modules/checkers/syntax/autoload.el
    - Scanning modules/completion/company/autoload.el
    - Scanning modules/completion/helm/autoload/evil.el
    - Scanning modules/completion/helm/autoload/helm.el
    - Scanning modules/completion/helm/autoload/posframe.el
    - Scanning modules/completion/ivy/autoload/evil.el
    - Scanning modules/completion/ivy/autoload/hydras.el
    - Scanning modules/completion/ivy/autoload/ivy.el
    - Scanning modules/completion/ivy/autoload/posframe.el
    - Scanning modules/config/default/autoload/default.el
    - Scanning modules/config/default/autoload/files.el
    - Scanning modules/config/default/autoload/search.el
    - Scanning modules/config/default/autoload/text.el
    - Scanning modules/config/literate/autoload.el
    - Scanning modules/editor/evil/autoload/advice.el
    - Scanning modules/editor/evil/autoload/embrace.el
    - Scanning modules/editor/evil/autoload/evil.el
    - Scanning modules/editor/evil/autoload/ex.el
    - Scanning modules/editor/evil/autoload/files.el
    - Scanning modules/editor/evil/autoload/textobjects.el
    - Scanning modules/editor/evil/autoload/unimpaired.el
    - Scanning modules/editor/file-templates/autoload.el
    - Scanning modules/editor/fold/autoload/fold.el
    - Scanning modules/editor/fold/autoload/hideshow.el
    - Scanning modules/editor/format/autoload/evil.el
    - Scanning modules/editor/format/autoload/format.el
    - Scanning modules/editor/format/autoload/settings.el
    - Scanning modules/editor/god/autoload.el
    - Scanning modules/editor/multiple-cursors/autoload/evil-mc.el
    - Scanning modules/editor/rotate-text/autoload.el
    - Scanning modules/editor/snippets/autoload/settings.el
    - Scanning modules/editor/snippets/autoload/snippets.el
    - Scanning modules/editor/word-wrap/autoload.el
    - Scanning modules/emacs/dired/autoload.el
    - Scanning modules/emacs/electric/autoload.el
    - Scanning modules/emacs/vc/autoload/hydra.el
    - Scanning modules/emacs/vc/autoload/vc.el
    - Scanning modules/email/mu4e/autoload/email.el
    - Scanning modules/email/mu4e/autoload/evil.el
    - Scanning modules/email/notmuch/autoload.el
    - Scanning modules/email/wanderlust/autoload.el
    - Scanning modules/lang/assembly/autoload.el
    - Scanning modules/lang/cc/autoload.el
    - Scanning modules/lang/clojure/autoload.el
    - Scanning modules/lang/common-lisp/autoload/common-lisp.el
    - Scanning modules/lang/csharp/autoload.el
    - Scanning modules/lang/emacs-lisp/autoload.el
    - Scanning modules/lang/ess/autoload.el
    - Scanning modules/lang/faust/autoload.el
    - Scanning modules/lang/go/autoload.el
    - Scanning modules/lang/haskell/autoload.el
    - Scanning modules/lang/java/autoload.el
    - Scanning modules/lang/javascript/autoload.el
    - Scanning modules/lang/julia/autoload.el
    - Scanning modules/lang/kotlin/autoload.el
    - Scanning modules/lang/latex/autoload.el
    - Scanning modules/lang/lua/autoload/lua.el
    - Scanning modules/lang/lua/autoload/moonscript.el
    - Scanning modules/lang/markdown/autoload.el
    - Scanning modules/lang/nix/autoload.el
    - Scanning modules/lang/ocaml/autoload.el
    - Scanning modules/lang/org/autoload/contrib-dragndrop.el
    - Scanning modules/lang/org/autoload/contrib-ipython.el
    - Scanning modules/lang/org/autoload/contrib-present.el
    - Scanning modules/lang/org/autoload/org-attach.el
    - Scanning modules/lang/org/autoload/org-avy.el
    - Scanning modules/lang/org/autoload/org-capture.el
    - Scanning modules/lang/org/autoload/org-export.el
    - Scanning modules/lang/org/autoload/org-link.el
    - Scanning modules/lang/org/autoload/org-refile.el
    - Scanning modules/lang/org/autoload/org-tables.el
    - Scanning modules/lang/org/autoload/org.el
    - Scanning modules/lang/php/autoload.el
    - Scanning modules/lang/plantuml/autoload.el
    - Scanning modules/lang/python/autoload/conda.el
    - Scanning modules/lang/python/autoload/pyenv.el
    - Scanning modules/lang/python/autoload/python.el
    - Scanning modules/lang/qt/autoload.el
    - Scanning modules/lang/racket/autoload.el
    - Scanning modules/lang/rest/autoload.el
    - Scanning modules/lang/ruby/autoload.el
    - Scanning modules/lang/rust/autoload.el
    - Scanning modules/lang/scala/autoload.el
    - Scanning modules/lang/scheme/autoload.el
    - Scanning modules/lang/sh/autoload.el
    - Scanning modules/lang/terra/autoload.el
    - Scanning modules/lang/web/autoload/css.el
    - Scanning modules/lang/web/autoload/evil.el
    - Scanning modules/lang/web/autoload/html.el
    - Scanning modules/term/eshell/autoload/commands.el
    - Scanning modules/term/eshell/autoload/company.el
    - Scanning modules/term/eshell/autoload/eshell.el
    - Scanning modules/term/eshell/autoload/evil.el
    - Scanning modules/term/eshell/autoload/prompts.el
    - Scanning modules/term/eshell/autoload/settings.el
    - Scanning modules/term/shell/autoload.el
    - Scanning modules/term/term/autoload.el
    - Scanning modules/term/vterm/autoload.el
    - Scanning modules/tools/debugger/autoload/debugger.el
    - Scanning modules/tools/debugger/autoload/evil.el
    - Scanning modules/tools/editorconfig/autoload.el
    - Scanning modules/tools/ein/autoload/ein.el
    - Scanning modules/tools/ein/autoload/hydra.el
    - Scanning modules/tools/eval/autoload/eval.el
    - Scanning modules/tools/eval/autoload/evil.el
    - Scanning modules/tools/eval/autoload/repl.el
    - Scanning modules/tools/eval/autoload/settings.el
    - Scanning modules/tools/gist/autoload/evil.el
    - Scanning modules/tools/lookup/autoload/docsets.el
    - Scanning modules/tools/lookup/autoload/evil.el
    - Scanning modules/tools/lookup/autoload/lookup.el
    - Scanning modules/tools/lookup/autoload/online.el
    - Scanning modules/tools/lsp/autoload.el
    - Scanning modules/tools/macos/autoload.el
    - Scanning modules/tools/magit/autoload.el
    - Scanning modules/tools/make/autoload.el
    - Scanning modules/tools/pass/autoload.el
    - Scanning modules/tools/pdf/autoload/pdf.el
    - Scanning modules/tools/prodigy/autoload.el
    - Scanning modules/tools/rgb/autoload.el
    - Scanning modules/tools/tmux/autoload/evil.el
    - Scanning modules/tools/tmux/autoload/tmux.el
    - Scanning modules/ui/doom-dashboard/autoload.el
    - Scanning modules/ui/fill-column/autoload.el
    - Scanning modules/ui/hydra/autoload/windows.el
    - Scanning modules/ui/modeline/autoload.el
    - Scanning modules/ui/nav-flash/autoload.el
    - Scanning modules/ui/neotree/autoload.el
    - Scanning modules/ui/popup/autoload/popup.el
    - Scanning modules/ui/popup/autoload/settings.el
    - Scanning modules/ui/pretty-code/autoload.el
    - Scanning modules/ui/treemacs/autoload.el
    - Scanning modules/ui/unicode/autoload.el
    - Scanning modules/ui/vc-gutter/autoload.el
    - Scanning modules/ui/vi-tilde-fringe/autoload.el
    - Scanning modules/ui/workspaces/autoload/evil.el
    - Scanning modules/ui/workspaces/autoload/workspaces.el
    > Byte-compiling core autoloads file...
    [32mΓ£ô Generated .local/autoloads.elc[0m
  > Installing packages...
    -> Building helm-posframe...
[31mx There was an unexpected error:[0m
  [1mType:[0m doom-package-error
  [1mMessage:[0m
    Error with packages
  [1mData:[0m
    "helm-posframe"
    (error "helm-posframe.el:0:0: error: error: (Local variables entry is missing the suffix)")
    "FIND: Invalid switch
    "

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d sync

If you file a bug report, please include it!

</pre></details>

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop ac87afe34 2020-02-29 00:30:22 -0500")
  (dir . "c:/Users/rzikm/.doom.d/"))
 (system
  (type . windows-nt)
  (config . "x86_64-w64-mingw32")
  (shell . "C:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/26.3/x86_64-w64-mingw32/cmdproxy.exe")
  (uname . "n/a")
  (path "c:/Program Files/ConEmu/ConEmu/Scripts" "C:/Program Files/ConEmu" "C:/Program Files/ConEmu/ConEmu" "C:/Perl64/site/bin" "C:/Perl64/bin" "C:/Program Files (x86)/Common Files/Oracle/Java/javapath" "C:/Python38/Scripts/" "C:/Python38/" "C:/Windows/system32" "C:/Windows" "C:/Windows/System32/Wbem" "C:/Windows/System32/WindowsPowerShell/v1.0/" "C:/Windows/System32/OpenSSH/" "C:/ProgramData/chocolatey/bin" "C:/Program Files/dotnet/" "C:/Program Files/Microsoft SQL Server/130/Tools/Binn/" "C:/tools/BCURRAN3" "C:/Program Files/LLVM/bin" "C:/Program Files/Git/cmd" "C:/Users/rzikm/.cargo/bin" "C:/Users/rzikm/AppData/Local/Microsoft/WindowsApps" "C:/Program Files/Emacs/x86_64/bin/" "C:/Program Files/NASM" "C:/Program Files (x86)/OpenSSL/bin/" "C:/Program Files/CMake/bin/" "C:/Users/rzikm/.dotnet/tools" "C:/Users/rzikm/.emacs.d/bin" "." "c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/26.3/x86_64-w64-mingw32"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company helm :ui doom doom-dashboard doom-quit fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) gist (lookup +docsets) lsp magit make :lang csharp data emacs-lisp fsharp latex markdown (org +dragndrop +present) php python rst rust sh web :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (unpin . "<(void-function sp-point-in-string)>")
  (elpa "n/a")))
</pre></details>

**Comment by newmaidumosa** [comment] 2020-03-30 22:04
is there any work around for this. I would like to get **lang cc** up and running.  Thanks.

**Comment by hlissner** [comment] 2020-05-12 08:14
Sorry for the long delay, I've finally zeroed in on the cause of this. The problem is that some packages have hard-coded an windows-unfriendly file encoding at the end of their packages.

irony-eldoc and helm-posframe are two known packages with these file local variables:

```elisp
;; Local Variables:
;; coding: utf-8-unix
;; End:
```

`utf-8-unix` should be `utf-8`. This will need to be brought up upstream.

**Comment by hlissner** [comment] 2020-05-12 09:20
I made a pull request upstream to fix the issue with helm-posframe, specifically, and it was merged, so @rzikm's original issue should be resolved. I'll keep this issue open until

1. I've updated Doom's documentation to mention this workaround for Windows users:

   ```sh
   git config --global core.autocrlf true
   ```

2. I've PRed a fix for irony-eldoc (or we move to a superior fork, since it may no longer be maintained).

**Comment by nmillington** [comment] 2020-05-23 20:48
Thank you, have just encountered this bug today.  Switched on lsp mode but will get the work around going.

**Closed** 2020-06-25 00:18 UTC
Labels: is:external, re:bin/doom, re:git, re:packages, status:has-workaround

**Comment by hlissner** [comment] 2020-06-25 00:20
As of 0443eeb (and ikirill/irony-eldoc#13 and tumashu/helm-posframe#9) this should be resolved (in irony-eldoc and helm-posframe's cases, at least). I haven't yet mentioned it in the docs, but I'm working on a documentation redesign and will include it with that. I'll close this for now, but thanks for bringing it to my attention!
