### ISSUE TITLE
Freezes when LSP is enabled

### ISSUE THREAD

**Issue by boppyt** [hlissner/doom-emacs#5557] opened 2021-10-02 15:43 UTC
### What did you expect to happen?

When I enable lsp plugin (the one with the comment 'M-x vscode') and any other language with +lsp, I expect to have LSP hints with fancy boxes from the lsp plugin.

### What actually happened?

Instead, entire emacs freezes until a USRSIG2 is recieved.

### Describe your attempts to resolve the issue

I have tried asking this question in discord, and was prompted to report the issue here.
I have tried disabling the LSP plugin, works flawlessly except that now I have crappy hints instead of those fancy boxes.

Trace:
https://hastebin.com/fohuwutazo

### Steps to reproduce

1. Open init.el
2. enable `lsp` and any language with `+lsp`
3. run `doom sync`
4. Restart emacs
5. open a project to trigger the LSP
6. emacs freezes

### System Information

https://hastebin.com/etozimizuj

**Comment by hlissner** [comment] 2021-10-02 16:51
Judging from the backtrace, `lsp-mode` is allocating too many file watchers, and doing so recursively in your `$HOME` -- which is usually not what the user wants. 

How `$HOME` became associated with your `/mnt/data/programming/projects/learn/haskell` project, I don't know. There are a number of possibilities, here are some common explanations:

- Projectile thinks `$HOME` is the root of your learn/haskell project, for some reason (projectile typically works up the file tree to find one of the project markers, like `.git` or `package.json`, but unless there's a symlink involved, I don't see how it could work up to `$HOME`. If this is the case, the quick fix is to add an empty `.project` file at the _real_ root. You may need to clear the cache though (`M-x projectile-invalidate-cache`) and kill/reopen the buffer.
- You've added `$HOME` to the workspace of one of your projects. LSP prompts you to select a project root if it can't determine it automatically (with projectile). If this is the case, you can remove it with `M-x lsp-workspace-folders-remove`
- Maybe one or both of the above is exactly what you wanted, in that case, you may be best off disabling file watching altogether: `(setq lsp-enable-file-watchers nil)` -- YMMV though. Some LSP servers require them.
- Alternatively, add your `$HOME` to `lsp-file-watch-ignored-directories`.

In any case this is a configuration issue, rather than a Doom or lsp-mode issue, but there is no general solution to this that Doom can employ, so I will close this.

Feel free to follow up here, but I would recommend bringing it up on [our Discord](https://doomemacs.org/discord) or taking this information back to the LSP guys -- perhaps they know better tricks. At the very least, I can't reproduce this in any normal LSP projects where `$HOME` _hasn't_ been added to the workspace.

Hope that helps!

**Closed by hlissner** 2021-10-02 16:51 UTC
Labels: invalid, delete me

**Comment by boppyt** [comment] 2021-10-03 07:55
Whoops, sorry can confirm this was indeed my configuration issue.
I accidently messed up the zsh config in my NixOS flakes which resulted in a weird dir getting symlinked to $HOME
