### ISSUE TITLE
(format +onsave) and (go +lsp) conflicts with each other

### ISSUE THREAD

**Issue by Kaali** [hlissner/doom-emacs#2516] opened 2020-02-10 13:05 UTC
**What did you expect to happen?**
I expected go buffers to be formatted and imports organized on save. Preferably by gopls. And expected there to be no errors.

**What actually happened?**
gofmt is run on save, which is fine. But then the .go file will have a persistent error that says `expected declaration, found 'package'`. After that it will start showing errors all around the files, that are not really errors. And sometimes the errors disappear. gopls logs are also filled with AST errors.

My guess is that gofmt and gopls sees different versions of the files as both are trying to touch it. As I also see errors from lsp-mode trying to apply edits and ending up in an error.

Sorry for the convoluted explanation, I haven't yet debugged this more.

**Additional details:**
I fixed the problem locally by disabling format-on-save for go-mode with:
```
(add-to-list '+format-on-save-enabled-modes 'go-mode t)
```

and using LSP formatters manually with:
```
(add-hook! 'go-mode-hook
  (add-hook 'before-save-hook #'lsp-format-buffer nil 'local)
  (add-hook 'before-save-hook #'lsp-organize-imports nil 'local))
```

If issue #1652 would be implemented then this would not be a problem.

**Steps to reproduce:**
1. Hard to come up with exact steps. As the problem is quite flaky.

**System information:**
<details>

```
emacs   version    27.0.60
        features   RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP
        build      Feb 10, 2020
        buildopts  (--prefix=/nix/store/jvd9gpf3r0lfpmd18aymx0ibcqrb08r4-emacs-27.0.50 --disable-build-details --with-modules --with-ns --disable-ns-self-contained 'CFLAGS=-O3 -DMAC_OS_X_VERSION_MAX_ALLOWED=101200')
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop ae75326a4 2020-02-10 02:39:26 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.2.0
        shell      /run/current-system/sw/bin/bash
        uname      Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
        path       (~/.nix-profile/bin ~/.gimme/versions/go1.13.5.darwin.amd64/bin  /run/current-system/sw/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /usr/sbin /bin /sbin ~/go/bin /nix/store/jvd9gpf3r0lfpmd18aymx0ibcqrb08r4-emacs-27.0.50/libexec/emacs/27.0.60/x86_64-apple-darwin19.2.0/)
config  envfile    envvar-file
        elc-files  2
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term vterm :checkers syntax :tools direnv docker editorconfig (eval +overlay) (lookup +docsets) lsp macos magit make :lang data emacs-lisp (go +lsp) (javascript +lsp) markdown nix (org +dragndrop +present) (python +lsp) sh web :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (vterm)
        unpin      (n/a)
```
</details>

**Comment by hlissner** [comment] 2020-02-20 23:27
Sorry for the late response.

> If issue #1652 would be implemented then this would not be a problem.

I'll consider this a duplicate of #1652 and move it (and my response) over there.

**Closed by hlissner** 2020-02-20 23:27 UTC
Labels: is:duplicate
