### ISSUE TITLE
Cannot install due to package breakage

### ISSUE THREAD

**Issue by birdiesanders** [hlissner/doom-emacs#5390] opened 2021-08-17 13:04 UTC
### What did you expect to happen?

When running the install command, the process fails due to an error. 

### What actually happened?

This was all that I could get out of it. 
```
 > Cloning gcmh...
    x There was an unexpected error
      Message: Wrong type argument
      Data: (wrong-type-argument . arrayp)
      Backtrace:
        (substring nil 0 0)
        (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
        (shell-quote-argument nil)
        (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
        (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name direct
        (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file
        (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (exp
        (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n
        (let* ((result result) (exit (car result)) (invoked (numberp exit)) (succe
        (let ((directory x6) (result x4) (args x2) (program x0)) (let* ((result re
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

### Describe your attempts to resolve the issue

I deleted .emacs.d and .doom.d

### Steps to reproduce

Run install steps

### System Information

could not get doom installed to pull this.

**Comment by BlueDrink9** [comment] 2021-09-04 10:16
If you are running a more stable branch of Doom rather than a bleeding-edge, this is better suited to asking on the Discord

**Comment by hlissner** [comment] 2021-09-04 14:44
Duplicate of https://github.com/hlissner/doom-emacs/issues/5207. See https://github.com/hlissner/doom-emacs/issues/5207#issuecomment-877750996.

**Closed by hlissner** 2021-09-04 14:44 UTC
Labels: duplicate
