### ISSUE TITLE
Error running timer ‘gac--after-save’: (args-out-of-range 60 119)

### ISSUE THREAD

**Issue by tru2dagame** [hlissner/doom-emacs#2532] opened 2020-02-12 20:29 UTC
**What did you expect to happen?**
`ws-butler-global-mode` works with `git-auto-commit-mode`

**What actually happened?**
When both mode is enabled, it would cause this error:
`Error running timer ‘gac--after-save’: (args-out-of-range 60 119)`

**Additional details:**
```
config.el
(use-package! git-auto-commit-mode
  :config
  (setq-default gac-debounce-interval 10)
)

package.el
(package! git-auto-commit-mode)
```

<details><pre>
If an error message is involved include a backtrace of it.

Debugger entered--Lisp error: (args-out-of-range 75 149)
  put-text-property(75 149 ws-butler-chg chg)
  ws-butler-after-change(75 149 0)
  call-process-region(27 27 "/bin/zsh" nil #<buffer *Shell Command Output*> nil "-c" "git add  daily.org && git commit -m daily.org")
  call-shell-region(27 27 "git add  daily.org && git commit -m daily.org" nil #<buffer *Shell Command Output*>)
  shell-command-on-region(27 27 "git add  daily.org && git commit -m daily.org" nil nil nil)
  #f(compiled-function (command &optional output-buffer error-buffer) "Execute string COMMAND in inferior shell; display output, if any.\nWith prefix argument, insert the COMMAND's output at point.\n\nInteractively, prompt for COMMAND in the minibuffer.\nIf `shell-command-prompt-show-cwd' is non-nil, show the current\ndirectory in the prompt.\n\nIf COMMAND ends in `&', execute it asynchronously.\nThe output appears in the buffer `*Async Shell Command*'.\nThat buffer is in shell mode.  You can also use\n`async-shell-command' that automatically adds `&'.\n\nOtherwise, COMMAND is executed synchronously.  The output appears in\nthe buffer `*Shell Command Output*'.  If the output is short enough to\ndisplay in the echo area (which is determined by the variables\n`resize-mini-windows' and `max-mini-window-height'), it is shown\nthere, but it is nonetheless available in buffer `*Shell Command\nOutput*' even though that buffer is not automatically displayed.\n\nTo specify a coding system for converting non-ASCII characters\nin the shell command output, use \\[universal-coding-system-argument] before this command.\n\nNoninteractive callers can specify coding systems by binding\n`coding-system-for-read' and `coding-system-for-write'.\n\nThe optional second argument OUTPUT-BUFFER, if non-nil,\nsays to put the output in some other buffer.\nIf OUTPUT-BUFFER is a buffer or buffer name, erase that buffer\nand insert the output there; a non-nil value of\n`shell-command-dont-erase-buffer' prevents the buffer from being\nerased.  If OUTPUT-BUFFER is not a buffer and not nil, insert the\noutput in current buffer after point leaving mark after it.  This\ncannot be done asynchronously.\n\nIf the command terminates without error, but generates output,\nand you did not specify \"insert it in the current buffer\",\nthe output can be displayed in the echo area or in its buffer.\nIf the output is short enough to display in the echo area\n(determined by the variable `max-mini-window-height' if\n`resize-mini-windows' is non-nil), it is shown there.\nOtherwise, the buffer containing the output is displayed.\n\nIf there is output and an error, and you did not specify \"insert it\nin the current buffer\", a message about the error goes at the end\nof the output.\n\nIf the optional third argument ERROR-BUFFER is non-nil, it is a buffer\nor buffer name to which to direct the command's standard error output.\nIf it is nil, error output is mingled with regular output.\nIn an interactive call, the variable `shell-command-default-error-buffer'\nspecifies the value of ERROR-BUFFER.\n\nIn Elisp, you will often be better served by calling `call-process' or\n`start-process' directly, since they offer more control and do not\nimpose the use of a shell (with its need to quote arguments)." (interactive #f(compiled-function () #<bytecode 0x1ff288e68699>)) #<bytecode 0x41ca1c91>)("git add  daily.org && git commit -m daily.org" nil nil)
  shell-command--shell-command-with-editor-mode(#f(compiled-function (command &optional output-buffer error-buffer) "Execute string COMMAND in inferior shell; display output, if any.\nWith prefix argument, insert the COMMAND's output at point.\n\nInteractively, prompt for COMMAND in the minibuffer.\nIf `shell-command-prompt-show-cwd' is non-nil, show the current\ndirectory in the prompt.\n\nIf COMMAND ends in `&', execute it asynchronously.\nThe output appears in the buffer `*Async Shell Command*'.\nThat buffer is in shell mode.  You can also use\n`async-shell-command' that automatically adds `&'.\n\nOtherwise, COMMAND is executed synchronously.  The output appears in\nthe buffer `*Shell Command Output*'.  If the output is short enough to\ndisplay in the echo area (which is determined by the variables\n`resize-mini-windows' and `max-mini-window-height'), it is shown\nthere, but it is nonetheless available in buffer `*Shell Command\nOutput*' even though that buffer is not automatically displayed.\n\nTo specify a coding system for converting non-ASCII characters\nin the shell command output, use \\[universal-coding-system-argument] before this command.\n\nNoninteractive callers can specify coding systems by binding\n`coding-system-for-read' and `coding-system-for-write'.\n\nThe optional second argument OUTPUT-BUFFER, if non-nil,\nsays to put the output in some other buffer.\nIf OUTPUT-BUFFER is a buffer or buffer name, erase that buffer\nand insert the output there; a non-nil value of\n`shell-command-dont-erase-buffer' prevents the buffer from being\nerased.  If OUTPUT-BUFFER is not a buffer and not nil, insert the\noutput in current buffer after point leaving mark after it.  This\ncannot be done asynchronously.\n\nIf the command terminates without error, but generates output,\nand you did not specify \"insert it in the current buffer\",\nthe output can be displayed in the echo area or in its buffer.\nIf the output is short enough to display in the echo area\n(determined by the variable `max-mini-window-height' if\n`resize-mini-windows' is non-nil), it is shown there.\nOtherwise, the buffer containing the output is displayed.\n\nIf there is output and an error, and you did not specify \"insert it\nin the current buffer\", a message about the error goes at the end\nof the output.\n\nIf the optional third argument ERROR-BUFFER is non-nil, it is a buffer\nor buffer name to which to direct the command's standard error output.\nIf it is nil, error output is mingled with regular output.\nIn an interactive call, the variable `shell-command-default-error-buffer'\nspecifies the value of ERROR-BUFFER.\n\nIn Elisp, you will often be better served by calling `call-process' or\n`start-process' directly, since they offer more control and do not\nimpose the use of a shell (with its need to quote arguments)." (interactive #f(compiled-function () #<bytecode 0x1ff289534ae5>)) #<bytecode 0x41ca1c91>) "git add  daily.org && git commit -m daily.org")
  apply(shell-command--shell-command-with-editor-mode #f(compiled-function (command &optional output-buffer error-buffer) "Execute string COMMAND in inferior shell; display output, if any.\nWith prefix argument, insert the COMMAND's output at point.\n\nInteractively, prompt for COMMAND in the minibuffer.\nIf `shell-command-prompt-show-cwd' is non-nil, show the current\ndirectory in the prompt.\n\nIf COMMAND ends in `&', execute it asynchronously.\nThe output appears in the buffer `*Async Shell Command*'.\nThat buffer is in shell mode.  You can also use\n`async-shell-command' that automatically adds `&'.\n\nOtherwise, COMMAND is executed synchronously.  The output appears in\nthe buffer `*Shell Command Output*'.  If the output is short enough to\ndisplay in the echo area (which is determined by the variables\n`resize-mini-windows' and `max-mini-window-height'), it is shown\nthere, but it is nonetheless available in buffer `*Shell Command\nOutput*' even though that buffer is not automatically displayed.\n\nTo specify a coding system for converting non-ASCII characters\nin the shell command output, use \\[universal-coding-system-argument] before this command.\n\nNoninteractive callers can specify coding systems by binding\n`coding-system-for-read' and `coding-system-for-write'.\n\nThe optional second argument OUTPUT-BUFFER, if non-nil,\nsays to put the output in some other buffer.\nIf OUTPUT-BUFFER is a buffer or buffer name, erase that buffer\nand insert the output there; a non-nil value of\n`shell-command-dont-erase-buffer' prevents the buffer from being\nerased.  If OUTPUT-BUFFER is not a buffer and not nil, insert the\noutput in current buffer after point leaving mark after it.  This\ncannot be done asynchronously.\n\nIf the command terminates without error, but generates output,\nand you did not specify \"insert it in the current buffer\",\nthe output can be displayed in the echo area or in its buffer.\nIf the output is short enough to display in the echo area\n(determined by the variable `max-mini-window-height' if\n`resize-mini-windows' is non-nil), it is shown there.\nOtherwise, the buffer containing the output is displayed.\n\nIf there is output and an error, and you did not specify \"insert it\nin the current buffer\", a message about the error goes at the end\nof the output.\n\nIf the optional third argument ERROR-BUFFER is non-nil, it is a buffer\nor buffer name to which to direct the command's standard error output.\nIf it is nil, error output is mingled with regular output.\nIn an interactive call, the variable `shell-command-default-error-buffer'\nspecifies the value of ERROR-BUFFER.\n\nIn Elisp, you will often be better served by calling `call-process' or\n`start-process' directly, since they offer more control and do not\nimpose the use of a shell (with its need to quote arguments)." (interactive #f(compiled-function () #<bytecode 0x1ff288e6b2a9>)) #<bytecode 0x41ca1c91>) "git add  daily.org && git commit -m daily.org")
  shell-command("git add  daily.org && git commit -m daily.org")
  gac-commit(#<buffer daily.org>)
  gac--after-save(#<buffer daily.org>)
  apply(gac--after-save #<buffer daily.org>)
  timer-event-handler([t 24132 24103 165838 nil gac--after-save (#<buffer daily.org>) nil 0])

</pre></details>

**System information:**
<details><pre>
```
emacs   version    27.0.60
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP
        build      Feb 07, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-b2e27d8/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-b2e27d8 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop f9eb6a3b6 2020-02-11 19:24:08 -0500
        dir        ~/Dropbox/Apps/emacs/tru/doom-emacs/
system  type       darwin
        config     x86_64-apple-darwin19.3.0
        shell      /bin/zsh
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (/usr/local/opt/sqlite/bin ~/.tgenv/bin /usr/local/opt/node@8/bin /usr/local/opt /usr/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Server.app/Contents/ServerRoot/usr/bin /Applications/Server.app/Contents/ServerRoot/usr/sbin /Applications/Wireshark.app/Contents/MacOS /opt/local/bin /opt/local/sbin /usr/local/mysql/bin /usr/bin /bin /usr/sbin /sbin /usr/local/bin /usr/local/git/bin ~/.composer/vendor/bin /usr/local/sbin ~/go/bin /usr/local/opt/go/libexec/bin /usr/local/Cellar/emacs-plus/HEAD-b2e27d8/libexec/emacs/27.0.60/x86_64-apple-darwin19.3.0/)
config  envfile    envvar-file
        elc-files  1079
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash neotree ophints (popup +all +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term vterm :checkers syntax :tools docker (eval +overlay) (lookup +docsets) macos magit terraform tmux :lang data emacs-lisp go markdown (org +dragndrop +hugo +present) php python sh web :config literate (default +bindings +smartparens))
        packages   ((ox-twbs) (sudo-edit) (google-this) (git-auto-commit-mode) (grab-mac-link) (ivy-posframe) (helm-org-rifle) (nyan-mode) (edit-server))
        elpa       (yasnippet writegood-mode with-editor winum wgrep web-mode vterm volatile-highlights vimish-fold undo-tree treepy treemacs-projectile treemacs-persp treemacs-magit treemacs-evil treemacs transient toc-org terraform-mode tablist switch-window swiper spinner solaire-mode shut-up shrink-path s request ranger pyvenv pythonic python-pytest pyimport pyenv-mode py-isort projectile prescient powerline posframe popup pkg-info pipenv phpactor php-runtime php-refactor-mode php-mode pfuture persp-mode pdf-tools pcre2el parent-mode ox-twbs org-tree-slide org-re-reveal org-pdfview org-download org-bullets org-bookmark-heading nose nav-flash memoize markdown-mode magit-todos magit-popup magit-gitflow magit lv lsp-python-ms lsp-mode langtool json-snatcher json-reformat json-mode ivy-xref ivy-rich ivy-prescient ivy-posframe ivy-hydra ivy iedit ibuffer-projectile hydra htmlize ht hl-todo helm-xref helm-core helm hcl-mode hack-mode graphql-mode goto-chg gorepl-mode go-mode github-review git-gutter git-commit ghub forge flyspell-correct flycheck-posframe flycheck-popup-tip flycheck-golangci-lint flycheck-cython flycheck-cask flycheck flx fish-mode fd-dired f evil-vimish-fold evil-org evil-multiedit evil-mc evil-magit evil-goggles evil-anzu evil eros epl emmet-mode emacsql-sqlite emacsql elisp-demos dumb-jump drag-stuff doom-themes doom-modeline diredfl dired-rsync diff-hl define-word dash-functional dash-docs dash cython-mode counsel-projectile counsel conda composer company-terraform company-shell company-prescient company-go company-dict company-box company closql centaur-tabs buttercup avy auto-yasnippet async anzu anaconda-mode all-the-icons-ivy all-the-icons-dired all-the-icons ace-window)
        unpin      (n/a)
```
</pre></details>

**Comment by hlissner** [comment] 2020-02-12 21:18
This is a duplicate of #2470. 

A change in later versions of Emacs (27+) doesn't jive well with ws-butler. I haven't looked into it yet, but someone else has in #2470. I'll keep folks posted there.

**Closed by hlissner** 2020-02-12 21:18 UTC
Labels: is:bug
