### ISSUE TITLE
readme links outdated

### ISSUE THREAD

**Issue by objque** [hlissner/doom-emacs#5973] opened 2022-01-08 20:02 UTC
### What did you expect to happen?

links from the roadmap routs to correct pages

### What actually happened?

links to dev. roadmap and plugins are outdated and response with 404 not found

### Steps to reproduce

try to open links as usual user (not maintainer)

https://github.com/hlissner/doom-emacs/projects/3

https://github.com/hlissner/doom-emacs/projects/2

### System Information

?

**Comment by hlissner** [comment] 2022-01-08 20:40
Duplicate of https://github.com/hlissner/doom-emacs/pull/4985

**Closed by hlissner** 2022-01-08 20:40 UTC
Labels: duplicate
