### ISSUE TITLE
doom upgrade does not work

### ISSUE THREAD

**Issue by jbulow** [hlissner/doom-emacs#5384] opened 2021-08-14 16:48 UTC
### What did you expect to happen?

Upgrade doom,

### What actually happened?

doom
x There was an unexpected error
  Message: error
  Data: (error . "Invalid value (1 single-branch) of depth for https://github.com/dimitri/el-get.git")
  Backtrace:
    (signal error ("Invalid value (1 single-branch) of depth for https://githu
    (error "Invalid value %S of depth for %s" (1 single-branch) "https://githu
    (cond ((eq depth 'full) (straight--get-call "git" "clone" "--origin" remot
    (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (c
    (let* ((depth (car (cdr (plist-member --cl-rest-- ':depth)))) (remote (car
    (straight-vc-git--clone-internal :depth (1 single-branch) :remote "origin"
    (progn (straight-vc-git--clone-internal :depth depth :remote remote :url u
    (unwind-protect (progn (straight-vc-git--clone-internal :depth depth :remo
    (let ((success nil) (repo-dir (straight--repos-dir local-repo)) (url (stra
    (let ((package (plist-get --recipe-- ':package)) (local-repo (plist-get --
! Extended backtrace logged to .emacs.d/.local/doom.error.log
No catch for tag: exit, 255

### Describe your attempts to resolve the issue

google the error message

### Steps to reproduce

doom upgrade

### System Information

doom info x There was an unexpected error   Message: error   Data: (error . "Invalid value (1 single-branch) of depth for https://github.com/dimitri/el-get.git")   Backtrace:     (signal error ("Invalid value (1 single-branch) of depth for https://githu     (error "Invalid value %S of depth for %s" (1 single-branch) "https://githu     (cond ((eq depth 'full) (straight--get-call "git" "clone" "--origin" remot     (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (c     (let* ((depth (car (cdr (plist-member --cl-rest-- ':depth)))) (remote (car     (straight-vc-git--clone-internal :depth (1 single-branch) :remote "origin"     (progn (straight-vc-git--clone-internal :depth depth :remote remote :url u     (unwind-protect (progn (straight-vc-git--clone-internal :depth depth :remo     (let ((success nil) (repo-dir (straight--repos-dir local-repo)) (url (stra     (let ((package (plist-get --recipe-- ':package)) (local-repo (plist-get -- ! Extended backtrace logged to .emacs.d/.local/doom.error.log No catch for tag: exit, 255

**Comment by hlissner** [comment] 2021-08-14 16:50
This only happens if you have an old version of straight installed somehow. Delete `~/.emacs.d/.local/straight` manually, then run `doom sync`. Since this isn't a Doom issue I'll close this.

**Closed by hlissner** 2021-08-14 16:50 UTC
Labels: invalid, delete me

**Comment by jbulow** [comment] 2021-08-15 12:35
I tried that. It does not solve the problem. The doom command still fails with the same error whatever argument I give to it.

I don`t undestand how it can not be a doom problem when the doom command fails just by running it.

**Comment by hlissner** [comment] 2021-08-15 14:25
It's not a Doom issue because the only way to make this very specific error occur is by misconfiguring Doom yourself. Specifically, this issue should only occur if you have a version of straight installed that's older than https://github.com/raxod502/straight.el/commit/253d7db6c1165741208219e7b3a29beb12dcd731 (4 months old), but Doom installs a much version that is two months newer (https://github.com/raxod502/straight.el/commit/b45dd00408ff8e922f2d7f75441fd5603e5222fa). 

I don't know how else this is possible. I can't reproduce it with vanilla Doom on any of my test systems, so I can only suspect your configuration or installation method, neither of which I have any clue about with only a backtrace to work with.

**Comment by JasonMFry** [comment] 2021-08-24 17:15
This works for me. I hadn't updated doom or packages in quite a while apparently (oops), then updated packages without updating doom. Restarted doom for an unrelated reason and when it started I was getting the error the OP mentions. Any `doom` terminal command would fail with the error the OP mentions, even just `doom`. `mv ~/.emacs.d/.local/straight ~/Downloads && doom sync` triggered an installation of `straight` and everything else I guess because it took several minutes and the output included "Building gorepl-mode" and many others.
