### ISSUE TITLE
org-babel-after-execute-hook failing after latest update

### ISSUE THREAD

**Issue by egidijusz** [hlissner/doom-emacs#6045] opened 2022-01-27 09:11 UTC
### What did you expect to happen?

Executing (C-c C-c) org bable src block (mermaidjs) I expect image to be rendered in RESULT block.

Using https://github.com/arnm/ob-mermaid to render the image.

### What actually happened?

No image rendered and error:
`Error (org-babel-after-execute-hook): Error running hook +org-redisplay-inline-images-in-babel-result-h because: (error Invalid search bound (wrong side of point))`

Backtrace:
```
Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-forward("\\[\\[\\(?:file\\|\\(?:d\\(?:\\(?:oom-rep\\|uckduckg\\)o\\)\\..." 7100 t)
  #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x155a2cafb751>)(nil nil 7101 7100)
  apply(#f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x155a2cafb751>) (nil nil 7101 7100))
  #f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x155a2cafb751>) org-display-user-inline-images)(nil nil 7101 7100)
  apply(#f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x155a2cafb751>) org-display-user-inline-images) (nil nil 7101 7100))
  (progn (fset #'create-image vnew) (apply fn args))
  (unwind-protect (progn (fset #'create-image vnew) (apply fn args)) (fset #'create-image old))
  (let* ((vnew #'(lambda (file-or-data &optional type data-p &rest props) "\n\n(fn FILE-OR-DATA &optional TYPE DATA-P &rest PRO..." (let ((type ...)) (apply create-image file-or-data type data-p props)))) (old (symbol-function #'create-image))) (unwind-protect (progn (fset #'create-image vnew) (apply fn args)) (fset #'create-image old)))
  (let ((create-image (symbol-function #'create-image))) (ignore create-image) (let* ((vnew #'(lambda (file-or-data &optional type data-p &rest props) "\n\n(fn FILE-OR-DATA &optional TYPE DATA-P &rest PRO..." (let (...) (apply create-image file-or-data type data-p props)))) (old (symbol-function #'create-image))) (unwind-protect (progn (fset #'create-image vnew) (apply fn args)) (fset #'create-image old))))
  +org--fix-inline-images-for-imagemagick-users-a(#f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x155a2cafb751>) org-display-user-inline-images) nil nil 7101 7100)
  apply(+org--fix-inline-images-for-imagemagick-users-a #f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x155a2cafb751>) org-display-user-inline-images) (nil nil 7101 7100))
  org-display-inline-images(nil nil 7101 7100)
  (if (or (and (boundp 'org-export-current-backend) org-export-current-backend) (string-match-p "^ \\*temp" (buffer-name))) nil (org-display-inline-images nil nil (org-babel-where-is-src-block-result) (org-babel-result-end)))
  +org-redisplay-inline-images-in-babel-result-h()
  funcall(+org-redisplay-inline-images-in-babel-result-h)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(+org-redisplay-inline-images-in-babel-result-h)
  run-hook-wrapped(doom-run-hook +org-redisplay-inline-images-in-babel-result-h)
  (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car (cdr e))) (symbol-name (car (cdr e))) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e)))))
  (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car ...)) (symbol-name (car ...)) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp ...) (symbol-name ...) (car ...)) (car (cdr ...)))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (run-hook-wrapped hook #'doom-run-hook) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if ... ... ...) (car ...))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  doom-run-hooks(org-babel-after-execute-hook)
  apply(doom-run-hooks org-babel-after-execute-hook)
  run-hooks(org-babel-after-execute-hook)
  org-babel-execute-src-block(nil ("mermaid" "sequenceDiagram\n    participant A as Alice\n    par..." ((:colname-names) (:rowname-names) (:result-params "file" "replace") (:result-type . value) (:results . "file replace") (:exports . "results") (:file . "renders/alice.svg") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 6937 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  #<subr funcall-interactively>(org-ctrl-c-ctrl-c nil)
  apply(#<subr funcall-interactively> (org-ctrl-c-ctrl-c nil))
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  #<subr call-interactively>(org-ctrl-c-ctrl-c nil nil)
  apply(#<subr call-interactively> (org-ctrl-c-ctrl-c nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> org-ctrl-c-ctrl-c nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (org-ctrl-c-ctrl-c nil nil))
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)

```

### Describe your attempts to resolve the issue

Reverting this commit https://github.com/hlissner/doom-emacs/commit/69340149f97445b3c6e728c692a96c18937feeb9 fixes the issue.

### Steps to reproduce

1. Install ob-mermaid
2. Open org buffer
3. Add
```
#+begin_src mermaid :file alice.svg
sequenceDiagram
    participant A as Alice
    participant B as Bob

    A->>B: Request
    B->>A: Response

#+end_src
```
4. Execute the src block (C-c C-c).

### System Information

https://pastebin.com/nKMrLzuf

**Comment by hlissner** [comment] 2022-01-27 13:36
Duplicate of https://github.com/hlissner/doom-emacs/issues/6046

**Closed by hlissner** 2022-01-27 13:36 UTC
Labels: duplicate, delete me
