### ISSUE TITLE
Change leader key mappings depending on major mode

### ISSUE THREAD

**Issue by lunik1** [hlissner/doom-emacs#3978] opened 2020-09-25 15:35 UTC
**Describe the feature**
Currently there does not seem to be an easy way of changing keymaps under the leader key depending on the active major mode (unless they are under local leader). The intuitive way to do it
```lisp
(map! :map some-major-mode-map
      :leader
      "b s" 'some-major-mode-save-function)
```
does not work. Specifying `:leader` overrides `:map` to use the global map (this might need clarification in the docs?).

This would be useful when you have functions that perform the same or similar functionality in a specific major mode as the default mappings. For example binding `cljr-rename-sybmol` in Clojure mode to `<leader> c r` (for non-lsp users) or `org-save-all-org-buffers` to `<leader> b s` in Org Agenda (which is what `C-x C-s` calls in this case).

...or maybe I've just overlooked something and this is actually trivially easy. My current best workaround has been to remap bindings such as these to a dispatch function that checks the current major mode.

**System information**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64
        path       (~/.cargo/bin ~/bin ~/.cargo/bin/ /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /mnt/c/Program Files/Alacritty/ /mnt/c/tools/miniconda3 /mnt/c/tools/miniconda3/Library/mingw-w64/bin /mnt/c/tools/miniconda3/Library/usr/bin /mnt/c/tools/miniconda3/Library/bin /mnt/c/tools/miniconda3/Scripts /mnt/c/Python38/Scripts/ /mnt/c/Python38/ /mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath /mnt/c/Python37/Scripts/ /mnt/c/Python37/ /mnt/c/Windows/system32 /mnt/c/Windows /mnt/c/Windows/System32/Wbem /mnt/c/Windows/System32/WindowsPowerShell/v1.0/ /mnt/c/Windows/System32/OpenSSH/ /mnt/c/ProgramData/chocolatey/bin /mnt/c/ProgramData/chocolatey/lib/mpv.install/tools /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common /mnt/c/Program Files/OpenSSH-Win64 /mnt/c/Program Files/OpenJDK/jdk-12.0.1/bin /mnt/c/Program Files/OpenJDK/jdk-12.0.2/bin /mnt/c/Program Files/OpenJDK/jdk-13/bin /mnt/c/Program Files (x86)/GNU/GnuPG/pub /mnt/c/Program Files/Git/cmd /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files (x86)/Streamlink/bin /mnt/c/Strawberry/c/bin /mnt/c/Strawberry/perl/site/bin /mnt/c/Strawberry/perl/bin /mnt/c/Program Files/Docker/Docker/resources/bin /mnt/c/ProgramData/DockerDesktop/version-bin /mnt/c/Program Files/nodejs/ /mnt/c/Program Files/OpenJDK/jdk-15/bin /mnt/c/Program Files/Mozilla Firefox /mnt/c/Users/$USER/AppData/Local/Microsoft/WindowsApps /mnt/c/tools/neovim/Neovim/bin /mnt/c/Program Files/MPC-BE x64/ /mnt/c/Program Files (x86)/FAHClient /mnt/c/Program Files/MKVToolNix /mnt/c/Users/$USER/AppData/Roaming/npm /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 1456108d 2020-09-10 18:03:32 -0400
        elc-files  144
        modules    (:completion (company +childframe) (ivy +icons +fuzzy) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline ophints (popup +all) treemacs unicode vc-gutter vi-tilde-fringe (window-select +numbers +switch-window) workspaces :editor (evil +everywhere) file-templates fold format snippets :emacs (dired +ranger +icons) electric (ibuffer +icons) (undo +tree) vc :term eshell shell vterm :checkers (syntax +childframe) (spell (:if (not IS-WINDOWS) +aspell) (:if IS-WINDOWS +hunspell) +everywhere) grammar :tools (docker +lsp) (eval +overlay) lookup lsp magit pdf rgb (&user tree-sitter) :os tty :lang (cc +lsp) clojure emacs-lisp json (latex +latexmk +lsp) markdown nix org (python +lsp) (rust +lsp) (sh +lsp) (yaml +lsp) :config (default +bindings +smartparens))
        packages   ((flycheck-clojure) (form-feed) (info-colors) (mixed-pitch))
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment] 2020-09-25 15:45
The leader key is not for mode/buffer local keybindings. It's for global keybinds. Use the _local_leader if you want a, well, local leader key.

```elisp
(map! :map some-major-mode-map
      :localleader
      "b s" #'some-major-mode-save-function)
```

Otherwise, remap the command on the keymap:

```
(map! :map some-major-mode-map
      [remap buffer-save-function] #'some-major-mode-save-function)
```

---

In any case, this is a duplicate of #3962 and #2718.

**Closed by hlissner** 2020-09-25 15:45 UTC
Labels: duplicate

**Comment by lunik1** [comment] 2020-09-25 15:59
Remapping the command on the keymap is exactly what I need, thank you!
