### ISSUE TITLE
all-the-icons broken

### ISSUE THREAD

**Issue by YutRetr0** [hlissner/doom-emacs#724] opened 2018-06-25 07:34 UTC
I have used the M-X then input all-the-icons-install-fonts. Also I have install the all-the-icons by fc-cache-fv.
I eve rebuild the doom-emacs. But all above don't work. The icons are still broken.

**Comment by dollarex** [comment] 2018-06-25 07:36
BTW, I use archlinux.

**Comment by dollarex** [comment] 2018-06-26 06:30
Thx for your comment, I mean that I install the icons by M-x all-the-icons at the first time then it didn't work. And I reinstall the icons in the ~/.local/share/fonts/ but it didn't work neither.

**Comment by hlissner** [comment] 2018-06-27 22:11
I cannot reproduce this. I'm an Arch too. To clarify, you've run `M-x all-the-icons-install-fonts`, restarted Emacs, and no dice? Perhaps it's something to do with your Arch setup? 

1. Does `fc-list` list the all-the-icons fonts?
2. Are you using `infinality-bundle`, by chance?

**Comment by dollarex** [comment] 2018-06-29 01:15
Thx for helping me. I will try it later.

**Comment by dollarex** [comment] 2018-07-03 12:53
```
[d011ar5@Retr0 ~]$ fc-list | grep all-the
/home/d011ar5/.local/share/fonts/all-the-icons.ttf: all\-the\-icons:style=Regular
```
I got this. Then the icon still can't work.

**Comment by hlissner** [comment] 2018-07-03 15:22
Odd. Nothing appears to be amiss. Are you using terminal emacs, by chance?

**Comment by dollarex** [comment] 2018-07-04 07:04
I have check terminal and applications both. BTW, I still not set the i3-wm, so I still use the xfce4.

**Comment by hlissner** [comment] 2018-08-02 10:32
Does `(find-font (font-spec "github-octicons"))` and `(find-font (font-spec "all-the-icons"))` work? (You can run them in `M-x eval-expression`)

It could be a malformed fontconfig, OS misbehavior (maybe xfce doesn't respect `~/.local/share/fonts`), or perhaps I misunderstood what "broken" means to you. Do you have a screenshot?

**Comment by idoo** [comment] 2018-08-09 06:28
works well on mac for me

**Comment by siddharthshekar** [comment] 2018-10-29 15:43
All-the-icons used to work as intended for me up until yesterday when I finally rebooted my machine and now the fonts don't show up any more. The screenshot below should give you an indication:

![screenshot at 2018-10-29 11-39-00](https://user-images.githubusercontent.com/1447996/47661510-93a95100-db6f-11e8-94c9-648e6b46653b.png)

Running `(find-font (font-spec :family "all-the-icons"))` returns `nil`, but `fc-list | grep all-the` shows that it is installed in the `~/.local/fonts` directory. I also tried running `make update` and `bin/doom refresh` but to no avail.

**Comment by JohnJohnstone** [comment] 2018-11-03 11:45
@siddharthshekar  Did you do anything with system fonts between the period you had it working and rebooting? I dont see why else this would happen, looks like emacs is not picking up the font and is falling back to the wrong one. Also try refreshing font cache, fc-cache -r.

**Comment by siddharthshekar** [comment] 2018-11-04 20:54
I went into `~/.local/share/fonts` where `all-the-icons-install-fonts` seems to have installed the fonts for me, deleted the relevant .ttf files, updated using `fc-cache` and reran `all-the-icons-install-fonts`. Everything works properly now :+1:

**Comment by vitaly-pushkar** [comment] 2019-01-16 20:07
Same problem here on Manjaro (Arch-based), tried deleting the font as suggested in the comment above but no success.
`(find-font (font-spec "github-octicons"))` returns `(wrong-type-argument symbolp "all-the-icons")`

**Comment by gorosz** [comment] 2019-01-18 06:15
I had the same problem checked the ~/.local/share/fonts folder and the files belong to all-the-icons were 0 bytes. I downloaded the files manually from Github everything is working fine now

**Comment by meziberry** [comment] 2019-01-22 14:16
> I had the same problem checked the ~/.local/share/fonts folder and the files belong to all-the-icons were 0 bytes. I downloaded the files manually from Github everything is working fine now

This method is work.  The fonts downloaded by the `M-x all-the-icons-install-fonts` command are zero bytes.

**Comment by memeplex** [comment] 2019-02-17 20:00
I reported this upstream, it's not really a problem with doom so it should be closed here.

**Comment by hlissner** [comment] 2019-02-23 22:30
A couple days ago [a PR to fix `all-the-icons-install-fonts`](https://github.com/domtronn/all-the-icons.el/pull/135) was merged, which should resolve this issue. You can update your packages with `bin/doom update`. Let me know if that isn't the case and I'll reopen this.

**Closed by hlissner** 2019-02-23 22:30 UTC
Labels: help wanted, investigating

**Comment by maikol-solis** [comment] 2020-08-16 17:02
I'm having the same problem with emacs 27.1 

Running `(find-font (font-spec :family "all-the-icons"))` returns `nil` but

```
fc-list  | grep all-the
/home/maikol/.local/share/fonts/all-the-icons.ttf: all\-the\-icons:style=Regular
```

![doom](https://user-images.githubusercontent.com/4078489/90339629-2cac9480-dfaf-11ea-91c2-fe21c0c6a943.png)
![d2](https://user-images.githubusercontent.com/4078489/90339635-31714880-dfaf-11ea-9691-804062716e97.png)


<details>

```
emacs   version    27.1
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Aug 16, 2020
        buildopts  (--disable-build-details --with-pop --without-hesiod --with-gameuser=:games --with-kerberos --with-kerberos5 --with-file-notification=inotify --with-modules --enable-autodepend --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --localstatedir=/var --sharedstatedir=/var/lib --libexecdir=/usr/lib --enable-locallisppath=/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --with-x --with-xim --with-sound --with-xpm --with-jpeg --with-tiff --with-gif --with-png --with-rsvg --with-dbus --with-xft --without-gpm --with-x-toolkit=gtk3 --with-toolkit-scroll-bars --x-includes=/usr/include --x-libraries=/usr/lib64 --with-libotf --with-m17n-flt --with-cairo --with-xwidgets --build=x86_64-suse-linux --with-dumping=pdumper 'CFLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -D_GNU_SOURCE -DGDK_DISABLE_DEPRECATION_WARNINGS -DGLIB_DISABLE_DEPRECATION_WARNINGS -pipe -Wno-pointer-sign -Wno-unused-variable -Wno-unused-label -fno-optimize-sibling-calls -fno-PIE -DSYSTEM_PURESIZE_EXTRA=55000 	 -DSITELOAD_PURESIZE_EXTRA=10000 ' LDFLAGS=-Wl,-O2)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 9a8fc46c 2020-08-15 15:13:50 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-suse-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.18-lp152.33-default #1 SMP Wed Jul 22 06:32:33 UTC 2020 (e5a8383) x86_64
        path       (~/.emacs.d/bin/ ~/bin /usr/local/bin /usr/bin /bin /snap/bin /usr/lib/emacs/27.1/x86_64-suse-linux/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) helm ivy :ui deft doom doom-dashboard fill-column hl-todo modeline nav-flash ophints (popup +defaults) pretty-code tabs treemacs vc-gutter vi-tilde-fringe window-select zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) (lookup +dictionary +offline) (lsp +peek +eglot) magit pdf :os tty :lang emacs-lisp (ess +lsp) (latex +latexmk +cdlatex +fold +lsp) markdown (org +pomodoro +roam +dragndrop +noter +pandoc) python sh :app calendar :config (default +bindings +smartparens))
        packages   ((evil-tutor) (org-fragtog) (real-auto-save) (org-roam-bibtex) (helm-bibtex) (org-ref) (org-roam-server) (org-roam-dashboard :recipe (:host github :repo publicimageltd/org-roam-dashboard)) (polymode) (poly-R) (ess-view) (minions) (beacon) (orgonomic :recipe (:host github :repo aaronjensen/emacs-orgonomic)) (org-clock-convenience) (secretaria) (company-statistics) (company-math) (move-dup) (discover-my-major) (academic-phrases) (org-tracktable))
        unpin      (org-roam company-org-roam org-roam-bibtex)
        elpa       (n/a)
```
</details>
