### ISSUE TITLE
consuel-find-file won't create new file

### ISSUE THREAD

**Issue by jcrono** [hlissner/doom-emacs#636] opened 2018-05-31 17:54 UTC
### Observed behavior

`find-file` binded to `SPC f .` `SPC .` opens dired if I type file that doesn't exist, instead of prompting to create it.

### Expected behavior

`find-file` should prompt user to create new file in case the file typed doesn't exist.

### Additional info

I `git bisect` the issue to commit 183ccbb8f17fad3225046ed06e738d3117a9c885. Also, `+everywhere` flag on the `feature/evil` must be set for the issue to happen. If `+everywhere ` is unset everything works as expected.

### Steps to reproduce
1. Enable `evil +everywhere` and `ivy`on the init.el
2. call `find-file` (`SPC .` on the default/+bindings)
3. Type a new file name e.g. `does-not-exsists.txt`

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 28, 2018)
- Doom: 2.0.9 (n/a 183ccbb8f17fad3225046ed06e738d3117a9c885)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  uname -a:  Linux  4.16.12-1-ARCH #1 SMP PREEMPT Fri May 25 23:30:31 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +childframe) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) vi-tilde-fringe window-select :emacs ediff electric-indent eshell imenu term :tools make magit pdf :lang data emacs-lisp latex markdown (org +attach +babel +capture +export +present) python rust sh web :config :private python-extra personal)
  packages:  n/a
  elc dirs:  n/a
  exec-path: (~/.cargo/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment] 2018-05-31 20:40
I've discovered the cause of this issue and will release a fix soon.

**Comment by hlissner** [comment] 2018-06-01 00:21
As of 4d9ddf2 this should be fixed. Let me know if that isn't the case!

**Comment by jcrono** [comment] 2018-06-01 02:43
@hlissner Fixed, great work!

**Closed** 2018-08-02 16:44 UTC
Labels: bug, fixed in develop
