### ISSUE TITLE
Issue running Doom sync on Windows 10 - Could not find package so-long in recipe repositories

### ISSUE THREAD

**Issue by danielbornt** [hlissner/doom-emacs#4892] opened 2021-04-19 14:07 UTC
While attempting the "doom sync" in windows 10, I ran into the following error message:

From the ~/.emacs.d/bin folder I ran the ``doom sync`` command which generated the following error:

``
Message: error
    Data: (error . "Could not find package so-long in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)")
    Backtrace:
      (signal error ("Could not find package so-long in recipe repositories: (or
      (error "Could not find package %S in recipe repositories: %S" so-long (org
      (if (straight--package-built-in-p melpa-style-recipe) (throw (quote --cl-b
      (or (straight-recipes-retrieve melpa-style-recipe nil cause) (if (straight
      (if recipe-specified-p melpa-style-recipe (or (straight-recipes-retrieve m
      (let* ((recipe-specified-p (listp melpa-style-recipe)) (full-melpa-style-r
      (or (and (symbolp melpa-style-recipe) (gethash (symbol-name melpa-style-re
      (catch (quote --cl-block-straight--convert-recipe--) (if (memq melpa-style
      (straight--convert-recipe so-long " ")
      (let ((recipe (straight--convert-recipe (or (straight--get-overridden-reci
  ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
``

I did search through the issues back catalog and happened upon #2802. I did try everything in that issue bit nothing seems to be resolving the issue.

I have attached the full error log. the pull went fine and the clean found no elc's. It's just on the sync.
[doom.error.log](https://github.com/hlissner/doom-emacs/files/6336605/doom.error.log)

**Comment by hlissner** [comment] 2021-04-19 21:15
so-long is available on [gnu elpa](https://elpa.gnu.org/packages/so-long.html) and [emacsmirror](https://github.com/emacsmirror/so-long). If straight can't find it, it's because your local recipes haven't been updated. Run `doom sync -u` or manually pull `~/.emacs.d/.local/straight/repos/{gnu-elpa-mirror,emacsmirror-mirror}`. Or better yet, simply delete `~/.emacs.d/.local/straight` and `doom sync`, starting over from scratch.

I can't reproduce it in any vanilla Doom setup, even fresh ones, and there's no way to effectively debug this without a time machine, I'll assume it's a local issue; a missed error, misconfiguration at some point, or just some bug that arose from updating Doom over the development of its CLI.

In any case, nothing can be done on Doom's end about this, and were there anything, it'd like fall under #4273 instead, so I'll close this, but feel free to follow up here.

**Closed by hlissner** 2021-04-19 21:15 UTC
Labels: invalid
