### ISSUE TITLE
OmniSharp - Wrong errors - Type "Class" already defines a member called "Method"

### ISSUE THREAD

**Issue by jigmpatel** [hlissner/doom-emacs#1204] opened 2019-02-26 18:16 UTC
<img width="1049" alt="screenshot 2019-02-26 at 18 13 35" src="https://user-images.githubusercontent.com/36105535/53436485-3923e280-39f3-11e9-8347-d0a7e735e7cf.png">
I couldn't find any solution to this problem on omnisharp as well. Not sure if this is still ongoing issue from omnisharp either. I don't get such error statements when I use OmniSharp with YCM on VIM.

**Comment by jigmpatel** [comment] 2019-02-26 18:19
I couldn't find any solution to this problem on omnisharp as well. Not sure if this is still ongoing issue from omnisharp either.

**Comment by hlissner** [comment] 2019-02-26 19:31
My C# is a bit rusty, but don't you need the `new` modifer to override inherited methods? e.g.

```cs
new private void Mul(int[] args) { 
    ... 
}
```

To quote [the .NET documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier):

> When used as a declaration modifier, the new keyword explicitly hides a member that is inherited from a base class. When you hide an inherited member, the derived version of the member replaces the base class version. **Although you can hide members without using the new modifier, you get a compiler warning.** If you use new to explicitly hide a member, it suppresses this warning.

----

Side note: you submitted the unaltered issue template again (like you did in #1176) and posted your actual issue as a reply to it. Please don't do that. Either fill out the template or replace it with your error report.

**Comment by jigmpatel** [comment] 2019-02-27 11:46
It is not required because I am not inheriting from any class and hence there are not matching methods or attributes for OmniSharp to complain about. Also, it is complaining about Program class where there are no similar methods with similar arguments. There is not a matching class in the entire solution with matching methods either.
I also tested this with OmniSharp v1.32.6 binaries replaced with v1.32.10 binaries and unfortunately I have the same behaviour.

**Comment by hlissner** [comment] 2019-02-27 20:04
I was hoping there'd be a `Mul` method on the base `Object` class, but I guess there isn't. I can't reproduce this in my local C# projects, so I'm afraid I have no more insight into the matter. Doom doesn't reconfigure omnisharp at all, so it's either in your project or an upstream issue. You may want to bring this up with [the omnisharp-emacs guys](https://github.com/OmniSharp/omnisharp-emacs) instead.

**Comment by jigmpatel** [comment] 2019-02-28 10:13
Thank you. I am sure that it isn't in my project so I rather raise it to upstream as you mentioned.

**Comment by jigmpatel** [comment] 2019-02-28 15:49
Update - I tried OmniSharp without doom, and I am getting the same issues. The YCMD plugin in VIM uses OmniSharp as a backend and it doesn't have the same issues. This means it's not an issue from doom but upstream (omnisharp-emacs).

**Comment by hlissner** [comment] 2019-02-28 18:52
Good to know Doom isn't the cause, in which case I'll close this issue. Thanks for looking into this and taking the time to follow up!

**Closed by hlissner** 2019-02-28 18:52 UTC
Labels: external
