### ISSUE TITLE
[QUESTION] what can i do if "! A thread has timed out."?

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#1899] opened 2019-10-14 03:10 UTC
Since doom switch to straight.el, I always get this error when I `doom update`. 
```
> Checking core autoloads file
  ✓ Skipping core autoloads, they are up-to-date
> Scanning for outdated packages (this may take a while)...
  . 0%
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  ! A thread has timed out. The following packages were skipped: melpa, gnu-elpa-mirror, emacsmirror-mirror, 
straight, bind-key, async, dotenv-mode, auto-minor-mode, all-the-icons, hide-mode-line, highlight-numbers, ra
inbow-delimiters, restart-emacs, better-jumper, dtrt-indent, helpful, pcre2el, smartparens, so-long, undo-tre
e, ws-butler, projectile, general, which-key, aweshell, avy, pamparam, company-lsp, clang-format, sml-mode, c
make-mode
  . 11%
  .
  .
  .
  .
  .
  .
  .
  .
  . 22%
  . 33%
  . 44%
  .
  .

Output:
/dev/null

--------------------------------------------------

There was an unexpected error:
  error (error)
Wrong type argument: listp, "There were errors:

   - org: ((wrong-type-argument stringp nil) fatal: No such remote 'origin')"
  .
  . 56%
```
I cannot figure how does doom/straight handle the scanning, can you tell me the call function so I can add `proxychains` for commands like git?

I have a socks5 port locally so cli can use this port if `proxychains` is append front of them, like:
```
proxychains4 git clone ......
```
will use socks5 so timeout will not occur while `git clone ...` may cause timeout for aweful Chinese network  envirunment

**Comment by FirstLoveLife** [comment] 2019-10-14 03:17
<details>

```
emacs   version    26.1
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2
        build      Sep 09, 2019
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-iJm1BQ/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 3f60e40f4 2019-10-13 19:23:54 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.0master+ #11 SMP Thu Oct 10 16:05:52 CST 2019 x86_64
        path       (/usr/local/bin /usr/bin /bin /usr/local/games /usr/games /usr/lib/emacs/26.1/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints pretty-code unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs (dired +icons) electric vc :term eshell term vterm :tools docker eval flycheck (lookup +docsets) lsp magit pdf tmux :lang csharp data erlang emacs-lisp markdown (org +attach +babel +capture +export +habit +present +protocol) perl qt sh web :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2019-10-14 03:25
This is a duplicate of #1721. Please see https://github.com/hlissner/doom-emacs/issues/1721#issuecomment-539221633. A fix is in the works.

**Closed by hlissner** 2019-10-14 03:25 UTC
Labels: is:duplicate
