### ISSUE TITLE
doom upgrade: Symbol's function definition is void

### ISSUE THREAD

**Issue by kaelte** [hlissner/doom-emacs#4966] opened 2021-05-02 15:17 UTC
**What did you expect to happen?**
An upgrade of my Doom Emacs

**What actually happened?**
Upgrade reported an error:
```doom -d upgrade```
```
- DEBUG=1
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

**~/.emacs.d/.local/doom.error.log:**

[https://cncloud.zaclys.com/index.php/s/rcQXwCq3RrfPx8e](https://cncloud.zaclys.com/index.php/s/rcQXwCq3RrfPx8e)

**Steps to reproduce:**
```doom -d upgrade```

**System information:**
`~/.emacs.d/bin/doom info`: [https://pastebin.com/CJ8PNfqf](https://pastebin.com/CJ8PNfqf)

**Comment by kaelte** [comment] 2021-05-02 15:19
Same error when upgrading in bash:
`$ doom -d upgrade`

**Comment by gagbo** [comment] 2021-05-02 15:27
Duplicate of #4950

**Comment by kaelte** [comment] 2021-05-02 16:11
Thanks for pointing out this issue. The following solved my problem:
```
mv ${HOME}/.emacs.d/.local/straight/repos/straight.el ${HOME}
```

**Closed** 2021-05-02 16:11 UTC
