### ISSUE TITLE
(setq doom-org-special-tags nil) breaks org-tables

### ISSUE THREAD

**Issue by hliebert** [hlissner/doom-emacs#657] opened 2018-06-05 20:32 UTC
### Observed behavior

I have set `(setq doom-org-special-tags nil)` in my `config.el` to disable the highlighting of #hashtags and @attags as this also highlights references in table formulas (screenshot below). However, this breaks updating and realigning of org-tables and causes `font-lock` error messages. Removing the line restores the functionality. 

<a href="https://i.imgur.com/3U6xGWh.png">
  <img src="https://imgur.com/3U6xGWhl.png" />
</a>

### Expected behavior

Field values in a table should be updated and columns realigned when exiting insert mode or upon `C-c C-c`.

### Steps to reproduce

1. Put `(setq doom-org-special-tags nil)` in `config.el`.
2. Add a new row to the following table.

```* Kosten Umzug
| Posten          | Kosten |
|-----------------+--------|
| Umzugskartons   |     55 |
| Übernahme Möbel |   -100 |
| Ikea            |    200 |
| Entsorgung      |      5 |
|-----------------+--------|
| Total           |    160 |
#+TBLFM: @>$2=vsum(@I..@II)
```
### System information

<details>
<summary>Click to expand</summary>

```- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 27.0.50 (Apr 13, 2018)
- Doom: 2.0.9 (develop 530bdca0977f2cd145e497054f00a72b7c80e306)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD JSON LCMS2
- Details:
  ```elisp
  uname -a:  Linux arch 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +childframe) :ui doom-dashboard doom-modeline hl-todo nav-flash neotree (popup +defaults) vi-tilde-fringe window-select :emacs ediff electric-indent eshell imenu :tools make magit pdf rgb rotate-text :lang emacs-lisp ess (latex +latexmk) markdown (org +attach +babel +capture +export +present) python sh web :app :config)
  packages:  n/a
  elc dirs:  n/a
  exec-path: (/usr/local/sbin /usr/local/bin /usr/bin /usr/sbin /opt/android-sdk/platform-tools /usr/share/java/basex/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```
```
</details>

**Comment by digizeph** [comment] 2018-06-05 21:10
I am able to reproduce this issue.

**Comment by hlissner** [comment] 2018-06-05 23:37
Turns out to be an issue with the `doom-themes` package. I have pushed a fix. Please update and let me know if that works for you.

**Comment by hliebert** [comment] 2018-06-06 06:57
The update fixes it for me. Thanks!

**Closed** 2018-06-07 16:05 UTC
Labels: plugins
