### ISSUE TITLE
Error in doom emacs core 

### ISSUE THREAD

**Issue by sbacelar** [hlissner/doom-emacs#5491] opened 2021-09-17 09:22 UTC
### What did you expect to happen?

This happened when I tried to do `doom upgrade` after a while.

### What actually happened?

```
> Executing 'doom doctor' with Emacs 27.1 at 2021-09-17 10:06:01
  The doctor will see you now...

  > Checking your Emacs version...
  > Checking for Doom's prerequisites...
  > Checking for Emacs config conflicts...
  > Checking for great Emacs features...
  > Checking for private config conflicts...
  > Checking for stale elc files...
  > Checking for problematic git global settings...
  > Checking Doom Emacs...
    x There was an unexpected error
      Message: Error in Doom Emacs core
      Data: (doom-error . "The installed version of Doom has changed since last 'doom sync' ran")
      Backtrace:
        (signal doom-error ("The installed version of Doom has changed since last
        (byte-code \306\232\204\n\307\310\311\312D\"\210\313\314\315\31
        (load "/home/sbac/.emacs.d/.local/autoloads.27.1" nil nomessage)
        (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) n
        (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message
        (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (if doom-de
        (doom-initialize force)
        (let ((doom-interactive-p 'doctor)) (doom-initialize 'force) (doom-initial
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (condition-case ex (let ((doom-output-indent (+ doom-output-indent-increme
    ! Extended backtrace logged to .emacs.d/.local/doom.error.log
```

### Steps to reproduce

Open Emacs

### System Information

https://pastebin.com/tgemKLDD

**Comment by hlissner** [comment] 2021-09-17 09:23
Does `doom sync` fix it?

**Comment by sbacelar** [comment] 2021-09-17 09:25
No. It gives this error:
```
❯ doom sync
> Executing 'doom sync' with Emacs 27.1 at 2021-09-17 10:24:31
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      > Updating recipe repos...
        x There was an unexpected error
          Message: Symbol's function definition is void
          Data: (void-function . straight--process-buffer)
          Backtrace:
            (straight--process-buffer)
            (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
            (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
            (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
            (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
            (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
            (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
            (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
            (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
        ! Extended backtrace logged to .emacs.d/.local/doom.error.log
```

**Comment by hlissner** [comment] 2021-09-17 09:30
This is a duplicate of #4950. See https://github.com/hlissner/doom-emacs/issues/4950#issuecomment-829944410

**Closed by hlissner** 2021-09-17 09:30 UTC
Labels: duplicate, delete me
