### ISSUE TITLE
Setting org-hide-leading-stars to nil is overriden

### ISSUE THREAD

**Issue by alarsyo** [hlissner/doom-emacs#3076] opened 2020-05-09 22:27 UTC
**What did you expect to happen?**

Setting `org-hide-leading-stars` to nil as mentioned in the FAQ results in org-mode not hiding leading stars.

My config:

```elisp
(after! org
  (setq org-hide-leading-stars nil
        org-hide-leading-stars-before-indent-mode nil
        org-startup-indented nil))
```

**What actually happened?**

It seems to get overriden by something else, maybe `+org-init-appearance-h` ?

Using `M-x describe variable` shows it is set to `t`. Org-mode still hides leading stars

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop c0d208965 2020-05-09 02:24:19 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.39-1-lts #1 SMP Wed, 06 May 2020 17:32:42 +0000 x86_64
        path       (/usr/local/texlive/2019/bin/x86_64-linux ~/.local/gcc-arm/bin ~/.node_modules/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.cargo/bin ~/.local/bin ~/go/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom fill-column hl-todo (modeline +light) (popup +defaults) vc-gutter :editor (evil +everywhere) fold snippets :emacs dired undo vc :checkers syntax :tools lookup lsp magit rgb :lang cc emacs-lisp (go +lsp) haskell latex markdown nix ocaml (org +journal +roam) (rust +lsp) sh yaml :config literate (default +bindings +smartparens))
        packages   ((solaire-mode :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2020-05-09 22:53
Have you disabled `org-superstar-mode`?

**Comment by alarsyo** [comment] 2020-05-09 23:38
Yes, I have :/

**Comment by hlissner** [comment] 2020-05-10 01:24
I cannot reproduce this issue with the following in `~/.doom.d/config.el`:

```elisp
(after! org
  (setq org-hide-leading-stars nil
        org-startup-indented nil))
(remove-hook 'org-mode-hook #'org-superstar-mode)
```

`org-hide-leading-stars` is `nil` in org-mode buffers, as expected. 

Does that match your config?

**Comment by alarsyo** [comment] 2020-05-10 09:18
Okay, so, very strange: here's [the relevant part of my config](https://github.com/alarsyo/doom-conf/tree/4474cbd97dbeb961b9f77ed6332ca2df8a90b5a0#doom-specific)

With this, it still hides leading stars, however if I remove the `org-hide-leading-stars-before-indent-mode nil` it does work! Thanks for taking the time to investigate :) I guess that line should  be removed from [the FAQ](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#why-is-scrolling-slow-in-emacsdoom)

**Comment by hlissner** [comment] 2020-05-10 09:26
Odd that its presence should have any effect. `org-hide-leading-stars-before-indent-mode` isn't used upstream anymore. You'd be setting a dead variable (which should have no effect on anything). Ah well. I've removed the line in 7e621e3 in any case. Glad we could figure it out!

**Comment by alarsyo** [comment] 2020-05-10 09:44
After more testing, it seems to be some kind of "race condition" while loading modules ?

During testing I'd restart my daemon and immediately open an org file to check for the stars: in that case they're not hidden, respecting my config.

However if I restart my daemon and wait for 10 seconds, *then* open an org file, it still hides leading stars, while my config is

```elisp
(remove-hook 'org-mode-hook #'org-superstar-mode)
(after! org
  (setq org-hide-leading-stars nil
        org-startup-indented nil))
```

Are you able to reproduce, knowing you have to wait for the daemon to load before opening a frame and an org file?

**Comment by alarsyo** [comment] 2020-05-10 22:32
@hlissner friendly ping in case you haven't seen my comment on the closed issue :)

**Comment by LoganBarnett** [comment] 2020-05-14 05:03
This appears to be involved: https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes-ext-org.el#L72-L73

I need to unwind my debugging I've done to confirm that `org-indent-mode` isn't getting pulled in as well (this was a rabbit hole I also went down) and also causing `org-hide-leading-stars` to be set to `t`.

I was able to work around it by adding my own `doom-themes-ext-org.el` file on my load path. It's just a copy of the original, sans star related settings.

**Comment by LoganBarnett** [comment] 2020-05-14 05:15
Looks like I also had to advice `+org-init-appearance-h` to exclude those variables like @alarsyo suggested earlier. Both this and my prior post's work were required to get the desired visible-stars.

**Comment by hlissner** [comment] 2020-05-14 07:08
I think I understand the issue now. Removing `+org-init-appearance-h` is not necessary. `doom-themes-ext-org.el` is the issue, and only for daemon users. Those settings don't take effect [until the theme is loaded](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/doom/config.el#L14), and for daemon users, the theme is deferred until the first frame is opened (which is usually longer after your config has been read).

As always, the daemon always complicates things. I'll look into a fix soon.

**Comment by hlissner** [comment] 2020-11-07 03:21
Sorry for the late response. This was fixed in https://github.com/hlissner/emacs-doom-themes/commit/5c12834e724869993e1fa62cb3be29fda994a0d6, and was pulled into Doom when `:ui doom` was bumped a couple days ago, so I'll consider this resolved. Thanks for bringing it to my attention!

**Closed by hlissner** 2020-11-07 03:21 UTC
Labels: :lang org, :ui doom, is:bug, is:external, re:emacs:daemon, status:resolved
