### ISSUE TITLE
`+vterm/here` launches in a popup instead of the full window

### ISSUE THREAD

**Issue by seanfarley** [hlissner/doom-emacs#2640] opened 2020-02-29 23:46 UTC
**What did you expect to happen?**
`=vterm` to launch in the current window.

**What actually happened?**
`=vterm` launches in a popup.

**System information:**
<details>

```
emacs   version    26.3
        features   DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
        build      Feb 19, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-gnutls --with-modules)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD aa627c7bb 2020-02-29 12:54:52 -0500
        dir        ~/projects/dotfiles/doom/
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /usr/local/bin/bash
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
        path       (~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin ~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin ~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin ~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin ~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin ~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin ~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin ~/.local/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.8/bin ~/.npm/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/texinfo/bin /Library/TeX/texbin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/libexec/emacs/26.3/x86_64-apple-darwin18.7.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto +childframe) (ivy +childframe +icons +prescient) :ui doom doom-dashboard fill-column hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor file-templates fold multiple-cursors (objed +manual) rotate-text snippets word-wrap :emacs (dired +ranger +icons) electric ibuffer vc :term vterm :checkers (syntax +childframe) (spell +everywhere) grammar :tools ansible debugger docker editorconfig eval gist (lookup +docsets +dictionary) lsp macos magit make pdf prodigy upload :lang (cc +lsp) clojure common-lisp data emacs-lisp go hy (javascript +lsp) (latex +latexmk) lua markdown nim (org +dragndrop +hugo +jupyter +pandoc +pomodoro +present) (python +cython +lsp) rest rst rust scheme sh (swift +lsp) web :email mu4e :app irc twitter :config (default +bindings +smartparens +snippets))
        packages   ((ace-mc) (banner-comment) (bitwarden :recipe (:host github :repo seanfarley/emacs-bitwarden)) (col-highlight :recipe (:host github :repo emacsmirror/col-highlight)) (color-identifiers-mode) (counsel-jq) (discover-my-major) (dot-mode) (easy-hugo) (elisp-slime-nav) (embrace) (emr) (fancy-narrow) (focus) (goto-chg) (ialign) (jump-tree) (lsp-focus :recipe (:host github :repo emacs-lsp/lsp-focus)) (lsp-origami) (lsp-treemacs) (mu4e :recipe (:local-repo ~/projects/mu/mu4e)) (mu4e-alert) (mu4e-maildirs-extension :disable t) (mu4e-patch :recipe (:host github :repo seanfarley/mu4e-patch)) (nov) (org-ref) (package-lint) (page-break-lines) (persistent-scratch) (resize-window) (ripgrep) (sphinx-doc) (srefactor) (sx) (unfill) (webpaste) (whole-line-or-region) (which-key-posframe) (xonsh-mode :recipe (:local-repo ~/projects/xonsh-mode)) (ztree))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment] 2020-02-29 23:55
`=vterm`? Did you mean `+vterm/toggle` or `+vterm/here`? I'm not aware of any Doom module that defines `=vterm`.

**Comment by seanfarley** [comment] 2020-03-01 00:03
Oh, geez; yeah, it's a custom function I wrote. Sorry for the noise.

**Comment by seanfarley** [comment] 2020-03-01 01:38
Seems like it's due to this: https://github.com/akermu/emacs-libvterm/commit/a9ec7533388870fb3a457f5f592cd4ae08412062

**Comment by AdamMarkowski** [comment] 2020-03-03 13:14
@seanfarley @hlissner is it really invalid? 
I experience the same issue since update - both `+vterm/here` and `+vterm/toggle` are opening the vterm in a popup. Previously `+vterm/here` were opening term in current window, thus, right now I can't even move it to another window using `SPC w H/JK/L`.

**Comment by AdamMarkowski** [comment] 2020-03-03 13:31
It seems the root cause is the `emacs-vterm` package itself. So far - reverting the bump up of the package fixes the issue:
`git checkout 5b242c73bbc2236bf1176b561b1d9d53cb2a2440 -- modules/term/vterm/packages.el`

**Comment by seanfarley** [comment] 2020-03-03 19:21
Yeah, you're right @AdamMarkowski; I've changed the title to reflect that. As usual, I just assume it's bad lisp code I wrote 😅

**Comment by hlissner** [comment] 2020-03-03 20:43
In that case, this is a duplicate of #2608. Will track this there.

**Closed by hlissner** 2020-03-03 20:43 UTC
Labels: is:duplicate
