### ISSUE TITLE
doom cli --localdir gets ignored 

### ISSUE THREAD

**Issue by guraltsev** [hlissner/doom-emacs#3370] opened 2020-06-12 20:03 UTC
**What did you expect to happen?**
To be able to specify DOOMLOCALDIR i.e. the location for `.local` storage using a commandline argument
```
doom.cmd --localdir %HOME%\.doom.d\.local sync
```

**What actually happened?**
The argument gets initially ignored, and straight and a bunch of other stuff gets put into the default `~/.emacs.d/.local`

**Additional details:**
HOWEVER this setup works if you specify the DOOMLOCALDIR environment variable!
```
set DOOMLOCALDIR=%HOME%\.doom.d\.local
doom.cmd sync
```
I believe this is due to the fact that straight init happens really early. 

**Steps to reproduce:**
1. clone `doom-emacs` to `~\.emacs.d`
2. setup template `~\.doom.d`
3. run `%HOME%\.emacs.d\bin\doom.cmd --localdir %HOME%\.doom.d\.local sync`
4. expect all local setup files to be in `~\.doom.d\.local`
5. they aren't

**System information:**
Cannot do, this happens before emacs is running.

**Comment by hlissner** [comment] 2020-06-12 20:14
The issue is likely the `doom.cmd` batch script not properly forwarding arguments, `~/.emacs.d/bin/doom --localdir ...` works on macOS, linux and git bash on Windows.

As this is a Windows issue and my batch scripting fu is weak, I cannot resolve this without help. I'd appreciate any advice.

**Comment by guraltsev** [comment] 2020-06-12 20:17
I am not sure this is the case. I opened the cmd and tried executing the emacs command with the correct arguments. It is the same

**Comment by guraltsev** [comment] 2020-06-12 20:24
Did you try deleting the `.local` dir from `~/.emacs.d/`? I think doom first checks that dir before actually doing anything else, so if it is not present it start installing `straight` immediately without bothering to check where it should do put it. Actually, if `~/.emacs.d/local` exists and straight is installed there then some stuff gets put into whatever one specifies as `--localdir`. 

Also, later on doom cli correctly gets that variable since it eventually prints 

```
DOOMLOCALDIR=whatever_you_specified_on_the_command_line
```

Also, in reference to https://github.com/hlissner/doom-emacs/issues/3371 , some cli options like 
```
--localdir
--help
```
should be evaluated before anything else happens.

**Comment by hlissner** [comment] 2020-06-12 20:47
Closing because https://github.com/hlissner/doom-emacs/issues/3367#issuecomment-643476446

**Closed by hlissner** 2020-06-12 20:47 UTC
Labels: is:bug, re:bin/doom, status:resolved-temporarily
