### ISSUE TITLE
wrong-type-argument listp doom/open-project-scratch-buffer

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#4164] opened 2020-10-27 03:55 UTC
<pre>
Debugger entered--Lisp error: (wrong-type-argument listp doom/open-project-scratch-buffer)
  describe-map-tree((keymap (3 keymap (112 . projectile-command-map)) (menu-bar keymap (Projectile menu-item "Projectile" (keymap "Projectile" (Find\ file menu-item "Find file" projectile-find-file) (Find\ file\ in\ known\ projects menu-item "Find file in known projects" projectile-find-file-in-known-projects) (Find\ test\ file menu-item "Find test file" projectile-find-test-file) (Find\ directory menu-item "Find directory" projectile-find-dir) (Find\ file\ in\ directory menu-item "Find file in directory" projectile-find-file-in-directory) (Find\ other\ file menu-item "Find other file" projectile-find-other-file) (Switch\ to\ buffer menu-item "Switch to buffer" projectile-switch-to-buffer) (Jump\ between\ implementation\ file\ and\ test\ file menu-item "Jump between implementation file and test file" projectile-toggle-between-implementation-and-test) (Kill\ project\ buffers menu-item "Kill project buffers" projectile-kill-buffers) (Save\ project\ buffers menu-item "Save project buffers" projectile-save-project-buffers) (Recent\ files menu-item "Recent files" projectile-recentf) (Previous\ buffer menu-item "Previous buffer" projectile-previous-project-buffer) (Next\ buffer menu-item "Next buffer" projectile-next-project-buffer) (nil menu-item "--") (Toggle\ project\ wide\ read-only menu-item "Toggle project wide read-only" projectile-toggle-project-read-only) (Edit\ \.dir-locals\.el menu-item "Edit .dir-locals.el" projectile-edit-dir-locals) (nil-16 menu-item "--") (Switch\ to\ project menu-item "Switch to project" projectile-switch-project) (Switch\ to\ open\ project menu-item "Switch to open project" projectile-switch-open-project) (Discover\ projects\ in\ directory menu-item "Discover projects in directory" projectile-discover-projects-in-directory) (Browse\ dirty\ projects menu-item "Browse dirty projects" projectile-browse-dirty-projects) (Open\ project\ in\ dired menu-item "Open project in dired" projectile-dired) (nil-22 menu-item "--") (Search\ in\ project\ \(grep\) menu-item "Search in project (grep)" projectile-grep) (Search\ in\ project\ \(ag\) menu-item "Search in project (ag)" projectile-ag) (Replace\ in\ project menu-item "Replace in project" projectile-replace) (Multi-occur\ in\ project menu-item "Multi-occur in project" projectile-multi-occur) (nil-27 menu-item "--") (Run\ GDB menu-item "Run GDB" projectile-run-gdb) (nil-29 menu-item "--") (Run\ shell menu-item "Run shell" projectile-run-shell) (Run\ eshell menu-item "Run eshell" projectile-run-eshell) (Run\ ielm menu-item "Run ielm" projectile-run-ielm) (Run\ term menu-item "Run term" projectile-run-term) (nil-34 menu-item "--") (Cache\ current\ file menu-item "Cache current file" projectile-cache-current-file) (Invalidate\ cache menu-item "Invalidate cache" projectile-invalidate-cache) (Regenerate\ \[e|g\]tags menu-item "Regenerate [e|g]tags" projectile-regenerate-tags) (nil-38 menu-item "--") (Configure\ project menu-item "Configure project" projectile-configure-project) (Compile\ project menu-item "Compile project" projectile-compile-project) (Test\ project menu-item "Test project" projectile-test-project) (Install\ project menu-item "Install project" projectile-install-project) (Package\ project menu-item "Package project" projectile-package-project) (Run\ project menu-item "Run project" projectile-run-project) (Repeat\ last\ external\ command menu-item "Repeat last external command" projectile-repeat-last-command) (nil-46 menu-item "--") (Project\ info menu-item "Project info" projectile-project-info) ...)))) t ((keymap (menu-bar keymap (Perspectives menu-item "Perspectives" (keymap (kill "kill" keymap "kill" (main menu-item "main" menu-function-2 :key-sequence nil)) "Perspectives" (nil menu-item "-") (none menu-item "none" menu-function-0 :key-sequence nil) (main menu-item "main" menu-function-1 :key-sequence nil)))) (remap keymap (evil-window-delete . +workspace/close-window-or-workspace) (delete-window . +workspace/close-window-or-workspace)) (3 keymap (119 . persp-key-map))) (keymap) (keymap (remap keymap (switch-to-buffer-other-window . ivy-switch-buffer-other-window) (switch-to-buffer . ivy-switch-buffer))) (keymap) (keymap) (keymap (3 . doom/leader) (4194424 . execute-extended-command) (27 keymap (120 . execute-extended-command))) (keymap #^[nil nil keymap nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil ...])) [3] "\f\n`projectile-mode' Minor Mode Bindings" t nil nil nil)
  describe-buffer-bindings(#<buffer *scratch*> [3])
  which-key--get-current-bindings([3])
  which-key--get-bindings([3] nil nil)
  which-key--create-buffer-and-show([3])
  which-key--update()
  apply(which-key--update nil)
  timer-event-handler([t 0 1 0 t which-key--update nil idle 0])
</pre>

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.9.1 #1 SMP Mon Oct 19 12:09:15 CST 2020 x86_64
	path       (~/.go/bin ~/.jenv/shims ~/.jenv/bin ~/.emacs.d/bin ~/.local/bin ~/.go/bin ~/.nvm/versions/node/v14.12.0/bin ~/.jenv/shims ~/.jenv/bin ~/.emacs.d/bin ~/.local/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/jvm/default/bin /usr/lib/jvm/default/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    28.0.50
	build      Oct 27, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --with-xwidgets --without-compress-install 'CFLAGS=-march=native -O2 -pipe -fno-plt -flto -fuse-linker-plugin' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
	traits     (batch server-running)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop, origin/develop, origin/HEAD adff1aa68 2020-10-22 02:10:59 -0400
	elc-files  0
	modules    (:completion (company +childframe) (ivy +prescient +fuzzy +icons) :ui doom doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter window-select workspaces :editor file-templates fold format multiple-cursors snippets word-wrap :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers (syntax +childframe) (spell +aspell) :tools (debugger +lsp) docker editorconfig (eval +overlay) lookup (lsp +peek) magit make pdf :lang data emacs-lisp (go +lsp) json (java +lsp) (javascript +lsp) (markdown +grip) (org +dragndrop +pandoc +present +pomodoro +journal +pretty) plantuml (python +lsp +pyright) rest (scala +lsp) sh (web +lsp) yaml :config (default +bindings +smartparens) :my (&user chinese +childframe) (&user ui) (&user editor) (&user spell) (&user calendar) (&user dired) (&user magit) (&user translate +childframe) (&user tools) (&user debugger) (&user lsp) (&user markdown) (&user plantuml) (&user protobuf) (&user go) (&user java +google-java-format) (&user scala) (&user sql) (&user keybindings))
	packages   ((magit-svn :pin 2cff1a30a30f2b3963342a7d185ec13fc12279c3) (pkgbuild-mode :pin 887c01cb06420501c7780fb01a8a76bdb0864cca))
	unpin      ((:completion ivy) (:ui doom) (:tools magit debugger lsp) (:lang java scala))
	elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment] 2020-10-27 04:14
How can I reproduce this error?

**Comment by cxb811201** [comment] 2020-10-27 04:26
This error will be reported when you press the `C-c` key after the initial installation of `doom-emacs` using the latest compiled emacs28 in a non evil environment

**Comment by cxb811201** [comment] 2020-10-30 08:37
> How can I reproduce this error?

@hlissner  You can reproduce this error?

**Comment by progfolio** [comment] 2020-10-31 21:56
related: https://github.com/justbur/emacs-which-key/issues/267

**Comment by progfolio** [comment] 2020-10-31 21:57
I believe this may be in the upstream lisp implementation of `describe-map-tree`.
Bug filed here with minimal reproduction case: https://lists.gnu.org/archive/html/bug-gnu-emacs/2020-10/msg02841.html

**Comment by zackteo** [comment] 2020-11-07 05:24
I get a similar error when I run

**Comment by hlissner** [comment] 2020-11-07 05:26
Just realized #4231 is a duplicate of this. This was fixed in 92c9127b8.

**Closed by hlissner** 2020-11-07 05:26 UTC
Labels: duplicate

**Comment by zackteo** [comment] 2020-11-07 06:20
Seems to still be an issue. 

When I run `doom sandbox` with `Doom + modules - private config`
If I run `describe-mode`, I get the following 
```

**Comment by progfolio** [comment] 2020-11-07 06:30
@zackteo what version of Emacs?

**Comment by zackteo** [comment] 2020-11-07 07:16
@progfolio native-comp
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3) of 2020-11-06

**Comment by progfolio** [comment] 2020-11-07 07:26
That branch looks like it's trailing master a bit. Here's the commit that fixed the bug:

https://github.com/emacs-mirror/emacs/commit/5ab5504def63ebdfba08169f24a5829353bff137

You could make your own branch and patch that into the native comp branch while you wait for it to update.

**Comment by zackteo** [comment] 2020-11-07 07:59
@progfolio Sorry a bit of a noob here, but what might be the best way for me to do this? Is there a way to do so without having to rebuild emacs? 
Am using this btw https://aur.archlinux.org/packages/emacs-native-comp-git/

**Comment by progfolio** [comment] 2020-11-07 08:06
This requires rebuilding Emacs from the source code after you've altered it. Unfortunately, I don't have time right now to give detailed instructions, but if you're interested in pursuing this, you would need to be somewhat familiar with git.

**Comment by zackteo** [comment] 2020-11-07 08:21
@progfolio okay! No worries, let me dig around ... Maybe I should learn how to build emacs myself hmmm

**Comment by zackteo** [comment] 2020-11-07 21:57
Actually other than `/usr/share/emacs/28.0.50/lisp` where else does core `.elc` files reside in? Or rather where else do I need to modify help.elc

**Comment by zackteo** [comment] 2020-11-07 22:16
Okay, for now I ...
1. Modified help.el in `/usr/share/emacs/28.0.50/lisp`
2. Used `(byte-compile-file)` to recompile `help.elc`
3. Added a hotfix of loading help.elc in my config
`(load "/usr/share/emacs/28.0.50/lisp/help.elc")` 

How might I generate a new `.eln` in   `/usr/lib/emacs/28.0.50/native-lisp/28.0.50-x86_64-pc-linux-gnu-a3d1b99a272f8f5ffd294637b5a1c6fd` so I can remove the hotfix in of my config?

**Comment by krageon** [comment] 2020-11-10 17:24
For the record, I tried replacing the file with the output of the `native-compile` function and that's not the right way to do it (it yields a segfault). I'm sure it's possible, but I can't figure it out rn.
