### ISSUE TITLE
Fonts/icons not displaying correctly.

### ISSUE THREAD

**Issue by mglebinski** [hlissner/doom-emacs#6112] opened 2022-02-13 21:59 UTC
### What did you expect to happen?

Fonts to show without weird stuff showing up in the process. I have tried following other issues that have had a similar thing happen but no fixes I've tried seemed to work.

### What actually happened?

![image](https://user-images.githubusercontent.com/56172613/153776596-2b51f166-0a5d-4cc9-b0e7-bf8af93b03c2.png)

### Describe your attempts to resolve the issue

Tried reinstalling and using doom doctor. Doctor says fonts are installed and found.

![image](https://user-images.githubusercontent.com/56172613/153776916-012f6136-7bfb-4bf5-b1fd-7b709267c72a.png)

### Steps to reproduce

1. Install emacs
2. Install default config of doom emacs.
3. Open emacs

### System Information

https://pastebin.com/K6hVYWNA

**Comment by hlissner** [comment] 2022-02-13 22:22
Duplicate of https://github.com/hlissner/doom-emacs/issues/2031.

**Closed by hlissner** 2022-02-13 22:22 UTC
Labels: duplicate
