### ISSUE TITLE
Flyspell stopped working

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#4420] opened 2020-12-12 19:37 UTC
**What did you expect to happen?**
For Flyspell to show wrong words.

**What actually happened?**
Flyspell does not mark any wrong words.

**Additional details:**
- [Private config](https://github.com/mrbig033/doom2) (also tested without private config).

**Steps to reproduce:**
1. Open a file with Flyspell on
2. Type a wrong word and save
3. The wrong word should be marked, but isnt

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/bash
	uname      Linux 5.8.0-31-generic #33-Ubuntu SMP Mon Nov 23 18:44:54 UTC 2020 x86_64
	path       (/home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/sbin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.fzf/bin ~/maps/scripts ~/.nimble/bin /usr/lib/emacs/27.1/x86_64-linux-gnu)
EMACS   dir        ~/Dropbox/emacs/emacs-files/.emacs.d/
	version    27.1
	build      set 19, 2020
	buildopts  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --program-suffix=27 --with-modules --with-file-notification=inotify --with-mailutils --with-harfbuzz --with-json --with-x=yes --with-x-toolkit=gtk3 --with-lcms2 --with-cairo --with-xpm=yes --with-gif=yes --with-gnutls=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xwidgets 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs27-bifpWT/emacs27-27.1~1.git86d8d76aa3=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch envvar-file)
DOOM    dir        ~/Dropbox/emacs/emacs-files/.doom.d/
	version    2.0.9
	build      HEAD -> develop 91ced7997 2020-12-12 13:49:05 -0500
	elc-files  1
	modules    (:completion company (ivy +prescient +childframe) :ui deft doom modeline ophints (popup +defaults) :editor (evil +everywhere) file-templates fold lispy multiple-cursors word-wrap :emacs (dired +ranger) electric undo vc :term term vterm :checkers syntax (spell +flyspell) :tools (eval +overlay) (lookup +dictionary +offline) :lang emacs-lisp markdown (org +pomodoro +roam +journal) (racket +xp) sh :config (default +bindings +smartparens))
	packages   ((cycle-buffer :recipe (:local-repo /home/jones/.doom.d/lisp/cycle-buffer)) (targets :recipe (:local-repo /home/jones/.doom.d/lisp/targets)) (typo) (olivetti) (eyebrowse) (caps-lock) (super-save) (engine-mode) (hl-sentence) (lorem-ipsum) (org-web-tools) (better-jumper) (google-translate) (electric-operator) (yasnippet-snippets) (git-auto-commit-mode) (evil-better-visual-line) (aggressive-fill-paragraph) (clipmon :disable t) (elmacro :disable t) (pabbrev :disable t) (evil-lion :disable t) (poet-theme :disable t) (evil-snipe :disable t) (kaolin-themes :disable t) (dracula-theme :disable t) (badwolf-theme :disable t) (fountain-mode :disable t) (url-shortener :disable t))
	unpin      (n/a)
	elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment] 2020-12-12 19:43
Cannot reproduce this and have no other leads to go on.

**Comment by AloisJanicek** [comment] 2020-12-12 20:02
Recently I noticed I had to set `(setq ispell-dictionary "en")` in my `config.el` (at top level, not in any `(after! ...)` block). Previously the value was `"english"` and that worked for years, but recently it stopped with some ispell or flyspell error complaining about insufficient aspell dictionary files in `/usr/lib/aspell-0.60/`. `"english" `is some kind of aspell alias to ` "en"`. `aspell` wasn't changed on my system since April, so the issue must be in emacs. But I am using `native-comp` and `flyspell` is built-in package, so maybe this issue is out of scope for the doom.

**Comment by RoryO** [comment] 2020-12-12 20:11
Dupe of #4407 ?

**Comment by mrbig033** [comment] 2020-12-12 20:13
> Can you @mrbig033 look at echo messages area (`view-echo-area-messages` on `SPC h e`) for any errors related to this?

`(setq ispell-dictionary "en")` had no effect, sadly. No relevant echo area messages either.

**Comment by mrbig033** [comment] 2020-12-12 20:14
> Dupe of #4407 ?

Maybe so. I should all that this does happen on markdown mode, now that I think of.

**Comment by AloisJanicek** [comment] 2020-12-12 20:28
Then this is an issue with what is run in `flyspell-mode-hook`. I was recently setting up [emacs_anywhere](https://github.com/zachcurry/emacs-anywhere) and I noticed that flyspell-mode doesn't work in markdown unless I set `flyspell-mode-hook` to `nil`

**Comment by RoryO** [comment] 2020-12-12 20:41
Try `git revert 7f99eb7a48e8e95cc3059eda7910cd6aaf7341cc` in `.emacs.d` and see if it fixes the issue.

**Comment by AloisJanicek** [comment] 2020-12-12 21:19
reverting `7f99eb7a` didn't helped but removing `flyspell-lazy-load` from hook did
`(remove-hook 'flyspell-mode-hook #'flyspell-lazy-load)`

**Comment by hlissner** [comment] 2020-12-13 05:21
Please update and see if fc955fa and/or 2e61fbb fixed your issue.

**Closed** 2021-01-04 03:58 UTC
Labels: :checkers spell, is:bug, status:resolved
