### ISSUE TITLE
main README's links to the Roadmaps are broken

### ISSUE THREAD

**Issue by jrmiller82** [hlissner/doom-emacs#5980] opened 2022-01-11 05:42 UTC
### What did you expect to happen?

I expected to click on a link and for it to work instead of 404'ing. 

### What actually happened?

It 404'd. 

### Describe your attempts to resolve the issue

Posting an issue here.

### Steps to reproduce

Got to the repo's main readme file and click on any of the 3 links in Roadmap section.

### System Information

no.

**Comment by hlissner** [comment] 2022-01-12 00:07
Duplicate of #5973

**Closed by hlissner** 2022-01-12 00:07 UTC
Labels: duplicate, delete me

**Comment by jrmiller82** [comment] 2022-01-12 00:42
Sorry; didn't mean to submit a duplicate. Thanks!
