### ISSUE TITLE
`doom/upgrade` Error building org-mode

### ISSUE THREAD

**Issue by JordanAnthonyKing** [hlissner/doom-emacs#4914] opened 2021-04-23 20:32 UTC
I haven't noticed any misbehaviour in usage yet, but running doom/upgrade today I was met with this error:

```
      x There was an unexpected error
        Message: File is missing
        Data: (file-missing . "/home/jordan/.emacs.d/.local/straight/build-28.0.50/org-mode/org-loaddefs.el")
        Backtrace:
          (comp-el-to-eln-filename "/home/jordan/.emacs.d/.local/straight/build-28.0
          (file-name-nondirectory (comp-el-to-eln-filename file))
          (concat comp-native-version-dir "/" (file-name-nondirectory (comp-el-to-el
          (doom--eln-file-name "/home/jordan/.emacs.d/.local/straight/build-28.0.50/
          (setq eln-name (doom--eln-file-name file))
          (while (consp --cl-var--) (setq file (car --cl-var--)) (setq eln-name (doo
          (let* ((--cl-var-- doom--eln-output-expected) (file nil) (eln-name nil) (e
          (doom--write-missing-eln-errors)
          (progn (doom--compile-site-packages) (doom--wait-for-compile-jobs) (doom--
          (if built (progn (doom--compile-site-packages) (doom--wait-for-compile-job
      ! Extended backtrace logged to .emacs.d/.local/doom.error.log

Comint exited abnormally with code 255 at Fri Apr 23 21:28:27
```

**System information:**
https://pastebin.com/KGhMpti7

**Comment by MarkusSagen** [comment] 2021-04-30 15:19
@JordanAnthonyKing, I had the same problem, but with another error message was different.    
What worked for me was either to   

**a**) Move my old doom emacs folder, re-download doom emacs and move my old config back in
```sh
mv ~/.doom.d ~/.doom.d_old      
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d                                                                  ~/.emacs.d/bin/doom install
cp ~/.doom.d/* ~/.doom.d/
doom sync
```
**b**) ...**or** reset doom emacs to a previous commit on the develop branch
```sh
cd ~/.emacs.d
git reset --hard 473417a8907559f0a60952ddcae8db861445a533  
doom sync
```

**Comment by hlissner** [comment] 2021-05-01 06:18
I cannot reproduce this. Please update Doom (at least e8d51f2be) and native-comp and try again.

+ Try upgrading doom manually:
   ```sh
   cd ~/.emacs.d
   git pull
   doom sync -up
   ```
+ Try deleting your local org-mode repo: `rm -rf ~/.emacs.d/.local/straight/repos/org-mode` then `doom sync` again.

Until I have leads to further suggest this is a Doom issue and not a local one I will close this issue, but feel free to follow up here.

>  I had the same problem, but with another error message was different.

@MarkusSagen And the contents of that error message was...?

**Closed by hlissner** 2021-05-01 06:18 UTC
Labels: :lang org, status:unknown
